/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        english: ['Lexend', 'sans-serif'],
        'english-medium': ['Lexend', 'sans-serif'],
        'english-semibold': ['Lexend', 'sans-serif'],
        arabic: ['Noto Sans Arabic', 'sans-serif'],
        'arabic-medium': ['Noto Sans Arabic', 'sans-serif'],
        'arabic-semibold': ['Noto Sans Arabic', 'sans-serif'],
        bengali: ['Noto Sans Bengali', 'sans-serif'],
      },
      fontSize: {
        display: ['34px', { lineHeight: '40px', letterSpacing: '-0.4px' }],
        h1: ['28px', { lineHeight: '34px', letterSpacing: '-0.2px' }],
        h2: ['22px', { lineHeight: '28px', letterSpacing: '-0.1px' }],
        body: ['16px', { lineHeight: '26px' }],
        'body-sm': ['14px', { lineHeight: '22px' }],
        caption: ['12px', { lineHeight: '18px' }],
        'arabic-display': ['44px', { lineHeight: '60px' }],
        'arabic-body': ['18px', { lineHeight: '34px' }],
      },
      colors: {
        primary: {
          50: '#ECFDF8',
          100: '#D1FAEF',
          200: '#A7F3DE',
          300: '#6EE7C8',
          400: '#34D3AA',
          500: '#16B78E',
          600: '#0F9373',
          700: '#0D775F',
          800: '#0F5F4D',
          900: '#124E41',
        },
        neutral: {
          50: '#F8F7F4',
          100: '#F0EEE8',
          200: '#E5E1D8',
          300: '#D5CEBF',
          400: '#B9AF9C',
          500: '#9A8F7B',
          600: '#7D7463',
          700: '#4F4A40',
          800: '#22201B',
          900: '#1A1815',
          950: '#0D0C0A',
        },
        status: {
          success: '#2E7D32',
          warning: '#C77D00',
          danger: '#C62828',
          info: '#1565C0',
        },
      },
    },
  },
  plugins: [],
};
