/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as VolumeVolumeIdIndexRouteImport } from './routes/volume/$volumeId/index'
import { Route as VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRouteImport } from './routes/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/index'
import { Route as VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport } from './routes/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeVolumeIdIndexRoute = VolumeVolumeIdIndexRouteImport.update({
  id: '/volume/$volumeId/',
  path: '/volume/$volumeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute =
  VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRouteImport.update({
    id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/',
    path: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute =
  VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport.update({
    id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId',
    path: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId/': typeof VolumeVolumeIdIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId': typeof VolumeVolumeIdIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId/': typeof VolumeVolumeIdIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId/'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId/'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  VolumeVolumeIdIndexRoute: typeof VolumeVolumeIdIndexRoute
  VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute
  VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$volumeId/': {
      id: '/volume/$volumeId/'
      path: '/volume/$volumeId'
      fullPath: '/volume/$volumeId/'
      preLoaderRoute: typeof VolumeVolumeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/': {
      id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/'
      path: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
      fullPath: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/'
      preLoaderRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': {
      id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
      path: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
      fullPath: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
      preLoaderRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  VolumeVolumeIdIndexRoute: VolumeVolumeIdIndexRoute,
  VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute:
    VolumeVolumeIdChapterChapterIdLessonDarsNumIndexRoute,
  VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute:
    VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
