/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolumeVolumeIdRouteImport } from './routes/volume/$volumeId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as VolumeVolumeIdChapterChapterIdLessonDarsNumRouteImport } from './routes/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
import { Route as VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport } from './routes/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeVolumeIdRoute = VolumeVolumeIdRouteImport.update({
  id: '/volume/$volumeId',
  path: '/volume/$volumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeVolumeIdChapterChapterIdLessonDarsNumRoute =
  VolumeVolumeIdChapterChapterIdLessonDarsNumRouteImport.update({
    id: '/chapter/$chapterId/lesson/$darsNum',
    path: '/chapter/$chapterId/lesson/$darsNum',
    getParentRoute: () => VolumeVolumeIdRoute,
  } as any)
const VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute =
  VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport.update({
    id: '/chunk/$chunkId',
    path: '/chunk/$chunkId',
    getParentRoute: () => VolumeVolumeIdChapterChapterIdLessonDarsNumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId': typeof VolumeVolumeIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId': typeof VolumeVolumeIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/volume/$volumeId': typeof VolumeVolumeIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren
  '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId'
    | '/api/auth/$'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId'
    | '/api/auth/$'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/volume/$volumeId'
    | '/api/auth/$'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
    | '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  VolumeVolumeIdRoute: typeof VolumeVolumeIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$volumeId': {
      id: '/volume/$volumeId'
      path: '/volume/$volumeId'
      fullPath: '/volume/$volumeId'
      preLoaderRoute: typeof VolumeVolumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum': {
      id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
      path: '/chapter/$chapterId/lesson/$darsNum'
      fullPath: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum'
      preLoaderRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRouteImport
      parentRoute: typeof VolumeVolumeIdRoute
    }
    '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId': {
      id: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
      path: '/chunk/$chunkId'
      fullPath: '/volume/$volumeId/chapter/$chapterId/lesson/$darsNum/chunk/$chunkId'
      preLoaderRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRouteImport
      parentRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRoute
    }
  }
}

interface VolumeVolumeIdChapterChapterIdLessonDarsNumRouteChildren {
  VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute
}

const VolumeVolumeIdChapterChapterIdLessonDarsNumRouteChildren: VolumeVolumeIdChapterChapterIdLessonDarsNumRouteChildren =
  {
    VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute:
      VolumeVolumeIdChapterChapterIdLessonDarsNumChunkChunkIdRoute,
  }

const VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren =
  VolumeVolumeIdChapterChapterIdLessonDarsNumRoute._addFileChildren(
    VolumeVolumeIdChapterChapterIdLessonDarsNumRouteChildren,
  )

interface VolumeVolumeIdRouteChildren {
  VolumeVolumeIdChapterChapterIdLessonDarsNumRoute: typeof VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren
}

const VolumeVolumeIdRouteChildren: VolumeVolumeIdRouteChildren = {
  VolumeVolumeIdChapterChapterIdLessonDarsNumRoute:
    VolumeVolumeIdChapterChapterIdLessonDarsNumRouteWithChildren,
}

const VolumeVolumeIdRouteWithChildren = VolumeVolumeIdRoute._addFileChildren(
  VolumeVolumeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  VolumeVolumeIdRoute: VolumeVolumeIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
