// Chapter 2 Lesson 3 Interactive Session Data (Directly mapped from textbook Volume 1 Chapter 2 Lesson 3, pages 60-64)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH2_LESSON_03_STEPS: SessionStep[] = [
  // 1. Vocabulary Discovery: Professions & Occupations
  {
    id: 'ch2-l3-step-1-vocab-professions',
    type: 'vocab_prime',
    pageNumber: 60,
    titleEn: 'Professions & Occupations Vocabulary',
    titleAr: 'مُفْرَدَاتُ المِهَنِ وَالأَعْمَالِ',
    instructionEn: 'Listen to and learn classical Arabic titles for professions and trades',
    instructionBn: 'বিভিন্ন পেশা ও বৃত্তি সম্পর্কিত আরবি শব্দগুলোর উচ্চারণ শুনুন ও অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l3_tabib', ar: 'طَبِيبٌ', en: 'Doctor / physician', bn: 'একজন চিকিৎসক / ডাক্তার', romanized: 'ṭabībun', emoji: '👨‍⚕️' },
        { id: 'v1_c2l3_marid', ar: 'مَرِيضٌ', en: 'Patient / sick person', bn: 'রোগী / অসুস্থ', romanized: 'marīḍun', emoji: '🤒' },
        { id: 'v1_c2l3_katib', ar: 'كَاتِبٌ', en: 'Writer / author', bn: 'একজন লেখক', romanized: 'kātibun', emoji: '✍️' },
        { id: 'v1_c2l3_khayyat', ar: 'خَيَّاطٌ', en: 'Tailor', bn: 'একজন দর্জি', romanized: 'khayyāṭun', emoji: '🪡' },
        { id: 'v1_c2l3_labban', ar: 'لَبَّانٌ', en: 'Milkman', bn: 'গোয়াল / দুধ বিক্রেতা', romanized: 'labbānun', emoji: '🥛' },
        { id: 'v1_c2l3_sayyad', ar: 'صَيَّادٌ', en: 'Hunter / fisherman', bn: 'শিকারী / জেলে', romanized: 'ṣayyādun', emoji: '🎣' },
        { id: 'v1_c2l3_saiq', ar: 'سَائِقٌ', en: 'Driver', bn: 'চালক / ড্রাইভার', romanized: 'sā’iqun', emoji: '🚗' },
        { id: 'v1_c2l3_tabbakh', ar: 'طَبَّاخٌ', en: 'Cook / chef', bn: 'বাবুর্চি / পাচক', romanized: 'ṭabbākhun', emoji: '👨‍🍳' },
      ],
    },
  },

  // 2. Speed Pairing: Professions & Trades
  {
    id: 'ch2-l3-step-2-pair-professions',
    type: 'speed_pair',
    pageNumber: 60,
    titleEn: 'Professions Recall Drill',
    titleAr: 'مُطَابَقَةُ أَسْمَاءِ المِهَنِ',
    instructionEn: 'Match each profession with its meaning',
    instructionBn: 'পেশাগুলোর সাথে সঠিক অর্থ দ্রুত মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pp-tabib', ar: 'طَبِيبٌ', meaning: 'Doctor / physician' },
        { id: 'pp-katib', ar: 'كَاتِبٌ', meaning: 'Writer / author' },
        { id: 'pp-khayyat', ar: 'خَيَّاطٌ', meaning: 'Tailor' },
        { id: 'pp-sayyad', ar: 'صَيَّادٌ', meaning: 'Hunter / fisherman' },
        { id: 'pp-tabbakh', ar: 'طَبَّاخٌ', meaning: 'Cook / chef' },
      ],
    },
  },

  // 3. Vocabulary Discovery: Character & Moral Attributes
  {
    id: 'ch2-l3-step-3-vocab-character',
    type: 'vocab_prime',
    pageNumber: 60,
    titleEn: 'Character & Moral Attributes',
    titleAr: 'مُفْرَدَاتُ الأَخْلَاقِ وَالطِّبَاعِ',
    instructionEn: 'Learn attributes describing moral integrity, honesty, generosity, and energy',
    instructionBn: 'চরিত্র, আমানতদারী, দানশীলতা ও কর্মোদ্যম প্রকাশক গুণবাচক শব্দগুলোর অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l3_amin', ar: 'أَمِينٌ', en: 'Trustworthy', bn: 'বিশ্বস্ত / আমানতদার', romanized: 'amīnun', emoji: '🛡️' },
        { id: 'v1_c2l3_sakhi', ar: 'سَخِيٌّ', en: 'Generous', bn: 'দানশীল / উদার', romanized: 'sakhiyyun', emoji: '🤲' },
        { id: 'v1_c2l3_bakhil', ar: 'بَخِيلٌ', en: 'Miserly / stingy', bn: 'কৃপণ', romanized: 'bakhīlun', emoji: '🪙' },
        { id: 'v1_c2l3_sadiq', ar: 'صَادِقٌ', en: 'Truthful', bn: 'সত্যবাদী', romanized: 'ṣādiqun', emoji: '⭐' },
        { id: 'v1_c2l3_kadhib', ar: 'كَاذِبٌ', en: 'Liar / untruthful', bn: 'মিথ্যাবাদী', romanized: 'kādhibun', emoji: '🤥' },
        { id: 'v1_c2l3_mutawadi', ar: 'مُتَوَاضِعٌ', en: 'Humble', bn: 'বিনয়ী', romanized: 'mutawāḍi‘un', emoji: '🌱' },
        { id: 'v1_c2l3_mutakabbir', ar: 'مُتَكَبِّرٌ', en: 'Arrogant / proud', bn: 'অহংকারী', romanized: 'mutakabbirun', emoji: '🦚' },
        { id: 'v1_c2l3_kaslan', ar: 'كَسْلَانُ', en: 'Lazy (diptote)', bn: 'অলস (তানভীনহীন)', romanized: 'kaslānu', emoji: '🦥' },
        { id: 'v1_c2l3_nashit', ar: 'نَشِيطٌ', en: 'Energetic / active', bn: 'উদ্যমী / কর্মঠ', romanized: 'nashīṭun', emoji: '⚡' },
      ],
    },
  },

  // 4. Speed Pairing: Character & Moral Attributes
  {
    id: 'ch2-l3-step-4-pair-character',
    type: 'speed_pair',
    pageNumber: 60,
    titleEn: 'Character Traits Recall Drill',
    titleAr: 'مُطَابَقَةُ الصِّفَاتِ الخُلُقِيَّةِ',
    instructionEn: 'Match each character trait with its meaning',
    instructionBn: 'গুণবাচক শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pc-amin', ar: 'أَمِينٌ', meaning: 'Trustworthy' },
        { id: 'pc-sakhi', ar: 'سَخِيٌّ', meaning: 'Generous' },
        { id: 'pc-bakhil', ar: 'بَخِيلٌ', meaning: 'Miserly' },
        { id: 'pc-sadiq', ar: 'صَادِقٌ', meaning: 'Truthful' },
        { id: 'pc-mutawadi', ar: 'مُتَوَاضِعٌ', meaning: 'Humble' },
      ],
    },
  },

  // 5. Concept Discovery: Attribute Negation with Ghayr (غَيْرُ)
  {
    id: 'ch2-l3-step-5-concept-ghayr',
    type: 'concept_intro',
    pageNumber: 62,
    titleEn: 'Negating Attributes with «غَيْرُ»',
    titleAr: 'نَفْيُ الصِّفَةِ بِـ «غَيْرُ» وَالإِضَافَةِ',
    instructionEn: 'Prefixing «غَيْرُ» negates the adjective into "un-" or "non-", turning the adjective into a genitive Mudaf Ilayh (ـٍ)',
    instructionBn: 'কোনো সিফাতের শুরুতে «غَيْرُ» যোগ করলে তা বিপরীত অর্থ দেয় এবং পরবর্তী শব্দটি মুদাফ ইলাইহি হিসেবে কাসরাহ (যের) যুক্ত হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-ghayr-mahir',
          ar: 'مَاهِرٌ ➔ غَيْرُ مَاهِرٍ',
          romanized: 'māhirun ➔ ghayru māhirin',
          meaningEn: 'Skilled ➔ Unskilled (Non-skilled)',
          meaningBn: 'দক্ষ ➔ অদক্ষ',
          exampleAr: 'رَاشِدٌ لَاعِبٌ مَاهِرٌ وَ أَنْتَ لَاعِبٌ غَيْرُ مَاهِرٍ',
          exampleEn: 'Rashid is a skilled player and you are an unskilled player.',
          exampleBn: 'রাশেদ একজন দক্ষ খেলোয়াড় এবং তুমি একজন অদক্ষ খেলোয়াড়।',
          audioKey: 'ghayru_mahir',
          exampleAudioKey: 'rashidun_laibun_mahir_wa_anta_laibun_ghayru_mahir',
          emoji: '⚽',
          compound: {
            baseAr: 'مَاهِرٌ',
            baseRom: 'māhirun',
            baseMeaningEn: 'Skilled',
            baseMeaningBn: 'দক্ষ',
            baseAudioKey: 'mahirun',
            operator: '+',
            particleAr: 'غَيْرُ',
            particleEn: 'non- / un- (Negator & Mudaf)',
            resultAr: 'غَيْرُ مَاهِرٍ',
            resultRom: 'ghayru māhirin',
            resultMeaningEn: 'Unskilled (Genitive Kasrah)',
            resultMeaningBn: 'অদক্ষ (কাসরাহ যুক্ত)',
            resultAudioKey: 'ghayru_mahir',
            badge: 'Ghayr Mudaf Construct',
          },
        },
        {
          id: 'cp-ghayr-ladhidh',
          ar: 'لَذِيذٌ ➔ غَيْرُ لَذِيذٍ',
          romanized: 'ladhīdhun ➔ ghayru ladhīdhin',
          meaningEn: 'Delicious ➔ Not delicious',
          meaningBn: 'সুস্বাদু ➔ অস্বাদু (সুস্বাদু নয়)',
          exampleAr: 'هَذِهِ سَمَكَةٌ لَذِيذَةٌ وَ تِلْكَ سَمَكَةٌ غَيْرُ لَذِيذَةٍ',
          exampleEn: 'This is a delicious fish and that is a fish that is not delicious.',
          exampleBn: 'এটি একটি সুস্বাদু মাছ এবং ওটি একটি স্বাদহীন মাছ।',
          audioKey: 'ghayru_ladhidh',
          exampleAudioKey: 'hadhihi_samakatun_ladhidhatun_wa_tilka_ghayru_ladhidhah',
          emoji: '🐟',
          compound: {
            baseAr: 'لَذِيذَةٌ',
            baseRom: 'ladhīdhatun',
            baseMeaningEn: 'Delicious (f)',
            baseMeaningBn: 'সুস্বাদু',
            baseAudioKey: 'ladhidhatun',
            operator: '+',
            particleAr: 'غَيْرُ',
            particleEn: 'un- / non-',
            resultAr: 'غَيْرُ لَذِيذَةٍ',
            resultRom: 'ghayru ladhīdhatin',
            resultMeaningEn: 'Not delicious (f)',
            resultMeaningBn: 'স্বাদহীন (স্ত্রীবাচক)',
            resultAudioKey: 'ghayru_ladhidhah',
            badge: 'Ghayr Feminine Construct',
          },
        },
      ],
    },
  },

  // 6. Concept Discovery: Focal Question (أَ alone) vs Alternative Question (أَ ... أَمْ)
  {
    id: 'ch2-l3-step-6-concept-focus-interrogation',
    type: 'concept_intro',
    pageNumber: 63,
    titleEn: 'Focal (أَ) vs Alternative (أَ ... أَمْ) Questions',
    titleAr: 'السُّؤَالُ بِهَمْزَةِ الاِسْتِفْهَامِ: مُفْرَدًا وَمَعَ «أَمْ»',
    instructionEn: 'Notice the contrast: Focal questions with أَ alone accept نَعَمْ or لَا, but alternative questions with أَمْ demand choosing the item directly',
    instructionBn: 'লক্ষ্য করো: শুধু «أَ» দিয়ে প্রশ্ন করলে «نَعَمْ» বা «لَا» দিয়ে উত্তর দেওয়া যায়, কিন্তু «أَمْ» যুক্ত বিকল্প প্রশ্নে সরাসরি বিষয়টির নাম বলতে হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-focus-yes-no',
          ar: 'أَ مُسْلِمٌ أَنْتَ ؟ ➔ نَعَمْ .. أَنَا مُسْلِمٌ',
          romanized: 'a muslimun anta? ➔ na‘am .. anā muslimun',
          meaningEn: 'Are you a Muslim? (Focus on Muslim) ➔ Yes, I am a Muslim.',
          meaningBn: 'তুমি কি মুসলিম? ➔ হ্যাঁ, আমি একজন মুসলিম।',
          exampleAr: 'أَ مُسْلِمٌ أَنْتَ ؟ نَعَمْ .. أَنَا مُسْلِمٌ',
          exampleEn: 'Are you a Muslim? Yes, I am a Muslim.',
          exampleBn: 'তুমি কি মুসলিম? হ্যাঁ, আমি একজন মুসলিম।',
          audioKey: 'a_muslimun_anta',
          exampleAudioKey: 'naam_ana_muslim',
          emoji: '🕌',
          compound: {
            baseAr: 'أَنْتَ مُسْلِمٌ',
            baseRom: 'anta muslimun',
            baseMeaningEn: 'You are a Muslim',
            baseMeaningBn: 'তুমি একজন মুসলিম',
            baseAudioKey: 'anta_muslimun',
            operator: '+',
            particleAr: 'أَ',
            particleEn: 'Focal Interrogative Hamzah',
            resultAr: 'أَ مُسْلِمٌ أَنْتَ ؟',
            resultRom: 'a muslimun anta?',
            resultMeaningEn: 'Focal Question: Are you a Muslim?',
            resultMeaningBn: 'ফোকাস প্রশ্ন: তুমি কি মুসলিম?',
            resultAudioKey: 'a_muslimun_anta',
            badge: 'Focal Interrogation',
          },
        },
        {
          id: 'cp-alternative-choice',
          ar: 'أَ مُسْلِمٌ أَنْتَ أَمْ مُشْرِكٌ ؟ ➔ مُسْلِمٌ',
          romanized: 'a muslimun anta am mushrikun? ➔ muslimun',
          meaningEn: 'Are you a Muslim or a polytheist? ➔ A Muslim (Direct choice, no Na‘am/La!)',
          meaningBn: 'তুমি কি মুসলিম, না মুশরিক? ➔ মুসলিম (সরাসরি উত্তর, হ্যাঁ/না নয়!)',
          exampleAr: 'أَ مُسْلِمٌ أَنْتَ أَمْ مُشْرِكٌ ؟ مُسْلِمٌ',
          exampleEn: 'Are you a Muslim or a polytheist? A Muslim.',
          exampleBn: 'তুমি কি মুসলিম, না মুশরিক? মুসলিম।',
          audioKey: 'a_muslimun_anta_am_mushrik',
          exampleAudioKey: 'muslimun',
          emoji: '⭐',
          compound: {
            baseAr: 'مُسْلِمٌ أَمْ مُشْرِكٌ',
            baseRom: 'muslimun am mushrikun',
            baseMeaningEn: 'Muslim or polytheist',
            baseMeaningBn: 'মুসলিম না মুশরিক',
            baseAudioKey: 'muslimun_am_mushrikun',
            operator: '+',
            particleAr: 'أَ ... أَمْ',
            particleEn: 'Disjunctive Choice Formula',
            resultAr: 'أَ مُسْلِمٌ أَنْتَ أَمْ مُشْرِكٌ ؟',
            resultRom: 'a muslimun anta am mushrikun?',
            resultMeaningEn: 'Alternative: Are you a Muslim or a polytheist?',
            resultMeaningBn: 'বিকল্প প্রশ্ন: তুমি কি মুসলিম, না মুশরিক?',
            resultAudioKey: 'a_muslimun_anta_am_mushrik',
            badge: 'Disjunctive Alternative',
          },
        },
      ],
    },
  },

  // 7. Dialogic Alternative Q&A Battery 1: Characters & Community (Pages 60-61)
  {
    id: 'ch2-l3-step-7-alt-qa-community',
    type: 'alternative_qa',
    pageNumber: 60,
    titleEn: 'Dialogue Battery: Characters & Community',
    titleAr: 'حِوَارُ الشَّخْصِيَّاتِ وَالمُجْتَمَعِ',
    instructionEn: 'Select the grammatically accurate response verifying character attributes and pronoun agreement',
    instructionBn: 'চরিত্রের গুণাবলী ও সর্বনামের সামঞ্জস্য বজায় রেখে ব্যাকরণগতভাবে সঠিক উত্তর নির্বাচন করুন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l3-1',
          questionAr: 'هَلْ مَاجِدٌ تَاجِرٌ أَمِينٌ ؟',
          optionsAr: ['نَعَمْ .. هُوَ تَاجِرٌ أَمِينٌ', 'نَعَمْ .. هِيَ تَاجِرَةٌ أَمِينَةٌ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ تَاجِرٌ أَمِينٌ',
        },
        {
          id: 'qa-c2l3-2',
          questionAr: 'هَلْ مَحْمُودٌ رَجُلٌ سَخِيٌّ ؟',
          optionsAr: ['نَعَمْ .. هُوَ رَجُلٌ سَخِيٌّ', 'نَعَمْ .. هُوَ رَجُلٌ سَخِيَّةٌ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ رَجُلٌ سَخِيٌّ',
        },
        {
          id: 'qa-c2l3-3',
          questionAr: 'كَيْفَ قَلْبُهُ ؟',
          optionsAr: ['قَلْبُهُ وَاسِعٌ', 'قَلْبُهُ وَاسِعَةٌ'],
          correctAnswerAr: 'قَلْبُهُ وَاسِعٌ',
        },
        {
          id: 'qa-c2l3-4',
          questionAr: 'هَلْ فَرْحَانَةُ امْرَأَةٌ كَسْلَانَةُ ؟',
          optionsAr: ['نَعَمْ .. هِيَ امْرَأَةٌ كَسْلَانَةُ', 'نَعَمْ .. هُوَ رَجُلٌ كَسْلَانُ'],
          correctAnswerAr: 'نَعَمْ .. هِيَ امْرَأَةٌ كَسْلَانَةُ',
        },
        {
          id: 'qa-c2l3-5',
          questionAr: 'هَلْ بَشِيرٌ كَاتِبٌ مَشْهُورٌ ؟',
          optionsAr: ['نَعَمْ .. هُوَ كَاتِبٌ مَشْهُورٌ', 'نَعَمْ .. هِيَ كَاتِبَةٌ مَشْهُورَةٌ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ كَاتِبٌ مَشْهُورٌ',
        },
      ],
    },
  },

  // 8. Page 60: Authentic Reading & Translation Drill 1: Majid the Honest Merchant
  {
    id: 'ch2-l3-step-8-assembly-majid-merchant',
    type: 'sentence_assembly',
    pageNumber: 60,
    titleEn: 'Textbook Translation: Majid the Merchant',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: مَاجِدٌ التَّاجِرُ الأَمِينُ',
    instructionEn: 'Read the Arabic sentence and assemble the accurate translation using word chips.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং শব্দ চিপস সাজিয়ে সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'مَاجِدٌ تَاجِرٌ كَبِيرٌ وَأَمِينٌ',
      promptEn: 'Majid is a big and trustworthy merchant',
      promptBn: 'মাজেদ একজন বড় ও বিশ্বস্ত ব্যবসায়ী',
      expectedAnswer: ['Majid', 'is', 'a', 'big', 'and', 'honest', 'merchant'],
      chips: ['Majid', 'is', 'a', 'big', 'and', 'honest', 'merchant', 'lazy', 'cook', 'miserly'],
      expectedAnswerBn: ['মাজেদ', 'একজন', 'বড়', 'ও', 'বিশ্বস্ত', 'ব্যবসায়ী'],
      chipsBn: ['মাজেদ', 'একজন', 'বড়', 'ও', 'বিশ্বস্ত', 'ব্যবসায়ী', 'অলস', 'কৃপণ'],
      emoji: '💼',
    },
  },

  // 9. Page 60: Authentic Reading & Translation Drill 2: Generous Heart with Mercy
  {
    id: 'ch2-l3-step-9-assembly-generous-heart',
    type: 'sentence_assembly',
    pageNumber: 60,
    titleEn: 'Textbook Translation: Mahmud the Generous',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: مَحْمُودٌ الرَّجُلُ السَّخِيُّ',
    instructionEn: 'Read the passage and assemble the translation in your language.',
    instructionBn: 'আরবি পাঠ্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'مَحْمُودٌ رَجُلٌ سَخِيٌّ ، قَلْبُهُ وَاسِعٌ وَفِي قَلْبِهِ رَحْمَةٌ',
      promptEn: 'Mahmud is a generous man, his heart is expansive and in his heart is mercy',
      promptBn: 'মাহমুদ একজন দানশীল ব্যক্তি, তার হৃদয় প্রশস্ত এবং তার অন্তরে দয়া আছে',
      expectedAnswer: ['Mahmud', 'is', 'a', 'generous', 'man', 'his', 'heart', 'is', 'expansive', 'and', 'in', 'his', 'heart', 'is', 'mercy'],
      chips: ['Mahmud', 'is', 'a', 'generous', 'man', 'his', 'heart', 'is', 'expansive', 'and', 'in', 'his', 'heart', 'is', 'mercy', 'narrow', 'harshness'],
      expectedAnswerBn: ['মাহমুদ', 'একজন', 'দানশীল', 'ব্যক্তি', 'তার', 'হৃদয়', 'প্রশস্ত', 'এবং', 'তার', 'অন্তরে', 'দয়া', 'আছে'],
      chipsBn: ['মাহমুদ', 'একজন', 'দানশীল', 'ব্যক্তি', 'তার', 'হৃদয়', 'প্রশস্ত', 'এবং', 'তার', 'অন্তরে', 'দয়া', 'আছে', 'সংকীর্ণ', 'কঠোরতা'],
      emoji: '❤️',
    },
  },

  // 10. Page 61: Authentic Reading & Translation Drill 3: Active & Lazy Farmer
  {
    id: 'ch2-l3-step-10-assembly-active-farmer',
    type: 'sentence_assembly',
    pageNumber: 61,
    titleEn: 'Textbook Translation: Active & Lazy Farmer',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: مَحْمُودٌ وَفَرْحَانَةُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'مَحْمُودٌ فَلَّاحٌ نَشِيطٌ وَفَرْحَانَةُ كَسْلَانَةُ',
      promptEn: 'Mahmud is an active farmer and Farhanah is lazy',
      promptBn: 'মাহমুদ একজন কর্মঠ কৃষক এবং ফারহানা অলস',
      expectedAnswer: ['Mahmud', 'is', 'an', 'active', 'farmer', 'and', 'Farhanah', 'is', 'lazy'],
      chips: ['Mahmud', 'is', 'an', 'active', 'farmer', 'and', 'Farhanah', 'is', 'lazy', 'truthful', 'writer', 'miserly'],
      expectedAnswerBn: ['মাহমুদ', 'একজন', 'কর্মঠ', 'কৃষক', 'এবং', 'ফারহানা', 'অলস'],
      chipsBn: ['মাহমুদ', 'একজন', 'কর্মঠ', 'কৃষক', 'এবং', 'ফারহানা', 'অলস', 'সত্যবাদী', 'লেখক', 'কৃপণ'],
      emoji: '🌾',
    },
  },

  // 11. Sentence Assembly Drill 4: Negated Skill with Ghayr
  {
    id: 'ch2-l3-step-11-assembly-ghayr-player',
    type: 'sentence_assembly',
    pageNumber: 62,
    titleEn: 'Sentence Building: Negation with Ghayr',
    titleAr: 'تَرْكِيبُ: أَنَا لَاعِبٌ غَيْرُ مَاهِرٍ',
    instructionEn: 'Assemble: "I am an unskillful player"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "আমি একজন অদক্ষ খেলোয়াড়"',
    assemblyPayload: {
      promptEn: 'I am an unskillful player',
      promptBn: 'আমি একজন অদক্ষ খেলোয়াড়',
      expectedAnswer: ['أَنَا', 'لَاعِبٌ', 'غَيْرُ', 'مَاهِرٍ'],
      chips: ['أَنَا', 'لَاعِبٌ', 'غَيْرُ', 'مَاهِرٍ', 'مَاهِرٌ', 'طَبَّاخٌ'],
      emoji: '⚽',
    },
  },

  // 12. Dialogic Alternative Q&A Battery 2: Negated Attributes with Ghayr (Page 62)
  {
    id: 'ch2-l3-step-12-alt-qa-ghayr-battery',
    type: 'alternative_qa',
    pageNumber: 62,
    titleEn: 'Dialogue Battery: Negation with Ghayr',
    titleAr: 'حِوَارُ الوَصْفِ المَنْفِيِّ بِـ (غَيْرِ)',
    instructionEn: 'Select the grammatically correct negation using Ghayr with Majroor desinence',
    instructionBn: '"গাইরু"-এর পরবর্তী পদের মাজরুর রূপ (জের) নিশ্চিত করে সঠিক উত্তর নির্বাচন করুন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l3-6',
          questionAr: 'هَلْ أَنْتَ لَاعِبٌ مَاهِرٌ ؟',
          optionsAr: ['لَا .. بَلْ أَنَا لَاعِبٌ غَيْرُ مَاهِرٍ', 'لَا .. بَلْ أَنَا لَاعِبٌ غَيْرُ مَاهِرٌ'],
          correctAnswerAr: 'لَا .. بَلْ أَنَا لَاعِبٌ غَيْرُ مَاهِرٍ',
        },
        {
          id: 'qa-c2l3-7',
          questionAr: 'هَلْ تِلْكَ سَمَكَةٌ لَذِيذَةٌ ؟',
          optionsAr: ['لَا .. تِلْكَ سَمَكَةٌ غَيْرُ لَذِيذَةٍ', 'لَا .. تِلْكَ سَمَكَةٌ غَيْرُ لَذِيذَةٌ'],
          correctAnswerAr: 'لَا .. تِلْكَ سَمَكَةٌ غَيْرُ لَذِيذَةٍ',
        },
        {
          id: 'qa-c2l3-8',
          questionAr: 'هَلْ هَذَا قِطَارٌ سَرِيعٌ ؟',
          optionsAr: ['لَا .. هَذَا قِطَارٌ غَيْرُ سَرِيعٍ', 'لَا .. هَذَا قِطَارٌ غَيْرُ سَرِيعٌ'],
          correctAnswerAr: 'لَا .. هَذَا قِطَارٌ غَيْرُ سَرِيعٍ',
        },
        {
          id: 'qa-c2l3-9',
          questionAr: 'هَلْ تِلْكَ جَرِيدَةٌ مَشْهُورَةٌ ؟',
          optionsAr: ['لَا .. تِلْكَ جَرِيدَةٌ غَيْرُ مَشْهُورَةٍ', 'لَا .. تِلْكَ جَرِيدَةٌ غَيْرُ مَشْهُورَةٌ'],
          correctAnswerAr: 'لَا .. تِلْكَ جَرِيدَةٌ غَيْرُ مَشْهُورَةٍ',
        },
        {
          id: 'qa-c2l3-10',
          questionAr: 'هَلْ ذَلِكَ الْجَبَلُ عَالٍ ؟',
          optionsAr: ['لَا .. ذَلِكَ الْجَبَلُ غَيْرُ عَالٍ', 'لَا .. ذَلِكَ الْجَبَلُ غَيْرُ عَالِيٌ'],
          correctAnswerAr: 'لَا .. ذَلِكَ الْجَبَلُ غَيْرُ عَالٍ',
        },
      ],
    },
  },

  // 13. Dialogic Alternative Q&A Battery 3: Focal vs Alternative Questions (Pages 63-64)
  {
    id: 'ch2-l3-step-13-alt-qa-focus-vs-alternative',
    type: 'alternative_qa',
    pageNumber: 63,
    titleEn: 'Dialogue Battery: Focal & Alternative Choices',
    titleAr: 'حِوَارُ الاِسْتِفْهَامِ التَّعْيِينِيِّ وَالتَّسْوِيَةِ',
    instructionEn: 'Select the precise answer for each focal alternative question',
    instructionBn: 'বিকল্প প্রশ্নগুলোর ক্ষেত্রে সুনির্দিষ্ট উত্তরটি বেছে নিন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l3-11',
          questionAr: 'أَ مُسْلِمٌ أَنْتَ أَمْ مُشْرِكٌ ؟',
          optionsAr: ['مُسْلِمٌ', 'نَعَمْ'],
          correctAnswerAr: 'مُسْلِمٌ',
        },
        {
          id: 'qa-c2l3-12',
          questionAr: 'أَ تِلْمِيذٌ خَالِدٌ أَمْ مُعَلِّمٌ ؟',
          optionsAr: ['مُعَلِّمٌ', 'لَا'],
          correctAnswerAr: 'مُعَلِّمٌ',
        },
        {
          id: 'qa-c2l3-13',
          questionAr: 'أَ خَالِدٌ مُعَلِّمٌ أَمْ رَاشِدٌ ؟',
          optionsAr: ['خَالِدٌ', 'نَعَمْ'],
          correctAnswerAr: 'خَالِدٌ',
        },
        {
          id: 'qa-c2l3-14',
          questionAr: 'أَ عَائِشَةُ أَنْتِ أَمْ فَاطِمَةُ ؟',
          optionsAr: ['عَائِشَةُ', 'لَا'],
          correctAnswerAr: 'عَائِشَةُ',
        },
        {
          id: 'qa-c2l3-15',
          questionAr: 'أَ قَلَمٌ هَذَا أَمْ مِسْطَرَةٌ ؟',
          optionsAr: ['مِسْطَرَةٌ', 'نَعَمْ'],
          correctAnswerAr: 'مِسْطَرَةٌ',
        },
      ],
    },
  },

  // 14. Sentence Assembly Drill 5: Rich & Humble Merchant
  {
    id: 'ch2-l3-step-14-assembly-humble-merchant',
    type: 'sentence_assembly',
    pageNumber: 61,
    titleEn: 'Sentence Building: Rich & Humble',
    titleAr: 'تَرْكِيبُ: هَذَا التَّاجِرُ غَنِيٌّ وَ مُتَوَاضِعٌ',
    instructionEn: 'Assemble: "This merchant is rich and humble"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "এই ব্যবসায়ী ধনী এবং বিনয়ী"',
    assemblyPayload: {
      promptEn: 'This merchant is rich and humble',
      promptBn: 'এই ব্যবসায়ী ধনী এবং বিনয়ী',
      expectedAnswer: ['هَذَا', 'التَّاجِرُ', 'غَنِيٌّ', 'وَ', 'مُتَوَاضِعٌ'],
      chips: ['هَذَا', 'التَّاجِرُ', 'غَنِيٌّ', 'وَ', 'مُتَوَاضِعٌ', 'مُتَكَبِّرٌ', 'فَقِيرٌ'],
      emoji: '🌱',
    },
  },

  // 15. Binary Polar Sort: Diptote Rule for كَسْلَانُ
  {
    id: 'ch2-l3-step-15-polar-kaslan-diptote',
    type: 'polar_sort',
    pageNumber: 60,
    titleEn: 'Morphological Invariant: Diptote (مَمْنُوعٌ مِنَ الصَّرْفِ)',
    titleAr: 'مَنْعُ كَلِمَةِ «كَسْلَانُ» مِنَ الصَّرْفِ',
    instructionEn: 'Adjectives on the pattern of فَعْلَانُ (like كَسْلَانُ) never accept Tanween. Choose the correct form:',
    instructionBn: '«فَعْلَانُ» ওজনে গঠিত বিশেষণ যেমন «كَسْلَانُ» (অলস) তানভীন গ্রহণ করে না। সঠিক রূপটি নির্বাচন করুন:',
    polarPayload: {
      arabicSubject: 'فَلَّاحٌ ...',
      meaningEn: 'A lazy farmer (Diptote without tanween)',
      meaningBn: 'একজন অলস কৃষক (তানভীনহীন)',
      gender: 'masculine',
      correctAnswer: 'كَسْلَانُ',
      options: ['كَسْلَانُ', 'كَسْلَانٌ'],
      emoji: '🦥',
    },
  },

  // 16. Sentence Assembly Drill 6: Skilled Cook & Tailor
  {
    id: 'ch2-l3-step-16-assembly-tailor-cook',
    type: 'sentence_assembly',
    pageNumber: 61,
    titleEn: 'Sentence Building: Cook & Tailor',
    titleAr: 'تَرْكِيبُ: فَاطِمَةُ طَبَّاخَةٌ مَاهِرَةٌ وَ بِنْتُهَا خَيَّاطَةٌ مَاهِرَةٌ',
    instructionEn: 'Assemble: "Fatimah is a skilled cook and her daughter is a skilled tailor"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "ফাতিমা একজন দক্ষ বাবুর্চি এবং তার মেয়ে একজন দক্ষ দর্জি"',
    assemblyPayload: {
      promptEn: 'Fatimah is a skilled cook and her daughter is a skilled tailor',
      promptBn: 'ফাতিমা একজন দক্ষ বাবুর্চি এবং তার মেয়ে একজন দক্ষ দর্জি',
      expectedAnswer: ['فَاطِمَةُ', 'طَبَّاخَةٌ', 'مَاهِرَةٌ', 'وَ', 'بِنْتُهَا', 'خَيَّاطَةٌ', 'مَاهِرَةٌ'],
      chips: ['فَاطِمَةُ', 'طَبَّاخَةٌ', 'مَاهِرَةٌ', 'وَ', 'بِنْتُهَا', 'خَيَّاطَةٌ', 'مَاهِرَةٌ', 'ابْنُهَا'],
      emoji: '👩‍🍳',
    },
  },

  // 17. Syntactic Tarkib Dissector: Ghayr Construct & Focal Alternative Question
  {
    id: 'ch2-l3-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 62,
    titleEn: 'Syntactic Tarkib Dissector: Negation & Focus Interrogation',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: تَرْكِيبُ «غَيْرُ» وَالاِسْتِفْهَامُ التَّعْيِينِيُّ',
    instructionEn: 'Dissect the syntactic constituents of the Ghayr genitive construct and the focal subject alternative question',
    instructionBn: '«غَيْرُ» যোগে গঠিত মুদাফ-মুদাফ ইলাইহি এবং ফোকাসড বিকল্প প্রশ্নের ব্যাকরণগত উপাদানগুলো আলাদা করুন',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c2l3-s1',
          sentenceAr: 'أَنْتَ لَاعِبٌ غَيْرُ مَاهِرٍ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مُبْتَدَأٌ مَعَ مَوْصُوفٍ وَصِفَةٍ مُضَافَةٍ)',
          sentenceTypeEn: 'Nominal Sentence (Subject + Qualified Noun + Negated Adjective Construct)',
          sentenceTypeBn: 'নামবাচক বাক্য (মুবতাদা + মাওসূফ + মুদাফযুক্ত সিফাত)',
          slots: [
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Subject Pronoun (Mubtada)',
              roleBn: 'উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'أَنْتَ',
            },
            {
              roleAr: 'خَبَرٌ وَمَوْصُوفٌ',
              roleEn: 'Predicate & Mawsoof',
              roleBn: 'খবর ও মাওসূফ',
              expectedWordAr: 'لَاعِبٌ',
            },
            {
              roleAr: 'صِفَةٌ وَمُضَافٌ',
              roleEn: 'Adjective Negator & Mudaf (Ghayr)',
              roleBn: 'সিফাত ও মুদাফ (গয়র)',
              expectedWordAr: 'غَيْرُ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ مَجْرُورٌ',
              roleEn: 'Genitive Mudaf Ilayh',
              roleBn: 'মুদাফ ইলাইহি (মাজরুর)',
              expectedWordAr: 'مَاهِرٍ',
            },
          ],
          availableWordsAr: ['مَاهِرٍ', 'أَنْتَ', 'غَيْرُ', 'لَاعِبٌ'],
        },
        {
          id: 'tarkib-c2l3-s2',
          sentenceAr: 'أَ خَالِدٌ مُعَلِّمٌ أَمْ رَاشِدٌ ؟',
          sentenceTypeAr: 'جُمْلَةٌ اسْتِفْهَامِيَّةٌ تَعْيِينِيَّةٌ (التَّرْكِيزُ عَلَى المُبْتَدَأِ)',
          sentenceTypeEn: 'Focal Alternative Interrogative (Focused Subject + Predicate + Conjunction + Alternative Subject)',
          sentenceTypeBn: 'বিকল্প প্রশ্নবোধক বাক্য (জিজ্ঞাসিত মুবতাদা + খবর + আম + দ্বিতীয় মুবতাদা)',
          slots: [
            {
              roleAr: 'هَمْزَةُ الاِسْتِفْهَامِ',
              roleEn: 'Interrogative Hamzah',
              roleBn: 'প্রশ্নবোধক হামযাহ',
              expectedWordAr: 'أَ',
            },
            {
              roleAr: 'مُبْتَدَأٌ (مُسْتَفْهَمٌ عَنْهُ)',
              roleEn: 'Focused Subject (Mubtada)',
              roleBn: 'জিজ্ঞাসিত উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'خَالِدٌ',
            },
            {
              roleAr: 'خَبَرٌ',
              roleEn: 'Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'مُعَلِّمٌ',
            },
            {
              roleAr: 'حَرْفُ عَطْفٍ مُعَادِلَةٌ',
              roleEn: 'Equaling Conjunction (Am)',
              roleBn: 'বিকল্প যোজক (আম)',
              expectedWordAr: 'أَمْ',
            },
            {
              roleAr: 'مَعْطُوفٌ',
              roleEn: 'Coordinated Alternative (Rashid)',
              roleBn: 'সংযোজিত বিকল্প পদ (রাশেদ)',
              expectedWordAr: 'رَاشِدٌ',
            },
          ],
          availableWordsAr: ['مُعَلِّمٌ', 'رَاشِدٌ', 'أَمْ', 'أَ', 'خَالِدٌ'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah Al-Fatihah 1:7)
  {
    id: 'ch2-l3-step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 62,
    titleEn: 'Sacred Reflection: Ghayr Construct in the Opening of the Quran',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: تَرْكِيبُ «غَيْرِ» فِي فَاتِحَةِ الكِتَابِ',
    instructionEn: 'Witness how «غَيْر» negates attributes and governs the genitive state in the opening chapter of the Quran (1:7)',
    instructionBn: 'সূরা আল-ফাতিহায় «غَيْر» দ্বারা গুণবাচক পদের অস্বীকৃতি ও মাজরুর করার পবিত্র ঐশী প্রয়োগ উপলব্ধি করুন।',
    echoPayload: {
      surahNumber: 1,
      ayahNumber: 7,
      surahNameAr: 'الفَاتِحَة',
      surahNameEn: 'Al-Fatihah',
      arabicText: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
      translationEn: 'The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.',
      translationBn: 'তাদের পথ যাদের আপনি অনুগ্রহ দান করেছেন, তাদের পথ নয় যারা ক্রোধে নিপতিত এবং যারা পথভ্রষ্ট নয়।',
      highlightedWords: ['غَيْرِ', 'الْمَغْضُوبِ'],
      patternNameEn: 'Attribute Negation with Ghayr (غَيْر + مُضَاف إِلَيْهِ)',
      patternNameBn: 'غَيْر দ্বারা গুণবাচক পদের অস্বীকৃতি (ইজাফাত)',
      lessonPatternAr: 'لَاعِبٌ غَيْرُ مَاهِرٍ / سَمَكَةٌ غَيْرُ لَذِيذَةٍ',
      lessonPatternEn: 'An unskilled player / A fish that is not delicious',
      lessonPatternBn: 'অদক্ষ খেলোয়াড় / স্বাদহীন মাছ',
      quranPatternAr: 'غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ',
      quranPatternEn: 'Not of those who have evoked anger',
      quranPatternBn: 'তাদের পথ নয় যারা ক্রোধে নিপতিত হয়েছে',
      reflection: "In Arabic syntax, «غَيْر» negates adjectives and acts as a governing Mudaf, rendering the subsequent word genitive (مَجْرُور). In your lesson, you built «لَاعِبٌ غَيْرُ مَاهِرٍ» (an unskilled player). In the opening chapter recited in every prayer, «غَيْرِ الْمَغْضُوبِ» applies this identical rule to distinctly contrast those blessed by Allah from those who incurred anger.",
      audioKey: 'quran_001007',
    },
  },
];

export const CH2_LESSON_03_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 2,
  lessonNum: 3,
  titleEn: 'People, Roles & Negating Attributes',
  titleAr: 'الأَوْصَافُ وَغَيْرُ',
  wordsLearned: [
    'طَبِيبٌ',
    'مَرِيضٌ',
    'كَاتِبٌ',
    'خَيَّاطٌ',
    'لَبَّانٌ',
    'صَيَّادٌ',
    'سَائِقٌ',
    'طَبَّاخٌ',
    'أَمِينٌ',
    'سَخِيٌّ',
    'بَخِيلٌ',
    'صَادِقٌ',
    'كَاذِبٌ',
    'مُتَوَاضِعٌ',
    'مُتَكَبِّرٌ',
    'كَسْلَانُ',
    'نَشِيطٌ',
    'غَيْرُ',
  ],
  steps: CH2_LESSON_03_STEPS,
};
