// Chapter 2 Lesson 5 Interactive Session Steps (Possessive Pronoun Suffixes & Anatomical Concord)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH2_LESSON_05_STEPS: SessionStep[] = [
  // 1. Spatial Pointing Anchor: Anatomy & Natural Feminine Gender
  {
    id: 'ch2-l5-step-1-spatial-eye',
    type: 'spatial_pointing',
    pageNumber: 71,
    titleEn: 'Spatial Anchor: Anatomical Demonstrative',
    titleAr: 'الإِشَارَةُ المَكَانِيَّةُ: عُضْوٌ مُؤَنَّثٌ',
    instructionEn: 'Point to this eye nearby. Remember that paired bodily organs are grammatically feminine in Arabic.',
    instructionBn: 'নিকটের একটি চোখের দিকে ইঙ্গিত করুন। মনে রাখবেন, শরীরের জোড়া অঙ্গসমূহ আরবিতে স্ত্রীলিঙ্গ।',
    spatialPointingPayload: {
      objectAr: 'عَيْنٌ',
      distance: 'near',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ عَيْنٌ',
      options: ['هَذَا عَيْنٌ', 'هَذِهِ عَيْنٌ', 'ذَلِكَ عَيْنٌ', 'تِلْكَ عَيْنٌ'],
      emoji: '👁️',
    },
  },

  // 2. Primary Vocabulary Priming: Physical Features & Facial Anatomy
  {
    id: 'ch2-l5-step-2-vocab-anatomy',
    type: 'vocab_prime',
    pageNumber: 71,
    titleEn: 'Physical Features & Facial Anatomy',
    titleAr: 'مُفْرَدَاتُ أَعْضَاءِ الوَجْهِ وَالجِسْمِ',
    instructionEn: 'Listen to classical Arabic terms for facial features and physical characteristics.',
    instructionBn: 'মুখমণ্ডল ও শরীরের অঙ্গপ্রত্যঙ্গ সম্পর্কিত মৌলিক আরবি শব্দগুলো মনোযোগ দিয়ে শুনুন।',
    vocabPayload: {
      words: [
        {
          id: 'c2l5-wajh',
          ar: 'وَجْهٌ',
          en: 'A face',
          bn: 'একটি মুখমণ্ডল বা চেহারা',
          romanized: 'wajhun',
          emoji: '😊',
        },
        {
          id: 'c2l5-ayn',
          ar: 'عَيْنٌ',
          en: 'An eye (fem. paired organ)',
          bn: 'একটি চোখ (স্ত্রীলিঙ্গ)',
          romanized: "'aynun",
          emoji: '👁️',
        },
        {
          id: 'c2l5-anf',
          ar: 'أَنْفٌ',
          en: 'A nose',
          bn: 'একটি নাক',
          romanized: 'anfun',
          emoji: '👃',
        },
        {
          id: 'c2l5-shar',
          ar: 'شَعْرٌ',
          en: 'Hair',
          bn: 'চুল',
          romanized: "sha'run",
          emoji: '💇',
        },
        {
          id: 'c2l5-khadd',
          ar: 'خَدٌّ',
          en: 'A cheek',
          bn: 'একটি গাল',
          romanized: 'khaddun',
          emoji: '😊',
        },
        {
          id: 'c2l5-lawn',
          ar: 'لَوْنٌ',
          en: 'A colour',
          bn: 'একটি রং বা বর্ণ',
          romanized: 'lawnun',
          emoji: '🎨',
        },
      ],
    },
  },

  // 3. Secondary Vocabulary Priming: Anatomy & Relational Terms
  {
    id: 'ch2-l5-step-3-vocab-relational',
    type: 'vocab_prime',
    pageNumber: 72,
    titleEn: 'Body & Relational Vocabulary',
    titleAr: 'مُفْرَدَاتُ الجِسْمِ وَالعَلَاقَاتِ',
    instructionEn: 'Expand your vocabulary with body dimensions and relational terminology.',
    instructionBn: 'শরীরের আরও কিছু অংশ এবং সামাজিক সম্পর্ক সম্পর্কিত শব্দগুলো জানুন।',
    vocabPayload: {
      words: [
        {
          id: 'c2l5-batn',
          ar: 'بَطْنٌ',
          en: 'A belly / stomach',
          bn: 'একটি পেট',
          romanized: 'batnun',
          emoji: '🫃',
        },
        {
          id: 'c2l5-zahr',
          ar: 'ظَهْرٌ',
          en: 'A back',
          bn: 'একটি পিঠ',
          romanized: 'zahrun',
          emoji: '🧍',
        },
        {
          id: 'c2l5-zamil',
          ar: 'زَمِيلٌ',
          en: 'A classmate / colleague',
          bn: 'সহপাঠী বা সাথী',
          romanized: 'zamīlun',
          emoji: '🤝',
        },
        {
          id: 'c2l5-raihah',
          ar: 'رَائِحَةٌ',
          en: 'A scent / fragrance',
          bn: 'সুঘ্রাণ বা গন্ধ',
          romanized: "rā'ihatun",
          emoji: '🌸',
        },
        {
          id: 'c2l5-abd',
          ar: 'عَبْدٌ',
          en: 'A servant / slave',
          bn: 'বান্দা বা দাস',
          romanized: "'abdun",
          emoji: '🤲',
        },
        {
          id: 'c2l5-midhanah',
          ar: 'مِئْذَنَةٌ',
          en: 'A minaret',
          bn: 'একটি মিনার',
          romanized: "mi'dhanatun",
          emoji: '🕌',
        },
      ],
    },
  },

  // 4. Synaptic Speed Match: Anatomical Lexicon
  {
    id: 'ch2-l5-step-4-speed-anatomy',
    type: 'speed_pair',
    pageNumber: 71,
    titleEn: 'Synaptic Speed Pairing: Anatomy',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: مُفْرَدَاتُ الجِسْمِ',
    instructionEn: 'Quickly match each Arabic anatomical term to its English meaning.',
    instructionBn: 'শরীরের বিভিন্ন অঙ্গের আরবি শব্দের সাথে সঠিক অর্থের দ্রুত সংযোগ স্থাপন করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c2l5-1', ar: 'وَجْهٌ', meaning: 'Face' },
        { id: 'p-c2l5-2', ar: 'عَيْنٌ', meaning: 'Eye (fem.)' },
        { id: 'p-c2l5-3', ar: 'أَنْفٌ', meaning: 'Nose' },
        { id: 'p-c2l5-4', ar: 'شَعْرٌ', meaning: 'Hair' },
        { id: 'p-c2l5-5', ar: 'بَطْنٌ', meaning: 'Belly' },
        { id: 'p-c2l5-6', ar: 'خَدٌّ', meaning: 'Cheek' },
      ],
    },
  },

  // 5. Concept Discovery: Attached Possessive Pronouns
  {
    id: 'ch2-l5-step-5-concept-pronouns',
    type: 'concept_intro',
    pageNumber: 71,
    titleEn: 'Grammar Paradigm: Attached Possessive Pronouns',
    titleAr: 'قَاعِدَةٌ: الضَّمَائِرُ الْمُتَّصِلَةُ لِلْمِلْكِيَّةِ',
    instructionEn: 'Nouns take attached pronoun suffixes to denote ownership: «ـِي» (my), «ـكَ» (your m.), «ـكِ» (your f.), «ـهُ» (his), «ـهَا» (her).',
    instructionBn: 'শব্দের শেষে যুক্ত সর্বনাম যোগ করে মালিকানা বোঝানো হয়: «ـِي» (আমার), «ـكَ» (তোমার পুং), «ـكِ» (তোমার স্ত্রী), «ـهُ» (তার পুং), «ـهَا» (তার স্ত্রী)।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c2l5-my',
          ar: 'بَيْتِي',
          romanized: 'baytī',
          meaningEn: 'My house (Noun + ـِي)',
          meaningBn: 'আমার বাড়ি',
          exampleAr: 'هَذَا بَيْتِي وَذَلِكَ بَيْتُكَ',
          exampleEn: 'This is my house and that is your house.',
          exampleBn: 'এটি আমার বাড়ি এবং ওটি তোমার বাড়ি।',
          audioKey: 'bayti',
          exampleAudioKey: 'hadha_bayti_wa_dhalika_baytuka',
          emoji: '🏡',
        },
        {
          id: 'cp-c2l5-your-m',
          ar: 'بَيْتُكَ',
          romanized: 'baytuka',
          meaningEn: 'Your house (masc.) (Noun + ـكَ)',
          meaningBn: 'তোমার বাড়ি (পুরুষ)',
          exampleAr: 'بَيْتُكَ جَدِيدٌ',
          exampleEn: 'Your house is new.',
          exampleBn: 'তোমার বাড়িটি নতুন।',
          audioKey: 'baytuka',
          exampleAudioKey: 'baytuka_jadid',
          emoji: '🏠',
        },
        {
          id: 'cp-c2l5-his',
          ar: 'بَيْتُهُ',
          romanized: 'baytuhu',
          meaningEn: 'His house (Noun + ـهُ)',
          meaningBn: 'তার বাড়ি (পুরুষ)',
          exampleAr: 'بَيْتُهُ جَدِيدٌ وَجَمِيلٌ',
          exampleEn: 'His house is new and beautiful.',
          exampleBn: 'তার বাড়ি নতুন ও সুন্দর।',
          audioKey: 'baytuhu',
          exampleAudioKey: 'baytuhu_jadid_wa_jamil',
          emoji: '🏘️',
        },
        {
          id: 'cp-c2l5-her',
          ar: 'شَعْرُهَا',
          romanized: "sha'ruhā",
          meaningEn: 'Her hair (Noun + ـهَا)',
          meaningBn: 'তার চুল (মহিলা)',
          exampleAr: 'شَعْرُهَا طَوِيلٌ وَلَوْنُهُ جَمِيلٌ',
          exampleEn: 'Her hair is long and its color is beautiful.',
          exampleBn: 'তার চুল লম্বা এবং তার রং সুন্দর।',
          audioKey: 'sharuha',
          exampleAudioKey: 'sharuha_tawil_wa_lawnuhu_jamil',
          emoji: '💇‍♀️',
        },
      ],
    },
  },

  // 6. Deep Pedagogical Concept: Paired Bodily Organs are Inherent Feminines
  {
    id: 'ch2-l5-step-6-concept-paired-gender',
    type: 'concept_intro',
    pageNumber: 71,
    titleEn: 'Syntactic Rule: Natural Gender of Paired Body Parts',
    titleAr: 'قَاعِدَةٌ: تَأْنِيثُ أَعْضَاءِ الجِسْمِ المُزْدَوَجَةِ',
    instructionEn: 'In Arabic, bodily organs that naturally occur in pairs (eyes, ears, hands, feet) are treated as grammatically feminine, requiring feminine adjectives.',
    instructionBn: 'আরবি ভাষায় শরীরের যেসব অঙ্গ জোড়ায় জোড়ায় থাকে (চোখ, কান, হাত, পা) সেগুলো ব্যাকরণগতভাবে স্ত্রীলিঙ্গ, তাই তাদের বিশেষণও স্ত্রীলিঙ্গ হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c2l5-eye-fem',
          ar: 'عَيْنٌ جَمِيلَةٌ',
          romanized: "'aynun jamīlatun",
          meaningEn: 'A beautiful eye (Feminine agreement)',
          meaningBn: 'একটি সুন্দর চোখ (স্ত্রীলিঙ্গ বিশেষণ)',
          exampleAr: 'هَذِهِ عَيْنٌ جَمِيلَةٌ',
          exampleEn: 'This is a beautiful eye.',
          exampleBn: 'এটি একটি সুন্দর চোখ।',
          audioKey: 'aynun_jamilah',
          exampleAudioKey: 'hadhihi_aynun_jamilah',
          emoji: '👁️',
        },
        {
          id: 'cp-c2l5-face-masc',
          ar: 'وَجْهٌ جَمِيلٌ',
          romanized: 'wajhun jamīlun',
          meaningEn: 'A handsome face (Masculine agreement)',
          meaningBn: 'একটি সুন্দর মুখ (পুংলিঙ্গ বিশেষণ)',
          exampleAr: 'هَذَا وَجْهٌ جَمِيلٌ',
          exampleEn: 'This is a handsome face.',
          exampleBn: 'এটি একটি সুন্দর মুখ।',
          audioKey: 'wajhun_jamil',
          exampleAudioKey: 'hadha_wajhun_jamil',
          emoji: '😊',
        },
      ],
    },
  },

  // 7. Polar Sort 1: Inherent Bodily Gender Sort
  {
    id: 'ch2-l5-step-7-polar-body-gender',
    type: 'polar_sort',
    pageNumber: 71,
    titleEn: 'Binary Gender Sort: Bodily Organs',
    titleAr: 'تَمْيِيزُ التَّذْكِيرِ وَالتَّأْنِيثِ فِي الأَعْضَاءِ',
    instructionEn: 'Identify the grammatical gender of the paired bodily organ «عَيْنٌ» (eye).',
    instructionBn: 'জোড়া অঙ্গ «عَيْنٌ» (চোখ)-এর ব্যাকরণগত লিঙ্গ শনাক্ত করুন।',
    polarPayload: {
      arabicSubject: 'عَيْنٌ',
      meaningEn: 'An eye (paired body part)',
      meaningBn: 'একটি চোখ (শরীরের জোড়া অঙ্গ)',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ عَيْنٌ جَمِيلَةٌ',
      options: ['هَذَا عَيْنٌ جَمِيلٌ', 'هَذِهِ عَيْنٌ جَمِيلَةٌ'],
      emoji: '👁️',
    },
  },

  // 8. Polar Sort 2: Direct Address Pronoun Concord (ـكَ vs ـكِ)
  {
    id: 'ch2-l5-step-8-polar-address-gender',
    type: 'polar_sort',
    pageNumber: 72,
    titleEn: 'Binary Pronoun Concord: Addressing Mother vs Friend',
    titleAr: 'تَمْيِيزُ ضَمِيرِ المُخَاطَبِ (ـكَ / ـكِ)',
    instructionEn: 'Shahed is speaking directly to his mother. Which possessive suffix correctly addresses her?',
    instructionBn: 'শাহেদ তার আম্মাকে সম্বোধন করে কথা বলছে। কোন সর্বনামটি উপযুক্ত?',
    polarPayload: {
      arabicSubject: 'غُرْفَةُ',
      meaningEn: 'Your room (addressing mother)',
      meaningBn: 'তোমার কামরা (মাকে সম্বোধন করে)',
      gender: 'feminine',
      correctAnswer: 'غُرْفَتُكِ',
      options: ['غُرْفَتُكَ', 'غُرْفَتُكِ'],
      emoji: '🛏️',
    },
  },

  // 9. Cloze Choice Drill 1: Khalid Describing Majid's Car
  {
    id: 'ch2-l5-step-9-cloze-car-possession',
    type: 'cloze_choice',
    pageNumber: 72,
    titleEn: 'Contextual Suffix: Third-Person Masculine Possession',
    titleAr: 'اخْتِيَارُ الضَّمِيرِ: سَيَّارَةُ خَالِدٍ',
    instructionEn: 'Select the correct possessive form: "That is Khalid’s car; his car is beautiful."',
    instructionBn: '"ওটি খালেদের গাড়ি; তার গাড়িটি সুন্দর" বাক্যটি পূর্ণ করতে সঠিক শব্দ নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'تِلْكَ سَيَّارَةُ خَالِدٍ ، ... جَمِيلَةٌ',
      questionEn: 'That is Khalid’s car, his car is beautiful.',
      questionBn: 'ওটি খালেদের গাড়ি, তার গাড়িটি সুন্দর।',
      partialAnswerAr: 'تِلْكَ سَيَّارَةُ خَالِدٍ ، ... جَمِيلَةٌ',
      correctAnswer: 'سَيَّارَتُهُ',
      options: ['سَيَّارَتُهُ', 'سَيَّارَتُهَا', 'سَيَّارَتِي', 'سَيَّارَتُكَ'],
      emoji: '🚗',
    },
  },

  // 10. Cloze Choice Drill 2: Concord with Paired Anatomy
  {
    id: 'ch2-l5-step-10-cloze-eye-adjective',
    type: 'cloze_choice',
    pageNumber: 73,
    titleEn: 'Syntactic Concord: Feminine Paired Organ',
    titleAr: 'اخْتِيَارُ الصِّفَةِ: عَيْنُ الطِّفْلِ',
    instructionEn: 'Select the correct adjective form: "The child’s face is handsome, and his eye is beautiful."',
    instructionBn: '"বাচ্চাটির মুখ সুন্দর এবং তার চোখ সুন্দর" বাক্যে চোখের জন্য সঠিক বিশেষণটি নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'وَجْهُ الطِّفْلِ جَمِيلٌ ، وَعَيْنُهُ ...',
      questionEn: 'The face of the child is handsome, and his eye is beautiful.',
      questionBn: 'বাচ্চাটির চেহারা সুন্দর, এবং তার চোখ সুন্দর।',
      partialAnswerAr: 'وَجْهُ الطِّفْلِ جَمِيلٌ ، وَعَيْنُهُ ...',
      correctAnswer: 'جَمِيلَةٌ',
      options: ['جَمِيلَةٌ', 'جَمِيلٌ', 'كَبِيرٌ', 'طَوِيلٌ'],
      emoji: '👶',
    },
  },

  // 11. Dialogic Alternative Q&A Battery 1: Paternal & Kinship Questions
  {
    id: 'ch2-l5-step-11-dialogue-kinship',
    type: 'alternative_qa',
    pageNumber: 74,
    titleEn: 'Dialogic Battery: Kinship & Paternal Questions',
    titleAr: 'حِوَارُ القَرَابَةِ: الأَسْئِلَةُ التَّعْيِينِيَّةُ',
    instructionEn: 'Select the grammatically accurate answer verifying kinship relations and pronoun shifts.',
    instructionBn: 'আত্মীয়তার পরিচয় ও সর্বনামের রূপান্তর লক্ষ্য রেখে ব্যাকরণগতভাবে সঠিক উত্তর দিন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l5-1',
          questionAr: 'هَلْ هَذَا الرَّجُلُ أَبُوكَ ؟ (👨‍👧 أَبِي)',
          optionsAr: ['نَعَمْ .. هُوَ أَبِي', 'نَعَمْ .. هُوَ أَبُوكَ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ أَبِي',
        },
        {
          id: 'qa-c2l5-2',
          questionAr: 'أَ أَبُوكَ هَذَا الرَّجُلُ ؟ (👨‍👧 أَبِي)',
          optionsAr: ['نَعَمْ .. هُوَ أَبِي', 'نَعَمْ .. هِيَ أُمِّي'],
          correctAnswerAr: 'نَعَمْ .. هُوَ أَبِي',
        },
        {
          id: 'qa-c2l5-3',
          questionAr: 'أَ عَمُّكَ هَذَا الرَّجُلُ ؟ (👨‍👧 أَبِي)',
          optionsAr: ['لَا .. بَلْ هُوَ أَبِي', 'لَا .. بَلْ هُوَ عَمِّي'],
          correctAnswerAr: 'لَا .. بَلْ هُوَ أَبِي',
        },
        {
          id: 'qa-c2l5-4',
          questionAr: 'أَ أَبُوكَ هَذَا الرَّجُلُ أَمْ عَمُّكَ ؟ (👨‍👧 أَبِي)',
          optionsAr: ['أَبِي', 'نَعَمْ'],
          correctAnswerAr: 'أَبِي',
        },
        {
          id: 'qa-c2l5-5',
          questionAr: 'أَ هَذَا الرَّجُلُ أَبُوكَ أَمْ ذَلِكَ الرَّجُلُ ؟ (👉 هَذَا)',
          optionsAr: ['هَذَا الرَّجُلُ', 'لَا'],
          correctAnswerAr: 'هَذَا الرَّجُلُ',
        },
      ],
    },
  },

  // 12. Dialogic Alternative Q&A Battery 2: Friendship & Identity
  {
    id: 'ch2-l5-step-12-dialogue-friendship',
    type: 'alternative_qa',
    pageNumber: 74,
    titleEn: 'Dialogic Battery: Friendship & Comradeship',
    titleAr: 'حِوَارُ الصَّدَاقَةِ: اخْتِيَارُ الصَّدِيقِ',
    instructionEn: 'Select the precise response discerning between friends and associates without using yes/no in alternatives.',
    instructionBn: 'বিকল্প প্রশ্নে হ্যাঁ বা না ছাড়া সুনির্দিষ্ট পরিচয় ও সর্বনামের সঠিক ব্যবহার নিশ্চিত করে উত্তর দিন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l5-6',
          questionAr: 'هَلْ مَاجِدٌ صَدِيقُكَ ؟ (🤝 صَدِيقِي)',
          optionsAr: ['نَعَمْ .. هُوَ صَدِيقِي', 'نَعَمْ .. هُوَ صَدِيقُكَ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ صَدِيقِي',
        },
        {
          id: 'qa-c2l5-7',
          questionAr: 'أَ خَالِدٌ صَدِيقُكَ ؟ (🤝 مَاجِدٌ)',
          optionsAr: ['لَا .. بَلْ مَاجِدٌ', 'لَا .. بَلْ خَالِدٌ'],
          correctAnswerAr: 'لَا .. بَلْ مَاجِدٌ',
        },
        {
          id: 'qa-c2l5-8',
          questionAr: 'أَ مَاجِدٌ صَدِيقُكَ أَمْ خَالِدٌ ؟ (🤝 مَاجِدٌ)',
          optionsAr: ['مَاجِدٌ', 'نَعَمْ'],
          correctAnswerAr: 'مَاجِدٌ',
        },
        {
          id: 'qa-c2l5-9',
          questionAr: 'أَ صَدِيقُكَ مَاجِدٌ أَمْ أَخُوكَ ؟ (🤝 صَدِيقِي)',
          optionsAr: ['صَدِيقِي', 'لَا'],
          correctAnswerAr: 'صَدِيقِي',
        },
        {
          id: 'qa-c2l5-10',
          questionAr: 'أَ صَدِيقُكَ مَاجِدٌ أَمْ صَدِيقُ خَالِدٍ ؟ (🤝 صَدِيقِي)',
          optionsAr: ['صَدِيقِي', 'صَدِيقُكَ'],
          correctAnswerAr: 'صَدِيقِي',
        },
      ],
    },
  },

  // 13. Speed Pair Matching 2: Relational Phrases with Attached Pronouns
  {
    id: 'ch2-l5-step-13-speed-phrases',
    type: 'speed_pair',
    pageNumber: 72,
    titleEn: 'Synaptic Speed Pairing: Relational Dialogue',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: الجُمَلُ الإِضَافِيَّةُ',
    instructionEn: 'Pair the possessive Arabic dialogues with their fluent English translations.',
    instructionBn: 'যুক্ত সর্বনামবিশিষ্ট আরবি বাক্যগুলোর সাথে তাদের অনুবাদের দ্রুত মিল করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c2l5-7', ar: 'أَنْتَ صَدِيقِي', meaning: 'You are my friend' },
        { id: 'p-c2l5-8', ar: 'أَنَا صَدِيقُكَ', meaning: 'I am your friend' },
        { id: 'p-c2l5-9', ar: 'سَيَّارَتُهُ جَمِيلَةٌ', meaning: 'His car is beautiful' },
        { id: 'p-c2l5-10', ar: 'لَوْنُهَا جَمِيلٌ', meaning: 'Its color is beautiful' },
        { id: 'p-c2l5-11', ar: 'مِفْتَاحُهُ فِي جَيْبِهِ', meaning: 'His key is in his pocket' },
      ],
    },
  },

  // 14. Sentence Assembly Drill 1: Shahed & Majid Dialogue
  {
    id: 'ch2-l5-step-14-assembly-houses',
    type: 'sentence_assembly',
    pageNumber: 71,
    titleEn: 'Sentence Assembly: Houses Contrast',
    titleAr: 'تَرْكِيبُ: بَيْتِي قَدِيمٌ وَبَيْتُكَ جَدِيدٌ',
    instructionEn: 'Assemble: "My house is old and your house is new."',
    instructionBn: 'শব্দগুলো সাজিয়ে বাক্য গঠন করুন: "আমার বাড়ি পুরনো এবং তোমার বাড়ি নতুন।"',
    assemblyPayload: {
      promptEn: 'My house is old and your house is new.',
      promptBn: 'আমার বাড়ি পুরনো এবং তোমার বাড়ি নতুন।',
      expectedAnswer: ['بَيْتِي', 'قَدِيمٌ', 'وَ', 'بَيْتُكَ', 'جَدِيدٌ'],
      chips: ['بَيْتِي', 'قَدِيمٌ', 'وَ', 'بَيْتُكَ', 'جَدِيدٌ', 'سَيَّارَتُهُ', 'نَظِيفٌ'],
      emoji: '🏡',
    },
  },

  // 15. Sentence Assembly Drill 2: Fatima’s Description
  {
    id: 'ch2-l5-step-15-assembly-hair',
    type: 'sentence_assembly',
    pageNumber: 72,
    titleEn: 'Sentence Assembly: Fatima’s Hair & Color',
    titleAr: 'تَرْكِيبُ: شَعْرُهَا طَوِيلٌ وَلَوْنُهُ جَمِيلٌ',
    instructionEn: 'Assemble: "Her hair is long and its color is beautiful."',
    instructionBn: 'শব্দগুলো সাজিয়ে বাক্য গঠন করুন: "তার চুল লম্বা এবং তার রং সুন্দর।"',
    assemblyPayload: {
      promptEn: 'Her hair is long and its color is beautiful.',
      promptBn: 'তার চুল লম্বা এবং তার রং সুন্দর।',
      expectedAnswer: ['شَعْرُهَا', 'طَوِيلٌ', 'وَ', 'لَوْنُهُ', 'جَمِيلٌ'],
      chips: ['شَعْرُهَا', 'طَوِيلٌ', 'وَ', 'لَوْنُهُ', 'جَمِيلٌ', 'قَصِيرٌ', 'عَيْنُهَا'],
      emoji: '💇‍♀️',
    },
  },

  // 16. Sentence Assembly Drill 3: Teacher Majid’s Key in Pocket
  {
    id: 'ch2-l5-step-16-assembly-pocket',
    type: 'sentence_assembly',
    pageNumber: 72,
    titleEn: 'Sentence Assembly: Majid’s Car & Key',
    titleAr: 'تَرْكِيبُ: سَيَّارَتُهُ أَمَامَ الْبَابِ وَمِفْتَاحُهُ فِي جَيْبِهِ',
    instructionEn: 'Assemble: "His car is in front of the door and the key is in his pocket."',
    instructionBn: 'শব্দগুলো সাজিয়ে বাক্য গঠন করুন: "তার গাড়ি দরজার সামনে এবং চাবিটি তার পকেটে।"',
    assemblyPayload: {
      promptEn: 'His car is in front of the door and the key is in his pocket.',
      promptBn: 'তার গাড়ি দরজার সামনে এবং চাবিটি তার পকেটে।',
      expectedAnswer: ['سَيَّارَتُهُ', 'أَمَامَ', 'الْبَابِ', 'وَ', 'الْمِفْتَاحُ', 'فِي', 'جَيْبِهِ'],
      chips: ['سَيَّارَتُهُ', 'أَمَامَ', 'الْبَابِ', 'وَ', 'الْمِفْتَاحُ', 'فِي', 'جَيْبِهِ', 'سَاعَتُهُ'],
      emoji: '🔑',
    },
  },

  // 17. Syntactic Tarkib Dissector: Possessive Nominal Construct
  {
    id: 'ch2-l5-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 71,
    titleEn: 'Syntactic Tarkib Dissector: Possessive Subject Architecture',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: بِنَاءُ المُبْتَدَأِ المُضَافِ إِلَى ضَمِيرٍ',
    instructionEn: 'Deconstruct how a noun combined with an attached pronoun serves as the subject (Mubtada) followed by its predicate (Khabar).',
    instructionBn: 'যুক্ত সর্বনামসহ মুদাফ কীভাবে মুবতাদা গঠিত হয়ে পরবর্তী খবর গ্রহণ করে তা ব্যাকরণগতভাবে বিশ্লেষণ করুন।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c2l5-s1',
          sentenceAr: 'بَيْتُهُ جَدِيدٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مُبْتَدَأٌ مُضَافٌ إِلَى ضَمِيرٍ + خَبَرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Possessive Subject + Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (সর্বনামযুক্ত মুবতাদা + খবর)',
          slots: [
            {
              roleAr: 'مُضَافٌ (مُبْتَدَأٌ)',
              roleEn: 'Possessed Noun / Mubtada',
              roleBn: 'মুদাফ (মুবতাদা)',
              expectedWordAr: 'بَيْتُ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ (ضَمِيرٌ)',
              roleEn: 'Pronominal Possessor',
              roleBn: 'মুদাফ ইলাইহি (যুক্ত সর্বনাম)',
              expectedWordAr: 'ـهُ',
            },
            {
              roleAr: 'خَبَرٌ',
              roleEn: 'Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'جَدِيدٌ',
            },
          ],
          availableWordsAr: ['ـهُ', 'جَدِيدٌ', 'بَيْتُ'],
        },
        {
          id: 'tarkib-c2l5-s2',
          sentenceAr: 'سَيَّارَتُهَا جَمِيلَةٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مُبْتَدَأٌ مُؤَنَّثٌ مُضَافٌ + خَبَرٌ مُؤَنَّثٌ)',
          sentenceTypeEn: 'Feminine Nominal Sentence (Feminine Subject + Feminine Predicate)',
          sentenceTypeBn: 'স্ত্রীলিঙ্গ নামবাচক বাক্য (মুদাফ মুবতাদা + স্ত্রীলিঙ্গ খবর)',
          slots: [
            {
              roleAr: 'مُضَافٌ (مُبْتَدَأٌ)',
              roleEn: 'Feminine Noun / Mubtada',
              roleBn: 'স্ত্রীলিঙ্গ মুদাফ (মুবতাদা)',
              expectedWordAr: 'سَيَّارَتُ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ (ضَمِيرٌ)',
              roleEn: 'Feminine Attached Pronoun',
              roleBn: 'স্ত্রীলিঙ্গ সর্বনাম',
              expectedWordAr: 'ـهَا',
            },
            {
              roleAr: 'خَبَرٌ',
              roleEn: 'Feminine Predicate (Khabar)',
              roleBn: 'স্ত্রীলিঙ্গ খবর',
              expectedWordAr: 'جَمِيلَةٌ',
            },
          ],
          availableWordsAr: ['جَمِيلَةٌ', 'ـهَا', 'سَيَّارَتُ'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah Ta-Ha 20:25-26)
  {
    id: 'ch2-l5-step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 76,
    titleEn: 'Sacred Reflection: Attached Possessive Pronouns in Sacred Supplication',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: ضَمِيرُ المُتَكَلِّمِ فِي الدُّعَاءِ المُبَارَكِ',
    instructionEn: 'Witness how the first-person attached pronoun «ـِي» attaches to body and affairs in the timeless supplication of Musa (peace be upon him) in Surah Ta-Ha (20:25-26).',
    instructionBn: 'সূরা ত্বা-হাতে মুসা (আ.)-এর দোয়ায় শরীরের অঙ্গ ও কাজের সাথে উত্তমভাবে প্রথম পুরুষ সর্বনাম «ـِي»-এর সংযোগ প্রত্যক্ষ করুন।',
    echoPayload: {
      surahNumber: 20,
      ayahNumber: 25,
      surahNameAr: 'طه',
      surahNameEn: 'Ta-Ha',
      arabicText: 'قَالَ رَبِّ اشْرَحْ لِي صَدْرِي * وَيَسِّرْ لِي أَمْرِي',
      translationEn: '[Musa] said, "My Lord, expand for me my breast, and ease for me my task."',
      translationBn: 'মুসা বললেন, "হে আমার পালনকর্তা, আমার বক্ষ প্রশস্ত করে দিন, এবং আমার কাজ সহজ করে দিন।"',
      highlightedWords: ['رَبِّ', 'صَدْرِي', 'أَمْرِي'],
      patternNameEn: 'First-Person Attached Pronoun (ـِي)',
      patternNameBn: 'উত্তম পুরুষের যুক্ত সর্বনাম (যমির মুত্তাসিল: ـِي)',
      lessonPatternAr: 'بَيْتِي وَ صَدِيقِي',
      lessonPatternEn: 'My house and my friend',
      lessonPatternBn: 'আমার বাড়ি ও আমার বন্ধু',
      quranPatternAr: 'صَدْرِي وَ أَمْرِي',
      quranPatternEn: 'My chest and my affair',
      quranPatternBn: 'আমার বক্ষ ও আমার কাজ',
      reflection: 'In Arabic, adding the suffix «ـِي» establishes intimate, direct possession with a noun. In this lesson, you mastered how «صَدِيقِي» means "my friend" and «بَيْتِي» means "my house". In Surah Ta-Ha, Prophet Musa (peace be upon him) uses this exact grammatical attachment when calling upon his Lord («رَبِّ») to expand his chest («صَدْرِي» - an anatomical term) and facilitate his task («أَمْرِي»).',
      audioKey: 'quran_020025',
    },
  },
];

export const CH2_LESSON_05_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 2,
  lessonNum: 5,
  titleEn: 'Possessive Pronoun Suffixes & Natural Gender',
  titleAr: 'الضَّمَائِرُ الْمُتَّصِلَةُ وَتَأْنِيثُ الأَعْضَاءِ',
  wordsLearned: [
    'وَجْهٌ',
    'شَعْرٌ',
    'عَيْنٌ',
    'أَنْفٌ',
    'خَدٌّ',
    'بَطْنٌ',
    'ظَهْرٌ',
    'لَوْنٌ',
    'زَمِيلٌ',
    'رَائِحَةٌ',
    'عَبْدٌ',
    'مِئْذَنَةٌ',
  ],
  steps: CH2_LESSON_05_STEPS,
};
