// Chapter 2 Lesson 4 Interactive Session Data (Directly mapped from textbook Volume 1 Chapter 2 Lesson 4, pages 65-70)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH2_LESSON_04_STEPS: SessionStep[] = [
  // 1. Vocabulary Discovery: Fruits & Taste
  {
    id: 'ch2-l4-step-1-vocab-fruits',
    type: 'vocab_prime',
    pageNumber: 65,
    titleEn: 'Fruits & Tastes Vocabulary',
    titleAr: 'مُفْرَدَاتُ الثِّمَارِ وَالأَطْعِمَةِ',
    instructionEn: 'Listen to and learn classical Arabic nouns for fruits, tastes, and beverages',
    instructionBn: 'বিভিন্ন সুস্বাদু ফল, স্বাদ ও পানীয়ের আরবি নাম ও বিশুদ্ধ উচ্চারণ শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l4_inab', ar: 'عِنَبٌ', en: 'Grape / grapes', bn: 'একটি আঙুর / আঙুরসমূহ', romanized: '‘inabun', emoji: '🍇' },
        { id: 'v1_c2l4_rumman', ar: 'رُمَّانَةٌ', en: 'Pomegranate', bn: 'একটি আনার / ডালিম', romanized: 'rummānatun', emoji: '🫐' },
        { id: 'v1_c2l4_tuffah', ar: 'تُفَّاحَةٌ', en: 'Apple', bn: 'একটি আপেল', romanized: 'tuffāḥatun', emoji: '🍎' },
        { id: 'v1_c2l4_bittikh', ar: 'بَطِّيخَةٌ', en: 'Watermelon', bn: 'একটি তরমুজ', romanized: 'baṭṭīkhatun', emoji: '🍉' },
        { id: 'v1_c2l4_hulw', ar: 'حُلْوٌ', en: 'Sweet', bn: 'মিষ্টি', romanized: 'ḥulwun', emoji: '🍯' },
        { id: 'v1_c2l4_hamid', ar: 'حَامِضٌ', en: 'Sour', bn: 'টক', romanized: 'ḥāmiḍun', emoji: '🍋' },
        { id: 'v1_c2l4_shay', ar: 'شَايٌ', en: 'Tea', bn: 'চা', romanized: 'shāyun', emoji: '🍵' },
      ],
    },
  },

  // 2. Speed Pairing: Fruits & Tastes
  {
    id: 'ch2-l4-step-2-pair-fruits',
    type: 'speed_pair',
    pageNumber: 65,
    titleEn: 'Fruits & Tastes Recall Drill',
    titleAr: 'مُطَابَقَةُ الثِّمَارِ وَالأَذْوَاقِ',
    instructionEn: 'Match each fruit or taste word with its meaning',
    instructionBn: 'ফল ও স্বাদের শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pf-inab', ar: 'عِنَبٌ', meaning: 'Grape' },
        { id: 'pf-tuffah', ar: 'تُفَّاحَةٌ', meaning: 'Apple' },
        { id: 'pf-rumman', ar: 'رُمَّانَةٌ', meaning: 'Pomegranate' },
        { id: 'pf-bittikh', ar: 'بَطِّيخَةٌ', meaning: 'Watermelon' },
        { id: 'pf-hulw', ar: 'حُلْوٌ', meaning: 'Sweet' },
      ],
    },
  },

  // 3. Vocabulary Discovery: Fauna & Living Creatures
  {
    id: 'ch2-l4-step-3-vocab-animals',
    type: 'vocab_prime',
    pageNumber: 70,
    titleEn: 'Fauna & Living Creatures',
    titleAr: 'مُفْرَدَاتُ الحَيَوَانَاتِ وَالطُّيُورِ',
    instructionEn: 'Learn classical names for animals, birds, and living creatures',
    instructionBn: 'পশুপাখি ও জীবজন্তু সম্পর্কিত আরবি শব্দগুলোর উচ্চারণ শুনুন ও অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l4_fil', ar: 'فِيلٌ', en: 'Elephant', bn: 'একটি হাতি', romanized: 'fīlun', emoji: '🐘' },
        { id: 'v1_c2l4_qird', ar: 'قِرْدٌ', en: 'Monkey', bn: 'একটি বানর', romanized: 'qirdun', emoji: '🐒' },
        { id: 'v1_c2l4_himar', ar: 'حِمَارٌ', en: 'Donkey', bn: 'একটি গাধা', romanized: 'ḥimārun', emoji: '🫏' },
        { id: 'v1_c2l4_ghurab', ar: 'غُرَابٌ', en: 'Crow', bn: 'একটি কাক', romanized: 'ghurābun', emoji: '🐦‍⬛' },
        { id: 'v1_c2l4_bulbul', ar: 'بُلْبُلٌ', en: 'Nightingale', bn: 'একটি বুলবুলি পাখি', romanized: 'bulbulun', emoji: '🐦' },
        { id: 'v1_c2l4_zaby', ar: 'ظَبْيٌ', en: 'Deer / gazelle', bn: 'একটি হরিণ', romanized: 'ẓabyun', emoji: '🦌' },
        { id: 'v1_c2l4_usfur', ar: 'عُصْفُورٌ', en: 'Sparrow', bn: 'একটি চড়ুই পাখি', romanized: '‘uṣfūrun', emoji: '🐤' },
        { id: 'v1_c2l4_faras', ar: 'فَرَسٌ', en: 'Horse', bn: 'একটি ঘোড়া', romanized: 'farasun', emoji: '🐎' },
      ],
    },
  },

  // 4. Speed Pairing: Animals & Creatures
  {
    id: 'ch2-l4-step-4-pair-animals',
    type: 'speed_pair',
    pageNumber: 70,
    titleEn: 'Animal Kingdom Recall Drill',
    titleAr: 'مُطَابَقَةُ أَسْمَاءِ الحَيَوَانَاتِ',
    instructionEn: 'Match each animal noun with its meaning',
    instructionBn: 'প্রাণীদের আরবি নামের সাথে সঠিক অর্থ দ্রুত মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pa-fil', ar: 'فِيلٌ', meaning: 'Elephant' },
        { id: 'pa-qird', ar: 'قِرْدٌ', meaning: 'Monkey' },
        { id: 'pa-bulbul', ar: 'بُلْبُلٌ', meaning: 'Nightingale' },
        { id: 'pa-zaby', ar: 'ظَبْيٌ', meaning: 'Deer / gazelle' },
        { id: 'pa-usfur', ar: 'عُصْفُورٌ', meaning: 'Sparrow' },
      ],
    },
  },

  // 5. Concept Discovery: The Interrogative Maddah Rule (أَ + ا = آ)
  {
    id: 'ch2-l4-step-5-concept-maddah',
    type: 'concept_intro',
    pageNumber: 67,
    titleEn: 'Orthography & Phonology: The Interrogative Maddah (أَ + ا = آ)',
    titleAr: 'قَاعِدَةُ مَدَّةِ الاِسْتِفْهَامِ (أَ + ا = آ)',
    instructionEn: 'When the interrogative Hamzah (أَ) precedes the definite article (الـ), they merge into a prolonged Alif Maddah (آ)',
    instructionBn: 'প্রশ্নবোধক হামযাহ (أَ) যখন আলিফ-লামের (الـ) পূর্বে আসে, তখন উভয়ে মিলে দীর্ঘ টানযুক্ত আলিফ মাদ্দাহ (آ) রূপ ধারণ করে।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-maddah-bab',
          ar: 'أَ + الْبَابُ ➔ آلْبَابُ مَفْتُوحٌ أَمِ النَّافِذَةُ ؟',
          romanized: 'a + al-bābu ➔ āl-bābu maftūḥun ami an-nāfidhah?',
          meaningEn: 'Is the door open or the window? (Maddah coalescence)',
          meaningBn: 'দরজাটি কি খোলা, না জানালাটি?',
          exampleAr: 'آلْبَابُ مَفْتُوحٌ أَمِ النَّافِذَةُ ؟ الْبَابُ',
          exampleEn: 'Is the door open or the window? The door.',
          exampleBn: 'দরজাটি কি খোলা, না জানালাটি? দরজাটি।',
          audioKey: 'al_babu_maftuhun_ami_an_nafidhah',
          exampleAudioKey: 'al_babu',
          emoji: '🚪',
          compound: {
            baseAr: 'الْبَابُ',
            baseRom: 'al-bābu',
            baseMeaningEn: 'The door (Definite noun)',
            baseMeaningBn: 'দরজাটি',
            baseAudioKey: 'al_babu',
            operator: '+',
            particleAr: 'أَ',
            particleEn: 'Interrogative Hamzah',
            resultAr: 'آلْبَابُ',
            resultRom: 'āl-bābu',
            resultMeaningEn: 'Is the door...? (Maddah Alif)',
            resultMeaningBn: 'দরজাটি কি...? (মাদ্দাহ)',
            resultAudioKey: 'al_babu_maddah',
            badge: 'Maddah Coalescence (آ)',
          },
        },
        {
          id: 'cp-maddah-walad',
          ar: 'أَ + الْوَلَدُ ➔ آلْوَلَدُ طَوِيلٌ أَمِ الْبِنْتُ ؟',
          romanized: 'a + al-waladu ➔ āl-waladu ṭawīlun ami al-bintu?',
          meaningEn: 'Is the boy tall or the girl? (Maddah coalescence)',
          meaningBn: 'ছেলেটি কি লম্বা, না মেয়েটি?',
          exampleAr: 'آلْوَلَدُ طَوِيلٌ أَمِ الْبِنْتُ ؟ الْوَلَدُ',
          exampleEn: 'Is the boy tall or the girl? The boy.',
          exampleBn: 'ছেলেটি কি লম্বা, না মেয়েটি? ছেলেটি।',
          audioKey: 'al_waladu_tawilun_ami_al_bint',
          exampleAudioKey: 'al_waladu',
          emoji: '👦',
          compound: {
            baseAr: 'الْوَلَدُ',
            baseRom: 'al-waladu',
            baseMeaningEn: 'The boy',
            baseMeaningBn: 'ছেলেটি',
            baseAudioKey: 'al_waladu',
            operator: '+',
            particleAr: 'أَ',
            particleEn: 'Interrogative Hamzah',
            resultAr: 'آلْوَلَدُ',
            resultRom: 'āl-waladu',
            resultMeaningEn: 'Is the boy...?',
            resultMeaningBn: 'ছেলেটি কি...?',
            resultAudioKey: 'al_waladu_maddah',
            badge: 'Maddah Coalescence (آ)',
          },
        },
      ],
    },
  },

  // 6. Concept Discovery: Incomplete Phrase vs Complete Sentence (Page 69 Architecture)
  {
    id: 'ch2-l4-step-6-concept-phrase-vs-sentence',
    type: 'concept_intro',
    pageNumber: 69,
    titleEn: 'Syntactic Architecture: Phrase vs Complete Sentence',
    titleAr: 'التَّرْكِيبُ: المُرَكَّبُ النَّاقِصُ وَالجُمْلَةُ التَّامَّةُ',
    instructionEn: 'Understand how a descriptive phrase (Mawsoof + Sifah) transforms into a complete nominal sentence',
    instructionBn: 'লক্ষ্য করো: অপূর্ণ গুণবাচক বাক্যাংশ (মাওসূফ-সিফাত) কীভাবে একটি পূর্ণাঙ্গ জুমলা ইসমিয়্যায় রূপ নেয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-arch-phrase',
          ar: 'مَسْجِدٌ جَمِيلٌ',
          romanized: 'masjidun jamīlun',
          meaningEn: 'A beautiful mosque (Descriptive Phrase ➔ Incomplete meaning)',
          meaningBn: 'একটি সুন্দর মসজিদ (অপূর্ণ কথা / মাওসূফ-সিফাত)',
          exampleAr: 'مَسْجِدٌ جَمِيلٌ',
          exampleEn: 'A beautiful mosque.',
          exampleBn: 'একটি সুন্দর মসজিদ।',
          audioKey: 'masjidun_jamil',
          exampleAudioKey: 'masjidun_jamil',
          emoji: '🧩',
          compound: {
            baseAr: 'مَسْجِدٌ',
            baseRom: 'masjidun',
            baseMeaningEn: 'Mawsoof: A mosque',
            baseMeaningBn: 'মাওসূফ: একটি মসজিদ',
            baseAudioKey: 'masjidun',
            operator: '+',
            particleAr: 'جَمِيلٌ',
            particleEn: 'Sifah: beautiful',
            resultAr: 'مَسْجِدٌ جَمِيلٌ',
            resultRom: 'masjidun jamīlun',
            resultMeaningEn: 'Incomplete: A beautiful mosque',
            resultMeaningBn: 'অপূর্ণ বাক্যাংশ: একটি সুন্দর মসজিদ',
            resultAudioKey: 'masjidun_jamil',
            badge: 'Incomplete Phrase (مُرَكَّبٌ نَاقِصٌ)',
          },
        },
        {
          id: 'cp-arch-sentence',
          ar: 'الْمَسْجِدُ جَمِيلٌ',
          romanized: 'al-masjidu jamīlun',
          meaningEn: 'The mosque is beautiful (Complete Sentence: Subject + Predicate)',
          meaningBn: 'মসজিদটি সুন্দর (পূর্ণ বাক্য / মুবতাদা ও খবর)',
          exampleAr: 'الْمَسْجِدُ جَمِيلٌ',
          exampleEn: 'The mosque is beautiful.',
          exampleBn: 'মসজিদটি সুন্দর।',
          audioKey: 'al_masjidu_jamil',
          exampleAudioKey: 'al_masjidu_jamil',
          emoji: '🕌',
          compound: {
            baseAr: 'الْمَسْجِدُ',
            baseRom: 'al-masjidu',
            baseMeaningEn: 'Mubtada (Definite Subject): The mosque',
            baseMeaningBn: 'মুবতাদা (নির্দিষ্ট): মসজিদটি',
            baseAudioKey: 'al_masjidu',
            operator: '+',
            particleAr: 'جَمِيلٌ',
            particleEn: 'Khabar (Indefinite Predicate): is beautiful',
            resultAr: 'الْمَسْجِدُ جَمِيلٌ',
            resultRom: 'al-masjidu jamīlun',
            resultMeaningEn: 'Complete Sentence: The mosque is beautiful',
            resultMeaningBn: 'পূর্ণ বাক্য: মসজিদটি সুন্দর',
            resultAudioKey: 'al_masjidu_jamil',
            badge: 'Complete Sentence (جُمْلَةٌ تَامَّةٌ)',
          },
        },
      ],
    },
  },

  // 7. Dialogic Alternative Q&A Battery 1: Daily Objects & Attributes
  {
    id: 'ch2-l4-step-7-dialogue-objects',
    type: 'alternative_qa',
    pageNumber: 66,
    titleEn: 'Dialogue Battery: Daily Objects & Attributes',
    titleAr: 'حِوَارُ الأَشْيَاءِ اليَوْمِيَّةِ وَالأَوْصَافِ',
    instructionEn: 'Select the authentic answer specifying each object based on the visual cue without using yes or no',
    instructionBn: 'হ্যাঁ বা না ছাড়া দৃশ্যায়ন অনুযায়ী সঠিক বস্তুটি নির্দেশ করে উত্তর দিন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l4-1',
          questionAr: 'أَ رَخِيصَةٌ هِيَ أَمْ غَالِيَةٌ ؟',
          visualCue: '💎',
          optionsAr: ['غَالِيَةٌ', 'رَخِيصَةٌ'],
          correctAnswerAr: 'غَالِيَةٌ',
        },
        {
          id: 'qa-c2l4-2',
          questionAr: 'أَ سَاعَةُ الطَّاوِلَةِ هَذِهِ أَمْ سَاعَةُ الْيَدِ ؟',
          visualCue: '⌚',
          optionsAr: ['سَاعَةُ الْيَدِ', 'سَاعَةُ الطَّاوِلَةِ'],
          correctAnswerAr: 'سَاعَةُ الْيَدِ',
        },
        {
          id: 'qa-c2l4-3',
          questionAr: 'أَ تُفَّاحَةٌ تِلْكَ أَمْ رُمَّانَةٌ ؟',
          visualCue: '🍎',
          optionsAr: ['تُفَّاحَةٌ', 'رُمَّانَةٌ'],
          correctAnswerAr: 'تُفَّاحَةٌ',
        },
        {
          id: 'qa-c2l4-4',
          questionAr: 'أَ عِقْدٌ هَذَا أَمْ سِوَارٌ ؟',
          visualCue: '📿',
          optionsAr: ['عِقْدٌ', 'سِوَارٌ'],
          correctAnswerAr: 'عِقْدٌ',
        },
        {
          id: 'qa-c2l4-5',
          questionAr: 'أَ نَظِيفَةٌ هِيَ أَمْ وَسِخَةٌ ؟',
          visualCue: '✨',
          optionsAr: ['نَظِيفَةٌ', 'وَسِخَةٌ'],
          correctAnswerAr: 'نَظِيفَةٌ',
        },
      ],
    },
  },

  // 8. Sentence Assembly Drill 1: Sweet Watermelon & Apple
  {
    id: 'ch2-l4-step-8-assembly-sweet-apple',
    type: 'sentence_assembly',
    pageNumber: 66,
    titleEn: 'Sentence Building: Sweet Fruits',
    titleAr: 'تَرْكِيبُ: هَذَا بِطِّيخٌ حُلْوٌ وَ تِلْكَ تُفَّاحَةٌ حُلْوَةٌ',
    instructionEn: 'Assemble: "This is a sweet watermelon and that is a sweet apple"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "এটি একটি মিষ্টি তরমুজ এবং ওটি একটি মিষ্টি আপেল"',
    assemblyPayload: {
      promptEn: 'This is a sweet watermelon and that is a sweet apple',
      promptBn: 'এটি একটি মিষ্টি তরমুজ এবং ওটি একটি মিষ্টি আপেল',
      expectedAnswer: ['هَذَا', 'بِطِّيخٌ', 'حُلْوٌ', 'وَ', 'تِلْكَ', 'تُفَّاحَةٌ', 'حُلْوَةٌ'],
      chips: ['هَذَا', 'بِطِّيخٌ', 'حُلْوٌ', 'وَ', 'تِلْكَ', 'تُفَّاحَةٌ', 'حُلْوَةٌ', 'حَامِضٌ'],
      emoji: '🍉',
    },
  },

  // 9. Sentence Assembly Drill 2: Clean Blackboard in Front of Teacher
  {
    id: 'ch2-l4-step-9-assembly-blackboard-teacher',
    type: 'sentence_assembly',
    pageNumber: 67,
    titleEn: 'Sentence Building: Clean Blackboard',
    titleAr: 'تَرْكِيبُ: السَّبُّورَةُ أَمَامَ الْمُعَلِّمِ نَظِيفَةٌ',
    instructionEn: 'Assemble: "The blackboard in front of the teacher is clean"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "শিক্ষকের সামনের ব্ল্যাকবোর্ডটি পরিষ্কার"',
    assemblyPayload: {
      promptEn: 'The blackboard in front of the teacher is clean',
      promptBn: 'শিক্ষকের সামনের ব্ল্যাকবোর্ডটি পরিষ্কার',
      expectedAnswer: ['السَّبُّورَةُ', 'أَمَامَ', 'الْمُعَلِّمِ', 'نَظِيفَةٌ'],
      chips: ['السَّبُّورَةُ', 'أَمَامَ', 'الْمُعَلِّمِ', 'نَظِيفَةٌ', 'وَسِخَةٌ', 'خَلْفَ'],
      emoji: '👨‍🏫',
    },
  },

  // 10. Vocabulary Discovery: Anatomy, Humanity & Spiritual Nourishment (Page 70)
  {
    id: 'ch2-l4-step-10-vocab-anatomy',
    type: 'vocab_prime',
    pageNumber: 70,
    titleEn: 'Anatomy & Humanity Vocabulary',
    titleAr: 'مُفْرَدَاتُ أَعْضَاءِ الإِنْسَانِ وَالحَيَوَانِ',
    instructionEn: 'Listen and learn nouns describing human anatomy, physical features, and spiritual nourishment',
    instructionBn: 'মানব ও প্রাণীর অঙ্গপ্রত্যঙ্গ এবং আত্মিক খোরাক সম্পর্কিত শব্দগুলো শুনুন ও মুখস্থ করুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l4_insan', ar: 'إِنْسَانٌ', en: 'A human being / person', bn: 'মানুষ', romanized: 'insānun', emoji: '🧑' },
        { id: 'v1_c2l4_raas', ar: 'رَأْسٌ', en: 'Head', bn: 'মাথা', romanized: 'ra’sun', emoji: '🗣️' },
        { id: 'v1_c2l4_wajh', ar: 'وَجْهٌ', en: 'Face', bn: 'মুখমণ্ডল', romanized: 'wajhun', emoji: '😀' },
        { id: 'v1_c2l4_ayn', ar: 'عَيْنٌ', en: 'Eye (Feminine noun)', bn: 'চোখ', romanized: '‘aynun', emoji: '👁️' },
        { id: 'v1_c2l4_anf', ar: 'أَنْفٌ', en: 'Nose', bn: 'নাক', romanized: 'anfun', emoji: '👃' },
        { id: 'v1_c2l4_fam', ar: 'فَمٌ', en: 'Mouth', bn: 'মুখ / ঠোঁট', romanized: 'famun', emoji: '👄' },
        { id: 'v1_c2l4_lisan', ar: 'لِسَانٌ', en: 'Tongue / Language', bn: 'জিহ্বা / ভাষা', romanized: 'lisānun', emoji: '👅' },
        { id: 'v1_c2l4_sadr', ar: 'صَدْرٌ', en: 'Chest', bn: 'বুক / বক্ষ', romanized: 'ṣadrun', emoji: '🫁' },
        { id: 'v1_c2l4_qalb', ar: 'قَلْبٌ', en: 'Heart', bn: 'অন্তর / হৃদয়', romanized: 'qalbun', emoji: '❤️' },
        { id: 'v1_c2l4_khurtum', ar: 'خُرْطُومٌ', en: 'Trunk (of elephant)', bn: 'হাতির শুঁড়', romanized: 'khurṭūmun', emoji: '🐘' },
        { id: 'v1_c2l4_dhikr', ar: 'ذِكْرٌ', en: 'Remembrance of Allah', bn: 'আল্লাহর স্মরণ / জিকির', romanized: 'dhikrun', emoji: '📿' },
        { id: 'v1_c2l4_ghidha', ar: 'غِذَاءٌ', en: 'Nourishment / Food', bn: 'খাদ্য / খোরাক', romanized: 'ghidhā’un', emoji: '🥗' },
      ],
    },
  },

  // 11. Speed Pairing: Anatomy & Nourishment
  {
    id: 'ch2-l4-step-11-pair-anatomy',
    type: 'speed_pair',
    pageNumber: 70,
    titleEn: 'Anatomy Recall Drill',
    titleAr: 'مُطَابَقَةُ أَعْضَاءِ الإِنْسَانِ',
    instructionEn: 'Match each anatomical term with its English meaning',
    instructionBn: 'অঙ্গপ্রত্যঙ্গের নামগুলোর সাথে সঠিক অর্থ মিলিয়ে দিন',
    pairPayload: {
      pairs: [
        { id: 'pa-raas', ar: 'رَأْسٌ', meaning: 'Head' },
        { id: 'pa-wajh', ar: 'وَجْهٌ', meaning: 'Face' },
        { id: 'pa-ayn', ar: 'عَيْنٌ', meaning: 'Eye' },
        { id: 'pa-fam', ar: 'فَمٌ', meaning: 'Mouth' },
        { id: 'pa-qalb', ar: 'قَلْبٌ', meaning: 'Heart' },
      ],
    },
  },

  // 12. Dialogic Alternative Q&A Battery 2: Maddah Interrogations (Page 67)
  {
    id: 'ch2-l4-step-12-alt-qa-maddah-battery',
    type: 'alternative_qa',
    pageNumber: 67,
    titleEn: 'Dialogue Battery: Maddah Interrogations',
    titleAr: 'حِوَارُ الاِسْتِفْهَامِ بِالمَدَّةِ (آلْـ)',
    instructionEn: 'Select the precise answer for each interrogative Maddah inquiry based on the visual cue',
    instructionBn: 'দৃশ্যায়ন অনুযায়ী আলিফ-মাদ যুক্ত বিকল্প প্রশ্নগুলোর সুনির্দিষ্ট উত্তর দিন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l4-6',
          questionAr: 'آلْبَابُ مَفْتُوحٌ أَمِ النَّافِذَةُ ؟',
          visualCue: '🚪🔓',
          optionsAr: ['الْبَابُ', 'النَّافِذَةُ'],
          correctAnswerAr: 'الْبَابُ',
        },
        {
          id: 'qa-c2l4-7',
          questionAr: 'آلْوَلَدُ طَوِيلٌ أَمِ الْبِنْتُ ؟',
          visualCue: '👦',
          optionsAr: ['الْوَلَدُ', 'الْبِنْتُ'],
          correctAnswerAr: 'الْوَلَدُ',
        },
        {
          id: 'qa-c2l4-8',
          questionAr: 'آلْبِنْتُ قَصِيرَةٌ أَمِ الْوَلَدُ ؟',
          visualCue: '👧',
          optionsAr: ['الْبِنْتُ', 'الْوَلَدُ'],
          correctAnswerAr: 'الْبِنْتُ',
        },
        {
          id: 'qa-c2l4-9',
          questionAr: 'أَ هَذِهِ السَّيَّارَةُ جَدِيدَةٌ أَمْ تِلْكَ ؟',
          visualCue: '🚗✨',
          optionsAr: ['هَذِهِ', 'تِلْكَ'],
          correctAnswerAr: 'هَذِهِ',
        },
        {
          id: 'qa-c2l4-10',
          questionAr: 'أَ هَذَا الْقُفْلُ كَبِيرٌ أَمْ ذَلِكَ ؟',
          visualCue: '🔒',
          optionsAr: ['هَذَا الْقُفْلُ', 'ذَلِكَ'],
          correctAnswerAr: 'هَذَا الْقُفْلُ',
        },
      ],
    },
  },

  // 13. Authentic Reading & Translation Drill: Elephant Head & Trunk
  {
    id: 'ch2-l4-step-13-assembly-elephant-trunk',
    type: 'sentence_assembly',
    pageNumber: 70,
    titleEn: 'Textbook Translation: Elephant Head & Trunk',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: رَأْسُ الفِيلِ وَ خُرْطُومُهُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'رَأْسُ الْفِيلِ صَغِيرٌ وَخُرْطُومُهُ طَوِيلٌ',
      promptEn: 'The head of the elephant is small and its trunk is long',
      promptBn: 'হাতির মাথা ছোট এবং তার শুঁড় লম্বা',
      expectedAnswer: ['The', 'head', 'of', 'the', 'elephant', 'is', 'small', 'and', 'its', 'trunk', 'is', 'long'],
      chips: ['The', 'head', 'of', 'the', 'elephant', 'is', 'small', 'and', 'its', 'trunk', 'is', 'long', 'ear', 'wide', 'neck'],
      expectedAnswerBn: ['হাতির', 'মাথা', 'ছোট', 'এবং', 'তার', 'শুঁড়', 'লম্বা'],
      chipsBn: ['হাতির', 'মাথা', 'ছোট', 'এবং', 'তার', 'শুঁড়', 'লম্বা', 'কান', 'বড়', 'গলা'],
      emoji: '🐘',
    },
  },

  // 14. Authentic Reading & Translation Drill: Dhikr is Nourishment of the Heart
  {
    id: 'ch2-l4-step-14-assembly-dhikr-heart',
    type: 'sentence_assembly',
    pageNumber: 70,
    titleEn: 'Textbook Translation: Dhikr and Honey',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: الذِّكْرُ غِذَاءُ القَلْبِ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'الذِّكْرُ غِذَاءُ الْقَلْبِ وَالْعَسَلُ غِذَاءٌ مُفِيدٌ',
      promptEn: 'Dhikr is the nourishment of the heart and honey is wholesome food',
      promptBn: 'যিকির হৃদয়ের খাদ্য এবং মধু উপকারী খাদ্য',
      expectedAnswer: ['Dhikr', 'is', 'the', 'nourishment', 'of', 'the', 'heart', 'and', 'honey', 'is', 'wholesome', 'food'],
      chips: ['Dhikr', 'is', 'the', 'nourishment', 'of', 'the', 'heart', 'and', 'honey', 'is', 'wholesome', 'food', 'water', 'fruit', 'sweet'],
      expectedAnswerBn: ['যিকির', 'হৃদয়ের', 'খাদ্য', 'এবং', 'মধু', 'উপকারী', 'খাবার'],
      chipsBn: ['যিকির', 'হৃদয়ের', 'খাদ্য', 'এবং', 'মধু', 'উপকারী', 'খাবার', 'ঠান্ডা', 'পানি', 'ফল'],
      emoji: '📿',
    },
  },

  // 15. Binary Polar Sort: Orthographic Rule of Interrogative Maddah
  {
    id: 'ch2-l4-step-15-polar-maddah-phonology',
    type: 'polar_sort',
    pageNumber: 67,
    titleEn: 'Orthographic Rule: Interrogative Hamzah with Alif-Lam',
    titleAr: 'رَسْمُ مَدَّةِ الاِسْتِفْهَامِ مَعَ «الْـ»',
    instructionEn: 'When the interrogative particle (أَ) combines with the definite article (الْـ), which written form is correct?',
    instructionBn: 'প্রশ্নবোধক হামযাহ (أَ) ও আলিফ-লাম (الْـ) একত্র হলে কোনটি সঠিক লিখিত রূপ?',
    polarPayload: {
      arabicSubject: 'أَ + الْبَابُ ...',
      meaningEn: 'Is the door...? (Maddah Alif)',
      meaningBn: 'দরজাটি কি...? (মাদ্দাহ যুক্ত)',
      correctAnswer: 'آلْبَابُ',
      options: ['آلْبَابُ', 'أَلْبَابُ'],
      emoji: '✍️',
    },
  },

  // 16. Authentic Reading & Translation Drill: Heart in Chest & Tongue in Mouth
  {
    id: 'ch2-l4-step-16-assembly-human-chest',
    type: 'sentence_assembly',
    pageNumber: 70,
    titleEn: 'Textbook Translation: Heart and Tongue',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: قَلْبُ الإِنْسَانِ وَ لِسَانُهُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'قَلْبُ الْإِنْسَانِ فِي صَدْرِهِ وَلِسَانُهُ فِي فَمِهِ',
      promptEn: 'The heart of man is in his chest and his tongue is in his mouth',
      promptBn: 'মানুষের অন্তর তার বক্ষে এবং তার জিহ্বা তার মুখে',
      expectedAnswer: ['The', 'heart', 'of', 'man', 'is', 'in', 'his', 'chest', 'and', 'his', 'tongue', 'is', 'in', 'his', 'mouth'],
      chips: ['The', 'heart', 'of', 'man', 'is', 'in', 'his', 'chest', 'and', 'his', 'tongue', 'is', 'in', 'his', 'mouth', 'head', 'eye'],
      expectedAnswerBn: ['মানুষের', 'অন্তর', 'তার', 'বক্ষে', 'এবং', 'তার', 'জিহ্বা', 'তার', 'মুখে'],
      chipsBn: ['মানুষের', 'অন্তর', 'তার', 'বক্ষে', 'এবং', 'তার', 'জিহ্বা', 'তার', 'মুখে', 'মাথায়', 'চোখে'],
      emoji: '🫀',
    },
  },

  // 17. Syntactic Tarkib Dissector: Phrase vs Complete Nominal Sentence (Page 69 Blueprint)
  {
    id: 'ch2-l4-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 69,
    titleEn: 'Syntactic Tarkib Dissector: Nominal Sentence Blueprint',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: بِنَاءُ الجُمْلَةِ الاِسْمِيَّةِ التَّامَّةِ',
    instructionEn: 'Dissect the foundational nominal sentence architecture (Mubtada and Khabar) as modeled on textbook page 69',
    instructionBn: 'পাঠ্যবইয়ের ৬৯ পৃষ্ঠার নকশা অনুযায়ী জুমলা ইসমিয়্যার (মুবতাদা ও খবর) ব্যাকরণগত উপাদানগুলো আলাদা করুন',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c2l4-s1',
          sentenceAr: 'الْمَسْجِدُ جَمِيلٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ تَامَّةٌ (مُبْتَدَأٌ وَخَبَرٌ)',
          sentenceTypeEn: 'Complete Nominal Sentence (Definite Subject + Indefinite Predicate)',
          sentenceTypeBn: 'পূর্ণ নামবাচক বাক্য (মুবতাদা ও খবর)',
          slots: [
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Definite Subject (Mubtada)',
              roleBn: 'উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'الْمَسْجِدُ',
            },
            {
              roleAr: 'خَبَرٌ',
              roleEn: 'Indefinite Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'جَمِيلٌ',
            },
          ],
          availableWordsAr: ['جَمِيلٌ', 'الْمَسْجِدُ'],
        },
        {
          id: 'tarkib-c2l4-s2',
          sentenceAr: 'هَذَا مَسْجِدٌ جَمِيلٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مُبْتَدَأٌ مَعَ خَبَرٍ مُرَكَّبٍ وَصْفِيٍّ)',
          sentenceTypeEn: 'Nominal Sentence (Demonstrative Subject + Descriptive Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (ইশারা মুবতাদা + মাওসূফ-সিফাত খবর)',
          slots: [
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Subject Demonstrative (Mubtada)',
              roleBn: 'উদ্দেশ্য / ইশারা (মুবতাদা)',
              expectedWordAr: 'هَذَا',
            },
            {
              roleAr: 'خَبَرٌ وَمَوْصُوفٌ',
              roleEn: 'Predicate & Mawsoof',
              roleBn: 'খবর ও মাওসূফ',
              expectedWordAr: 'مَسْجِدٌ',
            },
            {
              roleAr: 'صِفَةٌ',
              roleEn: 'Attribute / Sifah',
              roleBn: 'বিশেষণ (সিফাত)',
              expectedWordAr: 'جَمِيلٌ',
            },
          ],
          availableWordsAr: ['جَمِيلٌ', 'هَذَا', 'مَسْجِدٌ'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah Al-Baqarah 2:218)
  {
    id: 'ch2-l4-step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 70,
    titleEn: 'Sacred Reflection: Foundational Nominal Sentence in the Quran',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: الجُمْلَةُ الاِسْمِيَّةُ فِي آيَاتِ الرَّحْمَةِ',
    instructionEn: 'Witness the foundational nominal sentence architecture (Mubtada & Khabar) declaring divine mercy in Surah Al-Baqarah (2:218)',
    instructionBn: 'সূরা আল-বাকারার আয়াতে জুমলা ইসমিয়্যার (মুবতাদা ও খবর) মাধ্যমে পরম ক্ষমার ঐশী ঘোষণা উপলব্ধি করুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 218,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'وَاللَّهُ غَفُورٌ رَّحِيمٌ',
      translationEn: 'And Allah is Forgiving and Merciful.',
      translationBn: 'আর আল্লাহ পরম ক্ষমাশীল, পরম দয়ালু।',
      highlightedWords: ['وَاللَّهُ', 'غَفُورٌ', 'رَّحِيمٌ'],
      patternNameEn: 'The Nominal Sentence Architecture (Mubtada & Khabar)',
      patternNameBn: 'নামবাচক বাক্য কাঠামো (মুবতাদা ও দ্বৈত খবর)',
      lessonPatternAr: 'الْمَسْجِدُ جَمِيلٌ / الذِّكْرُ غِذَاءٌ',
      lessonPatternEn: 'The mosque is beautiful / Dhikr is nourishment',
      lessonPatternBn: 'মসজিদটি সুন্দর / যিকির হলো খাদ্য',
      quranPatternAr: 'وَاللَّهُ غَفُورٌ رَّحِيمٌ',
      quranPatternEn: 'And Allah is Forgiving, Merciful',
      quranPatternBn: 'আর আল্লাহ ক্ষমাশীল, পরম দয়ালু',
      reflection: "In Arabic sentence architecture (التَّرْكِيب), placing a definite subject (مُبْتَدَأ) before an indefinite predicate (خَبَر) produces a complete sentence without needing an auxiliary verb. In your lesson, «الْمَسْجِدُ جَمِيلٌ» and «الذِّكْرُ غِذَاءٌ» affirmed complete realities. In Surah Al-Baqarah, Allah employs this eternal grammatical structure to declare His perpetual forgiveness and mercy.",
      audioKey: 'quran_002218',
    },
  },
];

export const CH2_LESSON_04_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 2,
  lessonNum: 4,
  titleEn: 'Sentence Architecture (Tarkeeb)',
  titleAr: 'التَّرْكِيبُ وَالجُمْلَةُ الاِسْمِيَّةُ',
  wordsLearned: [
    'عِنَبٌ',
    'رُمَّانَةٌ',
    'تُفَّاحَةٌ',
    'بَطِّيخَةٌ',
    'حُلْوٌ',
    'حَامِضٌ',
    'شَايٌ',
    'فِيلٌ',
    'قِرْدٌ',
    'حِمَارٌ',
    'غُرَابٌ',
    'بُلْبُلٌ',
    'ظَبْيٌ',
    'عُصْفُورٌ',
    'فَرَسٌ',
    'إِنْسَانٌ',
    'خُرْطُومٌ',
    'رَأْسٌ',
    'جِسْمٌ',
    'صَدْرٌ',
    'لِسَانٌ',
    'فَمٌ',
    'غِذَاءٌ',
    'عَظِيمٌ',
  ],
  steps: CH2_LESSON_04_STEPS,
};
