// Chapter 3 Lesson 2 Interactive Session Steps (Definite Descriptive Concord & The 4-Step Progression)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH3_LESSON_02_STEPS: SessionStep[] = [
  // 1. Spatial Pointing Anchor: Definite Rose in Proximity
  {
    id: 'ch3-l2-step-1-spatial-rose',
    type: 'spatial_pointing',
    pageNumber: 95,
    titleEn: 'Spatial Anchor: The Definite Rose',
    titleAr: 'الإِشَارَةُ المَكَانِيَّةُ: هَذِهِ الوَرْدَةُ',
    instructionEn: 'Point to this specific rose nearby.',
    instructionBn: 'কাছে থাকা এই নির্দিষ্ট গোলাপটির দিকে ইঙ্গিত করুন।',
    spatialPointingPayload: {
      objectAr: 'الْوَرْدَةُ',
      distance: 'near',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ الْوَرْدَةُ',
      options: ['هَذَا الْوَرْدَةُ', 'هَذِهِ الْوَرْدَةُ', 'ذَلِكَ الْوَرْدَةُ', 'تِلْكَ الْوَرْدَةُ'],
      emoji: '🌹',
    },
  },

  // 2. Primary Vocabulary Priming: Nature, Flora & Fauna
  {
    id: 'ch3-l2-step-2-vocab-nature',
    type: 'vocab_prime',
    pageNumber: 95,
    titleEn: 'Flora, Aquatic Fauna & Flavors',
    titleAr: 'مُفْرَدَاتُ الطَّبِيعَةِ وَالأَحْوَاضِ وَالأَسْمَاكِ',
    instructionEn: 'Listen to classical Arabic terms for blossoms, marine life, and sensory descriptions.',
    instructionBn: 'গোলাপ, মাছ, জলাশয় ও স্বাদের আরবি শব্দগুলো শুনুন।',
    vocabPayload: {
      words: [
        {
          id: 'c3l2-wardah',
          ar: 'وَرْدَةٌ',
          en: 'A rose',
          bn: 'একটি গোলাপ',
          romanized: 'wardatun',
          emoji: '🌹',
        },
        {
          id: 'c3l2-samakah',
          ar: 'سَمَكَةٌ',
          en: 'A fish',
          bn: 'একটি মাছ',
          romanized: 'samakatun',
          emoji: '🐟',
        },
        {
          id: 'c3l2-hawd',
          ar: 'حَوْضٌ',
          en: 'A basin / pond / pool',
          bn: 'একটি জলাশয় বা হাউজ',
          romanized: 'ḥawḍun',
          emoji: '🏊',
        },
        {
          id: 'c3l2-ladhidh',
          ar: 'لَذِيذٌ',
          en: 'Delicious / savory',
          bn: 'সুস্বাদু বা উপাদেয়',
          romanized: 'ladhīdhun',
          emoji: '😋',
        },
        {
          id: 'c3l2-ajib',
          ar: 'عَجِيبٌ',
          en: 'Astonishing / wondrous',
          bn: 'আশ্চর্যজনক বা চমৎকার',
          romanized: "'ajībun",
          emoji: '✨',
        },
        {
          id: 'c3l2-mashhur',
          ar: 'مَشْهُورٌ',
          en: 'Famous / well-known',
          bn: 'বিখ্যাত বা প্রসিদ্ধ',
          romanized: 'mashhūrun',
          emoji: '🌟',
        },
      ],
    },
  },

  // 3. Secondary Vocabulary Priming: Velocity, Character & Ownership
  {
    id: 'ch3-l2-step-3-vocab-society',
    type: 'vocab_prime',
    pageNumber: 96,
    titleEn: 'Velocity, Diligence & Custodianship',
    titleAr: 'مُفْرَدَاتُ السُّرْعَةِ وَالاجْتِهَادِ وَالمِلْكِيَّةِ',
    instructionEn: 'Learn essential terms for speed contrast, industry, and property ownership.',
    instructionBn: 'গতি, অধ্যবসায় ও মালিকানা সম্পর্কিত গুরুত্বপূর্ণ আরবি শব্দগুলো জানুন।',
    vocabPayload: {
      words: [
        {
          id: 'c3l2-bati',
          ar: 'بَطِيءٌ',
          en: 'Slow',
          bn: 'ধীরগতিসম্পন্ন',
          romanized: 'baṭī’un',
          emoji: '🐢',
        },
        {
          id: 'c3l2-sari',
          ar: 'سَرِيعٌ',
          en: 'Fast / swift',
          bn: 'দ্রুতগতিসম্পন্ন',
          romanized: 'sarī‘un',
          emoji: '🏎️',
        },
        {
          id: 'c3l2-sahib',
          ar: 'صَاحِبٌ',
          en: 'An owner / master / companion',
          bn: 'মালিক বা সঙ্গী',
          romanized: 'ṣāḥibun',
          emoji: '👤',
        },
        {
          id: 'c3l2-mujtahid',
          ar: 'مُجْتَهِدٌ',
          en: 'Hardworking / diligent',
          bn: 'পরিশ্রমী বা অধ্যবসায়ী',
          romanized: 'mujtahidun',
          emoji: '💪',
        },
        {
          id: 'c3l2-kaslan',
          ar: 'كَسْلَانُ',
          en: 'Lazy (diptote)',
          bn: 'অলস',
          romanized: 'kaslānu',
          emoji: '🥱',
        },
        {
          id: 'c3l2-ghaniyy',
          ar: 'غَنِيٌّ',
          en: 'Rich / wealthy',
          bn: 'ধনী বা সম্পদশালী',
          romanized: 'ghaniyyun',
          emoji: '💰',
        },
      ],
    },
  },

  // 4. Synaptic Speed Match: Nature & Speed Terminology
  {
    id: 'ch3-l2-step-4-speed-nature',
    type: 'speed_pair',
    pageNumber: 95,
    titleEn: 'Synaptic Speed Pairing: Nature & Descriptors',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: الطَّبِيعَةُ وَالصِّفَاتُ',
    instructionEn: 'Rapidly link each Arabic noun and adjective to its English meaning.',
    instructionBn: 'প্রকৃতি ও গুণবাচক আরবি শব্দের সাথে অর্থের দ্রুত মিল করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c3l2-1', ar: 'وَرْدَةٌ', meaning: 'Rose' },
        { id: 'p-c3l2-2', ar: 'سَمَكَةٌ', meaning: 'Fish' },
        { id: 'p-c3l2-3', ar: 'حَوْضٌ', meaning: 'Basin / pond' },
        { id: 'p-c3l2-4', ar: 'عَجِيبٌ', meaning: 'Wondrous' },
        { id: 'p-c3l2-5', ar: 'لَذِيذٌ', meaning: 'Delicious' },
        { id: 'p-c3l2-6', ar: 'بَطِيءٌ', meaning: 'Slow' },
      ],
    },
  },

  // 5. Concept Discovery: The 4-Step Syntactic Progression
  {
    id: 'ch3-l2-step-5-concept-four-stages',
    type: 'concept_intro',
    pageNumber: 95,
    titleEn: 'Grammar Paradigm: The 4 Stages from Phrase to Sentence',
    titleAr: 'قَاعِدَةٌ: المَرَاحِلُ الأَرْبَعُ لِبِنَاءِ الجُمْلَةِ',
    instructionEn: 'Observe how the addition of «الـ» systematically transforms an incomplete phrase into a complete sentence, then into a definite complex subject.',
    instructionBn: 'লক্ষ্য করুন কীভাবে «الـ» যুক্ত হওয়ার মাধ্যমে একটি অপূর্ণ বাক্যাংশ পূর্ণ বাক্যে এবং পরবর্তীতে গুণান্বিত জটিল মুবতাদায় রূপ নেয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c3l2-stage1',
          ar: 'وَرْدَةٌ كَبِيرَةٌ',
          romanized: 'wardatun kabīratun',
          meaningEn: 'A big rose (Stage 1: Indefinite Phrase - Incomplete)',
          meaningBn: 'একটি বড় গোলাপ (অসম্পূর্ণ বাক্যাংশ)',
          exampleAr: 'كِتَابٌ جَدِيدٌ',
          exampleEn: 'A new book (Indefinite Phrase)',
          exampleBn: 'একটি নতুন কিতাব',
          audioKey: 'wardatun_kabirah',
          exampleAudioKey: 'kitab_jadid',
          emoji: '🌹',
        },
        {
          id: 'cp-c3l2-stage2',
          ar: 'الْوَرْدَةُ كَبِيرَةٌ',
          romanized: 'al-wardatu kabīratun',
          meaningEn: 'The rose is big (Stage 2: Complete Sentence: Subject + Predicate)',
          meaningBn: 'গোলাপটি বড় (পূর্ণ বাক্য: মুবতাদা ও খবর)',
          exampleAr: 'الْكِتَابُ جَدِيدٌ',
          exampleEn: 'The book is new (Complete Sentence)',
          exampleBn: 'কিতাবটি নতুন',
          audioKey: 'al_wardatu_kabirah',
          exampleAudioKey: 'al_kitabu_jadid',
          emoji: '🌺',
        },
        {
          id: 'cp-c3l2-stage3',
          ar: 'الْوَرْدَةُ الْكَبِيرَةُ',
          romanized: 'al-wardatu al-kabīratu',
          meaningEn: 'The big rose (Stage 3: Definite Phrase - Incomplete)',
          meaningBn: 'বড় গোলাপটি (নির্দিষ্ট গুণবাচক বাক্যাংশ - অপূর্ণ)',
          exampleAr: 'الْكِتَابُ الْجَدِيدُ',
          exampleEn: 'The new book (Definite Phrase)',
          exampleBn: 'নতুন কিতাবটি',
          audioKey: 'al_wardatu_al_kabirah',
          exampleAudioKey: 'al_kitabu_al_jadid',
          emoji: '🌷',
        },
        {
          id: 'cp-c3l2-stage4',
          ar: 'الْوَرْدَةُ الْكَبِيرَةُ جَمِيلَةٌ',
          romanized: 'al-wardatu al-kabīratu jamīlatun',
          meaningEn: 'The big rose is beautiful (Stage 4: Complete Qualified Sentence)',
          meaningBn: 'বড় গোলাপটি সুন্দর (পূর্ণ বাক্য: জটিল মুবতাদা + খবর)',
          exampleAr: 'الْكِتَابُ الْجَدِيدُ قَيِّمٌ',
          exampleEn: 'The new book is valuable.',
          exampleBn: 'নতুন কিতাবটি মূল্যবান।',
          audioKey: 'al_wardatu_al_kabiratu_jamilah',
          exampleAudioKey: 'al_kitabu_al_jadidu_qayyim',
          emoji: '💐',
        },
      ],
    },
  },

  // 6. Deep Pedagogical Concept: Proper Nouns with Definite Descriptive Titles
  {
    id: 'ch3-l2-step-6-concept-proper-title',
    type: 'concept_intro',
    pageNumber: 96,
    titleEn: 'Syntactic Rule: Proper Nouns with Definite Titles',
    titleAr: 'قَاعِدَةٌ: تَرْكِيبُ اللَّقَبِ المَعْرِفَةِ مَعَ العَلَمِ',
    instructionEn: 'A proper noun (عَلَم) is inherently definite without «الـ». When qualified by an occupational title, the title takes «الـ» to match definiteness.',
    instructionBn: 'নামবাচক বিশেষ্য (আলম) স্বভাবগতভাবেই নির্দিষ্ট। তাই তার গুণবাচক পেশা বা উপাধিতে «الـ» যুক্ত হয়ে নির্দিষ্টতার সামঞ্জস্য বিধান করে।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c3l2-mahmud-merchant',
          ar: 'مَحْمُودٌ التَّاجِرُ غَنِيٌّ',
          romanized: 'Maḥmūdun al-tājiru ghaniyyun',
          meaningEn: 'Mahmud the merchant is rich (Proper Noun + Definite Title + Predicate).',
          meaningBn: 'বণিক মাহমুদ ধনী (আলম + নির্দিষ্ট সিফাত + খবর)।',
          exampleAr: 'مَحْمُودٌ التَّاجِرُ غَنِيٌّ',
          exampleEn: 'Mahmud the merchant is rich.',
          exampleBn: 'বণিক মাহমুদ ধনী।',
          audioKey: 'mahmud_al_tajiru_ghaniyy',
          exampleAudioKey: 'mahmud_al_tajiru_ghaniyy',
          emoji: '👔',
        },
        {
          id: 'cp-c3l2-zaynab-teacher',
          ar: 'زَيْنَبُ الْمُعَلِّمَةُ امْرَأَةٌ طَيِّبَةٌ',
          romanized: 'Zaynabu al-mu‘allimatu imra’atun ṭayyibatun',
          meaningEn: 'Zaynab the teacher is a good woman.',
          meaningBn: 'শিক্ষিকা জয়নব একজন ভালো মহিলা।',
          exampleAr: 'زَيْنَبُ الْمُعَلِّمَةُ امْرَأَةٌ طَيِّبَةٌ',
          exampleEn: 'Zaynab the teacher is a good woman.',
          exampleBn: 'শিক্ষিকা জয়নব একজন ভালো মহিলা।',
          audioKey: 'zaynab_al_muallimah_imraah_tayyibah',
          exampleAudioKey: 'zaynab_al_muallimah_imraah_tayyibah',
          emoji: '👩‍🏫',
        },
      ],
    },
  },

  // 7. Polar Sort 1: Incomplete Phrase vs Complete Sentence
  {
    id: 'ch3-l2-step-7-polar-sentence-vs-phrase',
    type: 'polar_sort',
    pageNumber: 95,
    titleEn: 'Binary Syntactic Sort: Complete Sentence vs Phrase',
    titleAr: 'تَمْيِيزُ الجُمْلَةِ التَّامَّةِ مِنَ المُرَكَّبِ النَّاقِصِ',
    instructionEn: 'Analyze «الْكِتَابُ الْجَدِيدُ»: Is it a complete informational sentence or an incomplete descriptive phrase?',
    instructionBn: '«الْكِتَابُ الْجَدِيدُ» বিশ্লেষণ করুন: এটি কি একটি পূর্ণাঙ্গ বাক্য নাকি অপূর্ণ গুণবাচক বাক্যাংশ?',
    polarPayload: {
      arabicSubject: 'الْكِتَابُ الْجَدِيدُ',
      meaningEn: 'The new book (both terms have Al-)',
      meaningBn: 'নতুন কিতাবটি (উভয় পদে আল- যুক্ত)',
      gender: 'masculine',
      correctAnswer: 'Incomplete Phrase (نَاقِصَة)',
      options: ['Complete Sentence (تَامَّة)', 'Incomplete Phrase (نَاقِصَة)'],
      emoji: '📖',
    },
  },

  // 8. Polar Sort 2: Speed Concord of the New Car
  {
    id: 'ch3-l2-step-8-polar-car-speed',
    type: 'polar_sort',
    pageNumber: 96,
    titleEn: 'Binary Semantic Sort: Velocity of the New Automobile',
    titleAr: 'تَمْيِيزُ سُرْعَةِ السَّيَّارَةِ الجَدِيدَةِ',
    instructionEn: 'According to the reading passage, how is the new car characterized?',
    instructionBn: 'পাঠ্য অনুসারে নতুন গাড়িটির গতি কেমন?',
    polarPayload: {
      arabicSubject: 'السَّيَّارَةُ الْجَدِيدَةُ',
      meaningEn: 'The new car is...',
      meaningBn: 'নতুন গাড়িটি...',
      gender: 'feminine',
      correctAnswer: 'سَرِيعَةٌ',
      options: ['سَرِيعَةٌ', 'بَطِيئَةٌ'],
      emoji: '🏎️',
    },
  },

  // 9. Cloze Choice Drill 1: Ancient Mosque Renown
  {
    id: 'ch3-l2-step-9-cloze-old-mosque',
    type: 'cloze_choice',
    pageNumber: 96,
    titleEn: 'Contextual Selection: Renown of the Ancient Mosque',
    titleAr: 'إِخْبَارٌ عَنِ المَسْجِدِ القَدِيمِ',
    instructionEn: 'Complete the sentence: "The ancient mosque is famous": «الْمَسْجِدُ الْقَدِيمُ ...»',
    instructionBn: '"পুরাতন মসজিদটি প্রসিদ্ধ" বাক্যটি পূর্ণ করুন: «الْمَسْجِدُ الْقَدِيمُ ...»',
    clozePayload: {
      questionAr: 'الْمَسْجِدُ الْقَدِيمُ ...',
      questionEn: 'The ancient mosque is famous.',
      questionBn: 'পুরাতন মসজিদটি প্রসিদ্ধ।',
      partialAnswerAr: 'الْمَسْجِدُ الْقَدِيمُ ...',
      correctAnswer: 'مَشْهُورٌ',
      options: ['مَشْهُورٌ', 'الْمَشْهُورُ', 'مَشْهُورًا', 'كَبِيرَةٌ'],
      emoji: '🕌',
    },
  },

  // 10. Cloze Choice Drill 2: Mahmud the Merchant Title Accord
  {
    id: 'ch3-l2-step-10-cloze-mahmud-merchant',
    type: 'cloze_choice',
    pageNumber: 96,
    titleEn: 'Syntactic Selection: Definite Title Following Proper Noun',
    titleAr: 'تَرْكِيبُ اللَّقَبِ مَعَ العَلَمِ',
    instructionEn: 'Select the definite title: "Mahmud the merchant is rich": «مَحْمُودٌ ... غَنِيٌّ».',
    instructionBn: '"বণিক মাহমুদ ধনী" বাক্যটিতে সঠিক উপাধিটি বসান: «مَحْمُودٌ ... غَنِيٌّ»।',
    clozePayload: {
      questionAr: 'مَحْمُودٌ ... غَنِيٌّ',
      questionEn: 'Mahmud the merchant is rich.',
      questionBn: 'বণিক মাহমুদ ধনী।',
      partialAnswerAr: 'مَحْمُودٌ ... غَنِيٌّ',
      correctAnswer: 'التَّاجِرُ',
      options: ['التَّاجِرُ', 'تَاجِرٌ', 'التَّاجِرِ', 'التَّاجِرَ'],
      emoji: '👔',
    },
  },

  // 11. Dialogic Alternative Q&A Battery 1: Flora & Intellect
  {
    id: 'ch3-l2-step-11-dialogue-flora-study',
    type: 'alternative_qa',
    pageNumber: 97,
    titleEn: 'Dialogic Battery: The Rose, New Book & Diligent Student',
    titleAr: 'حِوَارُ التَّعْيِينِ: الوَرْدَةُ وَالكِتَابُ وَالتِّلْمِيذُ',
    instructionEn: 'Answer alternative conversational queries based on visual cues without using yes or no.',
    instructionBn: 'হ্যাঁ বা না ছাড়া দৃশ্যায়নের তথ্যের ভিত্তিতে বিকল্প প্রশ্নগুলোর সঠিক উত্তর দিন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c3l2-1',
          questionAr: 'كَيْفَ الْوَرْدَةُ ؟ أَ كَبِيرَةٌ هِيَ أَمْ صَغِيرَةٌ ؟',
          contextAr: 'الْوَرْدَةُ كَبِيرَةٌ',
          contextEn: 'The rose is large',
          contextBn: 'গোলাপটি বড়',
          visualCue: '🌹',
          optionsAr: ['كَبِيرَةٌ', 'صَغِيرَةٌ'],
          correctAnswerAr: 'كَبِيرَةٌ',
        },
        {
          id: 'qa-c3l2-2',
          questionAr: 'أَ عِنْدَ مَحْمُودٍ الْكِتَابُ الْجَدِيدُ أَمْ عِنْدَكَ ؟',
          contextAr: 'الْكِتَابُ الْجَدِيدُ عِنْدَ مَحْمُودٍ',
          contextEn: 'The new book is with Mahmud',
          contextBn: 'নতুন বইটি মাহমুদের কাছে আছে',
          visualCue: '📖',
          optionsAr: ['عِنْدَ مَحْمُودٍ', 'عِنْدِي'],
          correctAnswerAr: 'عِنْدَ مَحْمُودٍ',
        },
        {
          id: 'qa-c3l2-3',
          questionAr: 'أَ قِصَّةٌ عَجِيبَةٌ فِي الْكِتَابِ أَمْ شِعْرٌ ؟',
          contextAr: 'فِي الْكِتَابِ قِصَّةٌ عَجِيبَةٌ',
          contextEn: 'In the book is a wondrous story',
          contextBn: 'বইটিতে একটি চমৎকার গল্প আছে',
          visualCue: '📜',
          optionsAr: ['قِصَّةٌ عَجِيبَةٌ', 'شِعْرٌ'],
          correctAnswerAr: 'قِصَّةٌ عَجِيبَةٌ',
        },
        {
          id: 'qa-c3l2-4',
          questionAr: 'أَ مُجْتَهِدٌ التِّلْمِيذُ الذَّكِيُّ أَمْ كَسْلَانُ ؟',
          contextAr: 'التِّلْمِيذُ الذَّكِيُّ مُجْتَهِدٌ',
          contextEn: 'The intelligent student is diligent',
          contextBn: 'মেধাবী ছাত্রটি পরিশ্রমী',
          visualCue: '👦',
          optionsAr: ['مُجْتَهِدٌ', 'كَسْلَانُ'],
          correctAnswerAr: 'مُجْتَهِدٌ',
        },
        {
          id: 'qa-c3l2-5',
          questionAr: 'أَ فِي غُرْفَةِ الْمُعَلِّمِ هُوَ أَمْ فِي الْفَصْلِ ؟',
          contextAr: 'هُوَ فِي غُرْفَةِ الْمُعَلِّمِ',
          contextEn: 'He is in the teacher’s room',
          contextBn: 'সে শিক্ষকের কামরায় আছে',
          visualCue: '👨‍🏫',
          optionsAr: ['فِي غُرْفَةِ الْمُعَلِّمِ', 'فِي الْفَصْلِ'],
          correctAnswerAr: 'فِي غُرْفَةِ الْمُعَلِّمِ',
        },
      ],
    },
  },

  // 12. Dialogic Alternative Q&A Battery 2: Vehicle, House & Aquatic Basin
  {
    id: 'ch3-l2-step-12-dialogue-vehicle-basin',
    type: 'alternative_qa',
    pageNumber: 97,
    titleEn: 'Dialogic Battery: The Swift Car, House Owner & Great Fish',
    titleAr: 'حِوَارُ التَّعْيِينِ: السَّيَّارَةُ وَصَاحِبُ البَيْتِ وَالسَّمَكَةُ',
    instructionEn: 'Examine attributes of the vehicle, the house owner, and the fish based on visual cues without using yes or no.',
    instructionBn: 'হ্যাঁ বা না ছাড়া দৃশ্যায়নের আলোকে গাড়ির গতি, বাড়ির মালিক ও মাছ সম্পর্কিত প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c3l2-6',
          questionAr: 'كَيْفَ السَّيَّارَةُ الْجَدِيدَةُ ؟ أَ سَرِيعَةٌ هِيَ أَمْ بَطِيئَةٌ ؟',
          contextAr: 'السَّيَّارَةُ الْجَدِيدَةُ سَرِيعَةٌ',
          contextEn: 'The new car is fast',
          contextBn: 'নতুন গাড়িটি দ্রুতগামী',
          visualCue: '🏎️',
          optionsAr: ['سَرِيعَةٌ', 'بَطِيئَةٌ'],
          correctAnswerAr: 'سَرِيعَةٌ',
        },
        {
          id: 'qa-c3l2-7',
          questionAr: 'أَ سَيَّارَةٌ جَدِيدَةٌ أَمَامَ هَذَا الْبَيْتِ أَمْ قَدِيمَةٌ ؟',
          contextAr: 'أَمَامَ هَذَا الْبَيْتِ سَيَّارَةٌ جَدِيدَةٌ',
          contextEn: 'In front of this house is a new car',
          contextBn: 'এই বাড়ির সামনে একটি নতুন গাড়ি আছে',
          visualCue: '🚗✨',
          optionsAr: ['سَيَّارَةٌ جَدِيدَةٌ', 'سَيَّارَةٌ قَدِيمَةٌ'],
          correctAnswerAr: 'سَيَّارَةٌ جَدِيدَةٌ',
        },
        {
          id: 'qa-c3l2-8',
          questionAr: 'أَ فَلَّاحٌ صَاحِبُ هَذَا الْبَيْتِ الْجَمِيلِ أَمْ تَاجِرٌ ؟',
          contextAr: 'صَاحِبُ هَذَا الْبَيْتِ الْجَمِيلِ تَاجِرٌ',
          contextEn: 'The owner of this beautiful house is a merchant',
          contextBn: 'এই সুন্দর বাড়ির মালিক একজন ব্যবসায়ী',
          visualCue: '💼',
          optionsAr: ['تَاجِرٌ', 'فَلَّاحٌ'],
          correctAnswerAr: 'تَاجِرٌ',
        },
        {
          id: 'qa-c3l2-9',
          questionAr: 'أَ فِي الْحَوْضِ الْكَبِيرِ السَّمَكَةُ أَمْ فِي الصَّغِيرِ ؟',
          contextAr: 'السَّمَكَةُ فِي الْحَوْضِ الْكَبِيرِ',
          contextEn: 'The fish is in the big basin',
          contextBn: 'মাছটি বড় হাউজে আছে',
          visualCue: '🏊‍♂️',
          optionsAr: ['فِي الْحَوْضِ الْكَبِيرِ', 'فِي الصَّغِيرِ'],
          correctAnswerAr: 'فِي الْحَوْضِ الْكَبِيرِ',
        },
        {
          id: 'qa-c3l2-10',
          questionAr: 'أَ لَذِيذَةٌ السَّمَكَةُ الْكَبِيرَةُ أَمْ غَيْرُ لَذِيذَةٍ ؟',
          contextAr: 'السَّمَكَةُ الْكَبِيرَةُ لَذِيذَةٌ',
          contextEn: 'The big fish is delicious',
          contextBn: 'বড় মাছটি সুস্বাদু',
          visualCue: '🐟😋',
          optionsAr: ['لَذِيذَةٌ', 'غَيْرُ لَذِيذَةٍ'],
          correctAnswerAr: 'لَذِيذَةٌ',
        },
      ],
    },
  },

  // 13. Speed Pair Matching 2: Qualified Descriptive Sentences
  {
    id: 'ch3-l2-step-13-speed-qualified-sentences',
    type: 'speed_pair',
    pageNumber: 95,
    titleEn: 'Synaptic Speed Pairing: Definite Descriptive Sentences',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: الجُمَلُ الوَصْفِيَّةُ المَعْرِفَةُ',
    instructionEn: 'Pair the complex Arabic sentences with their precise English translations.',
    instructionBn: 'জটিল গুণবাচক আরবি বাক্যগুলোর সাথে তাদের অনুবাদের দ্রুত মিল করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c3l2-7', ar: 'الْوَرْدَةُ الْكَبِيرَةُ جَمِيلَةٌ', meaning: 'The big rose is beautiful' },
        { id: 'p-c3l2-8', ar: 'الْكِتَابُ الْجَدِيدُ قَيِّمٌ', meaning: 'The new book is valuable' },
        { id: 'p-c3l2-9', ar: 'التِّلْمِيذُ الذَّكِيُّ مُجْتَهِدٌ', meaning: 'The intelligent student is diligent' },
        { id: 'p-c3l2-10', ar: 'السَّيَّارَةُ الْجَدِيدَةُ سَرِيعَةٌ', meaning: 'The new car is fast' },
        { id: 'p-c3l2-11', ar: 'السَّمَكَةُ الْكَبِيرَةُ لَذِيذَةٌ', meaning: 'The big fish is delicious' },
      ],
    },
  },

  // 14. Page 95: Authentic Reading & Translation Drill 1: The Big Rose & Wondrous Story
  {
    id: 'ch3-l2-step-14-assembly-rose-story',
    type: 'sentence_assembly',
    pageNumber: 95,
    titleEn: 'Textbook Translation: Big Rose & Story',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: الوَرْدَةُ الكَبِيرَةُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'الْوَرْدَةُ الْكَبِيرَةُ جَمِيلَةٌ ، وَفِي الْكِتَابِ الْجَدِيدِ قِصَّةٌ عَجِيبَةٌ',
      promptEn: 'The big rose is beautiful and in the new book is a wondrous story',
      promptBn: 'বড় গোলাপটি সুন্দর এবং নতুন বইটিতে একটি চমৎকার গল্প রয়েছে',
      expectedAnswer: ['The', 'big', 'rose', 'is', 'beautiful', 'and', 'in', 'the', 'new', 'book', 'is', 'a', 'wondrous', 'story'],
      chips: ['The', 'big', 'rose', 'is', 'beautiful', 'and', 'in', 'the', 'new', 'book', 'is', 'a', 'wondrous', 'story', 'ugly', 'small'],
      expectedAnswerBn: ['বড়', 'গোলাপটি', 'সুন্দর', 'এবং', 'নতুন', 'বইটিতে', 'একটি', 'চমৎকার', 'গল্প', 'রয়েছে'],
      chipsBn: ['বড়', 'গোলাপটি', 'সুন্দর', 'এবং', 'নতুন', 'বইটিতে', 'একটি', 'চমৎকার', 'গল্প', 'রয়েছে', 'কুৎসিত', 'ছোট'],
      emoji: '🌹',
    },
  },

  // 15. Page 96: Authentic Reading & Translation Drill 2: Mahmud the Merchant
  {
    id: 'ch3-l2-step-15-assembly-mahmud-merchant',
    type: 'sentence_assembly',
    pageNumber: 96,
    titleEn: 'Textbook Translation: Mahmud the Merchant',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: مَحْمُودٌ التَّاجِرُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'مَحْمُودٌ التَّاجِرُ غَنِيٌّ ، وَدُكَّانُهُ فِي السُّوقِ',
      promptEn: 'Mahmud the merchant is rich and his shop is in the market',
      promptBn: 'বণিক মাহমুদ ধনী এবং তার দোকান বাজারে রয়েছে',
      expectedAnswer: ['Mahmud', 'the', 'merchant', 'is', 'rich', 'and', 'his', 'shop', 'is', 'in', 'the', 'market'],
      chips: ['Mahmud', 'the', 'merchant', 'is', 'rich', 'and', 'his', 'shop', 'is', 'in', 'the', 'market', 'poor', 'village'],
      expectedAnswerBn: ['বণিক', 'মাহমুদ', 'ধনী', 'এবং', 'তার', 'দোকানটি', 'বাজারে', 'রয়েছে'],
      chipsBn: ['বণিক', 'মাহমুদ', 'ধনী', 'এবং', 'তার', 'দোকানটি', 'বাজারে', 'রয়েছে', 'দরিদ্র', 'গ্রামে'],
      emoji: '👔',
    },
  },

  // 16. Page 96: Authentic Reading & Translation Drill 3: Fish in the Large Basin
  {
    id: 'ch3-l2-step-16-assembly-fish-basin',
    type: 'sentence_assembly',
    pageNumber: 96,
    titleEn: 'Textbook Translation: Fish in the Basin',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: السَّمَكَةُ فِي الحَوْضِ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'السَّمَكَةُ الْكَبِيرَةُ فِي الْحَوْضِ الْكَبِيرِ لَذِيذَةٌ جِدًّا',
      promptEn: 'The big fish in the large basin is very delicious',
      promptBn: 'বড় জলাশয়ের বড় মাছটি খুবই সুস্বাদু',
      expectedAnswer: ['The', 'big', 'fish', 'in', 'the', 'large', 'basin', 'is', 'very', 'delicious'],
      chips: ['The', 'big', 'fish', 'in', 'the', 'large', 'basin', 'is', 'very', 'delicious', 'small', 'cup', 'tasteless'],
      expectedAnswerBn: ['বড়', 'জলাশয়ের', 'বড়', 'মাছটি', 'খুবই', 'সুস্বাদু'],
      chipsBn: ['বড়', 'জলাশয়ের', 'বড়', 'মাছটি', 'খুবই', 'সুস্বাদু', 'ছোট', 'গ্লাসের', 'বিস্বাদ'],
      emoji: '🐟',
    },
  },

  // 17. Syntactic Tarkib Dissector: Qualified Descriptive Subject Architecture
  {
    id: 'ch3-l2-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 99,
    titleEn: 'Syntactic Tarkib Dissector: Definite Mawsoof-Sifah Subject Tree',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: بِنَاءُ المَوْصُوفِ وَالصِّفَةِ فِي مَوْقِعِ المُبْتَدَأِ',
    instructionEn: 'Dissect how a definite noun paired with a definite adjective forms a compound subject (Mubtada) followed by its predicate (Khabar).',
    instructionBn: 'নির্দিষ্ট মাওসূফ ও সিফাত মিলে কীভাবে যৌগিক মুবতাদা গঠিত হয়ে খবর গ্রহণ করে তা ব্যাকরণগতভাবে বিশ্লেষণ করুন।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c3l2-s1',
          sentenceAr: 'الْوَرْدَةُ الْكَبِيرَةُ جَمِيلَةٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مَوْصُوفٌ وَصِفَةٌ مُبْتَدَأٌ + خَبَرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Definite Descriptive Subject + Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (নির্দিষ্ট মাওসূফ-সিফাত মুবতাদা + খবর)',
          slots: [
            {
              roleAr: 'مَوْصُوفٌ (مُبْتَدَأٌ)',
              roleEn: 'Qualified Noun / Subject',
              roleBn: 'মাওসূফ (মুবতাদা)',
              expectedWordAr: 'الْوَرْدَةُ',
            },
            {
              roleAr: 'صِفَةٌ (مَرْفُوعَةٌ)',
              roleEn: 'Definite Adjective (Sifah)',
              roleBn: 'সিফাত (মারফু)',
              expectedWordAr: 'الْكَبِيرَةُ',
            },
            {
              roleAr: 'خَبَرٌ (مَرْفُوعٌ)',
              roleEn: 'Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'جَمِيلَةٌ',
            },
          ],
          availableWordsAr: ['جَمِيلَةٌ', 'الْكَبِيرَةُ', 'الْوَرْدَةُ'],
        },
        {
          id: 'tarkib-c3l2-s2',
          sentenceAr: 'مَحْمُودٌ التَّاجِرُ غَنِيٌّ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (عَلَمٌ مَوْصُوفٌ مَعَ لَقَبٍ مَعْرِفَةٍ + خَبَرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Proper Noun Subject + Definite Title + Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (আলম মাওসূফ + নির্দিষ্ট উপাধি + খবর)',
          slots: [
            {
              roleAr: 'مَوْصُوفٌ (عَلَمٌ مُبْتَدَأٌ)',
              roleEn: 'Proper Noun Subject',
              roleBn: 'আলম মাওসূফ (মুবতাদা)',
              expectedWordAr: 'مَحْمُودٌ',
            },
            {
              roleAr: 'صِفَةٌ (مَعْرِفَةٌ)',
              roleEn: 'Definite Title (Sifah)',
              roleBn: 'নির্দিষ্ট উপাধি (সিফাত)',
              expectedWordAr: 'التَّاجِرُ',
            },
            {
              roleAr: 'خَبَرٌ (مَرْفُوعٌ)',
              roleEn: 'Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'غَنِيٌّ',
            },
          ],
          availableWordsAr: ['غَنِيٌّ', 'مَحْمُودٌ', 'التَّاجِرُ'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah Al-Fatihah 1:6)
  {
    id: 'ch3-l2-step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 99,
    titleEn: 'Sacred Reflection: Definite Descriptive Concord in Surah Al-Fatihah',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: الصِّفَةُ وَالمَوْصُوفُ مَعَ أَلْ فِي أُمِّ القُرْآنِ',
    instructionEn: 'Witness how definite descriptive concordance (Mawsuf + Sifah with «الـ») forms the supreme supplication of Surah Al-Fatihah (1:6).',
    instructionBn: 'সূরা আল-ফাতিহার কেন্দ্রীয় প্রার্থনায় নির্দিষ্ট মাওসূফ ও সিফাতের (উভয়েই আল- যুক্ত) সমন্বয় প্রত্যক্ষ করুন।',
    echoPayload: {
      surahNumber: 1,
      ayahNumber: 6,
      surahNameAr: 'الفاتحة',
      surahNameEn: 'Al-Fatihah',
      arabicText: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
      translationEn: 'Guide us to the straight path.',
      translationBn: 'আমাদের সরল সঠিক পথ প্রদর্শন করুন।',
      highlightedWords: ['الصِّرَاطَ', 'الْمُسْتَقِيمَ'],
      patternNameEn: 'Definite Descriptive Phrase (الصِّفَةُ وَالمَوْصُوفُ مَعَ أَلْ)',
      patternNameBn: 'নির্দিষ্ট গুণবাচক বাক্যাংশ (মাওসূফ ও সিফাতে আল-)',
      lessonPatternAr: 'الْكِتَابُ الْجَدِيدُ / الْمَسْجِدُ الْقَدِيمُ',
      lessonPatternEn: 'The new book / The old mosque',
      lessonPatternBn: 'নতুন কিতাবটি / পুরাতন মসজিদটি',
      quranPatternAr: 'الصِّرَاطَ الْمُسْتَقِيمَ',
      quranPatternEn: 'The straight path',
      quranPatternBn: 'সরল সঠিক পথ',
      reflection: 'When both the qualified noun (مَوْصُوف) and the adjective (صِفَة) receive the definite article «الـ», they form an indivisible definite descriptive phrase. In this lesson, you mastered how «الْكِتَابُ الْجَدِيدُ» means "the new book". In Surah Al-Fatihah, recited in every unit of prayer, this identical syntactic rule pairs «الصِّرَاطَ» (the path) with «الْمُسْتَقِيمَ» (the straight) to specify the singular path of divine favor.',
      audioKey: 'quran_001006',
    },
  },
];

export const CH3_LESSON_02_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 3,
  lessonNum: 2,
  titleEn: 'Definite Descriptive Phrases & Sentences',
  titleAr: 'الصِّفَةُ وَالمَوْصُوفُ مَعَ أَلْ وَتَرْكِيبُ الجُمْلَةِ',
  wordsLearned: [
    'الْوَرْدَةُ',
    'الْكَبِيرَةُ',
    'الْجَدِيدُ',
    'الْقَدِيمُ',
    'الْمَشْهُورُ',
    'السَّمَكَةُ',
    'اللَّذِيذَةُ',
    'التَّاجِرُ',
    'الْعَجِيبَةُ',
    'حَوْضٌ',
    'بَطِيءٌ',
    'صَاحِبٌ',
  ],
  steps: CH3_LESSON_02_STEPS,
};
