// Lesson 8 Interactive Session Data (Directly mapped from textbook Volume 1 Chapter 1 Lesson 8, pages 43-44)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const LESSON_08_STEPS: SessionStep[] = [
  // 1. Concept Discovery: Preposition فِي (In) & Genitive Kasrah Shift
  {
    id: 'step-1-concept-fi-intro',
    type: 'concept_intro',
    pageNumber: 43,
    titleEn: 'Preposition فِي (In)',
    titleAr: 'حَرْفُ الجَرِّ «فِي»',
    instructionEn: 'Notice how the preposition فِي gives the following noun a Kasrah (ـِ)',
    instructionBn: 'লক্ষ্য করো: فِي যুক্ত হলে শব্দের শেষে কাসরা (যের) হয়',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-fi-masjid',
          ar: 'الْمَسْجِدُ ➔ فِي الْمَسْجِدِ',
          romanized: 'al-masjidu ➔ fī al-masjidi',
          meaningEn: 'The mosque ➔ In the mosque',
          meaningBn: 'মসজিদটি ➔ মসজিদে',
          exampleAr: 'الرَّجُلُ فِي الْمَسْجِدِ',
          exampleEn: 'The man is in the mosque.',
          exampleBn: 'লোকটি মসজিদে আছে।',
          audioKey: 'fi_al_masjid',
          exampleAudioKey: 'ar_rajulu_fi_al_masjid',
          emoji: '🕌',
          compound: {
            baseAr: 'الْمَسْجِدُ',
            baseRom: 'al-masjidu',
            baseMeaningEn: 'The mosque',
            baseMeaningBn: 'মসজিদটি',
            baseAudioKey: 'al_masjidu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي الْمَسْجِدِ',
            resultRom: 'fī al-masjidi',
            resultMeaningEn: 'In the mosque',
            resultMeaningBn: 'মসজিদে',
            resultAudioKey: 'fi_al_masjid',
            badge: 'Kasrah Shift (مَجْرُور)',
          },
        },
        {
          id: 'cp-fi-qaryah',
          ar: 'الْقَرْيَةُ ➔ فِي الْقَرْيَةِ',
          romanized: 'al-qaryatu ➔ fī al-qaryati',
          meaningEn: 'The village ➔ In the village',
          meaningBn: 'গ্রামটি ➔ গ্রামে',
          exampleAr: 'الْمَرْأَةُ فِي الْقَرْيَةِ',
          exampleEn: 'The woman is in the village.',
          exampleBn: 'মহিলাটি গ্রামে আছে।',
          audioKey: 'fi_al_qaryah',
          exampleAudioKey: 'al_maratu_fi_al_qaryah',
          emoji: '🏡',
          compound: {
            baseAr: 'الْقَرْيَةُ',
            baseRom: 'al-qaryatu',
            baseMeaningEn: 'The village',
            baseMeaningBn: 'গ্রামটি',
            baseAudioKey: 'al_qaryatu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي الْقَرْيَةِ',
            resultRom: 'fī al-qaryati',
            resultMeaningEn: 'In the village',
            resultMeaningBn: 'গ্রামে',
            resultAudioKey: 'fi_al_qaryah',
            badge: 'Kasrah Shift (مَجْرُور)',
          },
        },
        {
          id: 'cp-fi-suq',
          ar: 'سُوقُ الْقَرْيَةِ ➔ فِي سُوقِ الْقَرْيَةِ',
          romanized: 'sūqu al-qaryati ➔ fī sūqi al-qaryati',
          meaningEn: 'The village market ➔ In the village market',
          meaningBn: 'গ্রামের বাজার ➔ গ্রামের বাজারে',
          exampleAr: 'دُكَّانٌ فِي سُوقِ الْقَرْيَةِ',
          exampleEn: 'A shop is in the village market.',
          exampleBn: 'গ্রামের বাজারে একটি দোকান আছে।',
          audioKey: 'fi_suq_al_qaryah',
          exampleAudioKey: 'dukkanun_fi_suq_al_qaryah',
          emoji: '🏪',
          compound: {
            baseAr: 'سُوقُ الْقَرْيَةِ',
            baseRom: 'sūqu al-qaryati',
            baseMeaningEn: 'The village market',
            baseMeaningBn: 'গ্রামের বাজার',
            baseAudioKey: 'suq_al_qaryati',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي سُوقِ الْقَرْيَةِ',
            resultRom: 'fī sūqi al-qaryati',
            resultMeaningEn: 'In the village market',
            resultMeaningBn: 'গ্রামের বাজারে',
            resultAudioKey: 'fi_suq_al_qaryah',
            badge: 'Mudaf Kasrah Shift',
          },
        },
      ],
    },
  },

  // 2. Concept Discovery: Attached Pronouns with فِي
  {
    id: 'step-2-concept-fi-pronouns',
    type: 'concept_intro',
    pageNumber: 43,
    titleEn: 'Attached Pronouns with فِي',
    titleAr: 'الضَّمَائِرُ الْمُتَّصِلَةُ مَعَ «فِي»',
    instructionEn: 'Notice how nouns with attached pronouns take a Kasrah after فِي',
    instructionBn: 'সর্বনামযুক্ত শব্দের ক্ষেত্রেও فِي-এর পর কাসরা (যের) বিশিষ্ট রূপ ধারণ করে।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-fi-ghurfatihi',
          ar: 'غُرْفَتُهُ ➔ فِي غُرْفَتِهِ',
          romanized: 'ghurfatuhu ➔ fī ghurfatihi',
          meaningEn: 'His room ➔ In his room',
          meaningBn: 'তার কামরা ➔ তার কামরায়',
          exampleAr: 'هُوَ فِي غُرْفَتِهِ',
          exampleEn: 'He is in his room.',
          exampleBn: 'সে তার কামরায় আছে।',
          audioKey: 'fi_ghurfatihi',
          exampleAudioKey: 'huwa_fi_ghurfatihi',
          emoji: '🚪',
          compound: {
            baseAr: 'غُرْفَتُهُ',
            baseRom: 'ghurfatuhu',
            baseMeaningEn: 'His room',
            baseMeaningBn: 'তার কামরা',
            baseAudioKey: 'ghurfatuhu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي غُرْفَتِهِ',
            resultRom: 'fī ghurfatihi',
            resultMeaningEn: 'In his room',
            resultMeaningBn: 'তার কামরায়',
            resultAudioKey: 'fi_ghurfatihi',
            badge: 'Pronoun Genitive Kasrah',
          },
        },
        {
          id: 'cp-fi-ghurfatiha',
          ar: 'غُرْفَتُهَا ➔ فِي غُرْفَتِهَا',
          romanized: 'ghurfatuhā ➔ fī ghurfatihā',
          meaningEn: 'Her room ➔ In her room',
          meaningBn: 'তার কামরা ➔ তার কামরায়',
          exampleAr: 'عَائِشَةُ فِي غُرْفَتِهَا',
          exampleEn: 'Aisha is in her room.',
          exampleBn: 'আয়েশা তার কামরায় আছে।',
          audioKey: 'fi_ghurfatiha',
          exampleAudioKey: 'aishatu_fi_ghurfatiha',
          emoji: '🛏️',
          compound: {
            baseAr: 'غُرْفَتُهَا',
            baseRom: 'ghurfatuhā',
            baseMeaningEn: 'Her room',
            baseMeaningBn: 'তার কামরা',
            baseAudioKey: 'ghurfatuha',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي غُرْفَتِهَا',
            resultRom: 'fī ghurfatihā',
            resultMeaningEn: 'In her room',
            resultMeaningBn: 'তার কামরায়',
            resultAudioKey: 'fi_ghurfatiha',
            badge: 'Pronoun Genitive Kasrah',
          },
        },
        {
          id: 'cp-fi-ghurfatika',
          ar: 'غُرْفَتُكَ ➔ فِي غُرْفَتِكَ',
          romanized: 'ghurfatuka ➔ fī ghurfatika',
          meaningEn: 'Your room (m) ➔ In your room',
          meaningBn: 'তোমার কামরা (পুং) ➔ তোমার কামরায়',
          exampleAr: 'أَنْتَ فِي غُرْفَتِكَ',
          exampleEn: 'You are in your room.',
          exampleBn: 'তুমি তোমার কামরায় আছ।',
          audioKey: 'fi_ghurfatika',
          exampleAudioKey: 'anta_fi_ghurfatika',
          emoji: '🚪',
          compound: {
            baseAr: 'غُرْفَتُكَ',
            baseRom: 'ghurfatuka',
            baseMeaningEn: 'Your room (m)',
            baseMeaningBn: 'তোমার কামরা (পুং)',
            baseAudioKey: 'ghurfatuka',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي غُرْفَتِكَ',
            resultRom: 'fī ghurfatika',
            resultMeaningEn: 'In your room',
            resultMeaningBn: 'তোমার কামরায়',
            resultAudioKey: 'fi_ghurfatika',
            badge: 'Pronoun Genitive Kasrah',
          },
        },
      ],
    },
  },

  // 3. Speed Pairing: Location Phrases Active Recall
  {
    id: 'step-3-pair-fi-locations',
    type: 'speed_pair',
    pageNumber: 43,
    titleEn: 'Location Recall Drill',
    titleAr: 'تَطْبِيقُ عِبَارَاتِ «فِي»',
    instructionEn: 'Match each location phrase with its meaning',
    instructionBn: 'স্থানবাচক বাক্যাংশগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pfl-1', ar: 'فِي الْمَسْجِدِ', meaning: 'In the mosque' },
        { id: 'pfl-2', ar: 'فِي الْقَرْيَةِ', meaning: 'In the village' },
        { id: 'pfl-3', ar: 'فِي غُرْفَةِ الْمُعَلِّمِ', meaning: "In the teacher's room" },
        { id: 'pfl-4', ar: 'فِي سُوقِ الْقَرْيَةِ', meaning: 'In the village market' },
      ],
    },
  },

  // 4. Concept Discovery: Word Order & Fronting Syntax
  {
    id: 'step-4-concept-fronting',
    type: 'concept_intro',
    pageNumber: 43,
    titleEn: 'Word Order: Fronted Predicates',
    titleAr: 'تَقْدِيمُ الخَبَرِ وَتَأْخِيرُ المُبْتَدَأِ',
    instructionEn: 'Notice the difference when the prepositional phrase comes first',
    instructionBn: 'লক্ষ্য করো: অনির্দিষ্ট বিশেষ্য পরে আসলে "فِي" দিয়ে বাক্য শুরু হয়',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-front-man',
          ar: 'فِي الْمَسْجِدِ رَجُلٌ',
          romanized: 'fī al-masjidi rajulun',
          meaningEn: 'In the mosque is a man (A man is in the mosque)',
          meaningBn: 'মসজিদে একজন লোক আছে।',
          exampleAr: 'الرَّجُلُ فِي الْمَسْجِدِ',
          exampleEn: 'The man is in the mosque.',
          exampleBn: 'লোকটি মসজিদে আছে।',
          audioKey: 'fi_al_masjidi_rajul',
          exampleAudioKey: 'ar_rajulu_fi_al_masjid',
          emoji: '🕌',
          compound: {
            baseAr: 'الرَّجُلُ فِي الْمَسْجِدِ',
            baseRom: 'ar-rajulu fī al-masjidi',
            baseMeaningEn: 'Definite: The man is in the mosque',
            baseMeaningBn: 'নির্দিষ্ট: লোকটি মসজিদে আছে',
            baseAudioKey: 'ar_rajulu_fi_al_masjid',
            operator: '⇄',
            particleAr: 'فِي الْمَسْجِدِ رَجُلٌ',
            particleEn: 'Indefinite: In the mosque is a man',
            resultAr: 'فِي الْمَسْجِدِ رَجُلٌ',
            resultRom: 'fī al-masjidi rajulun',
            resultMeaningEn: 'Fronted: In the mosque is a man',
            resultMeaningBn: 'অনির্দিষ্ট: মসজিদে একজন লোক আছে',
            resultAudioKey: 'fi_al_masjidi_rajul',
            badge: 'Fronted Khabar (خَبَرٌ مُقَدَّمٌ)',
          },
        },
        {
          id: 'cp-front-lamp',
          ar: 'فِي الْغُرْفَةِ مِصْبَاحٌ',
          romanized: 'fī al-ghurfati miṣbāḥun',
          meaningEn: 'In the room is a lamp',
          meaningBn: 'কামরায় একটি বাতি আছে।',
          exampleAr: 'الْمِصْبَاحُ فِي الْغُرْفَةِ',
          exampleEn: 'The lamp is in the room.',
          exampleBn: 'বাতিটি কামরায় আছে।',
          audioKey: 'fi_al_ghurfati_misbah',
          exampleAudioKey: 'al_misbahu_fi_al_ghurfah',
          emoji: '💡',
          compound: {
            baseAr: 'الْمِصْبَاحُ فِي الْغُرْفَةِ',
            baseRom: 'al-miṣbāḥu fī al-ghurfati',
            baseMeaningEn: 'Definite: The lamp is in the room',
            baseMeaningBn: 'নির্দিষ্ট: বাতিটি কামরায় আছে',
            baseAudioKey: 'al_misbahu_fi_al_ghurfah',
            operator: '⇄',
            particleAr: 'فِي الْغُرْفَةِ مِصْبَاحٌ',
            particleEn: 'Indefinite: In the room is a lamp',
            resultAr: 'فِي الْغُرْفَةِ مِصْبَاحٌ',
            resultRom: 'fī al-ghurfati miṣbāḥun',
            resultMeaningEn: 'Fronted: In the room is a lamp',
            resultMeaningBn: 'অনির্দিষ্ট: কামরায় একটি বাতি আছে',
            resultAudioKey: 'fi_al_ghurfati_misbah',
            badge: 'Fronted Khabar (خَبَرٌ مُقَدَّمٌ)',
          },
        },
      ],
    },
  },

  // 5. Page 43: Authentic Reading & Translation Drill 1: In the mosque is a man
  {
    id: 'step-5-assembly-masjid-rajul',
    type: 'sentence_assembly',
    pageNumber: 43,
    titleEn: 'Textbook Translation: Man in Mosque',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: فِي المَسْجِدِ رَجُلٌ',
    instructionEn: 'Read the Arabic sentence and assemble the accurate translation using word chips.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং শব্দ চিপস সাজিয়ে সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'فِي الْمَسْجِدِ رَجُلٌ',
      promptEn: 'In the mosque is a man',
      promptBn: 'মসজিদে একজন লোক আছে',
      expectedAnswer: ['In the mosque', 'is', 'a man'],
      chips: ['In the mosque', 'is', 'a man', 'the teacher', 'a boy'],
      expectedAnswerBn: ['মসজিদে', 'একজন', 'লোক আছে'],
      chipsBn: ['মসজিদে', 'একজন', 'লোক আছে', 'শিক্ষক', 'ছেলে'],
      emoji: '🕌',
    },
  },

  // 6. Vocabulary Discovery: Objects & Places
  {
    id: 'step-6-vocab-objects-places',
    type: 'vocab_prime',
    pageNumber: 43,
    titleEn: 'Objects & Environment Vocabulary',
    titleAr: 'مُفْرَدَاتُ الأَشْيَاءِ وَالأَمَاكِنِ',
    instructionEn: 'Listen to and learn new core vocabulary from the lesson',
    instructionBn: 'পাঠের নতুন বস্তু ও স্থান সম্পর্কিত শব্দগুলোর উচ্চারণ শুনুন ও অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c8_sunduq', ar: 'صُنْدُوقٌ', en: 'Box / chest', bn: 'একটি বাক্স', romanized: 'ṣundūqun', emoji: '📦' },
        { id: 'v1_c8_iqd', ar: 'عِقْدٌ', en: 'Necklace', bn: 'একটি হার', romanized: '‘iqdun', emoji: '📿' },
        { id: 'v1_c8_shajarah', ar: 'شَجَرَةٌ', en: 'Tree', bn: 'একটি গাছ', romanized: 'shajaratun', emoji: '🌳' },
        { id: 'v1_c8_misbah', ar: 'مِصْبَاحٌ', en: 'Lamp', bn: 'একটি বাতি', romanized: 'miṣbāḥun', emoji: '💡' },
        { id: 'v1_c8_dukkan', ar: 'دُكَّانٌ', en: 'Shop / store', bn: 'একটি দোকান', romanized: 'dukkānun', emoji: '🏪' },
        { id: 'v1_c8_mirwahah', ar: 'مِرْوَحَةٌ', en: 'Fan', bn: 'একটি পাখা', romanized: 'mirwaḥatun', emoji: '🪭' },
        { id: 'v1_c8_mistarah', ar: 'مِسْطَرَةٌ', en: 'Ruler', bn: 'একটি স্কেল', romanized: 'misṭaratun', emoji: '📏' },
      ],
    },
  },

  // 7. Speed Pairing: Objects & Environment Active Recall
  {
    id: 'step-7-pair-objects',
    type: 'speed_pair',
    pageNumber: 43,
    titleEn: 'Object Matching Drill',
    titleAr: 'مُطَابَقَةُ الأَشْيَاءِ',
    instructionEn: 'Match each Arabic word with its meaning',
    instructionBn: 'শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pn-sunduq', ar: 'صُنْدُوقٌ', meaning: 'Box / chest' },
        { id: 'pn-iqd', ar: 'عِقْدٌ', meaning: 'Necklace' },
        { id: 'pn-shajarah', ar: 'شَجَرَةٌ', meaning: 'Tree' },
        { id: 'pn-misbah', ar: 'مِصْبَاحٌ', meaning: 'Lamp' },
        { id: 'pn-dukkan', ar: 'دُكَّانٌ', meaning: 'Shop / store' },
      ],
    },
  },

  // 8. Dialogic Alternative Q&A Battery 1 (Mosque & Aisha's Bag)
  {
    id: 'step-8-alt-qa-battery-1',
    type: 'alternative_qa',
    pageNumber: 44,
    titleEn: 'Dialogue Battery: Mosque & Aisha’s Bag',
    titleAr: 'حِوَارُ المَسْجِدِ وَحَقِيبَةِ عَائِشَةَ',
    instructionEn: 'Choose the authentic response corresponding to each dialogue inquiry',
    instructionBn: 'প্রতিটি কথোপকথনের প্রশ্নের সঠিক উত্তরটি নির্বাচন করুন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c8-1',
          questionAr: 'مَنْ فِي الْمَسْجِدِ ؟',
          optionsAr: ['فِي الْمَسْجِدِ رَجُلٌ', 'الرَّجُلُ فِي الْمَسْجِدِ'],
          correctAnswerAr: 'فِي الْمَسْجِدِ رَجُلٌ',
        },
        {
          id: 'qa-c8-2',
          questionAr: 'أَيْنَ الرَّجُلُ ؟',
          optionsAr: ['هُوَ فِي الْمَسْجِدِ', 'فِي الْمَسْجِدِ رَجُلٌ'],
          correctAnswerAr: 'هُوَ فِي الْمَسْجِدِ',
        },
        {
          id: 'qa-c8-3',
          questionAr: 'هَلْ هُوَ فِي الْمَسْجِدِ ؟',
          optionsAr: ['نَعَمْ .. هُوَ فِي الْمَسْجِدِ', 'نَعَمْ .. هِيَ فِي الْمَسْجِدِ'],
          correctAnswerAr: 'نَعَمْ .. هُوَ فِي الْمَسْجِدِ',
        },
        {
          id: 'qa-c8-4',
          questionAr: 'مَاذَا فِي حَقِيبَةِ عَائِشَةَ ؟',
          optionsAr: ['فِي حَقِيبَتِهَا كِتَابٌ وَ قَلَمٌ', 'فِي حَقِيبَتِهِ كِتَابٌ وَ قَلَمٌ'],
          correctAnswerAr: 'فِي حَقِيبَتِهَا كِتَابٌ وَ قَلَمٌ',
        },
        {
          id: 'qa-c8-5',
          questionAr: 'هَلْ فِي حَقِيبَتِهَا كِتَابٌ وَ قَلَمٌ ؟',
          optionsAr: ['نَعَمْ .. فِي حَقِيبَتِهَا كِتَابٌ وَ قَلَمٌ', 'نَعَمْ .. فِي حَقِيبَتِهِ كِتَابٌ وَ قَلَمٌ'],
          correctAnswerAr: 'نَعَمْ .. فِي حَقِيبَتِهَا كِتَابٌ وَ قَلَمٌ',
        },
        {
          id: 'qa-c8-6',
          questionAr: 'أَيْنَ الْكِتَابُ وَالْقَلَمُ ؟',
          optionsAr: ['الْكِتَابُ وَالْقَلَمُ فِي حَقِيبَةِ عَائِشَةَ', 'الْكِتَابُ فِي الْمَسْجِدِ'],
          correctAnswerAr: 'الْكِتَابُ وَالْقَلَمُ فِي حَقِيبَةِ عَائِشَةَ',
        },
      ],
    },
  },

  // 9. Page 43: Authentic Reading & Translation Drill 2: Village Shop
  {
    id: 'step-9-assembly-market-shop',
    type: 'sentence_assembly',
    pageNumber: 43,
    titleEn: 'Textbook Translation: Village Market Shop',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: دُكَّانُ القَرْيَةِ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'فِي سُوقِ الْقَرْيَةِ دُكَّانٌ صَغِيرٌ',
      promptEn: 'In the village market is a small shop',
      promptBn: 'গ্রামের বাজারে একটি ছোট দোকান আছে',
      expectedAnswer: ['In the village market', 'is', 'a small shop'],
      chips: ['In the village market', 'is', 'a small shop', 'a big house', 'a garden'],
      expectedAnswerBn: ['গ্রামের বাজারে', 'একটি', 'ছোট দোকান আছে'],
      chipsBn: ['গ্রামের বাজারে', 'একটি', 'ছোট দোকান আছে', 'বড় বাড়ি', 'বাগান'],
      emoji: '🏪',
    },
  },

  // 10. Page 44: Authentic Reading & Translation Drill 3: Aisha’s Room & Fan
  {
    id: 'step-10-assembly-room-fan',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: 'Textbook Translation: Room & New Fan',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: مِرْوَحَةُ الغُرْفَةِ',
    instructionEn: 'Read the sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'فِي غُرْفَتِهَا مِرْوَحَةٌ جَدِيدَةٌ',
      promptEn: 'In her room is a new fan',
      promptBn: 'তার কামরায় একটি নতুন পাখা আছে',
      expectedAnswer: ['In her room', 'is', 'a new fan'],
      chips: ['In her room', 'is', 'a new fan', 'an old lamp', 'a small bed'],
      expectedAnswerBn: ['তার কামরায়', 'একটি', 'নতুন পাখা আছে'],
      chipsBn: ['তার কামরায়', 'একটি', 'নতুন পাখা আছে', 'পুরনো বাতি', 'ছোট খাট'],
      emoji: '🪭',
    },
  },

  // 11. Vocabulary Discovery: Spiritual & Quranic Nouns
  {
    id: 'step-11-vocab-spiritual',
    type: 'vocab_prime',
    pageNumber: 44,
    titleEn: 'Spiritual & Cultural Vocabulary',
    titleAr: 'مُفْرَدَاتٌ إِيمَانِيَّةٌ وَثَقَافِيَّةٌ',
    instructionEn: 'Listen to and learn spiritual and Quranic nouns',
    instructionBn: 'ঈমানী ও কুরআনীয় শব্দগুলোর বিশুদ্ধ উচ্চারণ শুনুন ও অর্থ আয়ত্ত করুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c8_nur', ar: 'نُورٌ', en: 'Light', bn: 'আলো / জ্যোতি', romanized: 'nūrun', emoji: '✨' },
        { id: 'v1_c8_dhulmah', ar: 'ظُلْمَةٌ', en: 'Darkness', bn: 'অন্ধকার', romanized: 'ẓulmatun', emoji: '🌑' },
        { id: 'v1_c8_qalb', ar: 'قَلْبٌ', en: 'Heart', bn: 'অন্তর / হৃদয়', romanized: 'qalbun', emoji: '🫀' },
        { id: 'v1_c8_qissah', ar: 'قِصَّةٌ', en: 'Story', bn: 'একটি গল্প / কাহিনী', romanized: 'qiṣṣatun', emoji: '📖' },
        { id: 'v1_c8_kafir', ar: 'كَافِرٌ', en: 'Disbeliever', bn: 'কাফের / অবিশ্বাসী', romanized: 'kāfirun', emoji: '👤' },
        { id: 'v1_c8_qabr', ar: 'قَبْرٌ', en: 'Grave / resting place', bn: 'একটি কবর', romanized: 'qabrun', emoji: '🪦' },
        { id: 'v1_c8_madinah_munawwarah', ar: 'الْمَدِينَةُ الْمُنَوَّرَةُ', en: 'Madinah Al-Munawwarah', bn: 'মদীনা মুনাওয়ারা', romanized: 'al-madīnatu al-munawwaratu', emoji: '🕌' },
      ],
    },
  },

  // 12. Speed Pairing: Spiritual & Faith Recall
  {
    id: 'step-12-pair-spiritual',
    type: 'speed_pair',
    pageNumber: 44,
    titleEn: 'Spiritual Vocabulary Drill',
    titleAr: 'مُطَابَقَةُ المُفْرَدَاتِ الإِيمَانِيَّةِ',
    instructionEn: 'Match each Arabic spiritual word with its meaning',
    instructionBn: 'শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pn-nur', ar: 'نُورٌ', meaning: 'Light' },
        { id: 'pn-dhulmah', ar: 'ظُلْمَةٌ', meaning: 'Darkness' },
        { id: 'pn-qalb', ar: 'قَلْبٌ', meaning: 'Heart' },
        { id: 'pn-qissah', ar: 'قِصَّةٌ', meaning: 'Story' },
        { id: 'pn-qabr', ar: 'قَبْرٌ', meaning: 'Grave' },
      ],
    },
  },

  // 13. Sentence Assembly Drill 4: Heart Contrast
  {
    id: 'step-13-assembly-heart-contrast',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: 'Sentence Building: Light & Darkness',
    titleAr: 'تَرْكِيبُ: فِي قَلْبِ المُسْلِمِ نُورٌ وَ فِي قَلْبِ الكَافِرِ ظُلْمَةٌ',
    instructionEn: 'Assemble: "In the heart of the Muslim is light, and in the heart of the disbeliever is darkness"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "মুসলমানের অন্তরে আলো এবং কাফেরের অন্তরে অন্ধকার"',
    assemblyPayload: {
      promptEn: 'In the heart of the Muslim is light, and in the heart of the disbeliever is darkness',
      promptBn: 'মুসলমানের অন্তরে আলো এবং কাফেরের অন্তরে অন্ধকার',
      expectedAnswer: ['فِي', 'قَلْبِ', 'الْمُسْلِمِ', 'نُورٌ', 'وَ', 'فِي', 'قَلْبِ', 'الْكَافِرِ', 'ظُلْمَةٌ'],
      chips: ['فِي', 'قَلْبِ', 'الْمُسْلِمِ', 'نُورٌ', 'وَ', 'فِي', 'قَلْبِ', 'الْكَافِرِ', 'ظُلْمَةٌ', 'الْمُعَلِّمِ'],
      emoji: '✨',
    },
  },

  // 14. Sentence Assembly Drill 5: Book of Allah
  {
    id: 'step-14-assembly-book-of-allah',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: 'Sentence Building: Story in the Book of Allah',
    titleAr: 'تَرْكِيبُ: فِي كِتَابِ اللهِ قِصَّةٌ جَمِيلَةٌ',
    instructionEn: 'Assemble: "In the Book of Allah is a beautiful story"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "আল্লাহর কিতাবে একটি সুন্দর কাহিনী আছে"',
    assemblyPayload: {
      promptEn: 'In the Book of Allah is a beautiful story',
      promptBn: 'আল্লাহর কিতাবে একটি সুন্দর কাহিনী আছে',
      expectedAnswer: ['فِي', 'كِتَابِ', 'اللهِ', 'قِصَّةٌ', 'جَمِيلَةٌ'],
      chips: ['فِي', 'كِتَابِ', 'اللهِ', 'قِصَّةٌ', 'جَمِيلَةٌ', 'كَبِيرَةٌ', 'قَلَمٌ'],
      emoji: '📖',
    },
  },

  // 15. Sentence Assembly Drill 6: Resting Place of the Messenger
  {
    id: 'step-15-assembly-prophet-grave',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: "Sentence Building: Resting Place of the Messenger",
    titleAr: 'تَرْكِيبُ: قَبْرُ الرَّسُولِ فِي المَدِينَةِ المُنَوَّرَةِ',
    instructionEn: 'Assemble: "The grave of the Messenger is in Madinah Al-Munawwarah"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "রাসূলের কবর মদীনা মুনাওয়ারায়"',
    assemblyPayload: {
      promptEn: 'The grave of the Messenger is in Madinah Al-Munawwarah',
      promptBn: 'রাসূলের কবর মদীনা মুনাওয়ারায়',
      expectedAnswer: ['قَبْرُ', 'الرَّسُولِ', 'فِي', 'الْمَدِينَةِ', 'الْمُنَوَّرَةِ'],
      chips: ['قَبْرُ', 'الرَّسُولِ', 'فِي', 'الْمَدِينَةِ', 'الْمُنَوَّرَةِ', 'مَكَّةَ', 'الْبَيْتِ'],
      emoji: '🕌',
    },
  },

  // 16. Dialogic Alternative Q&A Battery 2 (Room, Mahmoud's Car, Heart & Prophet's Grave)
  {
    id: 'step-16-alt-qa-battery-2',
    type: 'alternative_qa',
    pageNumber: 44,
    titleEn: 'Dialogue Battery: Places, Heart & Prophet’s Resting Place',
    titleAr: 'حِوَارُ الأَمَاكِنِ وَالقَلْبِ وَقَبْرِ الرَّسُولِ',
    instructionEn: 'Choose the authentic response corresponding to each dialogue inquiry',
    instructionBn: 'প্রতিটি কথোপকথনের প্রশ্নের সঠিক উত্তরটি নির্বাচন করুন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c8-7',
          questionAr: 'يَا عَائِشَةُ ! مَاذَا فِي غُرْفَتِكِ ؟',
          optionsAr: ['فِي غُرْفَتِي مِرْوَحَةٌ', 'فِي غُرْفَتِكِ مِرْوَحَةٌ'],
          correctAnswerAr: 'فِي غُرْفَتِي مِرْوَحَةٌ',
        },
        {
          id: 'qa-c8-8',
          questionAr: 'أَيْنَ الْمِرْوَحَةُ ؟',
          optionsAr: ['هِيَ فِي غُرْفَتِي', 'هُوَ فِي غُرْفَتِي'],
          correctAnswerAr: 'هِيَ فِي غُرْفَتِي',
        },
        {
          id: 'qa-c8-9',
          questionAr: 'أَيْنَ مَحْمُودٌ ؟',
          optionsAr: ['هُوَ فِي سَيَّارَتِهِ', 'هُوَ فِي سَيَّارَتِهَا'],
          correctAnswerAr: 'هُوَ فِي سَيَّارَتِهِ',
        },
        {
          id: 'qa-c8-10',
          questionAr: 'هَلْ مَحْمُودٌ فِي سَيَّارَتِهِ ؟',
          optionsAr: ['نَعَمْ .. هُوَ فِي سَيَّارَتِهِ', 'نَعَمْ .. هِيَ فِي سَيَّارَتِهَا'],
          correctAnswerAr: 'نَعَمْ .. هُوَ فِي سَيَّارَتِهِ',
        },
        {
          id: 'qa-c8-11',
          questionAr: 'فِي قَلْبِ مَنِ النُّورُ ؟',
          optionsAr: ['النُّورُ فِي قَلْبِ الْمُسْلِمِ', 'النُّورُ فِي قَلْبِ الْكَافِرِ'],
          correctAnswerAr: 'النُّورُ فِي قَلْبِ الْمُسْلِمِ',
        },
        {
          id: 'qa-c8-12',
          questionAr: 'فِي قَلْبِ مَنِ الظُّلْمَةُ ؟',
          optionsAr: ['الظُّلْمَةُ فِي قَلْبِ الْكَافِرِ', 'الظُّلْمَةُ فِي قَلْبِ الْمُسْلِمِ'],
          correctAnswerAr: 'الظُّلْمَةُ فِي قَلْبِ الْكَافِرِ',
        },
        {
          id: 'qa-c8-13',
          questionAr: 'أَيْنَ قَبْرُ الرَّسُولِ ؟',
          optionsAr: ['قَبْرُهُ فِي الْمَدِينَةِ الْمُنَوَّرَةِ', 'قَبْرُهُ فِي مَكَّةَ'],
          correctAnswerAr: 'قَبْرُهُ فِي الْمَدِينَةِ الْمُنَوَّرَةِ',
        },
      ],
    },
  },

  // 17. Syntactic Tarkib Dissector: Fronted Prepositional Predicate vs Standard Order
  {
    id: 'step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 43,
    titleEn: 'Syntactic Tarkib Dissector',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: الخَبَرُ المُقَدَّمُ وَالمُبْتَدَأُ المُؤَخَّرُ',
    instructionEn: 'Dissect the syntactic constituents of the prepositional clause and observe the fronted predicate pattern',
    instructionBn: 'বাক্যের ব্যাকরণগত অংশগুলো (জার-মাজরুর ও মুবতাদা) আলাদা করে বিশ্লেষণ করুন',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-s1',
          sentenceAr: 'فِي الْمَسْجِدِ رَجُلٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (خَبَرٌ مُقَدَّمٌ وَمُبْتَدَأٌ مُؤَخَّرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Fronted Predicate + Delayed Subject)',
          sentenceTypeBn: 'নামবাচক বাক্য (অগ্রবর্তী খবর ও পশ্চাদ্বর্তী মুবতাদা)',
          slots: [
            {
              roleAr: 'حَرْفُ جَرٍّ',
              roleEn: 'Preposition (Harf Jarr)',
              roleBn: 'হরফে জর (অব্যয়)',
              expectedWordAr: 'فِي',
            },
            {
              roleAr: 'اسْمٌ مَجْرُورٌ',
              roleEn: 'Genitive Noun (Ism Majrur)',
              roleBn: 'মাজরুর বিশেষ্য',
              expectedWordAr: 'الْمَسْجِدِ',
            },
            {
              roleAr: 'مُبْتَدَأٌ مُؤَخَّرٌ',
              roleEn: 'Delayed Subject (Mubtada Mu’akhkhar)',
              roleBn: 'বিলম্বিত উদ্দেশ্য (মুবতাদা মুআখখার)',
              expectedWordAr: 'رَجُلٌ',
            },
          ],
          availableWordsAr: ['رَجُلٌ', 'الْمَسْجِدِ', 'فِي'],
        },
        {
          id: 'tarkib-s2',
          sentenceAr: 'الرَّجُلُ فِي الْمَسْجِدِ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (مُبْتَدَأٌ وَخَبَرٌ شِبْهُ جُمْلَةٍ)',
          sentenceTypeEn: 'Nominal Sentence (Subject + Prepositional Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (মুবতাদা ও জার-মাজরুর খবর)',
          slots: [
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Subject (Mubtada)',
              roleBn: 'উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'الرَّجُلُ',
            },
            {
              roleAr: 'حَرْفُ جَرٍّ',
              roleEn: 'Preposition (Harf Jarr)',
              roleBn: 'হরফে জর (অব্যয়)',
              expectedWordAr: 'فِي',
            },
            {
              roleAr: 'اسْمٌ مَجْرُورٌ',
              roleEn: 'Genitive Noun (Ism Majrur)',
              roleBn: 'মাজরুর বিশেষ্য',
              expectedWordAr: 'الْمَسْجِدِ',
            },
          ],
          availableWordsAr: ['الْمَسْجِدِ', 'الرَّجُلُ', 'فِي'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah Al-Baqarah 2:255)
  {
    id: 'step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 44,
    titleEn: 'Quranic Milestone',
    titleAr: 'الأَثَرُ القُرْآنِيُّ',
    instructionEn: 'Listen and observe the preposition فِي in Ayat al-Kursi (2:255)',
    instructionBn: 'আয়াতুল কুরসীতে ব্যবহৃত «فِي» হরফে জরের প্রয়োগ লক্ষ্য করুন ও শুদ্ধভাবে শুনুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 255,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      translationEn: 'To Him belongs whatever is in the heavens and whatever is in the earth.',
      translationBn: 'আসমানসমূহে এবং যমীনে যা কিছু আছে সবই তাঁর।',
      highlightedWords: ['فِي', 'السَّمَاوَاتِ', 'الْأَرْضِ'],
      patternNameEn: 'Preposition of Place with Genitive Noun (فِي + مَجْرُور)',
      patternNameBn: 'অব্যয় ও মাজরুর পদ (জার ও মাজরুর)',
      lessonPatternAr: 'فِي الْمَسْجِدِ / فِي الْمَدِينَةِ',
      lessonPatternEn: 'In the mosque / In the city',
      lessonPatternBn: 'মসজিদে / শহরে',
      quranPatternAr: 'فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      quranPatternEn: 'In the heavens and in the earth',
      quranPatternBn: 'আসমানসমূহে এবং যমীনে',
      reflection: "Notice the preposition 'فِي' (in) appearing twice in Ayat al-Kursi, governing both 'السَّمَاوَاتِ' (the heavens) and 'الْأَرْضِ' (the earth) into the genitive state.",
      audioKey: 'quran_002255',
    },
  },
];

export const LESSON_08_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 1,
  lessonNum: 8,
  titleEn: 'Preposition فِي and Genitive Case',
  titleAr: 'حَرْفُ الجَرِّ «فِي» وَحَالَةُ الجَرِّ',
  wordsLearned: [
    'فِي',
    'دُكَّانٌ',
    'شَجَرَةٌ',
    'صُنْدُوقٌ',
    'عِقْدٌ',
    'مِصْبَاحٌ',
    'مِرْوَحَةٌ',
    'مِسْطَرَةٌ',
    'نُورٌ',
    'ظُلْمَةٌ',
    'قَلْبٌ',
    'قِصَّةٌ',
    'كَافِرٌ',
    'قَبْرٌ',
    'الْمَدِينَةُ الْمُنَوَّرَةُ',
  ],
  steps: LESSON_08_STEPS,
};
