import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_11_STEPS: SessionStep[] = [
  // 1. Page 59-60: Concept Discovery - Particles of Emphasis (إِنَّ) and Hope (لَعَلَّ)
  {
    id: 'v2-c1-l11-step-1-concept-inna',
    type: 'concept_intro',
    pageNumber: 59,
    titleEn: 'Emphatic & Expectant Particles: إِنَّ & لَعَلَّ',
    titleAr: 'مَدْخَلُ حُرُوفِ التَّوْكِيدِ وَالتَّرَجِّي: إِنَّ وَلَعَلَّ',
    instructionEn: 'Observe how "إِنَّ" puts its noun into the accusative (fathah), preserves the nominative predicate, shifts fronted structures, and fuses with pronouns.',
    instructionBn: 'লক্ষ্য করুন কীভাবে "إِنَّ" তার পরবর্তী বিশেষ্যকে যবর দেয়, বিধেয়কে পেশযুক্ত রাখে, অগ্রবর্তী পদকে প্রভাবিত করে এবং সর্বনামের সাথে যুক্ত হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-inna-nominal-shift',
          ar: 'رَاشِدٌ تِلْمِيذٌ ➔ إِنَّ رَاشِدًا تِلْمِيذٌ',
          romanized: 'rāshidun tilmīdhun ➔ inna rāshidan tilmīdhun',
          meaningEn: 'Accusative Subject: "إِنَّ" causes the subject to take fathah/fathatayn',
          meaningBn: 'মুবতাদায় যবর: "إِنَّ" এর কারণে মুবতাদা যবর গ্রহণ করে (ইসমে ইন্না)',
          exampleAr: 'إِنَّ اللهَ رَبُّنَا وَرَبُّكُمْ',
          exampleEn: 'Indeed, Allah is our Lord and your Lord.',
          exampleBn: 'নিশ্চয়ই আল্লাহ আমাদের প্রতিপালক এবং তোমাদের প্রতিপালক।',
          audioKey: 'إِنَّ رَاشِدًا تِلْمِيذٌ',
          exampleAudioKey: 'إِنَّ اللهَ رَبُّنَا وَرَبُّكُمْ',
          emoji: '✨',
        },
        {
          id: 'c-inna-five-nouns',
          ar: 'أَخُونَا يَصْدُقُ ➔ إِنَّ أَخَانَا يَصْدُقُ',
          romanized: 'akhūnā yaṣduqu ➔ inna akhānā yaṣduqu',
          meaningEn: 'Five Nouns with Inna: "أَخُو" shifts from Waw (nominative) to Alif (accusative)',
          meaningBn: 'আসমায়ে খামসাহ: "إِنَّ" এর প্রভাবে ওয়াও পরিবর্তন হয়ে আলিফ হয় (আখানা)',
          exampleAr: 'إِنَّ أَخَانَا يَصْدُقُ دَائِمًا وَلَا يَكْذِبُ أَبَدًا',
          exampleEn: 'Indeed, our brother always speaks the truth and never lies.',
          exampleBn: 'নিশ্চয়ই আমাদের ভাই সর্বদা সত্য বলে এবং কখনও মিথ্যা বলে না।',
          audioKey: 'إِنَّ أَخَانَا يَصْدُقُ',
          exampleAudioKey: 'إِنَّ أَخَانَا يَصْدُقُ دَائِمًا وَلَا يَكْذِبُ أَبَدًا',
          emoji: '🛡️',
        },
        {
          id: 'c-inna-fronted-shibh-jumla',
          ar: 'فِي الغُرْفَةِ رَجُلٌ ➔ إِنَّ فِي الغُرْفَةِ رَجُلًا',
          romanized: 'fī al-ghurfati rajulun ➔ inna fī al-ghurfati rajulan',
          meaningEn: 'Delayed Subject: The postponed subject still takes accusative fathatayn',
          meaningBn: 'বিলম্বিত ইসমে ইন্না: জার-মাজরুর পূর্বে এলেও বিলম্বিত বিশেষ্যে দুই যবর হয়',
          exampleAr: 'إِنَّ فِي قَلْبِ المُسْلِمِ نُورًا',
          exampleEn: 'Indeed, in the heart of the Muslim is light.',
          exampleBn: 'নিশ্চয়ই মুসলমানের অন্তরে আলো রয়েছে।',
          audioKey: 'إِنَّ فِي الغُرْفَةِ رَجُلًا',
          exampleAudioKey: 'إِنَّ فِي قَلْبِ المُسْلِمِ نُورًا',
          emoji: '💡',
        },
        {
          id: 'c-inna-attached-pronoun',
          ar: 'أَنْتَ صَادِقٌ ➔ إِنَّكَ صَادِقٌ / أَنَا ➔ إِنِّي',
          romanized: 'anta ṣādiqun ➔ innaka ṣādiqun',
          meaningEn: 'Pronoun Fusion: Personal pronouns attach directly to "إِنَّ"',
          meaningBn: 'সর্বনাম সংযুক্তি: পৃথক সর্বনামগুলো "إِنَّ" এর সাথে যুক্ত সর্বনামে পরিণত হয়',
          exampleAr: 'إِنَّكَ صَادِقٌ، وَإِنِّي رَجُلٌ فَقِيرٌ',
          exampleEn: 'Indeed, you are truthful; and indeed, I am a poor man.',
          exampleBn: 'নিশ্চয়ই তুমি সত্যবাদী; এবং নিশ্চয়ই আমি একজন দরিদ্র লোক।',
          audioKey: 'إِنَّكَ صَادِقٌ',
          exampleAudioKey: 'إِنَّكَ صَادِقٌ، وَإِنِّي رَجُلٌ فَقِيرٌ',
          emoji: '🔗',
        },
      ],
    },
  },

  // 2. Page 59-60: Pronoun Explorer - إِنَّ with Attached Pronouns
  {
    id: 'v2-c1-l10-step-2-conjugator-inna-pronouns',
    type: 'verb_conjugator',
    pageNumber: 60,
    titleEn: 'Pronoun Fusion Paradigm: إِنَّ Across Persons',
    titleAr: 'تَصْرِيفُ إِنَّ مَعَ الضَّمَائِرِ المُتَّصِلَةِ',
    instructionEn: 'Explore how independent pronouns fuse into attached accusative pronouns with "إِنَّ".',
    instructionBn: 'লক্ষ্য করুন কীভাবে পৃথক সর্বনামগুলো "إِنَّ" এর সাথে যুক্ত হয়ে অবিকৃত অর্থ প্রকাশ করে।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'present',
      verbs: [
        {
          id: 'verb_inna_pronouns',
          rootAr: 'إ ن ن',
          masdarAr: 'التَّوْكِيدُ بِإِنَّ',
          meaningEn: 'Indeed / Surely with pronouns',
          meaningBn: 'ইন্না সহ সর্বনামের রূপ',
          baabAr: 'الحُرُوفُ المُشَبَّهَةُ بِالفِعْلِ',
          baabEn: 'Inna and its Sisters',
          emoji: '⚡',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'إِنَّهُ صَادِقٌ',
              presentAr: 'إِنَّهُ صَادِقٌ',
              imperativeAr: 'إِنَّهُ',
              pastMeaningEn: 'Indeed, he is truthful',
              pastMeaningBn: 'নিশ্চয়ই সে সত্যবাদী',
              presentMeaningEn: 'Indeed, he is truthful',
              presentMeaningBn: 'নিশ্চয়ই সে সত্যবাদী',
              audioKey: 'إِنَّهُ صَادِقٌ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'إِنَّهَا ذَكِيَّةٌ',
              presentAr: 'إِنَّهَا ذَكِيَّةٌ',
              imperativeAr: 'إِنَّهَا',
              pastMeaningEn: 'Indeed, she is smart',
              pastMeaningBn: 'নিশ্চয়ই সে বুদ্ধিমতী',
              presentMeaningEn: 'Indeed, she is smart',
              presentMeaningBn: 'নিশ্চয়ই সে বুদ্ধিমতী',
              audioKey: 'إِنَّهَا ذَكِيَّةٌ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'إِنَّكَ صَادِقٌ',
              presentAr: 'إِنَّكَ صَادِقٌ',
              imperativeAr: 'إِنَّكَ',
              pastMeaningEn: 'Indeed, you are truthful',
              pastMeaningBn: 'নিশ্চয়ই তুমি সত্যবাদী',
              presentMeaningEn: 'Indeed, you are truthful',
              presentMeaningBn: 'নিশ্চয়ই তুমি সত্যবাদী',
              audioKey: 'إِنَّكَ صَادِقٌ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'إِنَّكِ ذَكِيَّةٌ',
              presentAr: 'إِنَّكِ ذَكِيَّةٌ',
              imperativeAr: 'إِنَّكِ',
              pastMeaningEn: 'Indeed, you are smart',
              pastMeaningBn: 'নিশ্চয়ই তুমি বুদ্ধিমতী',
              presentMeaningEn: 'Indeed, you are smart',
              presentMeaningBn: 'নিশ্চয়ই তুমি বুদ্ধিমতী',
              audioKey: 'إِنَّكِ ذَكِيَّةٌ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'إِنِّي رَجُلٌ فَقِيرٌ',
              presentAr: 'إِنِّي رَجُلٌ فَقِيرٌ',
              imperativeAr: 'إِنِّي',
              pastMeaningEn: 'Indeed, I am a poor man',
              pastMeaningBn: 'নিশ্চয়ই আমি একজন দরিদ্র লোক',
              presentMeaningEn: 'Indeed, I am a poor man',
              presentMeaningBn: 'নিশ্চয়ই আমি একজন দরিদ্র লোক',
              audioKey: 'إِنِّي رَجُلٌ فَقِيرٌ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 60: Word Construction - Attached Pronouns with إِنَّ
  {
    id: 'v2-c1-l11-step-3-word-construction-inna',
    type: 'word_construction',
    pageNumber: 60,
    titleEn: 'Word Construction: Attaching Pronouns to إِنَّ',
    titleAr: 'تَرْكِيبُ الكَلِمَةِ: اتِّصَالُ الضَّمَائِرِ بِإِنَّ',
    instructionEn: 'Construct the unified emphatic pronoun forms by assembling the particle and pronoun morphemes.',
    instructionBn: 'অব্যয় ও সর্বনামের অংশগুলো যুক্ত করে সংক্ষিপ্ত অবিচ্ছেদ্য রূপ গঠন করুন।',
    itemId: 'v2_l11_word_construction_inna',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-innaka',
          sourceWordAr: 'أَنْتَ',
          sourceWordLabelEn: '2nd Person Masc Singular',
          sourceWordLabelBn: '২য় পুরুষ পুংলিঙ্গ একবচন',
          targetWordAr: 'إِنَّكَ',
          promptEn: 'Construct Emphatic: "Indeed, you (m)"',
          promptBn: 'দৃঢ়তাবোধক রূপ গঠন করুন: "নিশ্চয়ই তুমি (পুং)"',
          targetMeaningEn: 'Indeed, you (m)',
          targetMeaningBn: 'নিশ্চয়ই তুমি (পুং)',
          chips: ['إِ', 'نَّ', 'كَ', 'كِ', 'هُ'],
          emoji: '👉',
        },
        {
          id: 'wc-innaha',
          sourceWordAr: 'هِيَ',
          sourceWordLabelEn: '3rd Person Fem Singular',
          sourceWordLabelBn: '৩য় পুরুষ স্ত্রীলিঙ্গ একবচন',
          targetWordAr: 'إِنَّهَا',
          promptEn: 'Construct Emphatic: "Indeed, she"',
          promptBn: 'দৃঢ়তাবোধক রূপ গঠন করুন: "নিশ্চয়ই সে (স্ত্রী)"',
          targetMeaningEn: 'Indeed, she',
          targetMeaningBn: 'নিশ্চয়ই সে (স্ত্রী)',
          chips: ['إِ', 'نَّ', 'هَا', 'هُ', 'كِ'],
          emoji: '👩',
        },
        {
          id: 'wc-innana',
          sourceWordAr: 'نَحْنُ',
          sourceWordLabelEn: '1st Person Plural',
          sourceWordLabelBn: '১ম পুরুষ বহুবচন',
          targetWordAr: 'إِنَّنَا',
          promptEn: 'Construct Emphatic: "Indeed, we"',
          promptBn: 'দৃঢ়তাবোধক রূপ গঠন করুন: "নিশ্চয়ই আমরা"',
          targetMeaningEn: 'Indeed, we',
          targetMeaningBn: 'নিশ্চয়ই আমরা',
          chips: ['إِ', 'نَّ', 'نَا', 'كُمْ', 'تُمْ'],
          emoji: '👥',
        },
        {
          id: 'wc-innaki',
          sourceWordAr: 'أَنْتِ',
          sourceWordLabelEn: '2nd Person Fem Singular',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ একবচন',
          targetWordAr: 'إِنَّكِ',
          promptEn: 'Construct Emphatic: "Indeed, you (f)"',
          promptBn: 'দৃঢ়তাবোধক রূপ গঠন করুন: "নিশ্চয়ই তুমি (স্ত্রী)"',
          targetMeaningEn: 'Indeed, you (f)',
          targetMeaningBn: 'নিশ্চয়ই তুমি (স্ত্রী)',
          chips: ['إِ', 'نَّ', 'كِ', 'كَ', 'هَا'],
          emoji: '👧',
        },
        {
          id: 'wc-inni',
          sourceWordAr: 'أَنَا',
          sourceWordLabelEn: '1st Person Singular',
          sourceWordLabelBn: '১ম পুরুষ একবচন',
          targetWordAr: 'إِنِّي',
          promptEn: 'Construct Emphatic: "Indeed, I"',
          promptBn: 'দৃঢ়তাবোধক রূপ গঠন করুন: "নিশ্চয়ই আমি"',
          targetMeaningEn: 'Indeed, I',
          targetMeaningBn: 'নিশ্চয়ই আমি',
          chips: ['إِ', 'نِّ', 'ي', 'نَا', 'كَ'],
          emoji: '🙋',
        },
      ],
    },
  },

  // 4. Page 59-60: Vocabulary Prime
  {
    id: 'v2-c1-l11-step-4-vocab-prime',
    type: 'vocab_prime',
    pageNumber: 60,
    titleEn: 'Vocabulary: Divine Attributes, Virtues & Spiritual Terms',
    titleAr: 'مُفْرَدَاتُ الصِّفَاتِ وَالأَخْلَاقِ وَالمَعَانِي الإِيمَانِيَّةِ',
    instructionEn: 'Listen to the essential vocabulary for divine attributes, virtues, and life reflections introduced in Lesson 11.',
    instructionBn: '১১তম পাঠে উল্লেখিত আল্লাহ্‌র গুণবাচক নাম, নৈতিক গুণাবলী এবং আধ্যাত্মিক শব্দভাণ্ডার শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_malak', ar: 'مَلَكٌ', en: 'Angel', bn: 'ফিরিশতা', romanized: 'malakun', emoji: '🪽' },
        { id: 'v2_hasad', ar: 'حَسَدٌ', en: 'Envy / Jealousy', bn: 'হিংসা', romanized: 'ḥasadun', emoji: '🔥' },
        { id: 'v2_ajr', ar: 'أَجْرٌ', en: 'Reward / Recompense', bn: 'প্রতিদান / সওয়াব', romanized: 'ajrun', emoji: '🎁' },
        { id: 'v2_azim', ar: 'عَظِيمٌ', en: 'Immense / Mighty / Great', bn: 'বিরাট / মহান', romanized: '‘aẓīmun', emoji: '🏔️' },
        { id: 'v2_ghafur', ar: 'غَفُورٌ', en: 'All-Forgiving', bn: 'পরম ক্ষমাশীল', romanized: 'ghafūrun', emoji: '🤍' },
        { id: 'v2_khatar', ar: 'خَطَرٌ', en: 'Danger / Peril', bn: 'বিপদ / ঝুঁকি', romanized: 'khaṭarun', emoji: '⚠️' },
        { id: 'v2_miftah', ar: 'مِفْتَاحٌ', en: 'Key', bn: 'চাবি', romanized: 'miftāḥun', emoji: '🔑' },
        { id: 'v2_wudu', ar: 'وُضُوءٌ', en: 'Ablution', bn: 'ওযু', romanized: 'wuḍū’un', emoji: '💧' },
        { id: 'v2_khiyatah', ar: 'خِيَاطَةٌ', en: 'Sewing / Tailoring', bn: 'সেলাই কাজ', romanized: 'khiyāṭatun', emoji: '🪡' },
        { id: 'v2_laalla', ar: 'لَعَلَّ', en: 'Perhaps / Hopefully / Maybe', bn: 'হয়তো / মনে হয়', romanized: 'la‘alla', emoji: '🌱' },
      ],
    },
  },

  // 5. Page 59-60: Speed Pair Matching
  {
    id: 'v2-c1-l11-step-5-speed-pair',
    type: 'speed_pair',
    pageNumber: 60,
    titleEn: 'Rapid Pairing: Emphatic Clauses & Fronted Predicates',
    titleAr: 'المُطَابَقَةُ السَّرِيعَةُ: جُمَلُ إِنَّ وَالمَجْرُورَاتُ',
    instructionEn: 'Match each Arabic clause containing "إِنَّ" to its accurate English translation.',
    instructionBn: '"إِنَّ" যুক্ত প্রতিটি আরবি বাক্যাংশকে তার সঠিক ইংরেজি অনুবাদের সাথে মেলান।',
    pairPayload: {
      pairs: [
        { id: 'p1', ar: 'إِنَّ مَعَكَ مَلَكًا', meaning: 'Indeed, with you is an angel', meaningBn: 'নিশ্চয়ই তোমার সাথে একজন ফিরিশতা রয়েছে' },
        { id: 'p2', ar: 'إِنَّ فِي قَلْبِ المُسْلِمِ نُورًا', meaning: 'Indeed, in the Muslim’s heart is light', meaningBn: 'নিশ্চয়ই মুসলমানের অন্তরে আলো রয়েছে' },
        { id: 'p3', ar: 'إِنَّ بَعْدَ المَوْتِ حَيَاةً جَدِيدَةً', meaning: 'Indeed, after death is a new life', meaningBn: 'নিশ্চয়ই মৃত্যুর পর এক নতুন জীবন রয়েছে' },
        { id: 'p4', ar: 'إِنَّ الصَّلَاةَ مِفْتَاحُ الجَنَّةِ', meaning: 'Indeed, prayer is the key to Paradise', meaningBn: 'নিশ্চয়ই নামাজ জান্নাতের চাবি' },
        { id: 'p5', ar: 'لَعَلَّ فِي قَلْبِهِ حَسَدًا', meaning: 'Perhaps in his heart is envy', meaningBn: 'হয়তো তার অন্তরে হিংসা রয়েছে' },
      ],
    },
  },

  // 6. Page 59: Sentence Assembly - Creedal Declaration
  {
    id: 'v2-c1-l11-step-6-assembly-creed',
    type: 'sentence_assembly',
    pageNumber: 59,
    titleEn: 'Sentence Assembly: The Universal Lordship',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: رَبُّنَا وَرَبُّكُمْ',
    instructionEn: 'Assemble: "Indeed, Allah is our Lord and your Lord."',
    instructionBn: 'বাক্যটি সাজান: "নিশ্চয়ই আল্লাহ আমাদের প্রতিপালক এবং তোমাদের প্রতিপালক।"',
    assemblyPayload: {
      promptEn: 'Indeed, Allah is our Lord and your Lord.',
      promptBn: 'নিশ্চয়ই আল্লাহ আমাদের প্রতিপালক এবং তোমাদের প্রতিপালক।',
      expectedAnswer: ['إِنَّ', 'اللهَ', 'رَبُّنَا', 'وَرَبُّكُمْ'],
      chips: ['إِنَّ', 'اللهَ', 'رَبُّنَا', 'وَرَبُّكُمْ', 'اللهُ', 'رَبِّنَا'],
      expectedAnswerBn: ['নিশ্চয়ই', 'আল্লাহ', 'আমাদের প্রতিপালক', 'এবং তোমাদের প্রতিপালক'],
      chipsBn: ['নিশ্চয়ই', 'আল্লাহ', 'আমাদের প্রতিপালক', 'এবং তোমাদের প্রতিপালক', 'সৃষ্টিকর্তা'],
      emoji: '🕋',
    },
  },

  // 7. Page 59: Polar Sort - Accusative Ism Inna vs Nominative Error
  {
    id: 'v2-c1-l11-step-7-polar-inna-acc',
    type: 'polar_sort',
    pageNumber: 59,
    titleEn: 'Grammar Polarity: Accusative Ism Inna',
    titleAr: 'التَّمْيِيزُ القُطْبِيُّ: صِحَّةُ نَصْبِ اسْمِ إِنَّ',
    instructionEn: 'Select the grammatically correct sentence where the subject takes fathah after "إِنَّ".',
    instructionBn: '"إِنَّ" এর পর ইসমে ইন্নায় যথাযথ যবরযুক্ত সঠিক বাক্যটি নির্বাচন করুন।',
    polarPayload: {
      arabicSubject: 'إِنَّ رَاشِدًا',
      meaningEn: 'Accusative Subject after Inna',
      meaningBn: 'ইন্নার পর যবরযুক্ত বিশেষ্য',
      correctAnswer: 'إِنَّ رَاشِدًا تِلْمِيذٌ',
      options: ['إِنَّ رَاشِدًا تِلْمِيذٌ', 'إِنَّ رَاشِدٌ تِلْمِيذٌ'],
      emoji: '⚖️',
    },
  },

  // 8. Page 59: Alternative Q&A - Aisha's Skill
  {
    id: 'v2-c1-l11-step-8-qa-khiyatah',
    type: 'alternative_qa',
    pageNumber: 59,
    titleEn: "Comprehension: Aisha's Practical Knowledge",
    titleAr: 'سُؤَالٌ وَجَوَابٌ: مَعْرِفَةُ عَائِشَةَ بِالخِيَاطَةِ',
    instructionEn: 'Answer based on page 59: Does Aisha know sewing or cooking?',
    instructionBn: '৫৯ পৃষ্ঠার পাঠ অনুযায়ী উত্তর দিন: আয়েশা কি সেলাইয়ের কাজ জানে নাকি রান্নার কাজ?',
    alternativeQAPayload: {
      contextAr: 'إِنَّ عَائِشَةَ تَعْرِفُ الخِيَاطَةَ، وَهِيَ تِلْمِيذَةٌ ذَكِيَّةٌ.',
      questions: [
        {
          id: 'q-aisha-khiyatah',
          questionAr: 'أَ تَعْرِفُ عَائِشَةُ الخِيَاطَةَ أَمِ الطِّبَاخَةَ؟',
          optionsAr: [
            'إِنَّ عَائِشَةَ تَعْرِفُ الخِيَاطَةَ',
            'إِنَّ عَائِشَةَ تَعْرِفُ الطِّبَاخَةَ',
          ],
          correctAnswerAr: 'إِنَّ عَائِشَةَ تَعْرِفُ الخِيَاطَةَ',
        },
      ],
    },
  },

  // 9. Page 59: Sentence Assembly - Five Nouns Shift (أَخَانَا)
  {
    id: 'v2-c1-l11-step-9-assembly-brother-truth',
    type: 'sentence_assembly',
    pageNumber: 59,
    titleEn: 'Sentence Assembly: The Truthful Brother',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: صِدْقُ الأَخِ',
    instructionEn: 'Assemble: "Indeed, our brother always speaks the truth."',
    instructionBn: 'বাক্যটি সাজান: "নিশ্চয়ই আমাদের ভাই সর্বদা সত্য বলে।"',
    assemblyPayload: {
      promptEn: 'Indeed, our brother always speaks the truth.',
      promptBn: 'নিশ্চয়ই আমাদের ভাই সর্বদা সত্য বলে।',
      expectedAnswer: ['إِنَّ', 'أَخَانَا', 'يَصْدُقُ', 'دَائِمًا'],
      chips: ['إِنَّ', 'أَخَانَا', 'يَصْدُقُ', 'دَائِمًا', 'أَخُونَا', 'يَكْذِبُ'],
      expectedAnswerBn: ['নিশ্চয়ই', 'আমাদের ভাই', 'সর্বদা', 'সত্য বলে'],
      chipsBn: ['নিশ্চয়ই', 'আমাদের ভাই', 'সর্বদা', 'সত্য বলে', 'মিথ্যা বলে'],
      emoji: '⭐',
    },
  },

  // 10. Page 60: Cloze Choice - Delayed Accusative Subject
  {
    id: 'v2-c1-l11-step-10-cloze-delayed-subject',
    type: 'cloze_choice',
    pageNumber: 60,
    titleEn: 'Contextual Gap: Delayed Subject with Fathatayn',
    titleAr: 'مِلْءُ الفَرَاغِ: اسْمُ إِنَّ المُؤَخَّرُ',
    instructionEn: 'Choose the correct form of the delayed subject: "Indeed, in the room is a man."',
    instructionBn: 'বিলম্বিত ইসমে ইন্নার সঠিক রূপটি নির্বাচন করুন: "নিশ্চয়ই কামরায় একজন লোক রয়েছে।"',
    clozePayload: {
      questionAr: 'إِنَّ فِي الغُرْفَةِ ...',
      questionEn: 'Indeed, in the room is a [man].',
      questionBn: 'নিশ্চয়ই কামরার ভেতর একজন [লোক] রয়েছে।',
      partialAnswerAr: 'إِنَّ فِي الغُرْفَةِ ...',
      correctAnswer: 'رَجُلًا',
      options: ['رَجُلًا', 'رَجُلٌ', 'رَجُلٍ'],
      emoji: '🚪',
    },
  },

  // 11. Page 59: Alternative Q&A - Brother Truthfulness
  {
    id: 'v2-c1-l11-step-11-qa-brother-truth',
    type: 'alternative_qa',
    pageNumber: 59,
    titleEn: 'Comprehension: Does Our Brother Lie?',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: هَلْ يَكْذِبُ أَخُونَا؟',
    instructionEn: 'Answer: Does our brother ever tell a lie?',
    instructionBn: 'উত্তর দিন: আমাদের ভাই কি কখনও মিথ্যা বলে?',
    alternativeQAPayload: {
      contextAr: 'إِنَّ أَخَانَا يَصْدُقُ دَائِمًا وَلَا يَكْذِبُ أَبَدًا.',
      questions: [
        {
          id: 'q-brother-lie',
          questionAr: 'هَلْ يَكْذِبُ أَخُونَا أَبَدًا؟',
          optionsAr: [
            'لَا .. لَا يَكْذِبُ أَبَدًا بَلْ يَصْدُقُ دَائِمًا',
            'نَعَمْ .. يَكْذِبُ أَحْيَانًا',
          ],
          correctAnswerAr: 'لَا .. لَا يَكْذِبُ أَبَدًا بَلْ يَصْدُقُ دَائِمًا',
        },
      ],
    },
  },

  // 12. Page 60: Sentence Assembly - Light in the Believer's Heart
  {
    id: 'v2-c1-l11-step-12-assembly-light-heart',
    type: 'sentence_assembly',
    pageNumber: 60,
    titleEn: 'Sentence Assembly: Light in the Believer’s Heart',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: نُورٌ فِي قَلْبِ المُسْلِمِ',
    instructionEn: 'Assemble: "Indeed, in the heart of the Muslim is light."',
    instructionBn: 'বাক্যটি সাজান: "নিশ্চয়ই মুসলমানের অন্তরে আলো রয়েছে।"',
    assemblyPayload: {
      promptEn: 'Indeed, in the heart of the Muslim is light.',
      promptBn: 'নিশ্চয়ই মুসলমানের অন্তরে আলো রয়েছে।',
      expectedAnswer: ['إِنَّ', 'فِي', 'قَلْبِ', 'المُسْلِمِ', 'نُورًا'],
      chips: ['إِنَّ', 'فِي', 'قَلْبِ', 'المُسْلِمِ', 'نُورًا', 'نُورٌ', 'ظَلَامٌ'],
      expectedAnswerBn: ['নিশ্চয়ই', 'মুসলমানের', 'অন্তরে', 'আলো', 'রয়েছে'],
      chipsBn: ['নিশ্চয়ই', 'মুসলমানের', 'অন্তরে', 'আলো', 'রয়েছে', 'অন্ধকার'],
      emoji: '💖',
    },
  },

  // 13. Page 60: Cloze Choice - Attached Pronoun Selection
  {
    id: 'v2-c1-l11-step-13-cloze-attached-pronoun',
    type: 'cloze_choice',
    pageNumber: 60,
    titleEn: 'Contextual Gap: Emphatic Address to Rashid',
    titleAr: 'مِلْءُ الفَرَاغِ: خِطَابُ التَّوْكِيدِ لِرَاشِدٍ',
    instructionEn: 'Select the correct attached form addressing Rashid: "O Rashid! Indeed, you are an intelligent student."',
    instructionBn: 'রাশেদকে সম্বোধন করে সঠিক রূপটি নির্বাচন করুন: "হে রাশেদ! নিশ্চয়ই তুমি একজন মেধাবী ছাত্র।"',
    clozePayload: {
      questionAr: 'يَا رَاشِدُ! ... تِلْمِيذٌ ذَكِيٌّ',
      questionEn: 'O Rashid! [Indeed, you] are an intelligent student.',
      questionBn: 'হে রাশেদ! [নিশ্চয়ই তুমি] একজন মেধাবী ছাত্র।',
      partialAnswerAr: 'يَا رَاشِدُ! ... تِلْمِيذٌ ذَكِيٌّ',
      correctAnswer: 'إِنَّكَ',
      options: ['إِنَّكَ', 'إِنَّكِ', 'إِنَّهُ'],
      emoji: '🎓',
    },
  },

  // 14. Page 60: Sentence Assembly - Prayer is the Key to Paradise
  {
    id: 'v2-c1-l11-step-14-assembly-prayer-paradise',
    type: 'sentence_assembly',
    pageNumber: 60,
    titleEn: 'Sentence Assembly: Prayer is the Key to Paradise',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الصَّلَاةُ مِفْتَاحُ الجَنَّةِ',
    instructionEn: 'Assemble: "Indeed, prayer is the key to Paradise."',
    instructionBn: 'বাক্যটি সাজান: "নিশ্চয়ই নামাজ জান্নাতের চাবি।"',
    assemblyPayload: {
      promptEn: 'Indeed, prayer is the key to Paradise.',
      promptBn: 'নিশ্চয়ই নামাজ জান্নাতের চাবি।',
      expectedAnswer: ['إِنَّ', 'الصَّلَاةَ', 'مِفْتَاحُ', 'الجَنَّةِ'],
      chips: ['إِنَّ', 'الصَّلَاةَ', 'مِفْتَاحُ', 'الجَنَّةِ', 'الصَّلَاةُ', 'مِفْتَاحَ'],
      expectedAnswerBn: ['নিশ্চয়ই', 'নামাজ', 'জান্নাতের', 'চাবি'],
      chipsBn: ['নিশ্চয়ই', 'নামাজ', 'জান্নাতের', 'চাবি', 'রোজা'],
      emoji: '🗝️',
    },
  },

  // 15. Page 59: Tarkib Dissector - Standard Inna Sentence
  {
    id: 'v2-c1-l11-step-15-tarkib-standard-inna',
    type: 'tarkib_dissector',
    pageNumber: 59,
    titleEn: 'Syntactic Dissector: Standard Inna Clause Analysis',
    titleAr: 'تَرْكِيبُ جُمْلَةِ إِنَّ البَسِيطَةِ',
    instructionEn: 'Slot each syntactic component: Emphatic particle, accusative subject (Ism Inna), and nominative predicate (Khabar Inna).',
    instructionBn: 'প্রতিটি পদ বিন্যস্ত করুন: তাকিদসূচক অব্যয়, যবরযুক্ত ইসমে ইন্না এবং পেশযুক্ত খবরের ইন্না।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-standard-inna',
          sentenceAr: 'إِنَّ القُرْآنَ كِتَابُ اللهِ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ مُؤَكَّدَةٌ بِإِنَّ',
          sentenceTypeEn: 'Emphatic Nominal Sentence with Inna',
          sentenceTypeBn: 'ইন্না যোগে তাকিদযুক্ত নামবাচক বাক্য',
          slots: [
            {
              roleAr: 'حَرْفُ تَوْكِيدٍ وَنَصْبٍ',
              roleEn: 'Emphatic Particle (Inna)',
              roleBn: 'তাকিদসূচক অব্যয়',
              expectedWordAr: 'إِنَّ',
            },
            {
              roleAr: 'اسْمُ إِنَّ (مَنْصُوبٌ بِالفَتْحَةِ)',
              roleEn: 'Subject of Inna (Accusative)',
              roleBn: 'ইসমে ইন্না (যবরযুক্ত)',
              expectedWordAr: 'القُرْآنَ',
            },
            {
              roleAr: 'خَبَرُ إِنَّ (مَرْفُوعٌ بِالضَّمَّةِ)',
              roleEn: 'Predicate of Inna (Nominative)',
              roleBn: 'খবরে ইন্না (পেশযুক্ত)',
              expectedWordAr: 'كِتَابُ',
            },
          ],
          availableWordsAr: ['إِنَّ', 'القُرْآنَ', 'كِتَابُ'],
        },
      ],
    },
  },

  // 16. Page 60: Tarkib Dissector - Fronted Shibh Jumla with Inna
  {
    id: 'v2-c1-l11-step-16-tarkib-fronted-inna',
    type: 'tarkib_dissector',
    pageNumber: 60,
    titleEn: 'Syntactic Dissector: Fronted Prepositional Predicate',
    titleAr: 'تَرْكِيبُ إِنَّ مَعَ الخَبَرِ المُقَدَّمِ',
    instructionEn: 'Analyze: "إِنَّ مَعَكَ مَلَكًا" (Particle + Fronted Adverbial Predicate + Delayed Accusative Subject).',
    instructionBn: '"إِنَّ مَعَكَ مَلَكًا" বাক্যটি বিশ্লেষণ করুন: অব্যয় + অগ্রবর্তী বিধেয় + বিলম্বিত ইসমে ইন্না।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-fronted-inna',
          sentenceAr: 'إِنَّ مَعَكَ مَلَكًا',
          sentenceTypeAr: 'جُمْلَةُ إِنَّ ذَاتُ الخَبَرِ المُقَدَّمِ',
          sentenceTypeEn: 'Inna Sentence with Fronted Predicate',
          sentenceTypeBn: 'অগ্রবর্তী খবর বিশিষ্ট ইন্নার বাক্য',
          slots: [
            {
              roleAr: 'حَرْفُ تَوْكِيدٍ وَنَصْبٍ',
              roleEn: 'Emphatic Particle',
              roleBn: 'তাকিদসূচক অব্যয়',
              expectedWordAr: 'إِنَّ',
            },
            {
              roleAr: 'شِبْهُ جُمْلَةٍ ظَرْفِيَّةٍ (خَبَرٌ مُقَدَّمٌ)',
              roleEn: 'Fronted Adverbial Predicate',
              roleBn: 'অগ্রবর্তী শিভহে জুমলাহ খবর',
              expectedWordAr: 'مَعَكَ',
            },
            {
              roleAr: 'اسْمُ إِنَّ مُؤَخَّرٌ (مَنْصُوبٌ بِالفَتْحَةِ)',
              roleEn: 'Delayed Subject of Inna (Accusative)',
              roleBn: 'বিলম্বিত ইসমে ইন্না (যবরযুক্ত)',
              expectedWordAr: 'مَلَكًا',
            },
          ],
          availableWordsAr: ['إِنَّ', 'مَعَكَ', 'مَلَكًا'],
        },
      ],
    },
  },

  // 17. Quranic Milestone: Surah Al-Inshirah (94:6)
  {
    id: 'v2-c1-l11-step-17-quranic-echo-inshirah',
    type: 'quranic_echo',
    pageNumber: 60,
    titleEn: 'Quranic Milestone: The Assurance of Ease with Hardship',
    titleAr: 'صَدَى القُرْآنِ: إِنَّ مَعَ العُسْرِ يُسْرًا',
    instructionEn: 'Reflect on how the exact fronted prepositional structure "إِنَّ مَعَ العُسْرِ يُسْرًا" provides eternal solace in Surah Al-Inshirah (94:6).',
    instructionBn: 'সূরা আল-ইনশিরাহ (৯৪:৬) এ হুবহু একই গঠন "إِنَّ مَعَ العُسْرِ يُسْرًا" কীভাবে চিরন্তন সান্ত্বনা প্রদান করে তা অনুধাবন করুন।',
    echoPayload: {
      surahNumber: 94,
      ayahNumber: 6,
      surahNameAr: 'الشَّرْح',
      surahNameEn: 'Ash-Sharh',
      arabicText: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      translationEn: 'Indeed, with hardship [will be] ease.',
      translationBn: 'নিশ্চয়ই কষ্টের সাথেই রয়েছে স্বস্তি।',
      highlightedWords: ['إِنَّ', 'مَعَ الْعُسْرِ', 'يُسْرًا'],
      reflection: 'In this beloved verse, observe the exact fronted structure of Lesson 10/11: the emphatic particle "إِنَّ" is followed by the fronted prepositional phrase "مَعَ الْعُسْرِ" (with hardship), while the subject "يُسْرًا" (ease) is postponed and takes the characteristic accusative fathatayn. The Quran grammatically embeds ease alongside the trial itself.',
    },
  },
];

export const VOL2_CH1_LESSON_11_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 11,
  titleEn: 'The Emphatic & Expectant Particles: إِنَّ & لَعَلَّ',
  titleAr: 'حَرْفَا التَّوْكِيدِ وَالتَّرَجِّي: إِنَّ وَلَعَلَّ',
  wordsLearned: [
    'إِنَّ', 'لَعَلَّ', 'مَلَكٌ', 'حَسَدٌ', 'أَجْرٌ', 'عَظِيمٌ',
    'غَفُورٌ', 'خَطَرٌ', 'مِفْتَاحٌ', 'وُضُوءٌ', 'خِيَاطَةٌ'
  ],
  steps: VOL2_CH1_LESSON_11_STEPS,
};
