import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_09_STEPS: SessionStep[] = [
  // 1. Page 51-54: Concept Discovery - Lam of Purpose (لَامُ التَّعْلِيلِ) & Munada Mudaf (المُنَادَى المُضَاف)
  {
    id: 'v2-c1-l9-step-1-concept-lam',
    type: 'concept_intro',
    pageNumber: 51,
    titleEn: 'The Lam of Purpose (لَامُ التَّعْلِيلِ) & Vocative Idafah',
    titleAr: 'مَدْخَلُ لَامِ التَّعْلِيلِ وَالمُنَادَى المُضَافِ',
    instructionEn: 'Observe how the "لـِ" of purpose gives nasb (fathah) to present verbs, drops the nun in feminine "لِتَفْعَلِي", and how vocative mudaf takes fathah.',
    instructionBn: 'লক্ষ্য করুন কীভাবে কারণবাচক "لـِ" বর্তমান ক্রিয়ায় যবর দেয়, স্ত্রীলিঙ্গে নূন বিলুপ্ত করে "لِتَفْعَلِي" এবং মুনাদা মুদাফে যবর হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-lam-masdar-vs-mudari',
          ar: 'لِلْقِرَاءِةِ (جَارٌّ وَمَجْرُورٌ) = لِيَقْرَأَ (فِعْلٌ مَنْصُوبٌ)',
          romanized: 'lil-qirā’ati = li-yaqra’a',
          meaningEn: 'Purpose: With Masdar (Genitive) vs With Verb (Accusative Subjunctive)',
          meaningBn: 'উদ্দেশ্য: মাসদার যোগে (জের) বনাম ক্রিয়া যোগে (যবর)',
          exampleAr: 'جَلَسَ شَاهِدٌ لِلْقِرَاءَةِ = جَلَسَ شَاهِدٌ لِيَقْرَأَ',
          exampleEn: 'Shahid sat for reading = Shahid sat in order to read.',
          exampleBn: 'শাহিদ পড়ার জন্য বসল।',
          audioKey: 'لِلْقِرَاءِةِ = لِيَقْرَأَ',
          exampleAudioKey: 'جَلَسَ شَاهِدٌ لِيَقْرَأَ',
          emoji: '📖',
        },
        {
          id: 'c-lam-noon-drop',
          ar: 'أَنْتِ: لِتَقْرَئِي (بِحَذْفِ النُّونِ)',
          romanized: 'anti: li-taqra’ī',
          meaningEn: 'Feminine Drop of Nun: In order that you (f) read!',
          meaningBn: 'স্ত্রীলিঙ্গে নূন বিলুপ্তি: যাতে তুমি (স্ত্রী) পড়তে পারো!',
          exampleAr: 'يَا فَاطِمَةُ! اجْلِسِي لِتَقْرَئِي دَرْسَ اليَوْمِ',
          exampleEn: 'O Fatima! Sit down in order to read today\'s lesson.',
          exampleBn: 'হে ফাতেমা! আজকের পাঠ পড়ার জন্য বসো।',
          audioKey: 'لِتَقْرَئِي',
          exampleAudioKey: 'اجْلِسِي لِتَقْرَئِي دَرْسَ اليَوْمِ',
          emoji: '✂️',
        },
        {
          id: 'c-lam-purpose-sentences',
          ar: 'خَرَجَ رَاشِدٌ لِيَذْهَبَ إِلَى المَدْرَسَةِ',
          romanized: 'kharaja rāshidun li-yadh-haba ilā al-madrasati',
          meaningEn: 'Expressing Intention: He went out in order to go to school',
          meaningBn: 'উদ্দেশ্য প্রকাশ: সে মাদ্রাসায় যাওয়ার জন্য বের হলো',
          exampleAr: 'خَلَقَ اللهُ الإِنْسَانَ لِيَعْبُدَهُ وَيُطِيعَهُ',
          exampleEn: 'Allah created mankind in order to worship Him and obey Him.',
          exampleBn: 'আল্লাহ মানুষকে সৃষ্টি করেছেন তাঁর ইবাদত ও আনুগত্য করার জন্য।',
          audioKey: 'خَرَجَ رَاشِدٌ لِيَذْهَبَ',
          exampleAudioKey: 'خَلَقَ اللهُ الإِنْسَانَ لِيَعْبُدَهُ وَيُطِيعَهُ',
          emoji: '🎯',
        },
        {
          id: 'c-munada-mudaf-drill',
          ar: 'يَا صَدِيقَ رَاشِدٍ (مَنْصُوبٌ بِالفَتْحَةِ)',
          romanized: 'yā sadīqa rāshidin',
          meaningEn: 'Vocative with Idafah: Takes Fathah on the First Noun',
          meaningBn: 'মুদাফ বিশিষ্ট সম্বোধন: প্রথম শব্দে যবর গ্রহণ করে',
          exampleAr: 'يَا إِمَامَ المَسْجِدِ! يَا فَلَّاحَ القَرْيَةِ!',
          exampleEn: 'O imam of the mosque! O farmer of the village!',
          exampleBn: 'হে মসজিদের ইমাম! হে গ্রামের কৃষক!',
          audioKey: 'يَا صَدِيقَ رَاشِدٍ',
          exampleAudioKey: 'يَا إِمَامَ المَسْجِدِ',
          emoji: '📢',
        },
      ],
    },
  },

  // 2. Page 51: Verb Conjugator - Lam of Purpose across Pronouns
  {
    id: 'v2-c1-l9-step-2-conjugator-lam',
    type: 'verb_conjugator',
    pageNumber: 51,
    titleEn: 'Verb Paradigm: لِيَقْرَأَ (Conjugating with Lam of Purpose)',
    titleAr: 'تَصْرِيفُ فِعْلِ: لِيَقْرَأَ (لَامُ التَّعْلِيلِ مَعَ المُضَارِعِ)',
    instructionEn: 'Switch between pronouns to observe the accusative fathah and the deletion of the nun in "لِتَقْرَئِي".',
    instructionBn: 'সর্বনাম পরিবর্তন করে লক্ষ্য করুন শেষ অক্ষরে যবর এবং "لِتَقْرَئِي" তে নূন বিলুপ্তি।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'present',
      verbs: [
        {
          id: 'verb_li-yaqra-a',
          rootAr: 'ق ر أ',
          masdarAr: 'قِرَاءَةٌ',
          meaningEn: 'To read (with Lam of Purpose)',
          meaningBn: 'পড়ার জন্য (উদ্দেশ্যবাচক লাম সহ)',
          baabAr: 'لَامُ التَّعْلِيلِ مَعَ المُضَارِعِ',
          baabEn: 'Subjunctive Mudari with Lam of Purpose',
          emoji: '📖',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'قَرَأَ',
              presentAr: 'لِيَقْرَأَ',
              imperativeAr: 'لِيَقْرَأْ',
              pastMeaningEn: 'He read',
              pastMeaningBn: 'সে পড়েছিল',
              presentMeaningEn: 'In order that he read',
              presentMeaningBn: 'তার পড়ার জন্য',
              audioKey: 'لِيَقْرَأَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'قَرَأَتْ',
              presentAr: 'لِتَقْرَأَ',
              imperativeAr: 'لِتَقْرَأْ',
              pastMeaningEn: 'She read',
              pastMeaningBn: 'সে পড়েছিল',
              presentMeaningEn: 'In order that she read',
              presentMeaningBn: 'তার পড়ার জন্য (স্ত্রী)',
              audioKey: 'لِتَقْرَأَ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'قَرَأْتَ',
              presentAr: 'لِتَقْرَأَ',
              imperativeAr: 'اِقْرَأْ',
              pastMeaningEn: 'You read',
              pastMeaningBn: 'তুমি পড়েছিলে',
              presentMeaningEn: 'In order that you read',
              presentMeaningBn: 'তোমার পড়ার জন্য',
              audioKey: 'لِتَقْرَأَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'قَرَأْتِ',
              presentAr: 'لِتَقْرَئِي',
              imperativeAr: 'اِقْرَئِي',
              pastMeaningEn: 'You read (f)',
              pastMeaningBn: 'তুমি পড়েছিলে (স্ত্রী)',
              presentMeaningEn: 'In order that you read (f)',
              presentMeaningBn: 'তোমার পড়ার জন্য (স্ত্রী)',
              audioKey: 'لِتَقْرَئِي',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'قَرَأْتُ',
              presentAr: 'لِأَقْرَأَ',
              imperativeAr: 'لِأَقْرَأْ',
              pastMeaningEn: 'I read',
              pastMeaningBn: 'আমি পড়েছিলাম',
              presentMeaningEn: 'In order that I read',
              presentMeaningBn: 'আমার পড়ার জন্য',
              audioKey: 'لِأَقْرَأَ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 52: Word Construction - Deriving Verb from Verbal Noun (المَصْدَر)
  {
    id: 'v2-c1-l9-step-3-word-construction-masdar',
    type: 'word_construction',
    pageNumber: 52,
    titleEn: 'Word Construction: Deriving Verbs from the Verbal Noun',
    titleAr: 'اشْتِقَاقُ الفِعْلِ مِنَ المَصْدَرِ: بِنَاءُ الكَلِمَةِ',
    instructionEn: 'Derive the verb with Lam of Purpose (لـِ) from the verbal noun and assemble the letters in order.',
    instructionBn: 'মূল মাছদার থেকে কারণবাচক লাম (لـِ) সহ ক্রিয়াটি গঠন করুন এবং বর্ণগুলো ক্রমানুসারে সাজান।',
    itemId: 'v2_l9_word_construction_masdar',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-kataba',
          sourceWordAr: 'الكِتَابَةُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'لِيَكْتُبَ',
          promptEn: 'Derive: "In order that he write" (with Lam of Purpose)',
          promptBn: 'গঠন করুন: "যেন সে লেখে" (কারণবাচক লাম সহ)',
          targetMeaningEn: 'In order that he write',
          targetMeaningBn: 'যেন সে লেখে',
          chips: ['لِ', 'يَ', 'كْ', 'تُ', 'بَ', 'تَ', 'بُ', 'سَ'],
          emoji: '✍️',
        },
        {
          id: 'wc-shariba',
          sourceWordAr: 'الشُّرْبُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'لِيَشْرَبَ',
          promptEn: 'Derive: "In order that he drink" (with Lam of Purpose)',
          promptBn: 'গঠন করুন: "যেন সে পান করে" (কারণবাচক লাম সহ)',
          targetMeaningEn: 'In order that he drink',
          targetMeaningBn: 'যেন সে পান করে',
          chips: ['لِ', 'يَ', 'شْ', 'رَ', 'بَ', 'تَ', 'بُ', 'رُ'],
          emoji: '🥛',
        },
        {
          id: 'wc-fahima',
          sourceWordAr: 'الفَهْمُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'لِيَفْهَمَ',
          promptEn: 'Derive: "In order that he understand" (with Lam of Purpose)',
          promptBn: 'গঠন করুন: "যেন সে বোঝে" (কারণবাচক লাম সহ)',
          targetMeaningEn: 'In order that he understand',
          targetMeaningBn: 'যেন সে বোঝে',
          chips: ['لِ', 'يَ', 'فْ', 'هَ', 'مَ', 'نَ', 'مُ', 'عَ'],
          emoji: '💡',
        },
        {
          id: 'wc-qara-a-fem',
          sourceWordAr: 'القِرَاءَةُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'لِتَقْرَئِي',
          promptEn: 'Derive: "In order that you (f) read" (Feminine Nun-drop)',
          promptBn: 'গঠন করুন: "যেন তুমি (স্ত্রী) পড়ো" (স্ত্রীলিঙ্গে নূন বিলুপ্ত)',
          targetMeaningEn: 'In order that you (f) read',
          targetMeaningBn: 'যেন তুমি (স্ত্রী) পড়ো',
          chips: ['لِ', 'تَ', 'قْ', 'رَ', 'ئِ', 'ي', 'نَ', 'تُ'],
          emoji: '📖',
        },
      ],
    },
  },

  // 4. Page 51-54: Vocabulary Prime
  {
    id: 'v2-c1-l9-step-4-vocab-purpose',
    type: 'vocab_prime',
    pageNumber: 52,
    titleEn: 'Vocabulary: Purpose & Household Terms',
    titleAr: 'مُفْرَدَاتُ التَّعْلِيلِ وَالمَنْزِلِ',
    instructionEn: 'Listen to the essential vocabulary for expressing purpose, actions, meals, and family roles.',
    instructionBn: 'উদ্দেশ্য, দৈনন্দিন কাজ, খাবার এবং পারিবারিক সম্বোধনের প্রয়োজনীয় শব্দভাণ্ডার শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_lam_talil', ar: 'لَامُ التَّعْلِيلِ', en: 'Lam of Purpose (In order to)', bn: 'কারণবাচক লাম (যাতে/জন্য)', romanized: 'lāmu at-ta‘līli', emoji: '🎯' },
        { id: 'v2_usrah', ar: 'الأُسْرَةُ', en: 'The Family', bn: 'পরিবার', romanized: 'al-’usratu', emoji: '👨‍👩‍👧‍👦' },
        { id: 'v2_ghada', ar: 'الغَدَاءُ', en: 'Lunch', bn: 'দুপুরের খাবার', romanized: 'al-ghadā’u', emoji: '🍲' },
        { id: 'v2_ashaa', ar: 'العَشَاءُ', en: 'Dinner', bn: 'রাতের খাবার', romanized: 'al-‘ashā’u', emoji: '🍽️' },
        { id: 'v2_matbakh', ar: 'المَطْبَخُ', en: 'The Kitchen', bn: 'রান্নাঘর', romanized: 'al-matbakhu', emoji: '🍳' },
        { id: 'v2_hammam', ar: 'الحَمَّامُ', en: 'The Bathroom', bn: 'গোসলখানা', romanized: 'al-hammāmu', emoji: '🚿' },
        { id: 'v2_tabakha', ar: 'طَبَخَ يَطْبُخُ', en: 'To Cook', bn: 'রান্না করা', romanized: 'tabakha yatbukhu', emoji: '👩‍🍳' },
        { id: 'v2_akhadha', ar: 'أَخَذَ يَأْخُذُ', en: 'To Take / Seize', bn: 'নেওয়া / ধরা', romanized: 'akhadha ya’khudhu', emoji: '🤲' },
        { id: 'v2_darasa', ar: 'دَرَسَ يَدْرُسُ', en: 'To Study / Learn', bn: 'অধ্যয়ন করা', romanized: 'darasa yadrusu', emoji: '📚' },
        { id: 'v2_mudhnib', ar: 'مُذْنِبٌ', en: 'Sinner', bn: 'পাপী', romanized: 'mudhnibun', emoji: '⚠️' },
        { id: 'v2_dhanb', ar: 'ذَنْبٌ', en: 'Sin', bn: 'পাপ', romanized: 'dhanbun', emoji: '🛑' },
        { id: 'v2_shaykh_kabir', ar: 'شَيْخٌ كَبِيرٌ', en: 'Very Old Man / Elder', bn: 'অতিবৃদ্ধ ব্যক্তি', romanized: 'shaykhun kabīrun', emoji: '👴' },
      ],
    },
  },

  // 4. Page 52-53: Speed Pair Matching
  {
    id: 'v2-c1-l9-step-4-speed-pair-purpose',
    type: 'speed_pair',
    pageNumber: 52,
    titleEn: 'Rapid Pairing: Purpose Clauses',
    titleAr: 'المُطَابَقَةُ السَّرِيعَةُ: جُمَلُ التَّعْلِيلِ',
    instructionEn: 'Match each Arabic purpose clause to its exact English meaning.',
    instructionBn: 'প্রতিটি আরবি উদ্দেশ্যমূলক বাক্যাংশকে তার সঠিক ইংরেজি অর্থের সাথে মেলান।',
    pairPayload: {
      pairs: [
        { id: 'p1', ar: 'لِيَذْهَبَ إِلَى المَدْرَسَةِ', meaning: 'In order to go to school', meaningBn: 'মাদ্রাসায় যাওয়ার জন্য' },
        { id: 'p2', ar: 'لِتَلْعَبَ فِي الحَدِيقَةِ', meaning: 'In order to play in the garden', meaningBn: 'বাগানে খেলার জন্য' },
        { id: 'p3', ar: 'لِأَدْخُلَ الجَنَّةَ', meaning: 'In order that I enter Paradise', meaningBn: 'যেন আমি জান্নাতে প্রবেশ করি' },
        { id: 'p4', ar: 'لِتَطْبُخَ طَعَامَ الغَدَاءِ', meaning: 'In order to cook the lunch meal', meaningBn: 'দুপুরের খাবার রান্না করার জন্য' },
        { id: 'p5', ar: 'لِيَعْبُدَهُ وَيُطِيعَهُ', meaning: 'To worship Him and obey Him', meaningBn: 'তাঁর ইবাদত ও আনুগত্য করার জন্য' },
      ],
    },
  },

  // 5. Page 52: Sentence Assembly - Rashid going to school
  {
    id: 'v2-c1-l9-step-5-assembly-rashid',
    type: 'sentence_assembly',
    pageNumber: 52,
    titleEn: 'Sentence Assembly: Going out for School',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: خُرُوجُ رَاشِدٍ',
    instructionEn: 'Assemble: "Rashid went out of the house in order to go to the school."',
    instructionBn: 'বাক্যটি সাজান: "রাশিদ মাদ্রাসায় যাওয়ার উদ্দেশ্যে ঘর থেকে বের হলো।"',
    assemblyPayload: {
      promptEn: 'Rashid went out of the house in order to go to the school.',
      promptBn: 'রাশিদ মাদ্রাসায় যাওয়ার উদ্দেশ্যে ঘর থেকে বের হলো।',
      expectedAnswer: ['خَرَجَ', 'رَاشِدٌ', 'مِنَ', 'البَيْتِ', 'لِيَذْهَبَ', 'إِلَى', 'المَدْرَسَةِ'],
      chips: ['خَرَجَ', 'رَاشِدٌ', 'مِنَ', 'البَيْتِ', 'لِيَذْهَبَ', 'إِلَى', 'المَدْرَسَةِ', 'لِيَذْهَبُ', 'دَخَلَ'],
      expectedAnswerBn: ['রাশিদ', 'মাদ্রাসায়', 'যাওয়ার', 'উদ্দেশ্যে', 'ঘর', 'থেকে', 'বের হলো'],
      chipsBn: ['রাশিদ', 'মাদ্রাসায়', 'যাওয়ার', 'উদ্দেশ্যে', 'ঘর', 'থেকে', 'বের হলো', 'প্রবেশ করল'],
      emoji: '🎒',
    },
  },

  // 6. Page 52: Sentence Assembly - Creation for Worship
  {
    id: 'v2-c1-l9-step-6-assembly-worship',
    type: 'sentence_assembly',
    pageNumber: 52,
    titleEn: 'Sentence Assembly: The Purpose of Creation',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: غَايَةُ الخَلْقِ',
    instructionEn: 'Assemble: "Allah created mankind in order to worship Him and obey Him."',
    instructionBn: 'বাক্যটি সাজান: "আল্লাহ মানুষকে সৃষ্টি করেছেন তাঁর ইবাদত করতে ও তাঁর আনুগত্য করতে।"',
    assemblyPayload: {
      promptEn: 'Allah created mankind in order to worship Him and obey Him.',
      promptBn: 'আল্লাহ মানুষকে সৃষ্টি করেছেন তাঁর ইবাদত করতে ও তাঁর আনুগত্য করতে।',
      expectedAnswer: ['خَلَقَ', 'اللهُ', 'الإِنْسَانَ', 'لِيَعْبُدَهُ', 'وَيُطِيعَهُ'],
      chips: ['خَلَقَ', 'اللهُ', 'الإِنْسَانَ', 'لِيَعْبُدَهُ', 'وَيُطِيعَهُ', 'لِيَعْبُدُهُ', 'الإِنْسَانُ'],
      expectedAnswerBn: ['আল্লাহ', 'মানুষকে', 'সৃষ্টি করেছেন', 'তাঁর ইবাদত করতে', 'ও তাঁর আনুগত্য করতে'],
      chipsBn: ['আল্লাহ', 'মানুষকে', 'সৃষ্টি করেছেন', 'তাঁর ইবাদত করতে', 'ও তাঁর আনুগত্য করতে', 'মানুষ'],
      emoji: '🤲',
    },
  },

  // 7. Page 53: Sentence Assembly - Mother cooking lunch
  {
    id: 'v2-c1-l9-step-7-assembly-cooking',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Sentence Assembly: Cooking Lunch for the Family',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: طَبْخُ الغَدَاءِ',
    instructionEn: 'Assemble: "Majid\'s mother enters the kitchen now in order to cook lunch for the family."',
    instructionBn: 'বাক্যটি সাজান: "মাজেদের মা এখন রান্নাঘরে প্রবেশ করছেন পরিবারের জন্য দুপুরের খাবার রান্না করতে।"',
    assemblyPayload: {
      promptEn: 'Majid\'s mother enters the kitchen now in order to cook lunch for the family.',
      promptBn: 'মাজেদের মা এখন রান্নাঘরে প্রবেশ করছেন পরিবারের জন্য দুপুরের খাবার রান্না করতে।',
      expectedAnswer: ['تَدْخُلُ', 'أُمُّ', 'مَاجِدٍ', 'المَطْبَخَ', 'الآنَ', 'لِتَطْبُخَ', 'لِلْأُسْرَةِ', 'طَعَامَ', 'الغَدَاءِ'],
      chips: ['تَدْخُلُ', 'أُمُّ', 'مَاجِدٍ', 'المَطْبَخَ', 'الآنَ', 'لِتَطْبُخَ', 'لِلْأُسْرَةِ', 'طَعَامَ', 'الغَدَاءِ', 'تَطْبُخُ', 'العَشَاءِ'],
      expectedAnswerBn: ['মাজেদের মা', 'এখন', 'রান্নাঘরে প্রবেশ করছেন', 'পরিবারের জন্য', 'রান্না করতে', 'দুপুরের খাবার'],
      chipsBn: ['মাজেদের মা', 'এখন', 'রান্নাঘরে প্রবেশ করছেন', 'পরিবারের জন্য', 'রান্না করতে', 'দুপুরের খাবার', 'রাতের খাবার'],
      emoji: '👩‍🍳',
    },
  },

  // 8. Page 52: Cloze Choice - Feminine Nun Drop in Purpose
  {
    id: 'v2-c1-l9-step-8-cloze-drinking',
    type: 'cloze_choice',
    pageNumber: 52,
    titleEn: 'Cloze: Feminine Nun-Drop with Lam of Purpose',
    titleAr: 'اخْتِيَارُ المَلْءِ: حَذْفُ النُّونِ لِلْمُؤَنَّثِ مَعَ لَامِ التَّعْلِيلِ',
    instructionEn: 'Select the correct form with the nun dropped after the Lam of purpose: "لِتَشْرَبِي".',
    instructionBn: 'কারণবাচক লামের পরে নূন বিলুপ্ত হওয়া সঠিক রূপটি নির্বাচন করুন: "لِتَشْرَبِي"।',
    clozePayload: {
      questionAr: 'يَا زَيْنَبُ! خُذِي هَذَا الكَوْبَ ... مَاءً بَارِدًا',
      questionEn: 'O Zaynab! Take this cup in order to [drink] cold water.',
      questionBn: 'হে যয়নব! ঠাণ্ডা পানি [পান করার জন্য] এই গ্লাসটি নাও।',
      partialAnswerAr: 'يَا زَيْنَبُ! خُذِي هَذَا الكَوْبَ ... مَاءً بَارِدًا',
      correctAnswer: 'لِتَشْرَبِي',
      options: ['لِتَشْرَبِي', 'لِتَشْرَبِينَ', 'تَشْرَبِي'],
      emoji: '🥛',
    },
  },

  // 9. Page 53: Alternative QA - Rashid's Purpose
  {
    id: 'v2-c1-l9-step-9-qa-rashid',
    type: 'alternative_qa',
    pageNumber: 53,
    titleEn: 'Dialogue QA: Why did Rashid go out?',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: لِمَاذَا خَرَجَ رَاشِدٌ؟',
    instructionEn: 'Answer questions about Rashid\'s purpose using the Lam of purpose and proper negative correction.',
    instructionBn: 'কারণবাচক লাম এবং সঠিক না-বোধক সংশোধনের মাধ্যমে রাশিদের উদ্দেশ্য বিষয়ক প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'لِمَاذَا خَرَجَ رَاشِدٌ مِنَ البَيْتِ ؟ خَرَجَ لِيَذْهَبَ إِلَى المَدْرَسَةِ. أَلِيَذْهَبَ إِلَى السُّوقِ خَرَجَ مِنَ البَيْتِ ؟ لَا .. مَا خَرَجَ لِيَذْهَبَ إِلَى السُّوقِ بَلْ لِيَذْهَبَ إِلَى المَدْرَسَةِ.',
      questions: [
        {
          id: 'q-rashid-1',
          questionAr: 'لِمَاذَا خَرَجَ رَاشِدٌ مِنَ البَيْتِ ؟',
          optionsAr: [
            'خَرَجَ لِيَذْهَبَ إِلَى المَدْرَسَةِ',
            'خَرَجَ لِيَلْعَبَ فِي الحَدِيقَةِ',
          ],
          correctAnswerAr: 'خَرَجَ لِيَذْهَبَ إِلَى المَدْرَسَةِ',
        },
        {
          id: 'q-rashid-2',
          questionAr: 'أَلِيَذْهَبَ إِلَى السُّوقِ خَرَجَ مِنَ البَيْتِ ؟',
          optionsAr: [
            'لَا .. مَا خَرَجَ لِيَذْهَبَ إِلَى السُّوقِ بَلْ لِيَذْهَبَ إِلَى المَدْرَسَةِ',
            'نَعَمْ .. خَرَجَ لِيَذْهَبَ إِلَى السُّوقِ',
          ],
          correctAnswerAr: 'لَا .. مَا خَرَجَ لِيَذْهَبَ إِلَى السُّوقِ بَلْ لِيَذْهَبَ إِلَى المَدْرَسَةِ',
        },
      ],
    },
  },

  // 10. Page 52: Sentence Assembly - Pupil answering teacher
  {
    id: 'v2-c1-l9-step-10-assembly-pupil',
    type: 'sentence_assembly',
    pageNumber: 52,
    titleEn: 'Sentence Assembly: The Intelligent Pupil',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: التِّلْمِيذُ الذَّكِيُّ',
    instructionEn: 'Assemble: "The intelligent pupil stood up in order to answer the teacher\'s question."',
    instructionBn: 'বাক্যটি সাজান: "মেধাবী ছাত্রটি শিক্ষকের প্রশ্নের উত্তর দেওয়ার জন্য দাঁড়াল।"',
    assemblyPayload: {
      promptEn: 'The intelligent pupil stood up in order to answer the teacher\'s question.',
      promptBn: 'মেধাবী ছাত্রটি শিক্ষকের প্রশ্নের উত্তর দেওয়ার জন্য দাঁড়াল।',
      expectedAnswer: ['قَامَ', 'التِّلْمِيذُ', 'الذَّكِيُّ', 'لِيُجِيبَ', 'عَلَى', 'سُؤَالِ', 'المُعَلِّمِ'],
      chips: ['قَامَ', 'التِّلْمِيذُ', 'الذَّكِيُّ', 'لِيُجِيبَ', 'عَلَى', 'سُؤَالِ', 'المُعَلِّمِ', 'لِيُجِيبُ', 'جَلَسَ'],
      expectedAnswerBn: ['মেধাবী ছাত্রটি', 'দাঁড়াল', 'শিক্ষকের প্রশ্নের', 'উত্তর দেওয়ার জন্য'],
      chipsBn: ['মেধাবী ছাত্রটি', 'দাঁড়াল', 'শিক্ষকের প্রশ্নের', 'উত্তর দেওয়ার জন্য', 'বসল'],
      emoji: '🙋‍♂️',
    },
  },

  // 11. Page 53: Sentence Assembly - Helping the Elder
  {
    id: 'v2-c1-l9-step-11-assembly-elder',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Sentence Assembly: Helping the Elderly Father',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: مُسَاعَدَةُ الشَّيْخِ الكَبِيرِ',
    instructionEn: 'Assemble: "O uncle of Rashid! Your father is a very old man, so take his hand to help him down from the car."',
    instructionBn: 'বাক্যটি সাজান: "হে রাশিদের চাচা! আপনার পিতা একজন অতিবৃদ্ধ ব্যক্তি, কাজেই তাঁর হাত ধরুন তাঁকে গাড়ি থেকে নামানোর জন্য।"',
    assemblyPayload: {
      promptEn: 'O uncle of Rashid! Your father is a very old man, so take his hand to help him down from the car.',
      promptBn: 'হে রাশিদের চাচা! আপনার পিতা একজন অতিবৃদ্ধ ব্যক্তি, কাজেই তাঁর হাত ধরুন তাঁকে গাড়ি থেকে নামানোর জন্য।',
      expectedAnswer: ['يَا', 'عَمَّ', 'رَاشِدٍ!', 'أَبُوكَ', 'شَيْخٌ', 'كَبِيرٌ،', 'فَخُذْ', 'يَدَهُ', 'لِتُنْزِلَهُ', 'مِنَ', 'السَّيَّارَةِ'],
      chips: ['يَا', 'عَمَّ', 'رَاشِدٍ!', 'أَبُوكَ', 'شَيْخٌ', 'كَبِيرٌ،', 'فَخُذْ', 'يَدَهُ', 'لِتُنْزِلَهُ', 'مِنَ', 'السَّيَّارَةِ', 'عَمُّ', 'لِتُنْزِلُهُ'],
      expectedAnswerBn: ['হে রাশিদের চাচা!', 'আপনার পিতা', 'একজন অতিবৃদ্ধ ব্যক্তি,', 'কাজেই তাঁর হাত ধরুন', 'তাঁকে গাড়ি থেকে নামানোর জন্য'],
      chipsBn: ['হে রাশিদের চাচা!', 'আপনার পিতা', 'একজন অতিবৃদ্ধ ব্যক্তি,', 'কাজেই তাঁর হাত ধরুন', 'তাঁকে গাড়ি থেকে নামানোর জন্য', 'চাচা'],
      emoji: '🚗',
    },
  },

  // 12. Page 54: Alternative QA - Arabic Language & Munada Mudaf
  {
    id: 'v2-c1-l9-step-12-qa-study-arabic',
    type: 'alternative_qa',
    pageNumber: 54,
    titleEn: 'QA: Studying Arabic & Vocative Analysis',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: دِرَاسَةُ العَرَبِيَّةِ وَإِعْرَابُ المُنَادَى',
    instructionEn: 'Answer questions on why Majid\'s daughter studies Arabic and the grammatical case of the vocative mudaf.',
    instructionBn: 'মাজেদের মেয়ে কেন আরবি পড়ে এবং মুনাদা মুদাফের ব্যাকরণগত অবস্থা সম্পর্কিত প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'لِمَ تَدْرُسُ بِنْتُ مَاجِدٍ اللُّغَةَ العَرَبِيَّةَ ؟ تَدْرُسُهَا لِتَفْهَمَ كِتَابَ اللهِ. يَا عَمَّ رَاشِدٍ: (عَمَّ) مُنَادَى مُضَافٌ مَنْصُوبٌ بِالفَتْحَةِ.',
      questions: [
        {
          id: 'q-study-1',
          questionAr: 'لِمَ تَدْرُسُ بِنْتُ مَاجِدٍ اللُّغَةَ العَرَبِيَّةَ ؟',
          optionsAr: [
            'تَدْرُسُهَا لِتَفْهَمَ كِتَابَ اللهِ',
            'تَدْرُسُهَا لِتَلْعَبَ فِي الحَدِيقَةِ',
          ],
          correctAnswerAr: 'تَدْرُسُهَا لِتَفْهَمَ كِتَابَ اللهِ',
        },
        {
          id: 'q-study-2',
          questionAr: 'مَا إِعْرَابُ كَلِمَةِ (عَمَّ) فِي قَوْلِنَا: (يَا عَمَّ رَاشِدٍ) ؟',
          optionsAr: [
            'مُنَادَى مُضَافٌ مَنْصُوبٌ بِالفَتْحَةِ',
            'مُنَادَى مَرْفُوعٌ بِالضَّمَّةِ',
          ],
          correctAnswerAr: 'مُنَادَى مُضَافٌ مَنْصُوبٌ بِالفَتْحَةِ',
        },
      ],
    },
  },

  // 13. Page 53: Sentence Assembly - Studying Arabic to Understand Quran
  {
    id: 'v2-c1-l9-step-13-assembly-understand-quran',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Sentence Assembly: Studying Arabic to Understand the Quran',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: فَهْمُ كِتَابِ اللهِ',
    instructionEn: 'Assemble: "Majid\'s daughter studies the Arabic language in order to understand the Book of Allah."',
    instructionBn: 'বাক্যটি সাজান: "মাজেদের মেয়ে আল্লাহর কিতাব বোঝার জন্য আরবি ভাষা অধ্যয়ন করছে।"',
    assemblyPayload: {
      promptEn: 'Majid\'s daughter studies the Arabic language in order to understand the Book of Allah.',
      promptBn: 'মাজেদের মেয়ে আল্লাহর কিতাব বোঝার জন্য আরবি ভাষা অধ্যয়ন করছে।',
      expectedAnswer: ['تَدْرُسُ', 'بِنْتُ', 'مَاجِدٍ', 'اللُّغَةَ', 'العَرَبِيَّةَ', 'لِتَفْهَمَ', 'كِتَابَ', 'اللهِ'],
      chips: ['تَدْرُسُ', 'بِنْتُ', 'مَاجِدٍ', 'اللُّغَةَ', 'العَرَبِيَّةَ', 'لِتَفْهَمَ', 'كِتَابَ', 'اللهِ', 'بِنْتَ', 'لِتَفْهَمُ'],
      expectedAnswerBn: ['মাজেদের মেয়ে', 'আল্লাহর কিতাব বোঝার জন্য', 'আরবি ভাষা', 'অধ্যয়ন করছে'],
      chipsBn: ['মাজেদের মেয়ে', 'আল্লাহর কিতাব বোঝার জন্য', 'আরবি ভাষা', 'অধ্যয়ন করছে', 'মেয়ের'],
      emoji: '📖',
    },
  },

  // 14. Page 53: Sentence Assembly - Sinner Entering Mosque to Repent
  {
    id: 'v2-c1-l9-step-14-assembly-repent',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Sentence Assembly: Repenting in the Mosque',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: تَوْبَةُ المُذْنِبِ',
    instructionEn: 'Assemble: "O sinner! Enter the mosque in order to repent to Allah."',
    instructionBn: 'বাক্যটি সাজান: "হে পাপী! আল্লাহর কাছে তাওবা করার উদ্দেশ্যে মসজিদে প্রবেশ করো।"',
    assemblyPayload: {
      promptEn: 'O sinner! Enter the mosque in order to repent to Allah.',
      promptBn: 'হে পাপী! আল্লাহর কাছে তাওবা করার উদ্দেশ্যে মসজিদে প্রবেশ করো।',
      expectedAnswer: ['أَيُّهَا', 'المُذْنِبُ!', 'ادْخُلِ', 'المَسْجِدَ', 'لِتَتُوبَ', 'إِلَى', 'اللهِ'],
      chips: ['أَيُّهَا', 'المُذْنِبُ!', 'ادْخُلِ', 'المَسْجِدَ', 'لِتَتُوبَ', 'إِلَى', 'اللهِ', 'المُذْنِبَ!', 'لِتَتُوبُ'],
      expectedAnswerBn: ['হে পাপী!', 'আল্লাহর কাছে তাওবা করার উদ্দেশ্যে', 'মসজিদে', 'প্রবেশ করো'],
      chipsBn: ['হে পাপী!', 'আল্লাহর কাছে তাওবা করার উদ্দেশ্যে', 'মসজিদে', 'প্রবেশ করো', 'পাপীদের'],
      emoji: '🕌',
    },
  },

  // 15. Page 52: Tarkib Dissector - Purpose Clause Syntax
  {
    id: 'v2-c1-l9-step-15-tarkib-purpose',
    type: 'tarkib_dissector',
    pageNumber: 52,
    titleEn: 'Syntactic Dissector: Purpose Clause Analysis',
    titleAr: 'تَرْكِيبُ جُمْلَةِ التَّعْلِيلِ',
    instructionEn: 'Slot each component: Past verb, nominative doer, and purpose particle with accusative verb.',
    instructionBn: 'প্রতিটি অংশ স্থাপন করুন: অতীত ক্রিয়া, পেশযুক্ত কর্তা এবং কারণবাচক লাম সহ যবরযুক্ত বর্তমান ক্রিয়া।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-1',
          sentenceAr: 'خَرَجَ رَاشِدٌ لِيَذْهَبَ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ ذَاتُ تَعْلِيلٍ',
          sentenceTypeEn: 'Verbal Sentence with Purpose Clause',
          sentenceTypeBn: 'কারণবাচক বাক্যাংশযুক্ত ক্রিয়ামূলক বাক্য',
          slots: [
            {
              roleAr: 'فِعْلٌ مَاضٍ',
              roleEn: 'Past Verb',
              roleBn: 'অতীতকালের ক্রিয়া',
              expectedWordAr: 'خَرَجَ',
            },
            {
              roleAr: 'فَاعِلٌ (مَرْفُوعٌ بِالضَّمَّةِ)',
              roleEn: 'Doer / Subject (Nominative)',
              roleBn: 'কর্তা (পেশযুক্ত)',
              expectedWordAr: 'رَاشِدٌ',
            },
            {
              roleAr: 'لَامُ التَّعْلِيلِ مَعَ فِعْلٍ مُضَارِعٍ مَنْصُوبٍ',
              roleEn: 'Lam of Purpose + Accusative Present Verb',
              roleBn: 'কারণবাচক লাম ও যবরযুক্ত বর্তমান ক্রিয়া',
              expectedWordAr: 'لِيَذْهَبَ',
            },
          ],
          availableWordsAr: ['خَرَجَ', 'رَاشِدٌ', 'لِيَذْهَبَ'],
        },
      ],
    },
  },

  // 16. Page 54: Tarkib Dissector - Vocative Idafah Syntax
  {
    id: 'v2-c1-l9-step-16-tarkib-vocative',
    type: 'tarkib_dissector',
    pageNumber: 54,
    titleEn: 'Syntactic Dissector: Vocative Idafah Analysis',
    titleAr: 'تَرْكِيبُ نِدَاءِ المُضَافِ',
    instructionEn: 'Slot each component: Vocative particle, accusative called noun (mudaf), and genitive modifier (mudaf ilayh).',
    instructionBn: 'প্রতিটি অংশ স্থাপন করুন: আহ্বানসূচক অব্যয়, যবরযুক্ত মুনাদা মুদাফ এবং জেরযুক্ত মুদাফ ইলাইহ।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-2',
          sentenceAr: 'يَا إِمَامَ المَسْجِدِ',
          sentenceTypeAr: 'تَرْكِيبُ نِدَاءِ المُضَافِ',
          sentenceTypeEn: 'Vocative Idafah Construct',
          sentenceTypeBn: 'মুদাফ বিশিষ্ট আহ্বানসূচক গঠন',
          slots: [
            {
              roleAr: 'حَرْفُ نِدَاءٍ',
              roleEn: 'Vocative Particle',
              roleBn: 'আহ্বানসূচক অব্যয়',
              expectedWordAr: 'يَا',
            },
            {
              roleAr: 'مُنَادَى مُضَافٌ (مَنْصُوبٌ بِالفَتْحَةِ)',
              roleEn: 'Called Noun / Mudaf (Accusative)',
              roleBn: 'মুনাদা মুদাফ (যবরযুক্ত)',
              expectedWordAr: 'إِمَامَ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ (مَجْرُورٌ بِالكَسْرَةِ)',
              roleEn: 'Genitive Modifier (Mudaf Ilayh)',
              roleBn: 'মুদাফ ইলাইহ (জেরযুক্ত)',
              expectedWordAr: 'المَسْجِدِ',
            },
          ],
          availableWordsAr: ['يَا', 'إِمَامَ', 'المَسْجِدِ'],
        },
      ],
    },
  },

  // 17. Quranic Echo: Surah Adh-Dhariyat (51:56)
  {
    id: 'v2-c1-l9-step-17-quranic-echo-dhariyat',
    type: 'quranic_echo',
    pageNumber: 52,
    titleEn: 'Quranic Milestone: The Ultimate Purpose of Creation',
    titleAr: 'صَدَى القُرْآنِ: غَايَةُ خَلْقِ الجِنِّ وَالإِنْسِ',
    instructionEn: 'Reflect on how the Lam of purpose "لِيَعْبُدُونِ" defines the ultimate existential purpose of humanity in Surah Adh-Dhariyat (51:56).',
    instructionBn: 'সূরা আয-যারিয়াত (৫১:৫৬) এ কারণবাচক লাম "لِيَعْبُدُونِ" কীভাবে মানবজাতির সৃষ্টির চূড়ান্ত উদ্দেশ্য নির্ধারণ করেছে তা নিয়ে চিন্তা করুন।',
    echoPayload: {
      surahNumber: 51,
      ayahNumber: 56,
      surahNameAr: 'الذَّارِيَات',
      surahNameEn: 'Adh-Dhariyat',
      arabicText: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ',
      translationEn: 'And I did not create the jinn and mankind except to worship Me.',
      translationBn: 'আমি জিন এবং মানুষকে কেবল এই উদ্দেশ্যেই সৃষ্টি করেছি যে তারা আমার ইবাদত করবে।',
      highlightedWords: ['لِيَعْبُدُونِ'],
      reflection: 'The Lam of purpose (لَامُ التَّعْلِيلِ) that you learned today appears in this grand cosmic declaration: "إِلَّا لِيَعْبُدُونِ" (except in order that they worship Me). The "لـِ" prefix gives purpose to existence itself, demonstrating how a single grammatical letter anchors theological purpose across revelation.',
    },
  },
];

export const VOL2_CH1_LESSON_09_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 9,
  titleEn: 'The Lam of Purpose (لَامُ التَّعْلِيلِ) & Vocative Idafah',
  titleAr: 'لَامُ التَّعْلِيلِ وَالمُنَادَى المُضَافُ',
  wordsLearned: [
    'لَامُ التَّعْلِيلِ', 'الأُسْرَةُ', 'الغَدَاءُ', 'العَشَاءُ', 'المَطْبَخُ', 'الحَمَّامُ',
    'طَبَخَ', 'أَخَذَ', 'دَرَسَ', 'مُذْنِبٌ', 'ذَنْبٌ', 'شَيْخٌ كَبِيرٌ'
  ],
  steps: VOL2_CH1_LESSON_09_STEPS,
};
