// Volume 2 Chapter 1 Lesson 1 Interactive Session Steps (100% Curricular Parity with Physical Book Scans pages 4-18)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_01_STEPS: SessionStep[] = [
  // 1. Page 4-5: Concept Discovery - The Verbal Sentence (الجُمْلَةُ الفِعْلِيَّةُ) vs Nominal Sentence
  {
    id: 'v2-c1-l1-step-1-concept-verbal',
    type: 'concept_intro',
    pageNumber: 5,
    titleEn: 'The Verbal Sentence Begins',
    titleAr: 'مَدْخَلُ الجُمْلَةِ الفِعْلِيَّةِ',
    instructionEn: 'Notice how Arabic sentences now begin with an action (Verb) followed by the doer (Subject).',
    instructionBn: 'লক্ষ্য করুন: এখন থেকে আরবি বাক্য কাজ (ক্রিয়া/ফেল) দিয়ে শুরু হবে এবং এর পর কর্তা (ফায়েল) আসবে।',
    conceptPayload: {
      concepts: [
        {
          id: 'concept-v2-madi',
          ar: 'الفِعْلُ المَاضِي',
          romanized: 'al-fi‘lul-māḍī',
          meaningEn: 'Past Tense Verb',
          meaningBn: 'অতীতকালীন ক্রিয়া',
          exampleAr: 'ذَهَبَ رَاشِدٌ',
          exampleEn: 'Rashid went.',
          exampleBn: 'রাশেদ গেল / গিয়েছে।',
          audioKey: 'ذَهَبَ رَاشِدٌ',
          exampleAudioKey: 'ذَهَبَ رَاشِدٌ',
          emoji: '🚶‍♂️',
        },
        {
          id: 'concept-v2-mudari',
          ar: 'الفِعْلُ المُضَارِعُ',
          romanized: 'al-fi‘lul-muḍāri‘',
          meaningEn: 'Present / Future Verb',
          meaningBn: 'বর্তমান ও ভবিষ্যৎকালীন ক্রিয়া',
          exampleAr: 'يَذْهَبُ رَاشِدٌ',
          exampleEn: 'Rashid goes / will go.',
          exampleBn: 'রাশেদ যাচ্ছে / যাবে।',
          audioKey: 'يَذْهَبُ رَاشِدٌ',
          exampleAudioKey: 'يَذْهَبُ رَاشِدٌ',
          emoji: '⏳',
        },
      ],
    },
  },

  // 2. Page 5: Interactive Verb Conjugator - Past Tense (8 Foundation Verbs across 5 Persons)
  {
    id: 'v2-c1-l1-step-2-conjugator-past',
    type: 'verb_conjugator',
    pageNumber: 5,
    titleEn: 'Past Tense Paradigm Matrix',
    titleAr: 'تَصْرِيفُ الفِعْلِ المَاضِي',
    instructionEn: 'Explore the 8 foundational verbs across 5 pronoun persons in the past tense.',
    instructionBn: 'অতীতকালের ৮টি মূল ক্রিয়ার ৫টি সর্বনাম রূপ মনোযোগ দিয়ে শুনুন ও শিখুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'past',
      verbs: [
        {
          id: 'v-faala',
          rootAr: 'فَعَلَ',
          masdarAr: 'الفِعْلُ',
          meaningEn: 'To do',
          meaningBn: 'করা',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          baabEn: 'Fataha Pattern',
          baabBn: 'ফা-তা-হা বাবের ওজন',
          emoji: '⚡',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'فَعَلَ', presentAr: 'يَفْعَلُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'فَعَلَتْ', presentAr: 'تَفْعَلُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'فَعَلْتَ', presentAr: 'تَفْعَلُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'فَعَلْتِ', presentAr: 'تَفْعَلِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'فَعَلْتُ', presentAr: 'أَفْعَلُ' },
          ],
        },
        {
          id: 'v-kharaja',
          rootAr: 'خَرَجَ',
          masdarAr: 'الخُرُوجُ',
          meaningEn: 'To exit / go out',
          meaningBn: 'বের হওয়া',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          baabEn: 'Nasara Pattern',
          baabBn: 'না-সা-রা বাবের ওজন',
          emoji: '🚪',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'خَرَجَ', presentAr: 'يَخْرُجُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'خَرَجَتْ', presentAr: 'تَخْرُجُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'خَرَجْتَ', presentAr: 'تَخْرُجُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'خَرَجْتِ', presentAr: 'تَخْرُجِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'خَرَجْتُ', presentAr: 'أَخْرُجُ' },
          ],
        },
        {
          id: 'v-dhahaba',
          rootAr: 'ذَهَبَ',
          masdarAr: 'الذَّهَابُ',
          meaningEn: 'To go',
          meaningBn: 'যাওয়া',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          baabEn: 'Fataha Pattern',
          baabBn: 'ফা-তা-হা বাবের ওজন',
          emoji: '🚶‍♂️',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'ذَهَبَ', presentAr: 'يَذْهَبُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'ذَهَبَتْ', presentAr: 'تَذْهَبُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'ذَهَبْتَ', presentAr: 'تَذْهَبُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'ذَهَبْتِ', presentAr: 'تَذْهَبِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'ذَهَبْتُ', presentAr: 'أَذْهَبُ' },
          ],
        },
        {
          id: 'v-jalasa',
          rootAr: 'جَلَسَ',
          masdarAr: 'الجُلُوسُ',
          meaningEn: 'To sit',
          meaningBn: 'বসা',
          baabAr: 'بَاب ضَرَبَ يَضْرِبُ',
          baabEn: 'Daraba Pattern',
          baabBn: 'দা-রা-বা বাবের ওজন',
          emoji: '🪑',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'جَلَسَ', presentAr: 'يَجْلِسُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'جَلَسَتْ', presentAr: 'تَجْلِسُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'جَلَسْتَ', presentAr: 'تَجْلِسُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'جَلَسْتِ', presentAr: 'تَجْلِسِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'جَلَسْتُ', presentAr: 'أَجْلِسُ' },
          ],
        },
        {
          id: 'v-qaraa',
          rootAr: 'قَرَأَ',
          masdarAr: 'القِرَاءَةُ',
          meaningEn: 'To read',
          meaningBn: 'পড়া',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          baabEn: 'Fataha Pattern',
          baabBn: 'ফা-তা-হা বাবের ওজন',
          emoji: '📖',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'قَرَأَ', presentAr: 'يَقْرَأُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'قَرَأَتْ', presentAr: 'تَقْرَأُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'قَرَأْتَ', presentAr: 'تَقْرَأُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'قَرَأْتِ', presentAr: 'تَقْرَأِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'قَرَأْتُ', presentAr: 'أَقْرَأُ' },
          ],
        },
        {
          id: 'v-kataba',
          rootAr: 'كَتَبَ',
          masdarAr: 'الكِتَابَةُ',
          meaningEn: 'To write',
          meaningBn: 'লেখা',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          baabEn: 'Nasara Pattern',
          baabBn: 'না-সা-রা বাবের ওজন',
          emoji: '✍️',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'كَتَبَ', presentAr: 'يَكْتُبُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'كَتَبَتْ', presentAr: 'تَكْتُبُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'كَتَبْتَ', presentAr: 'تَكْتُبُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'كَتَبْتِ', presentAr: 'تَكْتُبِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'كَتَبْتُ', presentAr: 'أَكْتُبُ' },
          ],
        },
        {
          id: 'v-rajaa',
          rootAr: 'رَجَعَ',
          masdarAr: 'الرُّجُوعُ',
          meaningEn: 'To return',
          meaningBn: 'ফিরে আসা',
          baabAr: 'بَاب ضَرَبَ يَضْرِبُ',
          baabEn: 'Daraba Pattern',
          baabBn: 'দা-রা-বা বাবের ওজন',
          emoji: '🔄',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'رَجَعَ', presentAr: 'يَرْجِعُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'رَجَعَتْ', presentAr: 'تَرْجِعُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'رَجَعْتَ', presentAr: 'تَرْجِعُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'رَجَعْتِ', presentAr: 'تَرْجِعِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'رَجَعْتُ', presentAr: 'أَرْجِعُ' },
          ],
        },
        {
          id: 'v-laiba',
          rootAr: 'لَعِبَ',
          masdarAr: 'اللَّعِبُ',
          meaningEn: 'To play',
          meaningBn: 'খেলা করা',
          baabAr: 'بَاب سَمِعَ يَسْمَعُ',
          baabEn: 'Samia Pattern',
          baabBn: 'সা-মি-আ বাবের ওজন',
          emoji: '⚽',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'لَعِبَ', presentAr: 'يَلْعَبُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'لَعِبَتْ', presentAr: 'تَلْعَبُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'لَعِبْتَ', presentAr: 'تَلْعَبُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'لَعِبْتِ', presentAr: 'تَلْعَبِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'لَعِبْتُ', presentAr: 'أَلْعَبُ' },
          ],
        },
      ],
    },
  },

  // 3. Page 6: Vocabulary Priming - Prepositions of Direction & Conjunctions
  {
    id: 'v2-c1-l1-step-3-vocab-prep',
    type: 'vocab_prime',
    pageNumber: 6,
    titleEn: 'Directional Prepositions & Conjunctions',
    titleAr: 'حُرُوفُ الجَرِّ وَحُرُوفُ العَطْفِ',
    instructionEn: 'Listen to the essential prepositions that connect actions to locations and people.',
    instructionBn: 'স্থান ও ব্যক্তির সাথে ক্রিয়াকে যুক্তকারী অব্যয়গুলো শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_min', ar: 'مِنْ', en: 'From', bn: 'থেকে / হতে', romanized: 'min', emoji: '⬅️' },
        { id: 'v2_ila', ar: 'إِلَى', en: 'To / Towards', bn: 'দিকে / পর্যন্ত', romanized: 'ilā', emoji: '➡️' },
        { id: 'v2_ala', ar: 'عَلَى', en: 'On / Upon', bn: 'উপরে', romanized: '‘alā', emoji: '⬆️' },
        { id: 'v2_bi', ar: 'بِـ', en: 'With / By', bn: 'দ্বারা / দিয়ে', romanized: 'bi', emoji: '🤝' },
        { id: 'v2_thumma', ar: 'ثُمَّ', en: 'Then / After that', bn: 'তারপর', romanized: 'thumma', emoji: '⏭️' },
        { id: 'v2_malab', ar: 'مَلْعَبٌ', en: 'Playground', bn: 'খেলার মাঠ', romanized: 'mal‘abun', emoji: '🏟️' },
        { id: 'v2_manzil', ar: 'مَنْزِلٌ', en: 'Home / House', bn: 'ঘর / গৃহ', romanized: 'manzilun', emoji: '🏡' },
      ],
    },
  },

  // 4. Page 6: Active Recall - Speed Pair Matching
  {
    id: 'v2-c1-l1-step-4-pair-verbs',
    type: 'speed_pair',
    pageNumber: 6,
    titleEn: 'Synaptic Recall: Verbs & Particles',
    titleAr: 'تَطْبِيقُ الأَفْعَالِ وَالحُرُوفِ',
    instructionEn: 'Match each Arabic verb or preposition to its meaning.',
    instructionBn: 'আরবি শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে দিন।',
    pairPayload: {
      pairs: [
        { id: 'p-kharaja', ar: 'خَرَجَ', meaning: 'He exited' },
        { id: 'p-dhahaba', ar: 'ذَهَبَ', meaning: 'He went' },
        { id: 'p-jalasa', ar: 'جَلَسَ', meaning: 'He sat' },
        { id: 'p-ila', ar: 'إِلَى', meaning: 'To / Towards' },
        { id: 'p-min', ar: 'مِنْ', meaning: 'From' },
      ],
    },
  },

  // 5. Page 6: Sentence Assembly - Masculine Action Narrative
  {
    id: 'v2-c1-l1-step-5-assembly-rashid-exit',
    type: 'sentence_assembly',
    pageNumber: 6,
    titleEn: 'Sentence Assembly: Rashid Exits',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: خُرُوجُ رَاشِدٍ',
    instructionEn: 'Assemble the sentence: "Rashid exited from his house."',
    instructionBn: '"রাশেদ তার ঘর থেকে বের হলো" - বাক্যটি সাজান।',
    assemblyPayload: {
      promptEn: 'Rashid exited from his house.',
      promptBn: 'রাশেদ তার ঘর থেকে বের হলো।',
      expectedAnswer: ['خَرَجَ', 'رَاشِدٌ', 'مِنْ', 'بَيْتِهِ'],
      chips: ['خَرَجَ', 'رَاشِدٌ', 'مِنْ', 'بَيْتِهِ', 'خَرَجَتْ', 'إِلَى'],
      expectedAnswerBn: ['রাশেদ', 'তার', 'ঘর', 'থেকে', 'বের', 'হলো'],
      chipsBn: ['রাশেদ', 'তার', 'ঘর', 'থেকে', 'বের', 'হলো', 'গেল', 'মাদরাসায়'],
      emoji: '🚪',
    },
  },

  // 6. Page 6: Sentence Assembly - Feminine Action Narrative
  {
    id: 'v2-c1-l1-step-6-assembly-sister-exit',
    type: 'sentence_assembly',
    pageNumber: 6,
    titleEn: 'Sentence Assembly: Sister Exits',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: خُرُوجُ أُخْتِ رَاشِدٍ',
    instructionEn: 'Assemble the sentence: "Rashid\'s sister exited from her room."',
    instructionBn: '"রাশেদের বোন তার কামরা থেকে বের হলো" - বাক্যটি সাজান।',
    assemblyPayload: {
      promptEn: "Rashid's sister exited from her room.",
      promptBn: 'রাশেদের বোন তার কামরা থেকে বের হলো।',
      expectedAnswer: ['خَرَجَتْ', 'أُخْتُ', 'رَاشِدٍ', 'مِنْ', 'غُرْفَتِهَا'],
      chips: ['خَرَجَتْ', 'أُخْتُ', 'رَاشِدٍ', 'مِنْ', 'غُرْفَتِهَا', 'خَرَجَ', 'بَيْتِهِ'],
      expectedAnswerBn: ['রাশেদের', 'বোন', 'তার', 'কামরা', 'থেকে', 'বের', 'হলো'],
      chipsBn: ['রাশেদের', 'বোন', 'তার', 'কামরা', 'থেকে', 'বের', 'হলো', 'ভাই', 'ঘরে'],
      emoji: '👧',
    },
  },

  // 7. Page 6: Cloze Choice - Instrumental & Directional Case Endings
  {
    id: 'v2-c1-l1-step-7-cloze-ball',
    type: 'cloze_choice',
    pageNumber: 6,
    titleEn: 'Case Ending Precision: With a New Ball',
    titleAr: 'ضَبْطُ الإِعْرَابِ: لَعِبَ بِكُرَةٍ جَدِيدَةٍ',
    instructionEn: 'Select the correct form with Kasratayn after the preposition "بِـ".',
    instructionBn: 'হরফে জর "بِـ" এর পর সঠিক জেরযুক্ত শব্দটি নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'لَعِبَ رَاشِدٌ مَعَ خَالِدٍ ... جَدِيدَةٍ .',
      questionEn: 'Rashid played with Khalid with a new ball.',
      questionBn: 'রাশেদ খালেদের সাথে একটি নতুন বল দিয়ে খেলল।',
      partialAnswerAr: 'لَعِبَ رَاشِدٌ مَعَ خَالِدٍ ... جَدِيدَةٍ .',
      correctAnswer: 'بِكُرَةٍ',
      options: ['بِكُرَةٍ', 'بِكُرَةٌ', 'بِكُرَةً'],
      emoji: '⚽',
    },
  },

  // 8. Page 7-8: Dialogic Mini-Game - Past Tense Story Battery
  {
    id: 'v2-c1-l1-step-8-dialogue-past-story',
    type: 'alternative_qa',
    pageNumber: 7,
    titleEn: 'Dialogic Mini-Game: Reading Comprehension',
    titleAr: 'حِوَارُ الاسْتِيعَابِ: قِصَّةُ المَاضِي',
    instructionEn: 'Answer each question about the story without guessing.',
    instructionBn: 'গল্পের আলোকে সঠিক উত্তরটি নির্বাচন করুন।',
    alternativeQAPayload: {
      contextAr: 'خَرَجَ رَاشِدٌ مِنْ بَيْتِهِ وَذَهَبَ إِلَى الْمَدْرَسَةِ وَجَلَسَ أَمَامَ الْمُعَلِّمِ. قَرَأَ رَاشِدٌ وَكَتَبَ فِي الْمَدْرَسَةِ، ثُمَّ رَجَعَ إِلَى الْمَنْزِلِ وَلَعِبَ فِي مَلْعَبِ الْقَرْيَةِ. لَعِبَ رَاشِدٌ مَعَ خَالِدٍ بِكُرَةٍ جَدِيدَةٍ.',
      questions: [
        {
          id: 'q-who-exited',
          questionAr: 'أَ بِلَالٌ خَرَجَ أَمْ رَاشِدٌ ؟',
          optionsAr: ['رَاشِدٌ', 'بِلَالٌ'],
          correctAnswerAr: 'رَاشِدٌ',
        },
        {
          id: 'q-where-went',
          questionAr: 'أَ إِلَى السُّوقِ ذَهَبَ أَمْ إِلَى الْمَدْرَسَةِ ؟',
          optionsAr: ['إِلَى الْمَدْرَسَةِ', 'إِلَى السُّوقِ'],
          correctAnswerAr: 'إِلَى الْمَدْرَسَةِ',
        },
        {
          id: 'q-what-did',
          questionAr: 'أَ لَعِبَ هُنَاكَ أَمْ قَرَأَ وَكَتَبَ ؟',
          optionsAr: ['قَرَأَ وَكَتَبَ', 'لَعِبَ'],
          correctAnswerAr: 'قَرَأَ وَكَتَبَ',
        },
        {
          id: 'q-where-played',
          questionAr: 'أَ فِي الطَّرِيقِ لَعِبَ أَمْ فِي مَلْعَبِ الْقَرْيَةِ ؟',
          optionsAr: ['فِي مَلْعَبِ الْقَرْيَةِ', 'فِي الطَّرِيقِ'],
          correctAnswerAr: 'فِي مَلْعَبِ الْقَرْيَةِ',
        },
      ],
    },
  },

  // 9. Page 10: Interactive Verb Conjugator - Present / Future Tense (8 Verbs across 5 Persons)
  {
    id: 'v2-c1-l1-step-9-conjugator-present',
    type: 'verb_conjugator',
    pageNumber: 10,
    titleEn: 'Present & Future Tense Paradigm Matrix',
    titleAr: 'تَصْرِيفُ الفِعْلِ المُضَارِعِ',
    instructionEn: 'Explore the 8 foundational verbs in the present and future tense (Al-Mudari\').',
    instructionBn: 'বর্তমান ও ভবিষ্যৎকালের (আল-মুদারী\') ৮টি মূল ক্রিয়ার রূপগুলো শুনুন ও লক্ষ্য করুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'present',
      verbs: [
        {
          id: 'v-pres-faala',
          rootAr: 'فَعَلَ',
          masdarAr: 'الفِعْلُ',
          meaningEn: 'To do',
          meaningBn: 'করা',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          emoji: '⚡',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'فَعَلَ', presentAr: 'يَفْعَلُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'فَعَلَتْ', presentAr: 'تَفْعَلُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'فَعَلْتَ', presentAr: 'تَفْعَلُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'فَعَلْتِ', presentAr: 'تَفْعَلِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'فَعَلْتُ', presentAr: 'أَفْعَلُ' },
          ],
        },
        {
          id: 'v-pres-kharaja',
          rootAr: 'خَرَجَ',
          masdarAr: 'الخُرُوجُ',
          meaningEn: 'To exit / go out',
          meaningBn: 'বের হওয়া',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '🚪',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'خَرَجَ', presentAr: 'يَخْرُجُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'خَرَجَتْ', presentAr: 'تَخْرُجُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'خَرَجْتَ', presentAr: 'تَخْرُجُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'خَرَجْتِ', presentAr: 'تَخْرُجِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'خَرَجْتُ', presentAr: 'أَخْرُجُ' },
          ],
        },
        {
          id: 'v-pres-dhahaba',
          rootAr: 'ذَهَبَ',
          masdarAr: 'الذَّهَابُ',
          meaningEn: 'To go',
          meaningBn: 'যাওয়া',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          emoji: '🚶‍♂️',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'ذَهَبَ', presentAr: 'يَذْهَبُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'ذَهَبَتْ', presentAr: 'تَذْهَبُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'ذَهَبْتَ', presentAr: 'تَذْهَبُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'ذَهَبْتِ', presentAr: 'تَذْهَبِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'ذَهَبْتُ', presentAr: 'أَذْهَبُ' },
          ],
        },
        {
          id: 'v-pres-kataba',
          rootAr: 'كَتَبَ',
          masdarAr: 'الكِتَابَةُ',
          meaningEn: 'To write',
          meaningBn: 'লেখা',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '✍️',
          forms: [
            { subjectAr: 'هُوَ', subjectEn: 'He', subjectBn: 'সে (পুং)', pastAr: 'كَتَبَ', presentAr: 'يَكْتُبُ' },
            { subjectAr: 'هِيَ', subjectEn: 'She', subjectBn: 'সে (স্ত্রী)', pastAr: 'كَتَبَتْ', presentAr: 'تَكْتُبُ' },
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'كَتَبْتَ', presentAr: 'تَكْتُبُ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'كَتَبْتِ', presentAr: 'تَكْتُبِينَ' },
            { subjectAr: 'أَنَا', subjectEn: 'I', subjectBn: 'আমি', pastAr: 'كَتَبْتُ', presentAr: 'أَكْتُبُ' },
          ],
        },
      ],
    },
  },

  // 10. Page 10: Vocabulary Priming - Temporal Adverbs (ظُرُوفُ الزَّمَانِ)
  {
    id: 'v2-c1-l1-step-10-vocab-time',
    type: 'vocab_prime',
    pageNumber: 10,
    titleEn: 'Temporal Adverbs & Time Expressions',
    titleAr: 'ظُرُوفُ الزَّمَانِ',
    instructionEn: 'Learn essential Arabic adverbs for time: now, today, tomorrow, before, and after.',
    instructionBn: 'সময়বাচক গুরুত্বপূর্ণ আরবি শব্দগুলো শুনুন ও আয়ত্ত করুন।',
    vocabPayload: {
      words: [
        { id: 'v2_alan', ar: 'الآنَ', en: 'Now', bn: 'এখন', romanized: 'al-āna', emoji: '⏰' },
        { id: 'v2_alyawm', ar: 'اليَوْمَ', en: 'Today', bn: 'আজ', romanized: 'al-yawma', emoji: '📅' },
        { id: 'v2_ghadan', ar: 'غَدًا', en: 'Tomorrow', bn: 'আগামীকাল', romanized: 'ghadan', emoji: '🌅' },
        { id: 'v2_sabahan', ar: 'صَبَاحًا', en: 'In the morning', bn: 'সকালে', romanized: 'ṣabāḥan', emoji: '☀️' },
        { id: 'v2_masaan', ar: 'مَسَاءً', en: 'In the evening', bn: 'সন্ধ্যায়', romanized: 'masā’an', emoji: '🌙' },
        { id: 'v2_qabla', ar: 'قَبْلَ', en: 'Before', bn: 'পূর্বে / আগে', romanized: 'qabla', emoji: '◀️' },
        { id: 'v2_bada', ar: 'بَعْدَ', en: 'After', bn: 'পরে', romanized: 'ba‘da', emoji: '▶️' },
        { id: 'v2_mata', ar: 'مَتَى', en: 'When?', bn: 'কখন?', romanized: 'matā', emoji: '❓' },
      ],
    },
  },

  // 11. Page 10: Sentence Assembly - Present Tense with Temporal Adverb
  {
    id: 'v2-c1-l1-step-11-assembly-khalid-now',
    type: 'sentence_assembly',
    pageNumber: 10,
    titleEn: 'Sentence Assembly: Khalid Exits Now',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: يَخْرُجُ خَالِدٌ الآنَ',
    instructionEn: 'Assemble the sentence: "Khalid is exiting from his house now."',
    instructionBn: '"খালেদ এখন তার ঘর থেকে বের হচ্ছে" - বাক্যটি সাজান।',
    assemblyPayload: {
      promptEn: 'Khalid is exiting from his house now.',
      promptBn: 'খালেদ এখন তার ঘর থেকে বের হচ্ছে।',
      expectedAnswer: ['يَخْرُجُ', 'خَالِدٌ', 'الآنَ', 'مِنْ', 'بَيْتِهِ'],
      chips: ['يَخْرُجُ', 'خَالِدٌ', 'الآنَ', 'مِنْ', 'بَيْتِهِ', 'خَرَجَ', 'غَدًا'],
      expectedAnswerBn: ['খালেদ', 'এখন', 'তার', 'ঘর', 'থেকে', 'বের', 'হচ্ছে'],
      chipsBn: ['খালেদ', 'এখন', 'তার', 'ঘর', 'থেকে', 'বের', 'হচ্ছে', 'হলো', 'কাল'],
      emoji: '🚪',
    },
  },

  // 12. Page 11-12: Dialogic Mini-Game - Present Tense Battery
  {
    id: 'v2-c1-l1-step-12-dialogue-present',
    type: 'alternative_qa',
    pageNumber: 11,
    titleEn: 'Dialogic Mini-Game: Present Tense Timing',
    titleAr: 'حِوَارُ الاسْتِيعَابِ: الفِعْلُ المُضَارِعُ',
    instructionEn: 'Answer each question about Khalid\'s daily routine.',
    instructionBn: 'খালেদের রুটিন সম্পর্কিত প্রশ্নগুলোর সঠিক উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'هُوَ يَرْجِعُ قَبْلَ العَصْرِ وَيَلْعَبُ فِي مَلْعَبِ القَرْيَةِ بَعْدَ العَصْرِ',
      questions: [
        {
          id: 'q-return-time',
          questionAr: 'أَ يَرْجِعُ قَبْلَ العَصْرِ أَمْ بَعْدَ العَصْرِ ؟',
          optionsAr: ['قَبْلَ العَصْرِ', 'بَعْدَ العَصْرِ'],
          correctAnswerAr: 'قَبْلَ العَصْرِ',
        },
        {
          id: 'q-play-time',
          questionAr: 'أَ يَلْعَبُ قَبْلَ العَصْرِ أَمْ بَعْدَ العَصْرِ ؟',
          optionsAr: ['بَعْدَ العَصْرِ', 'قَبْلَ العَصْرِ'],
          correctAnswerAr: 'بَعْدَ العَصْرِ',
        },
      ],
    },
  },

  // 13. Page 14: Interactive Verb Conjugator - Command (الأَمْرُ)
  {
    id: 'v2-c1-l1-step-13-conjugator-command',
    type: 'verb_conjugator',
    pageNumber: 14,
    titleEn: 'Command Forms',
    titleAr: 'تَصْرِيفُ الأَمْرِ',
    instructionEn: 'Learn how direct commands are formed for masculine and feminine listeners.',
    instructionBn: 'পুংলিঙ্গ ও স্ত্রীলিঙ্গের শ্রোতার জন্য আদেশবাচক ক্রিয়া লক্ষ্য করুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'imperative',
      verbs: [
        {
          id: 'v-cmd-faala',
          rootAr: 'فَعَلَ',
          masdarAr: 'الفِعْلُ',
          meaningEn: 'To do',
          meaningBn: 'করা',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          emoji: '⚡',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'فَعَلْتَ', presentAr: 'تَفْعَلُ', imperativeAr: 'اِفْعَلْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'فَعَلْتِ', presentAr: 'تَفْعَلِينَ', imperativeAr: 'اِفْعَلِي' },
          ],
        },
        {
          id: 'v-cmd-kharaja',
          rootAr: 'خَرَجَ',
          masdarAr: 'الخُرُوجُ',
          meaningEn: 'To exit',
          meaningBn: 'বের হওয়া',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '🚪',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'خَرَجْتَ', presentAr: 'تَخْرُجُ', imperativeAr: 'اُخْرُجْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'خَرَجْتِ', presentAr: 'تَخْرُجِينَ', imperativeAr: 'اُخْرُجِي' },
          ],
        },
        {
          id: 'v-cmd-jalasa',
          rootAr: 'جَلَسَ',
          masdarAr: 'الجُلُوسُ',
          meaningEn: 'To sit',
          meaningBn: 'বসা',
          baabAr: 'بَاب ضَرَبَ يَضْرِبُ',
          emoji: '🪑',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'جَلَسْتَ', presentAr: 'تَجْلِسُ', imperativeAr: 'اِجْلِسْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'جَلَسْتِ', presentAr: 'تَجْلِسِينَ', imperativeAr: 'اِجْلِسِي' },
          ],
        },
        {
          id: 'v-cmd-kataba',
          rootAr: 'كَتَبَ',
          masdarAr: 'الكِتَابَةُ',
          meaningEn: 'To write',
          meaningBn: 'লেখা',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '✍️',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'كَتَبْتَ', presentAr: 'تَكْتُبُ', imperativeAr: 'اُكْتُبْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'كَتَبْتِ', presentAr: 'تَكْتُبِينَ', imperativeAr: 'اُكْتُبِي' },
          ],
        },
      ],
    },
  },

  // 14. Page 14: Interactive Verb Conjugator - Forbidding / Prohibition (النَّهْيُ)
  {
    id: 'v2-c1-l1-step-14-conjugator-prohibition',
    type: 'verb_conjugator',
    pageNumber: 14,
    titleEn: 'Forbidding Forms',
    titleAr: 'تَصْرِيفُ النَّهْيِ',
    instructionEn: 'Learn how negative commands (prohibitions) are formed using negative La.',
    instructionBn: 'না-বোধক লা (لَا النَّاهِيَة) দিয়ে কীভাবে নিষেধবাচক ক্রিয়া গঠিত হয় লক্ষ্য করুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'prohibition',
      verbs: [
        {
          id: 'v-proh-faala',
          rootAr: 'فَعَلَ',
          masdarAr: 'الفِعْلُ',
          meaningEn: 'To do',
          meaningBn: 'করা',
          baabAr: 'بَاب فَتَحَ يَفْتَحُ',
          emoji: '⚡',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'فَعَلْتَ', presentAr: 'تَفْعَلُ', prohibitionAr: 'لَا تَفْعَلْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'فَعَلْتِ', presentAr: 'تَفْعَلِينَ', prohibitionAr: 'لَا تَفْعَلِي' },
          ],
        },
        {
          id: 'v-proh-kharaja',
          rootAr: 'خَرَجَ',
          masdarAr: 'الخُرُوجُ',
          meaningEn: 'To exit',
          meaningBn: 'বের হওয়া',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '🚪',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'خَرَجْتَ', presentAr: 'تَخْرُجُ', prohibitionAr: 'لَا تَخْرُجْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'خَرَجْتِ', presentAr: 'تَخْرُجِينَ', prohibitionAr: 'لَا تَخْرُجِي' },
          ],
        },
        {
          id: 'v-proh-jalasa',
          rootAr: 'جَلَسَ',
          masdarAr: 'الجُلُوسُ',
          meaningEn: 'To sit',
          meaningBn: 'বসা',
          baabAr: 'بَاب ضَرَبَ يَضْرِبُ',
          emoji: '🪑',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'جَلَسْتَ', presentAr: 'تَجْلِسُ', prohibitionAr: 'لَا تَجْلِسْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'جَلَسْتِ', presentAr: 'تَجْلِسِينَ', prohibitionAr: 'لَا تَجْلِسِي' },
          ],
        },
        {
          id: 'v-proh-kataba',
          rootAr: 'كَتَبَ',
          masdarAr: 'الكِتَابَةُ',
          meaningEn: 'To write',
          meaningBn: 'লেখা',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          emoji: '✍️',
          forms: [
            { subjectAr: 'أَنْتَ', subjectEn: 'You (m)', subjectBn: 'তুমি (পুং)', pastAr: 'كَتَبْتَ', presentAr: 'تَكْتُبُ', prohibitionAr: 'لَا تَكْتُبْ' },
            { subjectAr: 'أَنْتِ', subjectEn: 'You (f)', subjectBn: 'তুমি (স্ত্রী)', pastAr: 'كَتَبْتِ', presentAr: 'تَكْتُبِينَ', prohibitionAr: 'لَا تَكْتُبِي' },
          ],
        },
      ],
    },
  },

  // 15. Page 14: Vocabulary Priming - Classroom & Living Objects
  {
    id: 'v2-c1-l1-step-15-vocab-objects',
    type: 'vocab_prime',
    pageNumber: 14,
    titleEn: 'Classroom & Household Objects',
    titleAr: 'مُفْرَدَاتُ الفَصْلِ وَالمَنْزِلِ',
    instructionEn: 'Listen to the remaining nouns introduced in the command dialogues.',
    instructionBn: 'আদেশবাচক সংলাপে ব্যবহৃত নতুন বিশেষ্য পদগুলো শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_hasir', ar: 'حَصِيرٌ', en: 'A mat', bn: 'একটি চাটাই', romanized: 'ḥaṣīrun', emoji: '🧺' },
        { id: 'v2_maqad', ar: 'مَقْعَدٌ', en: 'A bench / seat', bn: 'একটি আসন বা বসার স্থান', romanized: 'maq‘adun', emoji: '🪑' },
        { id: 'v2_sabil', ar: 'سَبِيلٌ', en: 'A path / way', bn: 'একটি পথ বা রাস্তা', romanized: 'sabīlun', emoji: '🛣️' },
        { id: 'v2_li', ar: 'لِـ', en: 'For / Belonging to', bn: 'জন্য / এর', romanized: 'li', emoji: '🏷️' },
      ],
    },
  },

  // 16. Page 14: Sentence Assembly - Masculine Command Dialogue
  {
    id: 'v2-c1-l1-step-16-assembly-rashid-command',
    type: 'sentence_assembly',
    pageNumber: 14,
    titleEn: 'Sentence Assembly: Command to Rashid',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَمْرٌ لِرَاشِدٍ',
    instructionEn: 'Assemble the command: "O Rashid! Exit from your room."',
    instructionBn: '"হে রাশেদ! তোমার কামরা থেকে বের হও" - বাক্যটি সাজান।',
    assemblyPayload: {
      promptEn: 'O Rashid! Exit from your room.',
      promptBn: 'হে রাশেদ! তোমার কামরা থেকে বের হও।',
      expectedAnswer: ['يَا', 'رَاشِدُ', 'اُخْرُجْ', 'مِنْ', 'غُرْفَتِكَ'],
      chips: ['يَا', 'رَاشِدُ', 'اُخْرُجْ', 'مِنْ', 'غُرْفَتِكَ', 'اُخْرُجِي', 'بَيْتِكَ'],
      expectedAnswerBn: ['হে', 'রাশেদ', 'তোমার', 'কামরা', 'থেকে', 'বের', 'হও'],
      chipsBn: ['হে', 'রাশেদ', 'তোমার', 'কামরা', 'থেকে', 'বের', 'হও', 'ঘরে', 'যাও'],
      emoji: '📢',
    },
  },

  // 17. Page 14: Sentence Assembly - Feminine Command & Prohibition
  {
    id: 'v2-c1-l1-step-17-assembly-fatima-command',
    type: 'sentence_assembly',
    pageNumber: 14,
    titleEn: 'Sentence Assembly: Command & Prohibition to Fatima',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَمْرٌ وَنَهْيٌ لِفَاطِمَةَ',
    instructionEn: 'Assemble: "O Fatima! Exit to the garden and do not play with the ball."',
    instructionBn: '"হে ফাতেমা! বাগানের দিকে বের হও এবং বল নিয়ে খেলো না" - বাক্যটি সাজান।',
    assemblyPayload: {
      promptEn: 'O Fatima! Exit to the garden and do not play with the ball.',
      promptBn: 'হে ফাতেমা! বাগানের দিকে বের হও এবং বল নিয়ে খেলো না।',
      expectedAnswer: ['يَا', 'فَاطِمَةُ', 'اُخْرُجِي', 'إِلَى', 'الْحَدِيقَةِ', 'وَلَا', 'تَلْعَبِي', 'بِالْكُرَةِ'],
      chips: ['يَا', 'فَاطِمَةُ', 'اُخْرُجِي', 'إِلَى', 'الْحَدِيقَةِ', 'وَلَا', 'تَلْعَبِي', 'بِالْكُرَةِ', 'اُخْرُجْ', 'تَلْعَبْ'],
      expectedAnswerBn: ['হে', 'ফাতেমা', 'বাগানের', 'দিকে', 'বের', 'হও', 'এবং', 'বল', 'নিয়ে', 'খেলো', 'না'],
      chipsBn: ['হে', 'ফাতেমা', 'বাগানের', 'দিকে', 'বের', 'হও', 'এবং', 'বল', 'নিয়ে', 'খেলো', 'না', 'মাঠে', 'বসো'],
      emoji: '🌸',
    },
  },

  // 18. Page 15: Dialogic Mini-Game - Command Comprehension
  {
    id: 'v2-c1-l1-step-18-dialogue-mat-chair',
    type: 'alternative_qa',
    pageNumber: 15,
    titleEn: 'Dialogic Mini-Game: Where to Sit?',
    titleAr: 'حِوَارُ الاسْتِيعَابِ: أَيْنَ يَجْلِسُ ؟',
    instructionEn: 'Choose the correct seat commanded to Rashid.',
    instructionBn: 'রাশেদকে কোথায় বসতে আদেশ করা হয়েছে তা নির্বাচন করুন।',
    alternativeQAPayload: {
      contextAr: 'اِجْلِسْ عَلَى الحَصِيرِ وَلَا تَجْلِسْ عَلَى الكُرْسِيِّ',
      questions: [
        {
          id: 'q-sit-seat',
          questionAr: 'أَ يَجْلِسُ عَلَى الحَصِيرِ أَمْ عَلَى الكُرْسِيِّ ؟',
          optionsAr: ['عَلَى الحَصِيرِ', 'عَلَى الكُرْسِيِّ'],
          correctAnswerAr: 'عَلَى الحَصِيرِ',
        },
      ],
    },
  },

  // 19. Page 18: Tarkib Dissector - Simple Verbal Sentence (فِعْل + فَاعِل)
  {
    id: 'v2-c1-l1-step-19-tarkib-simple-verbal',
    type: 'tarkib_dissector',
    pageNumber: 18,
    titleEn: 'Syntactic Dissector: Basic Verbal Sentence',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ الفِعْلِيَّةِ البَسِيطَةِ',
    instructionEn: 'Slot each word into its grammatical role: Verb (فعل) and Subject (فاعل).',
    instructionBn: 'প্রতিটি শব্দকে তার ব্যাকরণিক স্থানে বসান: কাজ (ফেল) ও কর্তা (ফায়েল)।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-dhahaba-rashid',
          sentenceAr: 'ذَهَبَ رَاشِدٌ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ',
          sentenceTypeEn: 'Verbal Sentence',
          sentenceTypeBn: 'ক্রিয়াবাচক বাক্য (জুমলা ফে\'লিইয়াহ)',
          slots: [
            {
              roleAr: 'فِعْلٌ',
              roleEn: 'Action / Verb',
              roleBn: 'কাজ (ফেল)',
              expectedWordAr: 'ذَهَبَ',
            },
            {
              roleAr: 'فَاعِلٌ',
              roleEn: 'Doer / Subject',
              roleBn: 'কর্তা (ফায়েল)',
              expectedWordAr: 'رَاشِدٌ',
            },
          ],
          availableWordsAr: ['ذَهَبَ', 'رَاشِدٌ'],
        },
      ],
    },
  },

  // 20. Page 18: Tarkib Dissector - Verbal Sentence with Prepositional Phrase (مُتَعَلِّق)
  {
    id: 'v2-c1-l1-step-20-tarkib-verbal-mutaallaq',
    type: 'tarkib_dissector',
    pageNumber: 18,
    titleEn: 'Syntactic Dissector: Verb with Attachment',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: فِعْلٌ وَفَاعِلٌ وَمُتَعَلِّقٌ',
    instructionEn: 'Slot: Verb (فعل), Subject (فاعل), and Prepositional Attachment (متعلق).',
    instructionBn: 'শব্দগুলো বসান: কাজ (ফেল), কর্তা (ফায়েল) এবং সংশ্লিষ্ট অংশ (মুতাআল্লিক)।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-kataba-biqalam',
          sentenceAr: 'كَتَبَ رَاشِدٌ بِالْقَلَمِ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ',
          sentenceTypeEn: 'Verbal Sentence with Prepositional Phrase',
          sentenceTypeBn: 'ক্রিয়াবাচক বাক্য (সংশ্লিষ্ট অংশসহ)',
          slots: [
            {
              roleAr: 'فِعْلٌ',
              roleEn: 'Action / Verb',
              roleBn: 'কাজ (ফেল)',
              expectedWordAr: 'كَتَبَ',
            },
            {
              roleAr: 'فَاعِلٌ',
              roleEn: 'Doer / Subject',
              roleBn: 'কর্তা (ফায়েল)',
              expectedWordAr: 'رَاشِدٌ',
            },
            {
              roleAr: 'مُتَعَلِّقٌ بِالفِعْلِ',
              roleEn: 'Prepositional Attachment',
              roleBn: 'ক্রিয়ার সংশ্লিষ্ট (মুতাআল্লিক)',
              expectedWordAr: 'بِالْقَلَمِ',
            },
          ],
          availableWordsAr: ['كَتَبَ', 'رَاشِدٌ', 'بِالْقَلَمِ'],
        },
      ],
    },
  },

  // 21. Page 18: Tarkib Dissector - Verbal Sentence as Predicate of Nominal Sentence
  {
    id: 'v2-c1-l1-step-21-tarkib-nominal-verbal-predicate',
    type: 'tarkib_dissector',
    pageNumber: 18,
    titleEn: 'Syntactic Dissector: Verbal Predicate',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: مُبْتَدَأٌ وَخَبَرٌ جُمْلَةٌ فِعْلِيَّةٌ',
    instructionEn: 'Notice how a noun fronted before a verb makes the sentence Nominal (المبتدأ) with a Verbal Predicate (الخبر).',
    instructionBn: 'ক্রিয়ার পূর্বে বিশেষ্য আসলে বাক্যটি নামবাচক (মুবতাদা) হয় এবং ক্রিয়াংশটি বিধেয় (খবর) হয়।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-rashid-kataba',
          sentenceAr: 'رَاشِدٌ كَتَبَ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (خَبَرُهَا جُمْلَةٌ فِعْلِيَّةٌ)',
          sentenceTypeEn: 'Nominal Sentence (Verbal Clause as Predicate)',
          sentenceTypeBn: 'নামবাচক বাক্য (যার খবর একটি ক্রিয়াবাচক বাক্য)',
          slots: [
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Topic / Subject',
              roleBn: 'উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'رَاشِدٌ',
            },
            {
              roleAr: 'خَبَرٌ (جُمْلَةٌ فِعْلِيَّةٌ)',
              roleEn: 'Verbal Predicate',
              roleBn: 'বিধেয় ক্রিয়াংশ (খবর)',
              expectedWordAr: 'كَتَبَ',
            },
          ],
          availableWordsAr: ['رَاشِدٌ', 'كَتَبَ'],
        },
      ],
    },
  },

  // 22. Sacred Quranic Echo: The Root "فَعَلَ" in Surah Al-Fil
  {
    id: 'v2-c1-l1-step-22-quranic-echo-fil',
    type: 'quranic_echo',
    pageNumber: 18,
    titleEn: 'Sacred Milestone: The Root Verb in the Quran',
    titleAr: 'صَدَى القُرْآنِ: أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ',
    instructionEn: 'Reflect on how the exact verb "فَعَلَ" you mastered today appears in the Holy Quran.',
    instructionBn: 'আজ আপনার শেখা মূল ক্রিয়া "فَعَلَ" পবিত্র কুরআনে কীভাবে এসেছে তা নিয়ে চিন্তা করুন।',
    echoPayload: {
      surahNumber: 105,
      ayahNumber: 1,
      surahNameAr: 'الفِيل',
      surahNameEn: 'Al-Fil',
      arabicText: 'أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ',
      translationEn: 'Have you not seen how your Lord dealt with the companions of the elephant?',
      translationBn: 'তুমি কি দেখনি তোমার পালনকর্তা হাতির অধিকারীদের সাথে কিরূপ আচরণ করেছিলেন?',
      highlightedWords: ['فَعَلَ'],
      reflection: 'The foundation verb "فَعَلَ" (He did / dealt) that forms the baseline paradigm of Arabic grammar is immortalized in Surah Al-Fil, demonstrating that every verb pattern you learn directly unlocks the words of Allah.',
      audioKey: 'quran_105_1',
      patternNameEn: 'Past Tense 3rd Person Masculine Verb',
      patternNameBn: 'অতীতকালীন নামপুরুষ পুংলিঙ্গ ক্রিয়া (মাযী মা\'রূফ)',
      lessonPatternAr: 'فَعَلَ رَاشِدٌ',
      lessonPatternEn: 'Rashid did / acted',
      lessonPatternBn: 'রাশেদ করল',
      quranPatternAr: 'فَعَلَ رَبُّكَ',
      quranPatternEn: 'Your Lord dealt / did',
      quranPatternBn: 'তোমার রব করলেন',
    },
  },
];

export const VOL2_CH1_LESSON_01_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 1,
  titleEn: 'The Verbal Sentence: Past, Present, Commands & Prohibitions',
  titleAr: 'الجُمْلَةُ الفِعْلِيَّةُ: المَاضِي وَالمُضَارِعُ وَالأَمْرُ وَالنَّهْيُ',
  wordsLearned: [
    'فَعَلَ', 'خَرَجَ', 'ذَهَبَ', 'جَلَسَ', 'قَرَأَ', 'كَتَبَ', 'رَجَعَ', 'لَعِبَ',
    'مِنْ', 'إِلَى', 'عَلَى', 'بِـ', 'ثُمَّ', 'مَلْعَبٌ', 'مَنْزِلٌ',
    'الآنَ', 'اليَوْمَ', 'غَدًا', 'صَبَاحًا', 'مَسَاءً', 'قَبْلَ', 'بَعْدَ', 'مَتَى',
    'حَصِيرٌ', 'مَقْعَدٌ', 'سَبِيلٌ', 'لِـ'
  ],
  steps: VOL2_CH1_LESSON_01_STEPS,
};
