import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_12_STEPS: SessionStep[] = [
  // 1. Page 61-62: Concept Discovery - Incomplete Verbs (الأَفْعَالُ النَّاقِصَةُ)
  {
    id: 'v2-c1-l12-step-1-concept-afal-naqisah',
    type: 'concept_intro',
    pageNumber: 61,
    titleEn: 'The Incomplete Verbs: كَانَ, صَارَ, and لَيْسَ',
    titleAr: 'مَدْخَلُ الأَفْعَالِ النَّاقِصَةِ: كَانَ وَصَارَ وَلَيْسَ',
    instructionEn: 'Observe how these three incomplete verbs govern a nominal sentence: the subject remains nominative (Ism with Dammah), while the predicate becomes accusative (Khabar with Fathah).',
    instructionBn: 'লক্ষ্য করুন কীভাবে এই তিনটি অপূর্ণাঙ্গ ক্রিয়া নামবাচক বাক্যকে প্রভাবিত করে: উদ্দেশ্য পূর্বের মতো পেশযুক্ত (মারফু) থাকে, কিন্তু বিধেয় যবরযুক্ত (মানসুব) হয়ে যায়।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-kana-past',
          ar: 'كَانَ (كَانَ رَاشِدٌ تِلْمِيذًا)',
          romanized: 'kāna (kāna rāshidun tilmīdhan)',
          meaningEn: 'Was: Indicates past continuous state or existence',
          meaningBn: 'ছিল: অতীতকালীন অবস্থা বা অস্তিত্ব প্রকাশ করে',
          exampleAr: 'كَانَ رَاشِدٌ تِلْمِيذًا فِي الصِّغَرِ',
          exampleEn: 'Rashid was a student in childhood.',
          exampleBn: 'রাশেদ শৈশবে একজন ছাত্র ছিল।',
          audioKey: 'كَانَ',
          exampleAudioKey: 'كَانَ رَاشِدٌ تِلْمِيذًا',
          emoji: '⏳',
        },
        {
          id: 'c-sara-transformation',
          ar: 'صَارَ (صَارَ رَاشِدٌ مُعَلِّمًا)',
          romanized: 'ṣāra (ṣāra rāshidun mu‘alliman)',
          meaningEn: 'Became: Indicates transformation or change of state',
          meaningBn: 'হয়ে গেছে: এক অবস্থা থেকে অন্য অবস্থায় রূপান্তর বোঝায়',
          exampleAr: 'صَارَ رَاشِدٌ مُعَلِّمًا مَاهِرًا',
          exampleEn: 'Rashid became a skilled teacher.',
          exampleBn: 'রাশেদ একজন দক্ষ শিক্ষক হয়ে গেছে।',
          audioKey: 'صَارَ',
          exampleAudioKey: 'صَارَ رَاشِدٌ مُعَلِّمًا',
          emoji: '🔄',
        },
        {
          id: 'c-laysa-negation',
          ar: 'لَيْسَ (لَيْسَ رَاشِدٌ تِلْمِيذًا)',
          romanized: 'laysa (laysa rāshidun tilmīdhan)',
          meaningEn: 'Is not: Negates the nominal relationship in the present',
          meaningBn: 'নয়: বর্তমান সময়ে উদ্দেশ্যের সাথে বিধেয়র সম্পর্ক অস্বীকার করে',
          exampleAr: 'لَيْسَ رَاشِدٌ تِلْمِيذًا الآنَ',
          exampleEn: 'Rashid is not a student now.',
          exampleBn: 'রাশেদ এখন ছাত্র নয়।',
          audioKey: 'لَيْسَ',
          exampleAudioKey: 'لَيْسَ رَاشِدٌ تِلْمِيذًا',
          emoji: '❌',
        },
      ],
    },
  },

  // 2. Page 61: Sarf Verb Explorer - Conjugation Paradigms for كَانَ, صَارَ, and لَيْسَ
  {
    id: 'v2-c1-l12-step-2-conjugator-paradigms',
    type: 'verb_conjugator',
    pageNumber: 61,
    titleEn: 'Verb Conjugator: Paradigms of Incomplete Verbs',
    titleAr: 'تَصْرِيفُ الأَفْعَالِ النَّاقِصَةِ: المَاضِي وَالنَّفْي',
    instructionEn: 'Explore the 5 essential singular conjugations for كَانَ (was), صَارَ (became), and لَيْسَ (is not). Notice the stem shortening when pronoun suffixes attach.',
    instructionBn: 'كَانَ (ছিল), صَارَ (হয়ে গেছে) এবং لَيْسَ (নয়) এর পাঁচটি প্রধান একবচন রূপ অধ্যয়ন করুন। সর্বনাম যুক্ত হলে মূল শব্দের সংক্ষিপ্ত রূপ লক্ষ্য করুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'past',
      verbs: [
        {
          id: 'v-kana',
          rootAr: 'ك-و-ن',
          masdarAr: 'الكَوْنُ',
          meaningEn: 'To be / was',
          meaningBn: 'হওয়া / ছিল',
          baabAr: 'بَابُ نَصَرَ',
          emoji: '⏳',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'كَانَ',
              pastMeaningEn: 'He was',
              pastMeaningBn: 'সে ছিল',
              presentAr: 'يَكُونُ',
              presentMeaningEn: 'He is / will be',
              presentMeaningBn: 'সে হবে / থাকে',
              audioKey: 'كَانَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'كَانَتْ',
              pastMeaningEn: 'She was',
              pastMeaningBn: 'সে ছিল',
              presentAr: 'تَكُونُ',
              presentMeaningEn: 'She is / will be',
              presentMeaningBn: 'সে হবে / থাকে',
              audioKey: 'كَانَتْ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'كُنْتَ',
              pastMeaningEn: 'You were',
              pastMeaningBn: 'তুমি ছিলে',
              presentAr: 'تَكُونُ',
              presentMeaningEn: 'You are / will be',
              presentMeaningBn: 'তুমি হবে / থাকো',
              audioKey: 'كُنْتَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'كُنْتِ',
              pastMeaningEn: 'You were',
              pastMeaningBn: 'তুমি ছিলে',
              presentAr: 'تَكُونِينَ',
              presentMeaningEn: 'You are / will be',
              presentMeaningBn: 'তুমি হবে / থাকো',
              audioKey: 'كُنْتِ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'كُنْتُ',
              pastMeaningEn: 'I was',
              pastMeaningBn: 'আমি ছিলাম',
              presentAr: 'أَكُونُ',
              presentMeaningEn: 'I am / will be',
              presentMeaningBn: 'আমি হব / থাকি',
              audioKey: 'كُنْتُ',
            },
          ],
        },
        {
          id: 'v-sara',
          rootAr: 'ص-ي-ر',
          masdarAr: 'الصَّيْرُورَةُ',
          meaningEn: 'To become',
          meaningBn: 'হয়ে যাওয়া',
          baabAr: 'بَابُ ضَرَبَ',
          emoji: '🔄',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'صَارَ',
              pastMeaningEn: 'He became',
              pastMeaningBn: 'সে হয়ে গেছে',
              presentAr: 'يَصِيرُ',
              presentMeaningEn: 'He becomes',
              presentMeaningBn: 'সে হয়ে যায়',
              audioKey: 'صَارَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'صَارَتْ',
              pastMeaningEn: 'She became',
              pastMeaningBn: 'সে হয়ে গেছে',
              presentAr: 'تَصِيرُ',
              presentMeaningEn: 'She becomes',
              presentMeaningBn: 'সে হয়ে যায়',
              audioKey: 'صَارَتْ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'صِرْتَ',
              pastMeaningEn: 'You became',
              pastMeaningBn: 'তুমি হয়ে গেছ',
              presentAr: 'تَصِيرُ',
              presentMeaningEn: 'You become',
              presentMeaningBn: 'তুমি হয়ে যাও',
              audioKey: 'صِرْتَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'صِرْتِ',
              pastMeaningEn: 'You became',
              pastMeaningBn: 'তুমি হয়ে গেছ',
              presentAr: 'تَصِيرِينَ',
              presentMeaningEn: 'You become',
              presentMeaningBn: 'তুমি হয়ে যাও',
              audioKey: 'صِرْتِ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'صِرْتُ',
              pastMeaningEn: 'I became',
              pastMeaningBn: 'আমি হয়ে গেছি',
              presentAr: 'أَصِيرُ',
              presentMeaningEn: 'I become',
              presentMeaningBn: 'আমি হয়ে যাই',
              audioKey: 'صِرْتُ',
            },
          ],
        },
        {
          id: 'v-laysa',
          rootAr: 'ل-ي-س',
          masdarAr: 'فِعْلٌ جَامِدٌ',
          meaningEn: 'To not be (is not)',
          meaningBn: 'না হওয়া (নয়)',
          baabAr: 'فِعْلٌ نَاقِصٌ جَامِدٌ',
          emoji: '❌',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'لَيْسَ',
              pastMeaningEn: 'He is not',
              pastMeaningBn: 'সে নয়',
              presentAr: 'لَيْسَ',
              presentMeaningEn: 'He is not',
              presentMeaningBn: 'সে নয়',
              audioKey: 'لَيْسَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'لَيْسَتْ',
              pastMeaningEn: 'She is not',
              pastMeaningBn: 'সে নয়',
              presentAr: 'لَيْسَتْ',
              presentMeaningEn: 'She is not',
              presentMeaningBn: 'সে নয়',
              audioKey: 'لَيْسَتْ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'لَسْتَ',
              pastMeaningEn: 'You are not',
              pastMeaningBn: 'তুমি নও',
              presentAr: 'لَسْتَ',
              presentMeaningEn: 'You are not',
              presentMeaningBn: 'তুমি নও',
              audioKey: 'لَسْتَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'لَسْتِ',
              pastMeaningEn: 'You are not',
              pastMeaningBn: 'তুমি নও',
              presentAr: 'لَسْتِ',
              presentMeaningEn: 'You are not',
              presentMeaningBn: 'তুমি নও',
              audioKey: 'لَسْتِ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'لَسْتُ',
              pastMeaningEn: 'I am not',
              pastMeaningBn: 'আমি নই',
              presentAr: 'لَسْتُ',
              presentMeaningEn: 'I am not',
              presentMeaningBn: 'আমি নই',
              audioKey: 'لَسْتُ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 61-62: Arabic Word Construction Pedagogy
  {
    id: 'v2-c1-l12-step-3-word-construction',
    type: 'word_construction',
    pageNumber: 61,
    titleEn: 'Word Construction: Suffix Fusion & Emphatic Predicates',
    titleAr: 'بِنَاءُ الكَلِمَةِ: تَصْرِيفُ الأَفْعَالِ النَّاقِصَةِ وَخَبَرِ لَيْسَ',
    instructionEn: 'Construct the conjugated forms of incomplete verbs and the emphatic prepositional predicate by selecting the exact letter and morpheme chips.',
    instructionBn: 'সঠিক বর্ণ ও হরকতযুক্ত চিপ নির্বাচন করে অপূর্ণাঙ্গ ক্রিয়ার সর্বনামযুক্ত রূপ এবং দৃঢ়তাবোধক বিধেয় গঠন করুন।',
    itemId: 'v2_l12_word_construction_afal',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-kunta',
          sourceWordAr: 'أَنْتَ + كَانَ',
          sourceWordLabelEn: '2nd Person Masc Suffix',
          sourceWordLabelBn: '২য় পুরুষ পুংলিঙ্গ সর্বনাম',
          targetWordAr: 'كُنْتَ',
          promptEn: 'Construct: "You were (m)" (Notice the short vowel u on kaf and sukun on nun)',
          promptBn: 'গঠন করুন: "তুমি ছিলে (পুং)" (কাফে পেশ ও নূনে সাকিন লক্ষ্য করুন)',
          targetMeaningEn: 'You were (m)',
          targetMeaningBn: 'তুমি ছিলে (পুং)',
          chips: ['كُ', 'نْ', 'تَ', 'تِ', 'تُ', 'كَ'],
          emoji: '⏳',
        },
        {
          id: 'wc-sirtu',
          sourceWordAr: 'أَنَا + صَارَ',
          sourceWordLabelEn: '1st Person Singular Suffix',
          sourceWordLabelBn: '১ম পুরুষ একবচন সর্বনাম',
          targetWordAr: 'صِرْتُ',
          promptEn: 'Construct: "I became" (Notice the kasrah on sad and sukun on ra)',
          promptBn: 'গঠন করুন: "আমি হয়ে গেছি" (সোয়াদে যের ও র-তে সাকিন লক্ষ্য করুন)',
          targetMeaningEn: 'I became',
          targetMeaningBn: 'আমি হয়ে গেছি',
          chips: ['صِ', 'رْ', 'تُ', 'تَ', 'تِ', 'صَ'],
          emoji: '🔄',
        },
        {
          id: 'wc-lasti',
          sourceWordAr: 'أَنْتِ + لَيْسَ',
          sourceWordLabelEn: '2nd Person Fem Suffix',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ সর্বনাম',
          targetWordAr: 'لَسْتِ',
          promptEn: 'Construct: "You are not (f)" (Notice the fathah on lam and sukun on seen)',
          promptBn: 'গঠন করুন: "তুমি নও (স্ত্রী)" (লামে যবর ও সীনে সাকিন লক্ষ্য করুন)',
          targetMeaningEn: 'You are not (f)',
          targetMeaningBn: 'তুমি নও (স্ত্রী)',
          chips: ['لَ', 'سْ', 'تِ', 'تَ', 'تُ', 'لَيْ'],
          emoji: '❌',
        },
        {
          id: 'wc-bikadhibin',
          sourceWordAr: 'بِـ + كَاذِبٌ',
          sourceWordLabelEn: 'Emphatic Predicate Construct',
          sourceWordLabelBn: 'তাকীদযুক্ত বিধেয়র রূপ',
          targetWordAr: 'بِكَاذِبٍ',
          promptEn: 'Construct: "At all a liar" (Emphatic Ba followed by genitive tanween)',
          promptBn: 'গঠন করুন: "কখনোই মিথ্যাবাদী নয়" (তাকীদের বা এবং দুই যেরযুক্ত রূপ)',
          targetMeaningEn: 'At all a liar',
          targetMeaningBn: 'মোটেই মিথ্যাবাদী (নয়)',
          chips: ['بِ', 'كَ', 'ا', 'ذِ', 'بٍ', 'بًا', 'بٌ'],
          emoji: '🛡️',
        },
      ],
    },
  },

  // 4. Page 61-62: Vocabulary Priming
  {
    id: 'v2-c1-l12-step-4-vocab-prime',
    type: 'vocab_prime',
    pageNumber: 61,
    titleEn: 'Vocabulary Priming: States, Occupations & Qualities',
    titleAr: 'تَقْدِيمُ المُفْرَدَاتِ: المِهَنُ وَالصِّفَاتُ وَالأَحْوَالُ',
    instructionEn: 'Familiarize yourself with the core nouns and descriptive adjectives introduced in Lesson 12 that undergo case transformations.',
    instructionBn: '১২শ পাঠে উল্লেখিত গুরুত্বপূর্ণ পেশা ও গুণবাচক শব্দগুলোর সাথে পরিচিত হোন, যেগুলোর শেষ অক্ষরে ব্যাকরণগত পরিবর্তন ঘটে।',
    itemId: 'v2_l12_vocab_prime_nouns',
    vocabPayload: {
      words: [
        {
          id: 'w-fallahun',
          ar: 'فَلَّاحٌ',
          en: 'Farmer',
          bn: 'কৃষক',
          romanized: 'fallāḥun',
          emoji: '🌾',
        },
        {
          id: 'w-tajirun',
          ar: 'تَاجِرٌ',
          en: 'Merchant / Trader',
          bn: 'ব্যবসায়ী',
          romanized: 'tājirun',
          emoji: '💼',
        },
        {
          id: 'w-ghaniyyun',
          ar: 'غَنِيٌّ',
          en: 'Wealthy / Rich',
          bn: 'ধনী',
          romanized: 'ghaniyyun',
          emoji: '💰',
        },
        {
          id: 'w-faqirun',
          ar: 'فَقِيرٌ',
          en: 'Poor / Needy',
          bn: 'দরিদ্র',
          romanized: 'faqīrun',
          emoji: '🤲',
        },
        {
          id: 'w-maftuhun',
          ar: 'مَفْتُوحٌ',
          en: 'Open / Unlocked',
          bn: 'উন্মুক্ত / খোলা',
          romanized: 'maftūḥun',
          emoji: '🚪',
        },
        {
          id: 'w-mughlaqun',
          ar: 'مُغْلَقٌ',
          en: 'Closed / Locked',
          bn: 'বন্ধ / রুদ্ধ',
          romanized: 'mughlaqun',
          emoji: '🔒',
        },
      ],
    },
  },

  // 5. Page 62: Speed Pair - Opposite States & Qualities
  {
    id: 'v2-c1-l12-step-5-speed-pair-opposites',
    type: 'speed_pair',
    pageNumber: 62,
    titleEn: 'Speed Pair: Contrasting States & Antonyms',
    titleAr: 'المُطَابَقَةُ السَّرِيعَةُ: الأَضْدَادُ وَالصِّفَاتُ المُتَقَابِلَةُ',
    instructionEn: 'Match each Arabic attribute with its contrasting English meaning as taught across the lesson examples.',
    instructionBn: 'পাঠে ব্যবহৃত বিপরীতার্থক গুণ ও অবস্থার আরবি শব্দের সাথে সঠিক অর্থের মিল করুন।',
    itemId: 'v2_l12_speed_pair_antonyms',
    pairPayload: {
      pairs: [
        { id: 'p-ghani-faqir', ar: 'غَنِيٌّ', meaning: 'Wealthy / Rich', meaningBn: 'ধনী' },
        { id: 'p-maftuh-mughlaq', ar: 'مَفْتُوحٌ', meaning: 'Open', meaningBn: 'উন্মুক্ত / খোলা' },
        { id: 'p-salih-fasiq', ar: 'صَالِحٌ', meaning: 'Righteous', meaningBn: 'নেককার / সৎকর্মশীল' },
        { id: 'p-nashita-kaslana', ar: 'نَشِيطَةٌ', meaning: 'Energetic (f)', meaningBn: 'উদ্যমী (স্ত্রী)' },
        { id: 'p-dhaki-ghabi', ar: 'ذَكِيٌّ', meaning: 'Intelligent', meaningBn: 'বুদ্ধিমান' },
        { id: 'p-sadiq-kadhib', ar: 'صَادِقٌ', meaning: 'Truthful', meaningBn: 'সত্যবাদী' },
      ],
    },
  },

  // 6. Page 61: Sentence Assembly - External Agent with كَانَ
  {
    id: 'v2-c1-l12-step-6-assembly-kana-rashid',
    type: 'sentence_assembly',
    pageNumber: 61,
    titleEn: 'Sentence Assembly: The Student of the Past',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: كَانَ رَاشِدٌ تِلْمِيذًا',
    instructionEn: 'Assemble the sentence meaning "Rashid was a student". Notice that the subject (Rashid) has dammahtayn and the predicate has fathatayn.',
    instructionBn: '"রাশেদ একজন ছাত্র ছিল" বাক্যটি গঠন করুন। লক্ষ্য করুন যে রাশেদ শব্দে দুই পেশ এবং তিলমীযান শব্দে দুই যবর বসবে।',
    itemId: 'v2_l12_assembly_kana_rashid',
    assemblyPayload: {
      promptEn: 'Assemble: "Rashid was a student"',
      promptBn: 'গঠন করুন: "রাশেদ একজন ছাত্র ছিল"',
      expectedAnswer: ['كَانَ', 'رَاشِدٌ', 'تِلْمِيذًا'],
      chips: ['كَانَ', 'رَاشِدٌ', 'تِلْمِيذًا', 'تِلْمِيذٌ', 'صَارَ'],
      emoji: '👨‍🎓',
    },
  },

  // 7. Page 61: Polar Sort - Case Governor Discrimination (Marfoo' Ism vs Mansoob Khabar)
  {
    id: 'v2-c1-l12-step-7-polar-sort-cases',
    type: 'polar_sort',
    pageNumber: 61,
    titleEn: 'Case Discrimination: Accusative Khabar vs Nominative Ism',
    titleAr: 'تَمْيِيزُ الإِعْرَابِ: خَبَرُ كَانَ المَنْصُوبُ أَمِ اسْمُهَا المَرْفُوعُ',
    instructionEn: 'Identify the role and case of the highlighted word "تِلْمِيذًا" in the sentence "كَانَ رَاشِدٌ تِلْمِيذًا".',
    instructionBn: '"كَانَ رَاشِدٌ تِلْمِيذًا" বাক্যে "تِلْمِيذًا" শব্দটির পদ ও ব্যাকরণগত অবস্থা নির্ণয় করুন।',
    itemId: 'v2_l12_polar_sort_cases',
    polarPayload: {
      arabicSubject: 'تِلْمِيذًا (فِي: كَانَ رَاشِدٌ تِلْمِيذًا)',
      meaningEn: 'A student (accusative predicate with fathatayn)',
      meaningBn: 'একজন ছাত্র (দুই যবরযুক্ত মানসুব খবর)',
      correctAnswer: 'خَبَرُ كَانَ مَنْصُوبٌ (Accusative Predicate)',
      options: [
        'خَبَرُ كَانَ مَنْصُوبٌ (Accusative Predicate)',
        'اسْمُ كَانَ مَرْفُوعٌ (Nominative Subject)',
      ],
      emoji: '⚖️',
    },
  },

  // 8. Page 61: Sentence Assembly - Internal Pronoun with كُنْتَ
  {
    id: 'v2-c1-l12-step-8-assembly-kunta-rajulan',
    type: 'sentence_assembly',
    pageNumber: 61,
    titleEn: 'Sentence Assembly: You Were a Poor Man',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: كُنْتَ رَجُلًا فَقِيرًا',
    instructionEn: 'Assemble the sentence meaning "You were a poor man". Notice the embedded subject pronoun (-ta) and the two accusative nouns.',
    instructionBn: '"তুমি একজন দরিদ্র মানুষ ছিলে" বাক্যটি গঠন করুন। অন্তর্ভুক্ত সর্বনাম (-তা) এবং দুই যবরযুক্ত মাউসুফ-সিফাত লক্ষ্য করুন।',
    itemId: 'v2_l12_assembly_kunta_rajulan',
    assemblyPayload: {
      promptEn: 'Assemble: "You were a poor man"',
      promptBn: 'গঠন করুন: "তুমি একজন দরিদ্র মানুষ ছিলে"',
      expectedAnswer: ['كُنْتَ', 'رَجُلًا', 'فَقِيرًا'],
      chips: ['كُنْتَ', 'رَجُلًا', 'فَقِيرًا', 'رَجُلٌ', 'فَقِيرٌ', 'صِرْتَ'],
      emoji: '👤',
    },
  },

  // 9. Page 61: Alternative QA - Incomplete Verb Transformations
  {
    id: 'v2-c1-l12-step-9-qa-transformations',
    type: 'alternative_qa',
    pageNumber: 61,
    titleEn: 'Transformations: From Nominal Sentence to Incomplete Verb',
    titleAr: 'التَّحْوِيلَاتُ اللُّغَوِيَّةُ: مِنَ الجُمْلَةِ الاسْمِيَّةِ إِلَى كَانَ وَأَخَوَاتِهَا',
    instructionEn: 'Select the grammatically correct transformation for each nominal sentence into the required incomplete verb form.',
    instructionBn: 'প্রদত্ত নামবাচক বাক্যগুলোকে অপূর্ণাঙ্গ ক্রিয়ার মাধ্যমে রূপান্তরের সঠিক বিকল্পটি বেছে নিন।',
    itemId: 'v2_l12_qa_transformations',
    alternativeQAPayload: {
      contextAr: 'تَحْوِيلُ المُبْتَدَأِ وَالخَبَرِ بِدُخُولِ كَانَ وَصَارَ وَلَيْسَ',
      questions: [
        {
          id: 'q-trans-1',
          questionAr: 'كَيْفَ تُحَوِّلُ (أَنْتَ رَجُلٌ فَقِيرٌ) مَعَ فِعْلِ التَّحَوُّلِ (صَارَ) لِتَدُلَّ عَلَى الغِنَى؟',
          optionsAr: [
            'صِرْتَ رَجُلًا غَنِيًّا',
            'صَارَ أَنْتَ رَجُلٌ غَنِيٌّ',
            'صِرْتَ رَجُلٌ غَنِيٌّ',
          ],
          correctAnswerAr: 'صِرْتَ رَجُلًا غَنِيًّا',
        },
        {
          id: 'q-trans-2',
          questionAr: 'كَيْفَ تُدْخِلُ (كَانَتْ) عَلَى الجُمْلَةِ الاسْمِيَّةِ: (فَاطِمَةُ صَغِيرَةٌ)؟',
          optionsAr: [
            'كَانَتْ فَاطِمَةُ صَغِيرَةً',
            'كَانَ فَاطِمَةُ صَغِيرَةً',
            'كَانَتْ فَاطِمَةُ صَغِيرَةٌ',
          ],
          correctAnswerAr: 'كَانَتْ فَاطِمَةُ صَغِيرَةً',
        },
        {
          id: 'q-trans-3',
          questionAr: 'كَيْفَ تَنْفِي جُمْلَةَ (أَنَا فَلَّاحٌ) بِاسْتِخْدَامِ (لَيْسَ)؟',
          optionsAr: [
            'لَسْتُ فَلَّاحًا',
            'لَيْسَ أَنَا فَلَّاحًا',
            'لَسْتَ فَلَّاحًا',
          ],
          correctAnswerAr: 'لَسْتُ فَلَّاحًا',
        },
      ],
    },
  },

  // 10. Page 62: Cloze Choice - Feminine Accusative Predicate
  {
    id: 'v2-c1-l12-step-10-cloze-madrasah',
    type: 'cloze_choice',
    pageNumber: 62,
    titleEn: 'Cloze Choice: Case Harmony in Historical Progression',
    titleAr: 'اخْتِيَارُ التَّتْمِيمِ: حَرَكَةُ خَبَرِ كَانَتْ فِي التَّارِيخِ المَدْرَسِيِّ',
    instructionEn: 'Select the correctly vowelled predicate to complete the statement: "The school was small, then it became big."',
    instructionBn: '"মাদরাসাটি ছোট ছিল, অতঃপর তা বড় হয়ে গেছে" বাক্যটি সম্পূর্ণ করতে সঠিক হরকতযুক্ত খবরটি নির্বাচন করুন।',
    itemId: 'v2_l12_cloze_madrasah',
    clozePayload: {
      questionAr: 'كَانَتِ المَدْرَسَةُ ... صَارَتْ كَبِيرَةً',
      questionEn: 'The school was ..., then it became big.',
      questionBn: 'মাদরাসাটি ... ছিল, অতঃপর বড় হয়ে গেছে।',
      partialAnswerAr: 'كَانَتِ المَدْرَسَةُ ... صَارَتْ كَبِيرَةً',
      correctAnswer: 'صَغِيرَةً',
      options: ['صَغِيرَةً', 'صَغِيرَةٌ', 'صَغِيرَةٍ'],
      emoji: '🏫',
    },
  },

  // 11. Page 62: Concept Discovery - Emphatic Negation with بِـ in Khabar Laysa
  {
    id: 'v2-c1-l12-step-11-concept-ba-laysa',
    type: 'concept_intro',
    pageNumber: 62,
    titleEn: 'Emphatic Negation: The Prepositional Predicate of لَيْسَ',
    titleAr: 'مَدْخَلُ تَأْكِيدِ النَّفْيِ: دُخُولُ البَاءِ الزَّائِدَةِ عَلَى خَبَرِ لَيْسَ',
    instructionEn: 'Study how the particle "بِـ" attaches to the predicate of "لَيْسَ" to produce categorical, emphatic negation. The noun takes kasrah in form (lafzan) while remaining accusative in position (mahlan).',
    instructionBn: 'লক্ষ্য করুন কীভাবে "لَيْسَ" এর বিধেয়ে "بِـ" যুক্ত হয়ে দৃঢ় ও সুস্পষ্ট না-বোধক অর্থ প্রকাশ করে। শব্দটি উচ্চারণে যেরযুক্ত (মাজরুর লাফযান) হলেও ব্যাকরণগত অবস্থানে যবরযুক্ত (মানসুব মাহলান) থাকে।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-laysa-plain',
          ar: 'لَيْسَ رَاشِدٌ كَاذِبًا (نَفْيٌ مُجَرَّدٌ)',
          romanized: 'laysa rāshidun kādhiban',
          meaningEn: 'Plain Negation: Rashid is not a liar',
          meaningBn: 'সাধারণ না-বোধক: রাশেদ মিথ্যাবাদী নয়',
          exampleAr: 'لَيْسَ رَاشِدٌ كَاذِبًا فِي حَدِيثِهِ',
          exampleEn: 'Rashid is not a liar in his speech.',
          exampleBn: 'রাশেদ তার কথায় মিথ্যাবাদী নয়।',
          audioKey: 'لَيْسَ رَاشِدٌ كَاذِبًا',
          exampleAudioKey: 'لَيْسَ رَاشِدٌ كَاذِبًا فِي حَدِيثِهِ',
          emoji: '💬',
        },
        {
          id: 'c-laysa-emphatic',
          ar: 'لَيْسَ رَاشِدٌ بِكَاذِبٍ (نَفْيٌ مُؤَكَّدٌ بِالبَاءِ)',
          romanized: 'laysa rāshidun bikādhibin',
          meaningEn: 'Emphatic Negation: Rashid is not at all a liar',
          meaningBn: 'তাকীদযুক্ত না-বোধক: রাশেদ মোটেই মিথ্যাবাদী নয়',
          exampleAr: 'لَيْسَ رَاشِدٌ بِكَاذِبٍ أَبَدًا',
          exampleEn: 'Rashid is not at all a liar, ever.',
          exampleBn: 'রাশেদ কখনোই কোনো মিথ্যাবাদী নয়।',
          audioKey: 'لَيْسَ رَاشِدٌ بِكَاذِبٍ',
          exampleAudioKey: 'لَيْسَ رَاشِدٌ بِكَاذِبٍ أَبَدًا',
          emoji: '🛡️',
        },
      ],
    },
  },

  // 12. Page 62: Sentence Assembly - Emphatic Negation with بِكَاذِبٍ
  {
    id: 'v2-c1-l12-step-12-assembly-bikadhibin',
    type: 'sentence_assembly',
    pageNumber: 62,
    titleEn: 'Sentence Assembly: Emphatic Negation',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: لَيْسَ رَاشِدٌ بِكَاذِبٍ',
    instructionEn: 'Assemble the emphatic negative sentence meaning "Rashid is not at all a liar".',
    instructionBn: '"রাশেদ মোটেই মিথ্যাবাদী নয়" বাক্যটি তাকীদযুক্ত গঠন অনুযায়ী সাজান।',
    itemId: 'v2_l12_assembly_bikadhibin',
    assemblyPayload: {
      promptEn: 'Assemble: "Rashid is not at all a liar"',
      promptBn: 'গঠন করুন: "রাশেদ মোটেই মিথ্যাবাদী নয়"',
      expectedAnswer: ['لَيْسَ', 'رَاشِدٌ', 'بِكَاذِبٍ'],
      chips: ['لَيْسَ', 'رَاشِدٌ', 'بِكَاذِبٍ', 'كَاذِبًا', 'بِكَاذِبًا'],
      emoji: '⚖️',
    },
  },

  // 13. Page 62: Alternative QA - Emphatic vs Plain Negation Drill
  {
    id: 'v2-c1-l12-step-13-qa-emphatic-negation',
    type: 'alternative_qa',
    pageNumber: 62,
    titleEn: 'Alternative QA: Formulating Categorical Negation',
    titleAr: 'الاسْتِفْهَامُ التَّطْبِيقِيُّ: صِيَغُ النَّفْيِ المُؤَكَّدِ بِالبَاءِ',
    instructionEn: 'Choose the grammatically accurate emphatic form for each statement using the extra particle "بِـ".',
    instructionBn: '"بِـ" অব্যয় ব্যবহার করে প্রতিটি বাক্যের সঠিক তাকীদযুক্ত না-বোধক রূপ নির্বাচন করুন।',
    itemId: 'v2_l12_qa_emphatic_negation',
    alternativeQAPayload: {
      contextAr: 'تَأْكِيدُ نَفْيِ خَبَرِ لَيْسَ بِدُخُولِ حَرْفِ البَاءِ الزَّائِدَةِ',
      questions: [
        {
          id: 'q-emph-1',
          questionAr: 'كَيْفَ تَنْفِي جُمْلَةَ (أَنْتَ صَادِقٌ) نَفْيًا مُؤَكَّدًا؟',
          optionsAr: [
            'لَسْتَ بِصَادِقٍ',
            'لَسْتَ بِصَادِقًا',
            'لَيْسَ أَنْتَ صَادِقٌ',
          ],
          correctAnswerAr: 'لَسْتَ بِصَادِقٍ',
        },
        {
          id: 'q-emph-2',
          questionAr: 'كَيْفَ تَنْفِي عَنْ نَفْسِكَ النِّفَاقَ نَفْيًا مُؤَكَّدًا؟',
          optionsAr: [
            'لَسْتُ بِمُنَافِقٍ',
            'لَسْتَ بِمُنَافِقٍ',
            'لَسْتُ مُنَافِقٌ',
          ],
          correctAnswerAr: 'لَسْتُ بِمُنَافِقٍ',
        },
        {
          id: 'q-emph-3',
          questionAr: 'كَيْفَ تَنْفِي سِعَةَ الحُجْرَةِ نَفْيًا مُؤَكَّدًا؟',
          optionsAr: [
            'لَيْسَتِ الحُجْرَةُ بِوَاسِعَةٍ',
            'لَيْسَ الحُجْرَةُ بِوَاسِعَةٍ',
            'لَيْسَتِ الحُجْرَةُ بِوَاسِعَةً',
          ],
          correctAnswerAr: 'لَيْسَتِ الحُجْرَةُ بِوَاسِعَةٍ',
        },
      ],
    },
  },

  // 14. Page 62: Tarkib Dissector - Syntactic Tree of كَانَ البَابُ مَفْتُوحًا
  {
    id: 'v2-c1-l12-step-14-tarkib-kana-bab',
    type: 'tarkib_dissector',
    pageNumber: 62,
    titleEn: 'Syntactic Dissector: The Open Door of the Past',
    titleAr: 'التَّشْرِيحُ التَّرْكِيبِيُّ: كَانَ البَابُ مَفْتُوحًا',
    instructionEn: 'Slot each word of the sentence "كَانَ البَابُ مَفْتُوحًا" into its exact grammatical role in the incomplete verb equation.',
    instructionBn: '"كَانَ البَابُ مَفْتُوحًا" বাক্যের প্রতিটি শব্দকে তার সঠিক ব্যাকরণগত পদে স্থাপন করুন।',
    itemId: 'v2_l12_tarkib_kana_bab',
    tarkibPayload: {
      sentences: [
        {
          id: 's-kana-bab',
          sentenceAr: 'كَانَ البَابُ مَفْتُوحًا',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ نَاقِصَةٌ',
          sentenceTypeEn: 'Incomplete Verbal Sentence (Kāna & governed nouns)',
          sentenceTypeBn: 'অপূর্ণাঙ্গ ক্রিয়াবাচক বাক্য (কান ও তার ইসমে-খবর)',
          slots: [
            {
              roleAr: 'فِعْلٌ مَاضٍ نَاقِصٌ',
              roleEn: 'Incomplete Past Verb',
              roleBn: 'অতীতকালীন অপূর্ণাঙ্গ ক্রিয়া',
              expectedWordAr: 'كَانَ',
            },
            {
              roleAr: 'اسْمُ كَانَ مَرْفُوعٌ',
              roleEn: 'Nominative Subject (Ism Kana)',
              roleBn: 'কান-এর পেশযুক্ত কর্তা (ইসমে কান)',
              expectedWordAr: 'البَابُ',
            },
            {
              roleAr: 'خَبَرُ كَانَ مَنْصُوبٌ',
              roleEn: 'Accusative Predicate (Khabar Kana)',
              roleBn: 'কান-এর যবরযুক্ত বিধেয় (খবরে কান)',
              expectedWordAr: 'مَفْتُوحًا',
            },
          ],
          availableWordsAr: ['كَانَ', 'البَابُ', 'مَفْتُوحًا', 'البَابَ', 'مَفْتُوحٌ'],
        },
      ],
    },
  },

  // 15. Page 62: Tarkib Dissector - Syntactic Tree of Emphatic Negation (لَيْسَ رَاشِدٌ بِكَاذِبٍ)
  {
    id: 'v2-c1-l12-step-15-tarkib-laysa-bikadhib',
    type: 'tarkib_dissector',
    pageNumber: 62,
    titleEn: 'Syntactic Dissector: Emphatic Negative Construction',
    titleAr: 'التَّشْرِيحُ التَّرْكِيبِيُّ: لَيْسَ رَاشِدٌ بِكَاذِبٍ',
    instructionEn: 'Dissect the structure of emphatic negation: identify the negative verb, the nominative subject, and the preposition-augmented predicate.',
    instructionBn: 'তাকীদযুক্ত না-বোধক বাক্যের গঠন বিশ্লেষণ করুন: না-বোধক ক্রিয়া, পেশযুক্ত ইসমে লাইসা এবং বা-যুক্ত বিধেয় চিহ্নিত করুন।',
    itemId: 'v2_l12_tarkib_laysa_bikadhib',
    tarkibPayload: {
      sentences: [
        {
          id: 's-laysa-bikadhib',
          sentenceAr: 'لَيْسَ رَاشِدٌ بِكَاذِبٍ',
          sentenceTypeAr: 'جُمْلَةٌ نَافِيَةٌ بِلَيْسَ مَعَ البَاءِ الزَّائِدَةِ',
          sentenceTypeEn: 'Negative Sentence with Laysa & Emphatic Ba',
          sentenceTypeBn: 'লাইসা ও অতিরিক্ত বা সহ না-বোধক বাক্য',
          slots: [
            {
              roleAr: 'فِعْلٌ نَاقِصٌ لِلنَّفْيِ',
              roleEn: 'Incomplete Negative Verb',
              roleBn: 'না-বোধক অপূর্ণাঙ্গ ক্রিয়া',
              expectedWordAr: 'لَيْسَ',
            },
            {
              roleAr: 'اسْمُ لَيْسَ مَرْفُوعٌ',
              roleEn: 'Nominative Subject (Ism Laysa)',
              roleBn: 'লাইসার পেশযুক্ত কর্তা (ইসমে লাইসা)',
              expectedWordAr: 'رَاشِدٌ',
            },
            {
              roleAr: 'خَبَرُ لَيْسَ (مَجْرُورٌ لَفْظًا مَنْصُوبٌ مَحَلًّا)',
              roleEn: 'Emphatic Predicate (Genitive in form, Accusative in position)',
              roleBn: 'লাইসার বিধেয় (উচ্চারণে যেরযুক্ত, স্থানে যবরযুক্ত)',
              expectedWordAr: 'بِكَاذِبٍ',
            },
          ],
          availableWordsAr: ['لَيْسَ', 'رَاشِدٌ', 'بِكَاذِبٍ', 'كَاذِبًا', 'رَاشِدًا'],
        },
      ],
    },
  },

  // 16. Page 62: Cloze Choice - State Transformation (صِرْتُ ذَكِيًّا)
  {
    id: 'v2-c1-l12-step-16-cloze-dhakiyyan',
    type: 'cloze_choice',
    pageNumber: 62,
    titleEn: 'Cloze Choice: Personal Intellectual Transformation',
    titleAr: 'اخْتِيَارُ التَّتْمِيمِ: صِرْتُ ذَكِيًّا',
    instructionEn: 'Complete the reflection: "I was dull, then I became intelligent" by choosing the correct accusative ending.',
    instructionBn: '"আমি নির্বোধ ছিলাম, অতঃপর বুদ্ধিমান হয়ে গেছি" বাক্যটি সম্পূর্ণ করতে সঠিক যবরযুক্ত পদটি বেছে নিন।',
    itemId: 'v2_l12_cloze_dhakiyyan',
    clozePayload: {
      questionAr: 'كُنْتُ غَبِيًّا فَصِرْتُ ...',
      questionEn: 'I was dull, then I became ...',
      questionBn: 'আমি নির্বোধ ছিলাম, অতঃপর ... হয়ে গেছি।',
      partialAnswerAr: 'كُنْتُ غَبِيًّا فَصِرْتُ ...',
      correctAnswer: 'ذَكِيًّا',
      options: ['ذَكِيًّا', 'ذَكِيٌّ', 'ذَكِيٍّ'],
      emoji: '💡',
    },
  },

  // 17. Sacred Milestone: Quranic Echo (Surah At-Tin 95:8)
  {
    id: 'v2-c1-l12-step-17-quranic-echo-tin',
    type: 'quranic_echo',
    pageNumber: 62,
    titleEn: 'Quranic Milestone: The Supreme Judge',
    titleAr: 'صَدَى القُرْآنِ: أَلَيْسَ اللَّهُ بِأَحْكَمِ الحَاكِمِينَ',
    instructionEn: 'Contemplate how the exact pedagogical structure of Lesson 12 - the interrogative prefix, the negative verb "لَيْسَ", and the emphatic prepositional predicate "بِأَحْكَمِ" - culminates in Surah At-Tin (95:8).',
    instructionBn: 'সূরা আত-তীন (৯৫:৮) এ কীভাবে ১২শ পাঠের হুবহু ব্যাকরণিক গঠন - প্রশ্নবোধক হামযা, না-বোধক ক্রিয়া "لَيْسَ" এবং তাকীদের বা-যুক্ত বিধেয় "بِأَحْكَمِ" সন্নিবেশিত হয়েছে তা অনুধাবন করুন।',
    echoPayload: {
      surahNumber: 95,
      ayahNumber: 8,
      surahNameAr: 'التِّين',
      surahNameEn: 'At-Tin',
      arabicText: 'أَلَيْسَ اللَّهُ بِأَحْكَمِ الْحَاكِمِينَ',
      translationEn: 'Is not Allah the most just of judges?',
      translationBn: 'আল্লাহ কি সকল বিচারকের চেয়ে শ্রেষ্ঠ বিচারক নন?',
      highlightedWords: ['أَلَيْسَ', 'اللَّهُ', 'بِأَحْكَمِ', 'الْحَاكِمِينَ'],
      reflection: 'In this profound climax of Surah At-Tin, observe the exact syntactic equation mastered in Lesson 12: the negative incomplete verb "لَيْسَ" is preceded by the interrogative "أَ", followed by its nominative subject "اللَّهُ" (Ism Laysa), and completed by the emphatic prepositional predicate "بِأَحْكَمِ" (Khabar Laysa with Ba Za\'idah, Majroor in form and Mansoob in position). The divine rhetoric delivers an unassailable confirmation of absolute divine justice.',
    },
  },
];

export const VOL2_CH1_LESSON_12_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 12,
  titleEn: 'The Incomplete Verbs: كَانَ, صَارَ, and لَيْسَ',
  titleAr: 'الأَفْعَالُ النَّاقِصَةُ: كَانَ وَصَارَ وَلَيْسَ',
  wordsLearned: [
    'كَانَ', 'صَارَ', 'لَيْسَ', 'فَلَّاحٌ', 'تَاجِرٌ', 'غَنِيٌّ',
    'فَقِيرٌ', 'مَفْتُوحٌ', 'مُغْلَقٌ', 'صَالِحٌ', 'فَاسِقٌ',
    'نَشِيطَةٌ', 'كَسْلَانَةُ', 'ذَكِيٌّ', 'غَبِيٌّ', 'كَاذِبٌ', 'صَادِقٌ'
  ],
  steps: VOL2_CH1_LESSON_12_STEPS,
};
