// Chapter 2 Lesson 8 Interactive Session Steps (Capstone Synthesis: Complex Constructs, Prepositional Badal & Spiritual Contrasts)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH2_LESSON_08_STEPS: SessionStep[] = [
  // 1. Spatial Pointing Anchor: Inherent Feminine Fire
  {
    id: 'ch2-l8-step-1-spatial-fire',
    type: 'spatial_pointing',
    pageNumber: 85,
    titleEn: 'Spatial Anchor: Inherent Feminine Elements',
    titleAr: 'الإِشَارَةُ المَكَانِيَّةُ: مُفْرَدَاتٌ مُؤَنَّثَةٌ سَمَاعًا',
    instructionEn: 'Point to this blazing fire nearby. In Arabic, «نَارٌ» (fire) is treated as grammatically feminine by linguistic convention.',
    instructionBn: 'নিকটের এই আগুনের দিকে ইঙ্গিত করুন। আরবি ভাষায় «نَارٌ» শব্দটি স্বভাবগতভাবেই স্ত্রীলিঙ্গ হিসেবে গণ্য হয়।',
    spatialPointingPayload: {
      objectAr: 'نَارٌ',
      distance: 'near',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ نَارٌ',
      options: ['هَذَا نَارٌ', 'هَذِهِ نَارٌ', 'ذَلِكَ نَارٌ', 'تِلْكَ نَارٌ'],
      emoji: '🔥',
    },
  },

  // 2. Primary Vocabulary Priming: Academic Quarters & Vessels
  {
    id: 'ch2-l8-step-2-vocab-academic',
    type: 'vocab_prime',
    pageNumber: 85,
    titleEn: 'Academic Spaces & Everyday Vessels',
    titleAr: 'مُفْرَدَاتُ الفَصْلِ وَالأَوَانِي',
    instructionEn: 'Listen to classical Arabic terms for classrooms, desks, grades, and drinking vessels.',
    instructionBn: 'শ্রেণিকক্ষ, লেখার টেবিল, শ্রেণি ও পাত্র সম্পর্কিত আরবি শব্দগুলো শুনুন।',
    vocabPayload: {
      words: [
        {
          id: 'c2l8-fasl',
          ar: 'فَصْلٌ',
          en: 'A classroom',
          bn: 'একটি শ্রেণিকক্ষ',
          romanized: 'faṣlun',
          emoji: '🏫',
        },
        {
          id: 'c2l8-saff',
          ar: 'صَفٌّ',
          en: 'A class / grade / row',
          bn: 'একটি শ্রেণী বা সারি',
          romanized: 'ṣaffun',
          emoji: '📋',
        },
        {
          id: 'c2l8-maktab',
          ar: 'مَكْتَبٌ',
          en: 'A desk / office',
          bn: 'একটি লেখার টেবিল বা দপ্তর',
          romanized: 'maktabun',
          emoji: '🗄️',
        },
        {
          id: 'c2l8-kub',
          ar: 'كُوبٌ',
          en: 'A cup / glass tumbler',
          bn: 'একটি গ্লাস বা পেয়ালা',
          romanized: 'kūbun',
          emoji: '🥛',
        },
        {
          id: 'c2l8-laban',
          ar: 'لَبَنٌ',
          en: 'Milk',
          bn: 'দুধ',
          romanized: 'labanun',
          emoji: '🥛',
        },
        {
          id: 'c2l8-ma',
          ar: 'مَاءٌ',
          en: 'Water',
          bn: 'পানি',
          romanized: 'mā’un',
          emoji: '💧',
        },
      ],
    },
  },

  // 3. Secondary Vocabulary Priming: Spiritual & Existential Contrasts
  {
    id: 'ch2-l8-step-3-vocab-spiritual',
    type: 'vocab_prime',
    pageNumber: 86,
    titleEn: 'Spiritual Realities & Existential Realities',
    titleAr: 'مُفْرَدَاتُ الإِيمَانِ وَالمَعْرِفَةِ',
    instructionEn: 'Master vocabulary denoting archetypes of faith, knowledge, and inner spiritual states.',
    instructionBn: 'ঈমান, জ্ঞান ও আত্মিক অবস্থার সাথে সংশ্লিষ্ট মৌলিক পরিভাষাগুলো জানুন।',
    vocabPayload: {
      words: [
        {
          id: 'c2l8-sayf',
          ar: 'سَيْفٌ',
          en: 'A sword',
          bn: 'একটি তরবারি',
          romanized: 'sayfun',
          emoji: '⚔️',
        },
        {
          id: 'c2l8-qalb',
          ar: 'قَلْبٌ',
          en: 'A heart',
          bn: 'একটি অন্তর বা হৃদয়',
          romanized: 'qalbun',
          emoji: '❤️',
        },
        {
          id: 'c2l8-nur',
          ar: 'نُورٌ',
          en: 'Light',
          bn: 'আলো বা নূর',
          romanized: 'nūrun',
          emoji: '✨',
        },
        {
          id: 'c2l8-zulmah',
          ar: 'ظُلْمَةٌ',
          en: 'Darkness',
          bn: 'অন্ধকার',
          romanized: 'ẓulmatun',
          emoji: '🌑',
        },
        {
          id: 'c2l8-mujahid',
          ar: 'مُجَاهِدٌ',
          en: 'A striver / defender',
          bn: 'মুজাহিদ বা সংগ্রামী',
          romanized: 'mujāhidun',
          emoji: '🛡️',
        },
        {
          id: 'c2l8-alim',
          ar: 'عَالِمٌ',
          en: 'A scholar / sage',
          bn: 'জ্ঞানী বা আলেম',
          romanized: "'ālimun",
          emoji: '📜',
        },
      ],
    },
  },

  // 4. Synaptic Speed Match: Capstone Synthesis Lexicon
  {
    id: 'ch2-l8-step-4-speed-capstone',
    type: 'speed_pair',
    pageNumber: 85,
    titleEn: 'Synaptic Speed Pairing: Capstone Vocabulary',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: مُفْرَدَاتُ التَّرْكِيبِ',
    instructionEn: 'Match classical terms for physical objects and internal states to their English translations.',
    instructionBn: 'ভৌত বস্তু ও আধ্যাত্মিক অবস্থার আরবি শব্দগুলোর সঠিক অর্থের সাথে দ্রুত মিল করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c2l8-1', ar: 'فَصْلٌ', meaning: 'Classroom' },
        { id: 'p-c2l8-2', ar: 'صَفٌّ', meaning: 'Grade / rank' },
        { id: 'p-c2l8-3', ar: 'نَارٌ', meaning: 'Fire (fem.)' },
        { id: 'p-c2l8-4', ar: 'سَيْفٌ', meaning: 'Sword' },
        { id: 'p-c2l8-5', ar: 'نُورٌ', meaning: 'Light' },
        { id: 'p-c2l8-6', ar: 'ظُلْمَةٌ', meaning: 'Darkness' },
      ],
    },
  },

  // 5. Concept Discovery: Demonstrative Badal Inside Prepositional Phrase
  {
    id: 'ch2-l8-step-5-concept-prepositional-badal',
    type: 'concept_intro',
    pageNumber: 85,
    titleEn: 'Grammar Paradigm: Preposition + Demonstrative + Definite Noun',
    titleAr: 'قَاعِدَةٌ: الجَارُّ مَعَ اسْمِ الإِشَارَةِ وَالبَدَلِ',
    instructionEn: 'When a preposition precedes a demonstrative phrase («فِي هَذَا الْفَصْلِ»), the definite noun follows the genitive case with Kasrah (ـِ).',
    instructionBn: 'অব্যয়ের (যার) পর ইশারা ও নির্দিষ্ট বিশেষ্য এলে তা বদল হিসেবে কাসরাহ (যের) গ্রহণ করে: «فِي هَذَا الْفَصْلِ»।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c2l8-fi-hadha-fasl',
          ar: 'فِي هَذَا الْفَصْلِ سَبُّورَةٌ',
          romanized: 'fī hādhā al-faṣli sabbūratun',
          meaningEn: 'In this classroom is a blackboard.',
          meaningBn: 'এই শ্রেণিকক্ষে একটি ব্ল্যাকবোর্ড আছে।',
          exampleAr: 'السَّبُّورَةُ فِي هَذَا الْفَصْلِ',
          exampleEn: 'The blackboard is in this classroom.',
          exampleBn: 'ব্ল্যাকবোর্ডটি এই শ্রেণিকক্ষে রয়েছে।',
          audioKey: 'fi_hadha_al_fasli_sabburah',
          exampleAudioKey: 'as_sabburatu_fi_hadha_al_fasl',
          emoji: '🏫',
        },
        {
          id: 'cp-c2l8-fi-dhalika-kub',
          ar: 'فِي ذَلِكَ الْكُوبِ لَبَنٌ',
          romanized: 'fī dhālika al-kūbi labanun',
          meaningEn: 'In that cup is milk.',
          meaningBn: 'ওই গ্লাসে দুধ আছে।',
          exampleAr: 'فِي هَذَا الْكُوبِ مَاءٌ وَ فِي ذَلِكَ الْكُوبِ لَبَنٌ',
          exampleEn: 'In this cup is water and in that cup is milk.',
          exampleBn: 'এই গ্লাসে পানি এবং ওই গ্লাসে দুধ আছে।',
          audioKey: 'fi_dhalika_al_kubi_laban',
          exampleAudioKey: 'fi_hadha_al_kubi_ma_wa_fi_dhalika_laban',
          emoji: '🥛',
        },
      ],
    },
  },

  // 6. Deep Pedagogical Concept: Parallel Balanced Syntactic Antitheses
  {
    id: 'ch2-l8-step-6-concept-antitheses',
    type: 'concept_intro',
    pageNumber: 86,
    titleEn: 'Syntactic Mastery: Balanced Prepositional Contrasts',
    titleAr: 'قَاعِدَةٌ: التَّوَازُنُ التَّرْكِيبِيُّ بَيْنَ الجُمَلِ',
    instructionEn: 'Classical Arabic creates profound harmony through mirrored parallel clauses balancing subjects and prepositional predicates.',
    instructionBn: 'শাস্ত্রীয় আরবিতে সমান্তরাল বাক্যরীতির মাধ্যমে গভীর অর্থবোধক ভারসাম্য ও বৈপরীত্য প্রকাশ করা হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-c2l8-sword-pen',
          ar: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ وَ فِي يَدِ الْعَالِمِ قَلَمٌ',
          romanized: 'fī yadi al-mujāhidi sayfun wa fī yadi al-‘ālimi qalamun',
          meaningEn: 'In the hand of the striver is a sword, and in the hand of the scholar is a pen.',
          meaningBn: 'সংগ্রামীর হাতে তরবারি এবং আলেমের হাতে কলম রয়েছে।',
          exampleAr: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ وَ فِي يَدِ الْعَالِمِ قَلَمٌ',
          exampleEn: 'In the hand of the striver is a sword, and in the hand of the scholar is a pen.',
          exampleBn: 'মুজাহিদের হাতে তরবারি এবং আলেমের হাতে কলম।',
          audioKey: 'fi_yadi_al_mujahidi_sayf',
          exampleAudioKey: 'fi_yadi_al_mujahidi_sayf_wa_fi_yadi_al_alimi_qalam',
          emoji: '⚔️',
        },
        {
          id: 'cp-c2l8-light-darkness',
          ar: 'فِي قَلْبِ الْمُسْلِمِ نُورٌ وَ فِي قَلْبِ الْكَافِرِ ظُلْمَةٌ',
          romanized: 'fī qalbi al-muslimi nūrun wa fī qalbi al-kāfiri ẓulmatun',
          meaningEn: 'In the heart of the Muslim is light, and in the heart of the disbeliever is darkness.',
          meaningBn: 'মুসলমানের অন্তরে আলো এবং কাফেরের অন্তরে অন্ধকার।',
          exampleAr: 'فِي قَلْبِ الْمُسْلِمِ نُورٌ وَ فِي قَلْبِ الْكَافِرِ ظُلْمَةٌ',
          exampleEn: 'In the heart of the Muslim is light, and in the heart of the disbeliever is darkness.',
          exampleBn: 'মুসলমানের অন্তরে নূর এবং কাফেরের অন্তরে অন্ধকার রয়েছে।',
          audioKey: 'fi_qalbi_al_muslimi_nur',
          exampleAudioKey: 'fi_qalbi_al_muslimi_nur_wa_fi_qalbi_al_kafiri_zulmah',
          emoji: '✨',
        },
      ],
    },
  },

  // 7. Polar Sort 1: Inherent Feminine Gender of Fire
  {
    id: 'ch2-l8-step-7-polar-nar-gender',
    type: 'polar_sort',
    pageNumber: 85,
    titleEn: 'Binary Gender Sort: The Element of Fire',
    titleAr: 'تَمْيِيزُ تَأْنِيثِ النَّارِ سَمَاعًا',
    instructionEn: 'Identify the demonstrative pronoun that correctly accords with «نَارٌ» (fire), which is feminine by convention.',
    instructionBn: '«نَارٌ» (আগুন) স্বভাবগতভাবে স্ত্রীলিঙ্গ হওয়ায় কোন ইশারাটি সঠিক তা নির্বাচন করুন।',
    polarPayload: {
      arabicSubject: 'نَارٌ',
      meaningEn: 'Fire (inherently feminine)',
      meaningBn: 'আগুন (স্বভাবগত স্ত্রীলিঙ্গ)',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ نَارٌ',
      options: ['هَذَا نَارٌ', 'هَذِهِ نَارٌ'],
      emoji: '🔥',
    },
  },

  // 8. Polar Sort 2: Spiritual States of the Heart
  {
    id: 'ch2-l8-step-8-polar-heart-state',
    type: 'polar_sort',
    pageNumber: 86,
    titleEn: 'Binary Semantic Sort: The Believer’s Heart',
    titleAr: 'تَمْيِيزُ النُّورِ وَالظُّلْمَةِ فِي القُلُوبِ',
    instructionEn: 'What illumination resides within the heart of the believer according to the lesson text?',
    instructionBn: 'পাঠ্য অনুসারে মুমিনের অন্তরে কোন আলো বা অবস্থা বিরাজমান?',
    polarPayload: {
      arabicSubject: 'فِي قَلْبِ الْمُسْلِمِ',
      meaningEn: 'In the heart of the Muslim is...',
      meaningBn: 'মুসলমানের অন্তরে রয়েছে...',
      gender: 'masculine',
      correctAnswer: 'نُورٌ',
      options: ['نُورٌ', 'ظُلْمَةٌ'],
      emoji: '✨',
    },
  },

  // 9. Cloze Choice Drill 1: Syntactic Badal Kasrah Concord
  {
    id: 'ch2-l8-step-9-cloze-badal-kasrah',
    type: 'cloze_choice',
    pageNumber: 85,
    titleEn: 'Syntactic Case Ending: Prepositional Badal',
    titleAr: 'إِعْرَابُ البَدَلِ بَعْدَ حَرْفِ الجَرِّ',
    instructionEn: 'Select the grammatically correct word ending for the appositive noun inside: «فِي هَذَا ___ سَبُّورَةٌ».',
    instructionBn: '«فِي هَذَا ___ سَبُّورَةٌ» বাক্যাংশে বদল হিসেবে আগত শব্দের সঠিক হরকতযুক্ত রূপ নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'فِي هَذَا ... سَبُّورَةٌ',
      questionEn: 'In this classroom is a blackboard.',
      questionBn: 'এই শ্রেণিকক্ষে একটি ব্ল্যাকবোর্ড আছে।',
      partialAnswerAr: 'فِي هَذَا ... سَبُّورَةٌ',
      correctAnswer: 'الْفَصْلِ',
      options: ['الْفَصْلِ', 'الْفَصْلُ', 'الْفَصْلَ', 'فَصْلٌ'],
      emoji: '🏫',
    },
  },

  // 10. Cloze Choice Drill 2: Cup Contents Discrimination
  {
    id: 'ch2-l8-step-10-cloze-cup-milk',
    type: 'cloze_choice',
    pageNumber: 85,
    titleEn: 'Contextual Selection: Liquid in the Distant Cup',
    titleAr: 'اخْتِيَارُ الاسْمِ: شَرَابُ الكُوبِ البَعِيدِ',
    instructionEn: 'Complete the contrast: "In this cup is water, and in that cup is ..."',
    instructionBn: '"এই গ্লাসে পানি এবং ওই গ্লাসে ... আছে" বাক্যটি পূর্ণ করুন।',
    clozePayload: {
      questionAr: 'فِي هَذَا الْكُوبِ مَاءٌ ، وَ فِي ذَلِكَ الْكُوبِ ...',
      questionEn: 'In this cup is water, and in that cup is milk.',
      questionBn: 'এই গ্লাসে পানি, এবং ওই গ্লাসে দুধ রয়েছে।',
      partialAnswerAr: 'فِي هَذَا الْكُوبِ مَاءٌ ، وَ فِي ذَلِكَ الْكُوبِ ...',
      correctAnswer: 'لَبَنٌ',
      options: ['لَبَنٌ', 'عَسَلٌ', 'شَايٌ', 'مَاءٌ'],
      emoji: '🥛',
    },
  },

  // 11. Dialogic Alternative Q&A Battery 1: Classroom Furniture & Fatima’s Room
  {
    id: 'ch2-l8-step-11-dialogue-classroom-quarters',
    type: 'alternative_qa',
    pageNumber: 87,
    titleEn: 'Dialogic Battery: Classroom Furniture & Domestic Quarters',
    titleAr: 'حِوَارُ التَّعْيِينِ: أَثَاثُ الفَصْلِ وَغُرْفَةُ فَاطِمَةَ',
    instructionEn: 'Dissect the furniture in the classroom and Fatima’s room based on the visual cues without using yes or no.',
    instructionBn: 'হ্যাঁ বা না ছাড়া দৃশ্যায়ন অনুযায়ী শ্রেণিকক্ষ ও ফাতেমার কামরার আসবাবপত্রের আপেক্ষিক অবস্থান নির্ণয় করুন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l8-1',
          questionAr: 'أَ سَبُّورَةٌ فِي هَذَا الْفَصْلِ أَمْ سَرِيرٌ ؟',
          contextAr: 'فِي هَذَا الْفَصْلِ سَبُّورَةٌ',
          contextEn: 'In this classroom is a blackboard',
          contextBn: 'এই শ্রেণিকক্ষে একটি ব্ল্যাকবোর্ড আছে',
          visualCue: '📋',
          optionsAr: ['سَبُّورَةٌ', 'سَرِيرٌ'],
          correctAnswerAr: 'سَبُّورَةٌ',
        },
        {
          id: 'qa-c2l8-2',
          questionAr: 'أَ فِي هَذَا الْفَصْلِ الْكُرْسِيُّ وَ الطَّاوِلَةُ أَمْ فِي الْمَكْتَبِ ؟',
          contextAr: 'الْكُرْسِيُّ وَالطَّاوِلَةُ فِي هَذَا الْفَصْلِ',
          contextEn: 'The chair and table are in this classroom',
          contextBn: 'চেয়ার ও টেবিল এই শ্রেণিকক্ষে আছে',
          visualCue: '🏫',
          optionsAr: ['فِي هَذَا الْفَصْلِ', 'فِي الْمَكْتَبِ'],
          correctAnswerAr: 'فِي هَذَا الْفَصْلِ',
        },
        {
          id: 'qa-c2l8-3',
          questionAr: 'أَ فِي هَذَا الْفَصْلِ الْكُرْسِيُّ وَ الطَّاوِلَةُ أَمْ فِي ذَلِكَ الْفَصْلِ ؟',
          contextAr: 'الْكُرْسِيُّ وَالطَّاوِلَةُ فِي هَذَا الْفَصْلِ',
          contextEn: 'The chair and table are in this classroom',
          contextBn: 'চেয়ার ও টেবিল এই শ্রেণিকক্ষে আছে',
          visualCue: '👉',
          optionsAr: ['فِي هَذَا الْفَصْلِ', 'فِي ذَلِكَ الْفَصْلِ'],
          correctAnswerAr: 'فِي هَذَا الْفَصْلِ',
        },
        {
          id: 'qa-c2l8-4',
          questionAr: 'أَ سَرِيرٌ فِي غُرْفَتِهَا أَمْ كُرْسِيٌّ ؟',
          contextAr: 'فِي غُرْفَةِ فَاطِمَةَ سَرِيرٌ',
          contextEn: 'In Fatima’s room is a bed',
          contextBn: 'ফাতেমার ঘরে একটি খাট আছে',
          visualCue: '🛏️',
          optionsAr: ['سَرِيرٌ', 'كُرْسِيٌّ'],
          correctAnswerAr: 'سَرِيرٌ',
        },
        {
          id: 'qa-c2l8-5',
          questionAr: 'أَ فِي غُرْفَةِ فَاطِمَةَ الْمِرْوَحَةُ أَمْ فِي غُرْفَةِ عَائِشَةَ ؟',
          contextAr: 'الْمِرْوَحَةُ فِي غُرْفَةِ فَاطِمَةَ',
          contextEn: 'The fan is in Fatima’s room',
          contextBn: 'ফ্যানটি ফাতেমার ঘরে আছে',
          visualCue: '👧',
          optionsAr: ['فِي غُرْفَةِ فَاطِمَةَ', 'فِي غُرْفَةِ عَائِشَةَ'],
          correctAnswerAr: 'فِي غُرْفَةِ فَاطِمَةَ',
        },
      ],
    },
  },

  // 12. Dialogic Alternative Q&A Battery 2: Cup Liquids & Archetypes
  {
    id: 'ch2-l8-step-12-dialogue-liquids-archetypes',
    type: 'alternative_qa',
    pageNumber: 87,
    titleEn: 'Dialogic Battery: Vessels & Archetypal Implements',
    titleAr: 'حِوَارُ التَّعْيِينِ: شَرَابُ الأَكْوَابِ وَأَدَوَاتُ النَّاسِ',
    instructionEn: 'Analyze the contents of the cups and implements based on the visual cues without using yes or no.',
    instructionBn: 'হ্যাঁ বা না ছাড়া দৃশ্যায়ন অনুযায়ী গ্লাসের পানীয় এবং সংশ্লিষ্ট সামগ্রী যাচাই করে উত্তর দিন।',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l8-6',
          questionAr: 'آلْمَاءُ فِي هَذَا الْكُوبِ أَمِ اللَّبَنُ ؟',
          contextAr: 'فِي هَذَا الْكُوبِ مَاءٌ',
          contextEn: 'In this cup is water',
          contextBn: 'এই গ্লাসে পানি আছে',
          visualCue: '💧',
          optionsAr: ['الْمَاءُ', 'اللَّبَنُ'],
          correctAnswerAr: 'الْمَاءُ',
        },
        {
          id: 'qa-c2l8-7',
          questionAr: 'آللَّبَنُ فِي ذَلِكَ الْكُوبِ أَمِ الْمَاءُ ؟',
          contextAr: 'فِي ذَلِكَ الْكُوبِ لَبَنٌ',
          contextEn: 'In that cup is milk',
          contextBn: 'ওই গ্লাসে দুধ আছে',
          visualCue: '🥛',
          optionsAr: ['اللَّبَنُ', 'الْمَاءُ'],
          correctAnswerAr: 'اللَّبَنُ',
        },
        {
          id: 'qa-c2l8-8',
          questionAr: 'أَ فِي هَذَا الْكُوبِ الْمَاءُ أَمْ فِي ذَلِكَ الْكُوبِ ؟',
          contextAr: 'الْمَاءُ فِي هَذَا الْكُوبِ',
          contextEn: 'The water is in this cup',
          contextBn: 'পানিটি এই গ্লাসে আছে',
          visualCue: '💧',
          optionsAr: ['فِي هَذَا الْكُوبِ', 'فِي ذَلِكَ الْكُوبِ'],
          correctAnswerAr: 'فِي هَذَا الْكُوبِ',
        },
        {
          id: 'qa-c2l8-9',
          questionAr: 'أَ فِي ذَلِكَ الْكُوبِ اللَّبَنُ أَمْ فِي هَذَا الْكُوبِ ؟',
          contextAr: 'اللَّبَنُ فِي ذَلِكَ الْكُوبِ',
          contextEn: 'The milk is in that cup',
          contextBn: 'দুধটি ওই গ্লাসে আছে',
          visualCue: '🥛',
          optionsAr: ['فِي ذَلِكَ الْكُوبِ', 'فِي هَذَا الْكُوبِ'],
          correctAnswerAr: 'فِي ذَلِكَ الْكُوبِ',
        },
        {
          id: 'qa-c2l8-10',
          questionAr: 'أَ فِي يَدِ الْمُجَاهِدِ سَيْفٌ أَمْ قَلَمٌ ؟',
          contextAr: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ',
          contextEn: 'In the striver’s hand is a sword',
          contextBn: 'মুজাহিদের হাতে তরবারি আছে',
          visualCue: '⚔️',
          optionsAr: ['سَيْفٌ', 'قَلَمٌ'],
          correctAnswerAr: 'سَيْفٌ',
        },
      ],
    },
  },

  // 13. Speed Pair Matching 2: Balanced Prepositional Contrasts
  {
    id: 'ch2-l8-step-13-speed-contrasts',
    type: 'speed_pair',
    pageNumber: 86,
    titleEn: 'Synaptic Speed Pairing: Balanced Antitheses',
    titleAr: 'التَّطَابُقُ السَّرِيعُ: الجُمَلُ المُتَقَابِلَةُ',
    instructionEn: 'Pair the mirrored Arabic clauses with their exact English equivalents.',
    instructionBn: 'বিপরীতমুখী বাক্যজোড়াগুলোর সাথে তাদের অনুবাদের দ্রুত মিল করুন।',
    pairPayload: {
      pairs: [
        { id: 'p-c2l8-7', ar: 'فِي هَذَا الْكُوبِ مَاءٌ', meaning: 'In this cup is water' },
        { id: 'p-c2l8-8', ar: 'فِي ذَلِكَ الْكُوبِ لَبَنٌ', meaning: 'In that cup is milk' },
        { id: 'p-c2l8-9', ar: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ', meaning: 'In the striver’s hand is a sword' },
        { id: 'p-c2l8-10', ar: 'فِي يَدِ الْعَالِمِ قَلَمٌ', meaning: 'In the scholar’s hand is a pen' },
        { id: 'p-c2l8-11', ar: 'فِي هَذَا الْفَصْلِ سَبُّورَةٌ', meaning: 'In this classroom is a board' },
      ],
    },
  },

  // 14. Page 85: Authentic Reading & Translation Drill 1: Grade Five Classroom
  {
    id: 'ch2-l8-step-14-assembly-grade5-classroom',
    type: 'sentence_assembly',
    pageNumber: 85,
    titleEn: 'Textbook Translation: Grade Five Classroom',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: فَصْلُ الصَّفِّ الخَامِسِ',
    instructionEn: 'Read the textbook sentence and assemble the translation.',
    instructionBn: 'আরবি পাঠ্যটি পড়ুন এবং শব্দ চিপস সাজিয়ে সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'هَذَا فَصْلُ الصَّفِّ الْخَامِسِ ، وَفِي هَذَا الْفَصْلِ سَبُّورَةٌ',
      promptEn: 'This is the classroom of the fifth grade and in this classroom is a blackboard',
      promptBn: 'এটি পঞ্চম শ্রেণীর শ্রেণিকক্ষ এবং এই শ্রেণিকক্ষে একটি ব্ল্যাকবোর্ড আছে',
      expectedAnswer: ['This', 'is', 'the', 'classroom', 'of', 'the', 'fifth', 'grade', 'and', 'in', 'this', 'classroom', 'is', 'a', 'blackboard'],
      chips: ['This', 'is', 'the', 'classroom', 'of', 'the', 'fifth', 'grade', 'and', 'in', 'this', 'classroom', 'is', 'a', 'blackboard', 'bed', 'library'],
      expectedAnswerBn: ['এটি', 'পঞ্চম', 'শ্রেণীর', 'শ্রেণিকক্ষ', 'এবং', 'এই', 'শ্রেণিকক্ষে', 'একটি', 'ব্ল্যাকবোর্ড', 'আছে'],
      chipsBn: ['এটি', 'পঞ্চম', 'শ্রেণীর', 'শ্রেণিকক্ষ', 'এবং', 'এই', 'শ্রেণিকক্ষে', 'একটি', 'ব্ল্যাকবোর্ড', 'আছে', 'খাট', 'লাইব্রেরি'],
      emoji: '🏫',
    },
  },

  // 15. Page 85: Authentic Reading & Translation Drill 2: Liquid Contrasts in Cups
  {
    id: 'ch2-l8-step-15-assembly-cups-water-milk',
    type: 'sentence_assembly',
    pageNumber: 85,
    titleEn: 'Textbook Translation: Water & Milk in Cups',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: المَاءُ وَاللَّبَنُ فِي الكُوبِ',
    instructionEn: 'Read the textbook contrast and assemble the translation.',
    instructionBn: 'আরবি বিপরীত বাক্যটি পড়ুন এবং সঠিক অনুবাদ তৈরি করুন।',
    assemblyPayload: {
      promptAr: 'فِي هَذَا الْكُوبِ مَاءٌ بَارِدٌ ، وَفِي ذَلِكَ الْكُوبِ لَبَنٌ حَارٌّ',
      promptEn: 'In this cup is cold water and in that cup is hot milk',
      promptBn: 'এই গ্লাসে ঠান্ডা পানি এবং ওই গ্লাসে গরম দুধ আছে',
      expectedAnswer: ['In', 'this', 'cup', 'is', 'cold', 'water', 'and', 'in', 'that', 'cup', 'is', 'hot', 'milk'],
      chips: ['In', 'this', 'cup', 'is', 'cold', 'water', 'and', 'in', 'that', 'cup', 'is', 'hot', 'milk', 'honey', 'tea'],
      expectedAnswerBn: ['এই', 'গ্লাসে', 'ঠান্ডা', 'পানি', 'এবং', 'ওই', 'গ্লাসে', 'গরম', 'দুধ', 'আছে'],
      chipsBn: ['এই', 'গ্লাসে', 'ঠান্ডা', 'পানি', 'এবং', 'ওই', 'গ্লাসে', 'গরম', 'দুধ', 'আছে', 'মধু', 'চা'],
      emoji: '🥛',
    },
  },

  // 16. Page 86: Authentic Reading & Translation Drill 3: Sword & Pen
  {
    id: 'ch2-l8-step-16-assembly-sword-pen',
    type: 'sentence_assembly',
    pageNumber: 86,
    titleEn: 'Textbook Translation: Sword & Pen',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: سَيْفُ المُجَاهِدِ وَقَلَمُ العَالِمِ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ ، وَفِي يَدِ الْعَالِمِ قَلَمٌ',
      promptEn: 'In the hand of the striver is a sword and in the hand of the scholar is a pen',
      promptBn: 'মুজাহিদের হাতে রয়েছে তরবারি এবং আলেমের হাতে রয়েছে কলম',
      expectedAnswer: ['In', 'the', 'hand', 'of', 'the', 'striver', 'is', 'a', 'sword', 'and', 'in', 'the', 'hand', 'of', 'the', 'scholar', 'is', 'a', 'pen'],
      chips: ['In', 'the', 'hand', 'of', 'the', 'striver', 'is', 'a', 'sword', 'and', 'in', 'the', 'hand', 'of', 'the', 'scholar', 'is', 'a', 'pen', 'shield', 'spear'],
      expectedAnswerBn: ['মুজাহিদের', 'হাতে', 'রয়েছে', 'তরবারি', 'এবং', 'আলেমের', 'হাতে', 'রয়েছে', 'কলম'],
      chipsBn: ['মুজাহিদের', 'হাতে', 'রয়েছে', 'তরবারি', 'এবং', 'আলেমের', 'হাতে', 'রয়েছে', 'কলম', 'ঢাল', 'বল্লম'],
      emoji: '⚔️',
    },
  },

  // 17. Syntactic Tarkib Dissector: Complex Prepositional & Genitive Syntax
  {
    id: 'ch2-l8-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 86,
    titleEn: 'Syntactic Tarkib Dissector: Multi-Tiered Fronted Predicate Architecture',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: بِنَاءُ الجَارِّ وَالمَجْرُورِ المُرَكَّبِ مَعَ المُبْتَدَأِ',
    instructionEn: 'Analyze the intricate multi-tiered construction where a preposition introduces a possessive construct serving as the fronted predicate.',
    instructionBn: 'হরফে যার এবং মুদাফ-মুদাফ ইলাইহি মিলে কীভাবে যৌগিক অগ্রবর্তী খবর গঠন করে তা ব্যাকরণগতভাবে বিশ্লেষণ করুন।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c2l8-s1',
          sentenceAr: 'فِي يَدِ الْمُجَاهِدِ سَيْفٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (خَبَرٌ مُقَدَّمٌ مُرَكَّبٌ إِضَافِيٌّ مَجْرُورٌ + مُبْتَدَأٌ مُؤَخَّرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Compound Prepositional Predicate + Delayed Subject)',
          sentenceTypeBn: 'নামবাচক বাক্য (যৌগিক যার-মুদাফ খবর + বিলম্বিত মুবতাদা)',
          slots: [
            {
              roleAr: 'حَرْفُ جَرٍّ',
              roleEn: 'Preposition (Harf Jarr)',
              roleBn: 'হরফে যার',
              expectedWordAr: 'فِي',
            },
            {
              roleAr: 'مَجْرُورٌ وَمُضَافٌ',
              roleEn: 'Genitive Noun & Mudaf',
              roleBn: 'মাজরুর ও মুদাফ',
              expectedWordAr: 'يَدِ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ (مَجْرُورٌ)',
              roleEn: 'Possessor Noun (Genitive)',
              roleBn: 'মুদাফ ইলাইহি (মাজরুর)',
              expectedWordAr: 'الْمُجَاهِدِ',
            },
            {
              roleAr: 'مُبْتَدَأٌ مُؤَخَّرٌ (مَرْفُوعٌ)',
              roleEn: 'Delayed Indefinite Subject',
              roleBn: 'বিলম্বিত মুবতাদা (মারফু)',
              expectedWordAr: 'سَيْفٌ',
            },
          ],
          availableWordsAr: ['سَيْفٌ', 'يَدِ', 'الْمُجَاهِدِ', 'فِي'],
        },
        {
          id: 'tarkib-c2l8-s2',
          sentenceAr: 'فِي قَلْبِ الْمُسْلِمِ نُورٌ',
          sentenceTypeAr: 'جُمْلَةٌ اسْمِيَّةٌ (خَبَرٌ مُقَدَّمٌ إِضَافِيٌّ مَجْرُورٌ + مُبْتَدَأٌ مُؤَخَّرٌ)',
          sentenceTypeEn: 'Nominal Sentence (Fronted Prepositional Predicate + Delayed Subject)',
          sentenceTypeBn: 'নামবাচক বাক্য (যার-মুদাফ অগ্রবর্তী খবর + বিলম্বিত মুবতাদা)',
          slots: [
            {
              roleAr: 'حَرْفُ جَرٍّ',
              roleEn: 'Preposition (Harf Jarr)',
              roleBn: 'হরফে যার',
              expectedWordAr: 'فِي',
            },
            {
              roleAr: 'مَجْرُورٌ وَمُضَافٌ',
              roleEn: 'Genitive Noun & Mudaf',
              roleBn: 'মাজরুর ও মুদাফ',
              expectedWordAr: 'قَلْبِ',
            },
            {
              roleAr: 'مُضَافٌ إِلَيْهِ (مَجْرُورٌ)',
              roleEn: 'Possessor Noun (Genitive)',
              roleBn: 'মুদাফ ইলাইহি (মাজরুর)',
              expectedWordAr: 'الْمُسْلِمِ',
            },
            {
              roleAr: 'مُبْتَدَأٌ مُؤَخَّرٌ (مَرْفُوعٌ)',
              roleEn: 'Delayed Indefinite Subject',
              roleBn: 'বিলম্বিত মুবতাদা (মারফু)',
              expectedWordAr: 'نُورٌ',
            },
          ],
          availableWordsAr: ['قَلْبِ', 'نُورٌ', 'فِي', 'الْمُسْلِمِ'],
        },
      ],
    },
  },

  // 18. Verb Paradigm Preview (Imperative & Prohibitive - Al-Amr wa An-Nahy)
  // "শুধু মুখস্থ করার জন্য, ব্যবহার করার জন্য নয়"
  {
    id: 'ch2-l8-step-18-verb-preview-imperative',
    type: 'verb_preview_grid',
    pageNumber: 87,
    titleEn: 'Foundational Verb Preview: Imperative & Prohibitive (Memorization Drill)',
    titleAr: 'مَدْخَلُ تَصْرِيفِ الأَفْعَالِ: فِعْلُ الأَمْرِ وَالنَّهْيِ (لِلْحِفْظِ فَقَطْ)',
    instructionEn: "Special preview: Read and memorize these 8 command and prohibition verb pairs. Note the author's pedagogical rule: for memorization only, not for sentence usage yet.",
    instructionBn: 'বিশেষ পরিশিষ্ট: আদেশ ও নিষেধবাচক এই ৮টি ক্রিয়ার রূপান্তর মনোযোগ দিয়ে পড়ুন ও মুখস্থ করুন। লেখকের মৌলিক নির্দেশনা: শুধু মুখস্থ করার জন্য, এখনই বাক্যে ব্যবহারের জন্য নয়।',
    verbPreviewPayload: {
      tense: 'imperative',
      tenseLabelAr: 'فِعْلُ الأَمْرِ وَالنَّهْيِ',
      tenseLabelEn: 'Imperative & Prohibitive (Al-Amr wa An-Nahy)',
      tenseLabelBn: 'আদেশ ও নিষেধবাচক ক্রিয়া (আমর ও নাহী)',
      disclaimerAr: 'فَقَطْ لِلْحِفْظِ ، لَا لِلِاسْتِعْمَالِ',
      disclaimerEn: 'For memorization only, not for practice yet',
      disclaimerBn: 'শুধু মুখস্থ করার জন্য, ব্যবহার করার জন্য নয়',
      verbs: [
        {
          id: 'v-imp-ifal',
          rootAr: 'اِفْعَلْ',
          rootBn: 'করা (Do / Do not do)',
          rootEn: 'To do / Do not do',
          emoji: '⚡',
          forms: [
            {
              id: 'v-imp-ifal-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِفْعَلْ',
              masculineBn: 'তুমি কর (পুং)',
              masculineEn: 'Do (m)',
              feminineAr: 'اِفْعَلِيْ',
              feminineBn: 'তুমি কর (স্ত্রী)',
              feminineEn: 'Do (f)',
            },
            {
              id: 'v-imp-ifal-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَفْعَلْ',
              masculineBn: 'তুমি করো না (পুং)',
              masculineEn: 'Do not do (m)',
              feminineAr: 'لَا تَفْعَلِيْ',
              feminineBn: 'তুমি করো না (স্ত্রী)',
              feminineEn: 'Do not do (f)',
            },
          ],
        },
        {
          id: 'v-imp-ukhruj',
          rootAr: 'اُخْرُجْ',
          rootBn: 'বের হওয়া (Exit / Do not exit)',
          rootEn: 'To exit / Do not exit',
          emoji: '🚪',
          forms: [
            {
              id: 'v-imp-ukhruj-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اُخْرُجْ',
              masculineBn: 'তুমি বের হও (পুং)',
              masculineEn: 'Exit (m)',
              feminineAr: 'اُخْرُجِيْ',
              feminineBn: 'তুমি বের হও (স্ত্রী)',
              feminineEn: 'Exit (f)',
            },
            {
              id: 'v-imp-ukhruj-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَخْرُجْ',
              masculineBn: 'তুমি বের হয়ো না (পুং)',
              masculineEn: 'Do not exit (m)',
              feminineAr: 'لَا تَخْرُجِيْ',
              feminineBn: 'তুমি বের হয়ো না (স্ত্রী)',
              feminineEn: 'Do not exit (f)',
            },
          ],
        },
        {
          id: 'v-imp-idhhab',
          rootAr: 'اِذْهَبْ',
          rootBn: 'যাওয়া (Go / Do not go)',
          rootEn: 'To go / Do not go',
          emoji: '🚶',
          forms: [
            {
              id: 'v-imp-idhhab-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِذْهَبْ',
              masculineBn: 'তুমি যাও (পুং)',
              masculineEn: 'Go (m)',
              feminineAr: 'اِذْهَبِيْ',
              feminineBn: 'তুমি যাও (স্ত্রী)',
              feminineEn: 'Go (f)',
            },
            {
              id: 'v-imp-idhhab-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَذْهَبْ',
              masculineBn: 'তুমি যেয়ো না (পুং)',
              masculineEn: 'Do not go (m)',
              feminineAr: 'لَا تَذْهَبِيْ',
              feminineBn: 'তুমি যেয়ো না (স্ত্রী)',
              feminineEn: 'Do not go (f)',
            },
          ],
        },
        {
          id: 'v-imp-ijlis',
          rootAr: 'اِجْلِسْ',
          rootBn: 'বসা (Sit / Do not sit)',
          rootEn: 'To sit / Do not sit',
          emoji: '🪑',
          forms: [
            {
              id: 'v-imp-ijlis-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِجْلِسْ',
              masculineBn: 'তুমি বসো (পুং)',
              masculineEn: 'Sit (m)',
              feminineAr: 'اِجْلِسِيْ',
              feminineBn: 'তুমি বসো (স্ত্রী)',
              feminineEn: 'Sit (f)',
            },
            {
              id: 'v-imp-ijlis-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَجْلِسْ',
              masculineBn: 'তুমি বসো না (পুং)',
              masculineEn: 'Do not sit (m)',
              feminineAr: 'لَا تَجْلِسِيْ',
              feminineBn: 'তুমি বসো না (স্ত্রী)',
              feminineEn: 'Do not sit (f)',
            },
          ],
        },
        {
          id: 'v-imp-iqra',
          rootAr: 'اِقْرَأْ',
          rootBn: 'পড়া (Read / Do not read)',
          rootEn: 'To read / Do not read',
          emoji: '📖',
          forms: [
            {
              id: 'v-imp-iqra-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِقْرَأْ',
              masculineBn: 'তুমি পড়ো (পুং)',
              masculineEn: 'Read (m)',
              feminineAr: 'اِقْرَئِيْ',
              feminineBn: 'তুমি পড়ো (স্ত্রী)',
              feminineEn: 'Read (f)',
            },
            {
              id: 'v-imp-iqra-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَقْرَأْ',
              masculineBn: 'তুমি পড়ো না (পুং)',
              masculineEn: 'Do not read (m)',
              feminineAr: 'لَا تَقْرَئِيْ',
              feminineBn: 'তুমি পড়ো না (স্ত্রী)',
              feminineEn: 'Do not read (f)',
            },
          ],
        },
        {
          id: 'v-imp-uktub',
          rootAr: 'اُكْتُبْ',
          rootBn: 'লেখা (Write / Do not write)',
          rootEn: 'To write / Do not write',
          emoji: '✍️',
          forms: [
            {
              id: 'v-imp-uktub-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اُكْتُبْ',
              masculineBn: 'তুমি লেখো (পুং)',
              masculineEn: 'Write (m)',
              feminineAr: 'اُكْتُبِيْ',
              feminineBn: 'তুমি লেখো (স্ত্রী)',
              feminineEn: 'Write (f)',
            },
            {
              id: 'v-imp-uktub-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَكْتُبْ',
              masculineBn: 'তুমি লিখো না (পুং)',
              masculineEn: 'Do not write (m)',
              feminineAr: 'لَا تَكْتُبِيْ',
              feminineBn: 'তুমি লিখো না (স্ত্রী)',
              feminineEn: 'Do not write (f)',
            },
          ],
        },
        {
          id: 'v-imp-irji',
          rootAr: 'اِرْجِعْ',
          rootBn: 'ফেরা (Return / Do not return)',
          rootEn: 'To return / Do not return',
          emoji: '🔄',
          forms: [
            {
              id: 'v-imp-irji-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِرْجِعْ',
              masculineBn: 'তুমি ফিরো (পুং)',
              masculineEn: 'Return (m)',
              feminineAr: 'اِرْجِعِيْ',
              feminineBn: 'তুমি ফিরো (স্ত্রী)',
              feminineEn: 'Return (f)',
            },
            {
              id: 'v-imp-irji-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَرْجِعْ',
              masculineBn: 'তুমি ফিরো না (পুং)',
              masculineEn: 'Do not return (m)',
              feminineAr: 'لَا تَرْجِعِيْ',
              feminineBn: 'তুমি ফিরো না (স্ত্রী)',
              feminineEn: 'Do not return (f)',
            },
          ],
        },
        {
          id: 'v-imp-ilab',
          rootAr: 'اِلْعَبْ',
          rootBn: 'খেলা (Play / Do not play)',
          rootEn: 'To play / Do not play',
          emoji: '⚽',
          forms: [
            {
              id: 'v-imp-ilab-cmd',
              roleAr: 'فِعْلُ الأَمْرِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Command (m / f)',
              roleBn: 'আদেশবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'اِلْعَبْ',
              masculineBn: 'তুমি খেলো (পুং)',
              masculineEn: 'Play (m)',
              feminineAr: 'اِلْعَبِيْ',
              feminineBn: 'তুমি খেলো (স্ত্রী)',
              feminineEn: 'Play (f)',
            },
            {
              id: 'v-imp-ilab-prohib',
              roleAr: 'فِعْلُ النَّهْيِ (مُذَكَّرٌ - مُؤَنَّثٌ)',
              roleEn: 'Prohibition (m / f)',
              roleBn: 'নিষেধবাচক ক্রিয়া (পুং - স্ত্রী)',
              masculineAr: 'لَا تَلْعَبْ',
              masculineBn: 'তুমি খেলো না (পুং)',
              masculineEn: 'Do not play (m)',
              feminineAr: 'لَا تَلْعَبِيْ',
              feminineBn: 'তুমি খেলো না (স্ত্রী)',
              feminineEn: 'Do not play (f)',
            },
          ],
        },
      ],
    },
  },

  // 19. Sacred Milestone: Quranic Echo (Surah Al-Baqarah 2:257)
  {
    id: 'ch2-l8-step-19-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 90,
    titleEn: 'Sacred Reflection: Deliverance from Darkness into Light',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: الإِخْرَاجُ مِنَ الظُّلُمَاتِ إِلَى النُّورِ',
    instructionEn: 'Witness how the ultimate cosmic antithesis of Light («النُّور») and Darkness («الظُّلُمَات») anchors divine deliverance in Surah Al-Baqarah (2:257).',
    instructionBn: 'সূরা আল-বাকারার আয়াতুল কুরসীর পরবর্তী আয়াতে নূর («النُّور») ও অন্ধকারের («الظُّلُمَات») মাধ্যমে ঐশী মুক্তির চিরন্তন ঘোষণা প্রত্যক্ষ করুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 257,
      surahNameAr: 'البقرة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا يُخْرِجُهُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ',
      translationEn: 'Allah is the ally of those who believe. He brings them out from darknesses into the light.',
      translationBn: 'যারা ঈমান এনেছে আল্লাহ তাদের অভিভাবক। তিনি তাদেরকে অন্ধকার থেকে আলোর দিকে বের করে আনেন।',
      highlightedWords: ['الظُّلُمَاتِ', 'النُّورِ'],
      patternNameEn: 'Spiritual Antithesis: Light vs Darknesses (النُّور وَ الظُّلُمَات)',
      patternNameBn: 'আত্মিক বৈপরীত্য: আলো ও অন্ধকার',
      lessonPatternAr: 'فِي قَلْبِ الْمُسْلِمِ نُورٌ وَ فِي قَلْبِ الْكَافِرِ ظُلْمَةٌ',
      lessonPatternEn: 'In the Muslim’s heart is light, and in the disbeliever’s heart is darkness',
      lessonPatternBn: 'মুসলমানের অন্তরে আলো এবং কাফেরের অন্তরে অন্ধকার',
      quranPatternAr: 'مِّنَ الظُّلُمَاتِ إِلَى النُّورِ',
      quranPatternEn: 'From darknesses into light',
      quranPatternBn: 'অন্ধকারসমূহ থেকে আলোর দিকে',
      reflection: 'In the Capstone Lesson of Chapter 2, you observed the foundational spiritual contrast: «فِي قَلْبِ الْمُسْلِمِ نُورٌ وَ فِي قَلْبِ الْكَافِرِ ظُلْمَةٌ». In Surah Al-Baqarah, Allah articulates His divine guardianship over the faithful through this exact cosmic dichotomy: delivering them from the manifold darknesses of confusion («الظُّلُمَاتِ») into the unified, luminous guidance of truth («النُّورِ»).',
      audioKey: 'quran_002257',
    },
  },
];

export const CH2_LESSON_08_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 2,
  lessonNum: 8,
  titleEn: 'Classrooms, Prepositional Badal & Contrasts',
  titleAr: 'الفُصُولُ وَالبَدَلُ الظَّرْفِيُّ وَالمُقَابَلَاتُ',
  wordsLearned: [
    'فَصْلٌ',
    'صَفٌّ',
    'مَكْتَبٌ',
    'سَبُّورَةٌ',
    'نَارٌ',
    'كُوبٌ',
    'لَبَنٌ',
    'مَاءٌ',
    'سَيْفٌ',
    'قَلْبٌ',
    'نُورٌ',
    'ظُلْمَةٌ',
    'مُجَاهِدٌ',
    'عَالِمٌ',
  ],
  steps: CH2_LESSON_08_STEPS,
};
