// Chapter 2 Lesson 1 Interactive Session Data (Directly mapped from textbook Volume 1 Chapter 2 Lesson 1, pages 50-54)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const CH2_LESSON_01_STEPS: SessionStep[] = [
  // 1. Vocabulary Discovery: Defense, Military & Transport
  {
    id: 'ch2-l1-step-1-vocab-military',
    type: 'vocab_prime',
    pageNumber: 50,
    titleEn: 'Defense & Transport Vocabulary',
    titleAr: 'مُفْرَدَاتُ الدِّفَاعِ وَالنَّقْلِ',
    instructionEn: 'Listen to and learn new nouns for defense, weapons, and historical transport',
    instructionBn: 'প্রতিরক্ষা, অস্ত্রশস্ত্র ও প্রাচীন পরিবহন বিষয়ক নতুন শব্দগুলোর উচ্চারণ শুনুন ও অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l1_bunduqiyyah', ar: 'بُنْدُقِيَّةٌ', en: 'Rifle / gun', bn: 'একটি বন্দুক', romanized: 'bunduqiyyatun', emoji: '🔫' },
        { id: 'v1_c2l1_dabbabah', ar: 'دَبَّابَةٌ', en: 'Tank', bn: 'একটি ট্যাঙ্ক', romanized: 'dabbābatun', emoji: '🛡️' },
        { id: 'v1_c2l1_qunbulah', ar: 'قُنْبُلَةٌ', en: 'Bomb', bn: 'একটি বোমা', romanized: 'qunbulatun', emoji: '💣' },
        { id: 'v1_c2l1_sayf', ar: 'سَيْفٌ', en: 'Sword', bn: 'একটি তরবারি', romanized: 'sayfun', emoji: '⚔️' },
        { id: 'v1_c2l1_bakhirah', ar: 'بَاخِرَةٌ', en: 'Steamer / ship', bn: 'একটি স্টীমার বা জাহাজ', romanized: 'bākhiratun', emoji: '🚢' },
        { id: 'v1_c2l1_madfa', ar: 'مِدْفَعٌ', en: 'Cannon', bn: 'একটি কামান', romanized: 'midfa‘un', emoji: '💥' },
        { id: 'v1_c2l1_hisn', ar: 'حِصْنٌ', en: 'Fort / fortress', bn: 'একটি দুর্গ', romanized: 'ḥiṣnun', emoji: '🏰' },
        { id: 'v1_c2l1_sahm', ar: 'سَهْمٌ', en: 'Arrow', bn: 'একটি তীর', romanized: 'sahmun', emoji: '🏹' },
        { id: 'v1_c2l1_qaws', ar: 'قَوْسٌ', en: 'Bow (feminine noun)', bn: 'একটি ধনুক (স্ত্রীবাচক)', romanized: 'qawsun', emoji: '🏹' },
      ],
    },
  },

  // 2. Spatial Pointing: Defense Object
  {
    id: 'ch2-l1-step-2-spatial-defense',
    type: 'spatial_pointing',
    pageNumber: 50,
    titleEn: 'Spatial Pointing: Defense Object',
    titleAr: 'الإِشَارَةُ: مِدْفَعٌ',
    instructionEn: 'Choose the correct pointer matching the visual distance',
    instructionBn: 'দূরত্ব অনুসারে সঠিক ইশারার বাক্যটি নির্বাচন করুন।',
    spatialPointingPayload: {
      objectAr: 'مِدْفَعٌ',
      distance: 'near',
      gender: 'masculine',
      correctAnswer: 'هَذَا مِدْفَعٌ',
      options: ['هَذَا مِدْفَعٌ', 'ذَلِكَ مِدْفَعٌ'],
      emoji: '💥',
    },
  },

  // 3. Speed Pairing: Defense & Transport
  {
    id: 'ch2-l1-step-3-pair-defense',
    type: 'speed_pair',
    pageNumber: 50,
    titleEn: 'Defense Vocabulary Recall Drill',
    titleAr: 'مُطَابَقَةُ أَدَوَاتِ الدِّفَاعِ',
    instructionEn: 'Match each Arabic word with its meaning',
    instructionBn: 'শব্দগুলোর সাথে সঠিক অর্থ দ্রুত মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pd-bunduqiyyah', ar: 'بُنْدُقِيَّةٌ', meaning: 'Rifle / gun' },
        { id: 'pd-dabbabah', ar: 'دَبَّابَةٌ', meaning: 'Tank' },
        { id: 'pd-bakhirah', ar: 'بَاخِرَةٌ', meaning: 'Steamer / ship' },
        { id: 'pd-madfa', ar: 'مِدْفَعٌ', meaning: 'Cannon' },
        { id: 'pd-hisn', ar: 'حِصْنٌ', meaning: 'Fortress' },
      ],
    },
  },

  // 4. Vocabulary Discovery: Kitchen & Dining Utensils
  {
    id: 'ch2-l1-step-4-vocab-kitchen',
    type: 'vocab_prime',
    pageNumber: 52,
    titleEn: 'Kitchen & Dining Vocabulary',
    titleAr: 'مُفْرَدَاتُ المَطْبَخِ وَالمَائِدَةِ',
    instructionEn: 'Learn new nouns for kitchen utensils, dining ware, and tableware',
    instructionBn: 'খাবার ও রান্নাঘরের তৈজসপত্রের নাম ও উচ্চারণ শুদ্ধভাবে শিখুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c2l1_mil’aqah', ar: 'مِلْعَقَةٌ', en: 'Spoon', bn: 'একটি চামচ', romanized: 'mil‘aqatun', emoji: '🥄' },
        { id: 'v1_c2l1_kub', ar: 'كُوبٌ', en: 'Glass / tumbler', bn: 'একটি গ্লাস', romanized: 'kūbun', emoji: '🥛' },
        { id: 'v1_c2l1_ibriq', ar: 'إِبْرِيقٌ', en: 'Jug / kettle', bn: 'একটি জগ / কেতলি', romanized: 'ibrīqun', emoji: '🫖' },
        { id: 'v1_c2l1_mawqid', ar: 'مَوْقِدٌ', en: 'Stove / hearth', bn: 'একটি চুলা', romanized: 'mawqidun', emoji: '🔥' },
        { id: 'v1_c2l1_finjan', ar: 'فِنْجَانٌ', en: 'Teacup', bn: 'একটি চায়ের কাপ', romanized: 'finjānun', emoji: '☕' },
        { id: 'v1_c2l1_mamlahah', ar: 'مَمْلَحَةٌ', en: 'Saltcellar', bn: 'একটি নিমকদানি', romanized: 'mamlaḥatun', emoji: '🧂' },
        { id: 'v1_c2l1_sahn', ar: 'صَحْنٌ', en: 'Plate / dish', bn: 'একটি থালা / বাসন', romanized: 'ṣaḥnun', emoji: '🍽️' },
        { id: 'v1_c2l1_matbakh', ar: 'مَطْبَخٌ', en: 'Kitchen', bn: 'একটি রান্নাঘর', romanized: 'maṭbakhun', emoji: '🍳' },
      ],
    },
  },

  // 5. Speed Pairing: Kitchen & Dining Ware
  {
    id: 'ch2-l1-step-5-pair-kitchen',
    type: 'speed_pair',
    pageNumber: 52,
    titleEn: 'Kitchen Utensils Recall Drill',
    titleAr: 'مُطَابَقَةُ أَدَوَاتِ المَطْبَخِ',
    instructionEn: 'Match each kitchen item with its meaning',
    instructionBn: 'রান্নাঘরের জিনিসপত্রগুলোর সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pk-mil’aqah', ar: 'مِلْعَقَةٌ', meaning: 'Spoon' },
        { id: 'pk-kub', ar: 'كُوبٌ', meaning: 'Glass / tumbler' },
        { id: 'pk-ibriq', ar: 'إِبْرِيقٌ', meaning: 'Jug / kettle' },
        { id: 'pk-finjan', ar: 'فِنْجَانٌ', meaning: 'Teacup' },
        { id: 'pk-matbakh', ar: 'مَطْبَخٌ', meaning: 'Kitchen' },
      ],
    },
  },

  // 6. Concept Discovery: General Question with Hal (هَلْ)
  {
    id: 'ch2-l1-step-6-concept-hal',
    type: 'concept_intro',
    pageNumber: 54,
    titleEn: 'General Question (هَلْ): Yes/No Inquiries',
    titleAr: 'السُّؤَالُ العَامُّ بِـ «هَلْ»',
    instructionEn: 'Learn how «هَلْ» asks general confirmation questions answered with «نَعَمْ» or «لَا»',
    instructionBn: '«هَلْ» দিয়ে সাধারণ হ্যাঁ/না বাচক প্রশ্ন করা হয় এবং উত্তরে «نَعَمْ» (হ্যাঁ) বা «لَا» (না) বলা হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-hal-yes',
          ar: 'هَلْ هَذَا قَلَمٌ ؟ ➔ نَعَمْ .. هَذَا قَلَمٌ',
          romanized: 'hal hādhā qalamun? ➔ na‘am .. hādhā qalamun',
          meaningEn: 'Is this a pen? ➔ Yes .. this is a pen.',
          meaningBn: 'এটি কি একটি কলম? ➔ হ্যাঁ .. এটি একটি কলম।',
          exampleAr: 'هَلْ هَذَا قَلَمٌ ؟ نَعَمْ .. هَذَا قَلَمٌ',
          exampleEn: 'Is this a pen? Yes, this is a pen.',
          exampleBn: 'এটি কি একটি কলম? হ্যাঁ, এটি একটি কলম।',
          audioKey: 'hal_hadha_qalam',
          exampleAudioKey: 'naam_hadha_qalam',
          emoji: '✏️',
          compound: {
            baseAr: 'هَذَا قَلَمٌ',
            baseRom: 'hādhā qalamun',
            baseMeaningEn: 'Statement: This is a pen',
            baseMeaningBn: 'বিবৃতি: এটি একটি কলম',
            baseAudioKey: 'hadha_qalamun',
            operator: '+',
            particleAr: 'هَلْ',
            particleEn: 'Is/Does (Yes/No Interrogative)',
            resultAr: 'هَلْ هَذَا قَلَمٌ ؟',
            resultRom: 'hal hādhā qalamun?',
            resultMeaningEn: 'General Question: Is this a pen?',
            resultMeaningBn: 'সাধারণ প্রশ্ন: এটি কি একটি কলম?',
            resultAudioKey: 'hal_hadha_qalam',
            badge: 'General Question (سُؤَالٌ عَامٌّ)',
          },
        },
        {
          id: 'cp-hal-no',
          ar: 'هَلْ هَذَا مِفْتَاحٌ ؟ ➔ لَا .. هَذَا قُفْلٌ',
          romanized: 'hal hādhā miftāḥun? ➔ lā .. hādhā quflun',
          meaningEn: 'Is this a key? ➔ No .. this is a lock.',
          meaningBn: 'এটি কি একটি চাবি? ➔ না .. এটি একটি তালা।',
          exampleAr: 'هَلْ هَذَا مِفْتَاحٌ ؟ لَا .. هَذَا قُفْلٌ',
          exampleEn: 'Is this a key? No, this is a lock.',
          exampleBn: 'এটি কি একটি চাবি? না, এটি একটি তালা।',
          audioKey: 'hal_hadha_miftah',
          exampleAudioKey: 'la_hadha_qufl',
          emoji: '🔒',
          compound: {
            baseAr: 'هَذَا قُفْلٌ',
            baseRom: 'hādhā quflun',
            baseMeaningEn: 'Reality: This is a lock',
            baseMeaningBn: 'প্রকৃত বিষয়: এটি একটি তালা',
            baseAudioKey: 'hadha_quflun',
            operator: '⇄',
            particleAr: 'لَا .. بَلْ',
            particleEn: 'Negative correction: No .. rather',
            resultAr: 'لَا .. هَذَا قُفْلٌ',
            resultRom: 'lā .. hādhā quflun',
            resultMeaningEn: 'No .. this is a lock',
            resultMeaningBn: 'না .. এটি একটি তালা',
            resultAudioKey: 'la_hadha_qufl',
            badge: 'Negative Answer (جَوَابُ النَّفْيِ)',
          },
        },
      ],
    },
  },

  // 7. Concept Discovery: Special Alternative Question (أَ ... أَمْ)
  {
    id: 'ch2-l1-step-7-concept-a-am',
    type: 'concept_intro',
    pageNumber: 54,
    titleEn: 'Alternative Question (أَ ... أَمْ): Distinct Choices',
    titleAr: 'السُّؤَالُ الخَاصُّ بِـ «أَ ... أَمْ»',
    instructionEn: 'Notice how «أَ ... أَمْ» requires naming the chosen item directly - NEVER say نَعَمْ or لَا',
    instructionBn: 'লক্ষ্য করো: «أَ ... أَمْ» (এটা না ওটা) দিয়ে প্রশ্ন করা হলে উত্তরে «نَعَمْ» বা «لَا» বলা নিষেধ; সরাসরি কাঙ্ক্ষিত বস্তুর নাম বলতে হয়!',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-a-am-nouns',
          ar: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟ ➔ قَلَمٌ',
          romanized: 'a qalamun hādhā am miftāḥun? ➔ qalamun',
          meaningEn: 'Is this a pen or a key? ➔ A pen.',
          meaningBn: 'এটি কি কলম, না চাবি? ➔ কলম।',
          exampleAr: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟ قَلَمٌ',
          exampleEn: 'Is this a pen or a key? A pen.',
          exampleBn: 'এটি কি কলম, না চাবি? কলম।',
          audioKey: 'a_qalamun_hadha_am_miftah',
          exampleAudioKey: 'qalamun',
          emoji: '🖋️',
          compound: {
            baseAr: 'قَلَمٌ أَمْ مِفْتَاحٌ',
            baseRom: 'qalamun am miftāḥun',
            baseMeaningEn: 'Alternative: A pen or a key',
            baseMeaningBn: 'বিকল্প: কলম না চাবি',
            baseAudioKey: 'qalamun_am_miftahun',
            operator: '+',
            particleAr: 'أَ ... أَمْ',
            particleEn: 'Is it [A] or [B]?',
            resultAr: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟',
            resultRom: 'a qalamun hādhā am miftāḥun?',
            resultMeaningEn: 'Special Question: Is this a pen or a key?',
            resultMeaningBn: 'বিশেষ প্রশ্ন: এটি কি কলম, না চাবি?',
            resultAudioKey: 'a_qalamun_hadha_am_miftah',
            badge: 'Alternative Choice (سُؤَالٌ خَاصٌّ)',
          },
        },
        {
          id: 'cp-a-am-pointers',
          ar: 'أَ هَذَا قَلَمٌ أَمْ ذَلِكَ ؟ ➔ ذَلِكَ',
          romanized: 'a hādhā qalamun am dhālika? ➔ dhālika',
          meaningEn: 'Is the pen this one, or that one? ➔ That one.',
          meaningBn: 'কলম কি এটি, না সেটি? ➔ সেটি।',
          exampleAr: 'أَ هَذَا قَلَمٌ أَمْ ذَلِكَ ؟ ذَلِكَ',
          exampleEn: 'Is the pen this, or that? That.',
          exampleBn: 'কলম কি এটি, না সেটি? সেটি।',
          audioKey: 'a_hadha_qalamun_am_dhalika',
          exampleAudioKey: 'dhalika',
          emoji: '👉',
          compound: {
            baseAr: 'هَذَا أَمْ ذَلِكَ',
            baseRom: 'hādhā am dhālika',
            baseMeaningEn: 'Alternative: This or that',
            baseMeaningBn: 'বিকল্প: এটি না সেটি',
            baseAudioKey: 'hadha_am_dhalika',
            operator: '+',
            particleAr: 'أَ',
            particleEn: 'Interrogative Focus',
            resultAr: 'أَ هَذَا قَلَمٌ أَمْ ذَلِكَ ؟',
            resultRom: 'a hādhā qalamun am dhālika?',
            resultMeaningEn: 'Pointer Choice: Is the pen this, or that?',
            resultMeaningBn: 'ইশারা নির্বাচন: কলম কি এটি, না সেটি?',
            resultAudioKey: 'a_hadha_qalamun_am_dhalika',
            badge: 'Demonstrative Choice (تَعْيِينُ الإِشَارَةِ)',
          },
        },
      ],
    },
  },

  // 8. Dialogic Alternative Q&A Battery 1: General Hal Inquiry (Page 53)
  {
    id: 'ch2-l1-step-8-alt-qa-hal-battery',
    type: 'alternative_qa',
    pageNumber: 53,
    titleEn: 'Dialogue Battery: General Question Verification',
    titleAr: 'حِوَارُ التَّحَقُّقِ بِـ «هَلْ»',
    instructionEn: 'Verify each object based on the visual cue and select the accurate response',
    instructionBn: 'সাধারণ প্রশ্নের উত্তরে সঠিক হ্যাঁ/না ও সংশোধিত উত্তরটি নির্বাচন করুন',
    alternativeQAPayload: {
      questions: [
        {
          id: 'qa-c2l1-1',
          questionAr: 'هَلْ ذَلِكَ مِفْتَاحٌ ؟',
          visualCue: '🖊️',
          optionsAr: ['لَا ، بَلْ ذَلِكَ قَلَمٌ', 'نَعَمْ ، ذَلِكَ مِفْتَاحٌ'],
          correctAnswerAr: 'لَا ، بَلْ ذَلِكَ قَلَمٌ',
        },
        {
          id: 'qa-c2l1-2',
          questionAr: 'هَلْ هَذِهِ دَبَّابَةٌ ؟',
          visualCue: '🚢',
          optionsAr: ['لَا ، بَلْ هَذِهِ بَاخِرَةٌ', 'نَعَمْ ، هَذِهِ دَبَّابَةٌ'],
          correctAnswerAr: 'لَا ، بَلْ هَذِهِ بَاخِرَةٌ',
        },
        {
          id: 'qa-c2l1-3',
          questionAr: 'هَلْ هَذِهِ مِلْعَقَةٌ ؟',
          visualCue: '🥛',
          optionsAr: ['لَا ، بَلْ هَذَا كُوبٌ', 'نَعَمْ ، هَذِهِ مِلْعَقَةٌ'],
          correctAnswerAr: 'لَا ، بَلْ هَذَا كُوبٌ',
        },
        {
          id: 'qa-c2l1-4',
          questionAr: 'هَلْ هَذَا كُوبٌ ؟',
          visualCue: '🫖',
          optionsAr: ['لَا ، بَلْ هَذَا إِبْرِيقٌ', 'نَعَمْ ، هَذَا كُوبٌ'],
          correctAnswerAr: 'لَا ، بَلْ هَذَا إِبْرِيقٌ',
        },
        {
          id: 'qa-c2l1-5',
          questionAr: 'هَلْ تِلْكَ نَظَّارَةٌ ؟',
          visualCue: '👓',
          optionsAr: ['نَعَمْ ، تِلْكَ نَظَّارَةٌ', 'لَا ، تِلْكَ سَاعَةٌ'],
          correctAnswerAr: 'نَعَمْ ، تِلْكَ نَظَّارَةٌ',
        },
      ],
    },
  },

  // 9. Sentence Assembly Drill 1: General Question
  {
    id: 'ch2-l1-step-9-assembly-hal-question',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Sentence Building: General Question',
    titleAr: 'تَرْكِيبُ: هَلْ هَذِهِ دَبَّابَةٌ ؟',
    instructionEn: 'Assemble: "Is this a tank?"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "এটি কি একটি ট্যাঙ্ক?"',
    assemblyPayload: {
      promptEn: 'Is this a tank?',
      promptBn: 'এটি কি একটি ট্যাঙ্ক?',
      expectedAnswer: ['هَلْ', 'هَذِهِ', 'دَبَّابَةٌ', '؟'],
      chips: ['هَلْ', 'هَذِهِ', 'دَبَّابَةٌ', '؟', 'هَذَا', 'بَاخِرَةٌ'],
      emoji: '🛡️',
    },
  },

  // 10. Authentic Reading & Translation Drill: Tank and Steamer
  {
    id: 'ch2-l1-step-10-assembly-hal-correction',
    type: 'sentence_assembly',
    pageNumber: 53,
    titleEn: 'Textbook Translation: Tank & Steamer',
    titleAr: 'اقْرَأْ وَتَرْجِمْ: الدَّبَّابَةُ وَالبَاخِرَةُ',
    instructionEn: 'Read the Arabic sentence and assemble the translation.',
    instructionBn: 'আরবি বাক্যটি পড়ুন এবং সঠিক অনুবাদ সাজিয়ে তুলুন।',
    assemblyPayload: {
      promptAr: 'تِلْكَ دَبَّابَةٌ وَهَذِهِ بَاخِرَةٌ',
      promptEn: 'That is a tank and this is a steamer',
      promptBn: 'ওটি একটি ট্যাঙ্ক এবং এটি একটি স্টীমার',
      expectedAnswer: ['That', 'is', 'a', 'tank', 'and', 'this', 'is', 'a', 'steamer'],
      chips: ['That', 'is', 'a', 'tank', 'and', 'this', 'is', 'a', 'steamer', 'cannon', 'arrow'],
      expectedAnswerBn: ['ওটি', 'একটি', 'ট্যাঙ্ক', 'এবং', 'এটি', 'একটি', 'স্টীমার'],
      chipsBn: ['ওটি', 'একটি', 'ট্যাঙ্ক', 'এবং', 'এটি', 'একটি', 'স্টীমার', 'কামান', 'তীর'],
      emoji: '🚢',
    },
  },

  // 11. Dialogic Alternative Q&A Battery 2: Specific Choice Between Objects (Page 54)
  {
    id: 'ch2-l1-step-11-alt-qa-special-objects',
    type: 'alternative_qa',
    pageNumber: 54,
    titleEn: 'Dialogue Battery: Specific Choice Between Objects',
    titleAr: 'حِوَارُ التَّعْيِينِ بَيْنَ الأَشْيَاءِ',
    instructionEn: 'Select the precise object chosen in response to each alternative inquiry',
    instructionBn: 'বিকল্প প্রশ্নগুলোর ক্ষেত্রে কাঙ্ক্ষিত বস্তুর সঠিক উত্তরটি নির্বাচন করুন',
    alternativeQAPayload: {
      contextAr: 'هَذَا قَلَمٌ وَتِلْكَ مِسْطَرَةٌ',
      contextEn: 'Premise: This is a pen and that is a ruler',
      contextBn: 'প্রেক্ষাপট: এটি কলম এবং ওটি স্কেল',
      questions: [
        {
          id: 'qa-c2l1-6',
          questionAr: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟',
          optionsAr: ['قَلَمٌ', 'مِفْتَاحٌ'],
          correctAnswerAr: 'قَلَمٌ',
        },
        {
          id: 'qa-c2l1-7',
          questionAr: 'أَ مِفْتَاحٌ هَذَا أَمْ قَلَمٌ ؟',
          optionsAr: ['قَلَمٌ', 'مِفْتَاحٌ'],
          correctAnswerAr: 'قَلَمٌ',
        },
        {
          id: 'qa-c2l1-8',
          questionAr: 'أَ مِسْطَرَةٌ هَذِهِ أَمْ قَلَمٌ ؟',
          optionsAr: ['قَلَمٌ', 'مِسْطَرَةٌ'],
          correctAnswerAr: 'قَلَمٌ',
        },
        {
          id: 'qa-c2l1-9',
          questionAr: 'أَ قَلَمٌ هَذَا أَمْ مِسْطَرَةٌ ؟',
          optionsAr: ['مِسْطَرَةٌ', 'قَلَمٌ'],
          correctAnswerAr: 'مِسْطَرَةٌ',
        },
        {
          id: 'qa-c2l1-10',
          questionAr: 'أَ سَيْفٌ هَذَا أَمْ سَهْمٌ ؟',
          contextAr: 'هَذَا سَهْمٌ',
          contextBn: 'প্রেক্ষাপট: এটি তীর',
          contextEn: 'Premise: This is an arrow',
          optionsAr: ['سَهْمٌ', 'سَيْفٌ'],
          correctAnswerAr: 'سَهْمٌ',
        },
      ],
    },
  },

  // 12. Dialogic Alternative Q&A Battery 3: Specific Choice Between Demonstrative Pointers (Page 54)
  {
    id: 'ch2-l1-step-12-alt-qa-special-pointers',
    type: 'alternative_qa',
    pageNumber: 54,
    titleEn: 'Dialogue Battery: Specific Choice Between Pointers',
    titleAr: 'حِوَارُ التَّعْيِينِ بَيْنَ الإِشَارَاتِ',
    instructionEn: 'Select the correct demonstrative pronoun specified in the inquiry',
    instructionBn: 'ইশারা নির্বাচনের বিকল্প প্রশ্নের সঠিক উত্তরটি নির্বাচন করুন',
    alternativeQAPayload: {
      contextAr: 'ذَلِكَ قَلَمٌ وَهَذَا مِفْتَاحٌ',
      contextEn: 'Premise: That is a pen and this is a key',
      contextBn: 'প্রেক্ষাপট: ওইটি কলম এবং এটি চাবি',
      questions: [
        {
          id: 'qa-c2l1-11',
          questionAr: 'أَ هَذَا قَلَمٌ أَمْ ذَلِكَ ؟',
          optionsAr: ['ذَلِكَ', 'هَذَا'],
          correctAnswerAr: 'ذَلِكَ',
        },
        {
          id: 'qa-c2l1-12',
          questionAr: 'أَ ذَلِكَ مِفْتَاحٌ أَمْ هَذَا ؟',
          optionsAr: ['هَذَا', 'ذَلِكَ'],
          correctAnswerAr: 'هَذَا',
        },
        {
          id: 'qa-c2l1-13',
          questionAr: 'أَ هَذِهِ مِسْطَرَةٌ أَمْ تِلْكَ ؟',
          optionsAr: ['تِلْكَ', 'هَذِهِ'],
          correctAnswerAr: 'تِلْكَ',
        },
        {
          id: 'qa-c2l1-14',
          questionAr: 'أَ تِلْكَ بَاخِرَةٌ أَمْ هَذِهِ ؟',
          optionsAr: ['هَذِهِ', 'تِلْكَ'],
          correctAnswerAr: 'هَذِهِ',
        },
      ],
    },
  },

  // 13. Sentence Assembly Drill 3: Choice Question (Objects)
  {
    id: 'ch2-l1-step-13-assembly-a-am-objects',
    type: 'sentence_assembly',
    pageNumber: 54,
    titleEn: 'Sentence Building: Alternative Inquiry (Objects)',
    titleAr: 'تَرْكِيبُ: أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟',
    instructionEn: 'Assemble: "Is this a pen or a key?"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "এটি কি কলম, না চাবি?"',
    assemblyPayload: {
      promptEn: 'Is this a pen or a key?',
      promptBn: 'এটি কি কলম, না চাবি?',
      expectedAnswer: ['أَ', 'قَلَمٌ', 'هَذَا', 'أَمْ', 'مِفْتَاحٌ', '؟'],
      chips: ['أَ', 'قَلَمٌ', 'هَذَا', 'أَمْ', 'مِفْتَاحٌ', '؟', 'هَلْ', 'سَيْفٌ'],
      emoji: '🖋️',
    },
  },

  // 14. Sentence Assembly Drill 4: Choice Question (Pointers)
  {
    id: 'ch2-l1-step-14-assembly-a-am-pointers',
    type: 'sentence_assembly',
    pageNumber: 54,
    titleEn: 'Sentence Building: Alternative Inquiry (Pointers)',
    titleAr: 'تَرْكِيبُ: أَ هَذَا قَلَمٌ أَمْ ذَلِكَ ؟',
    instructionEn: 'Assemble: "Is the pen this one, or that one?"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "কলম কি এটি, না সেটি?"',
    assemblyPayload: {
      promptEn: 'Is the pen this one, or that one?',
      promptBn: 'কলম কি এটি, না সেটি?',
      expectedAnswer: ['أَ', 'هَذَا', 'قَلَمٌ', 'أَمْ', 'ذَلِكَ', '؟'],
      chips: ['أَ', 'هَذَا', 'قَلَمٌ', 'أَمْ', 'ذَلِكَ', '؟', 'تِلْكَ', 'هَلْ'],
      emoji: '👉',
    },
  },

  // 15. Binary Polar Sort: Grammatical Gender of قَوْسٌ
  {
    id: 'ch2-l1-step-15-polar-qaws-gender',
    type: 'polar_sort',
    pageNumber: 51,
    titleEn: 'Morphological Concord: Gender of قَوْسٌ',
    titleAr: 'تَأْنِيثُ كَلِمَةِ «قَوْسٌ» سَمَاعًا',
    instructionEn: 'The word «قَوْسٌ» (bow) is feminine by linguistic convention in Arabic. Select its correct demonstrative pronoun:',
    instructionBn: 'আরবি ভাষায় «قَوْسٌ» (ধনুক) শব্দটি তা-মরবূতাহ ছাড়া স্বভাবগতভাবে স্ত্রীবাচক। সঠিক ইশারা নির্বাচন করুন:',
    polarPayload: {
      arabicSubject: 'قَوْسٌ',
      meaningEn: 'A bow (feminine by usage)',
      meaningBn: 'একটি ধনুক (স্ত্রীবাচক)',
      gender: 'feminine',
      correctAnswer: 'هَذِهِ',
      options: ['هَذِهِ', 'هَذَا'],
      emoji: '🏹',
    },
  },

  // 16. Sentence Assembly Drill 5: Kitchen Utensils
  {
    id: 'ch2-l1-step-16-assembly-kitchen-sentence',
    type: 'sentence_assembly',
    pageNumber: 52,
    titleEn: 'Sentence Building: In the Kitchen',
    titleAr: 'تَرْكِيبُ: فِي المَطْبَخِ مَوْقِدٌ وَ صَحْنٌ',
    instructionEn: 'Assemble: "In the kitchen is a stove and a dish"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "রান্নাঘরে একটি চুলা ও একটি থালা আছে"',
    assemblyPayload: {
      promptEn: 'In the kitchen is a stove and a dish',
      promptBn: 'রান্নাঘরে একটি চুলা ও একটি থালা আছে',
      expectedAnswer: ['فِي', 'الْمَطْبَخِ', 'مَوْقِدٌ', 'وَ', 'صَحْنٌ'],
      chips: ['فِي', 'الْمَطْبَخِ', 'مَوْقِدٌ', 'وَ', 'صَحْنٌ', 'كُوبٌ', 'مِلْعَقَةٌ'],
      emoji: '🍳',
    },
  },

  // 17. Syntactic Tarkib Dissector: General vs Alternative Interrogation
  {
    id: 'ch2-l1-step-17-tarkib-dissector',
    type: 'tarkib_dissector',
    pageNumber: 54,
    titleEn: 'Syntactic Tarkib Dissector: Interrogative Structures',
    titleAr: 'التَّرْكِيبُ النَّحْوِيُّ: أُسْلُوبُ الاِسْتِفْهَامِ العَامِّ وَالخَاصِّ',
    instructionEn: 'Dissect the syntactic constituents of the general question with «هَلْ» and the alternative choice question with «أَ ... أَمْ»',
    instructionBn: 'সাধারণ প্রশ্ন (هَلْ) এবং বিকল্প প্রশ্নের (أَ ... أَمْ) বাক্য উপাদানগুলোর ব্যাকরণগত বিশ্লেষণ সম্পন্ন করুন',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-c2l1-s1',
          sentenceAr: 'هَلْ هَذَا قَلَمٌ ؟',
          sentenceTypeAr: 'جُمْلَةٌ اسْتِفْهَامِيَّةٌ عَامَّةٌ (حَرْفُ اسْتِفْهَامٍ مَعَ مُبْتَدَأٍ وَخَبَرٍ)',
          sentenceTypeEn: 'General Interrogative Sentence (Particle + Subject + Predicate)',
          sentenceTypeBn: 'সাধারণ প্রশ্নবোধক বাক্য (অব্যয় + মুবতাদা + খবর)',
          slots: [
            {
              roleAr: 'حَرْفُ اسْتِفْهَامٍ',
              roleEn: 'Interrogative Particle (Hal)',
              roleBn: 'প্রশ্নবোধক অব্যয় (হাল)',
              expectedWordAr: 'هَلْ',
            },
            {
              roleAr: 'مُبْتَدَأٌ',
              roleEn: 'Subject Demonstrative (Mubtada)',
              roleBn: 'উদ্দেশ্য / ইশারা (মুবতাদা)',
              expectedWordAr: 'هَذَا',
            },
            {
              roleAr: 'خَبَرٌ',
              roleEn: 'Predicate (Khabar)',
              roleBn: 'বিধেয় (খবর)',
              expectedWordAr: 'قَلَمٌ',
            },
          ],
          availableWordsAr: ['قَلَمٌ', 'هَلْ', 'هَذَا'],
        },
        {
          id: 'tarkib-c2l1-s2',
          sentenceAr: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟',
          sentenceTypeAr: 'جُمْلَةٌ اسْتِفْهَامِيَّةٌ خَاصَّةٌ (هَمْزَةُ التَّسْوِيَةِ مَعَ العَطْفِ)',
          sentenceTypeEn: 'Alternative Interrogative Sentence (Focus + Subject + Conjunction + Alternative)',
          sentenceTypeBn: 'বিকল্প প্রশ্নবোধক বাক্য (হামযাহ + প্রথম বিকল্প + মুবতাদা + আম + দ্বিতীয় বিকল্প)',
          slots: [
            {
              roleAr: 'هَمْزَةُ الاِسْتِفْهَامِ',
              roleEn: 'Interrogative Hamzah',
              roleBn: 'প্রশ্নবোধক হামযাহ',
              expectedWordAr: 'أَ',
            },
            {
              roleAr: 'خَبَرٌ مُقَدَّمٌ (مُسْتَفْهَمٌ عَنْهُ)',
              roleEn: 'Fronted Predicate (Interrogated Focus)',
              roleBn: 'অগ্রবর্তী খবর (জিজ্ঞাসিত বিষয়)',
              expectedWordAr: 'قَلَمٌ',
            },
            {
              roleAr: 'مُبْتَدَأٌ مُؤَخَّرٌ',
              roleEn: 'Delayed Subject (Mubtada)',
              roleBn: 'বিলম্বিত উদ্দেশ্য (মুবতাদা)',
              expectedWordAr: 'هَذَا',
            },
            {
              roleAr: 'حَرْفُ عَطْفٍ مُعَادِلَةٌ',
              roleEn: 'Equaling Conjunction (Am)',
              roleBn: 'বিকল্প যোজক অব্যয় (আম)',
              expectedWordAr: 'أَمْ',
            },
            {
              roleAr: 'مَعْطُوفٌ',
              roleEn: 'Coordinated Alternative (Ma‘tuf)',
              roleBn: 'সংযোজিত বিকল্প পদ',
              expectedWordAr: 'مِفْتَاحٌ',
            },
          ],
          availableWordsAr: ['مِفْتَاحٌ', 'أَمْ', 'قَلَمٌ', 'هَذَا', 'أَ'],
        },
      ],
    },
  },

  // 18. Sacred Milestone: Quranic Echo (Surah At-Tur 52:35)
  {
    id: 'ch2-l1-step-18-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 54,
    titleEn: 'Sacred Reflection: Alternative Interrogation in the Quran',
    titleAr: 'الأَثَرُ القُرْآنِيُّ: الاِسْتِفْهَامُ التَّقْرِيرِيُّ بِـ «أَمْ»',
    instructionEn: 'Witness how the alternative interrogation pattern «أَمْ» elevates to divine existential inquiry in Surah At-Tur (52:35)',
    instructionBn: 'সূরা আত-তূরে ব্যবহৃত বিকল্প প্রশ্নবোধক «أَمْ» অব্যয়ের গভীর ঐশী তাৎপর্য উপলব্ধি করুন ও তেলাওয়াত শুনুন।',
    echoPayload: {
      surahNumber: 52,
      ayahNumber: 35,
      surahNameAr: 'الطُّور',
      surahNameEn: 'At-Tur',
      arabicText: 'أَمْ خُلِقُوا مِنْ غَيْرِ شَيْءٍ أَمْ هُمُ الْخَالِقُونَ',
      translationEn: 'Or were they created by nothing, or are they the creators?',
      translationBn: 'তারা কি কোনো স্রষ্টা ছাড়াই সৃষ্টি হয়েছে, নাকি তারাই সৃষ্টিকর্তা?',
      highlightedWords: ['أَمْ'],
      patternNameEn: 'Alternative Interrogation (أَ ... أَمْ)',
      patternNameBn: 'বিকল্প প্রশ্নবোধক বাক্য (أَ ... أَمْ)',
      lessonPatternAr: 'أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟',
      lessonPatternEn: 'Is this a pen or a key?',
      lessonPatternBn: 'এটি কি কলম, না চাবি?',
      quranPatternAr: 'أَمْ خُلِقُوا مِنْ غَيْرِ شَيْءٍ أَمْ هُمُ الْخَالِقُونَ',
      quranPatternEn: 'Or were they created by nothing, or are they the creators?',
      quranPatternBn: 'তারা কি কোনো স্রষ্টা ছাড়াই সৃষ্টি হয়েছে, নাকি তারাই সৃষ্টিকর্তা?',
      reflection: "In Arabic, «أَمْ» serves as the disjunctive interrogation particle used specifically when offering distinct alternatives. In your lesson, you used «أَ قَلَمٌ هَذَا أَمْ مِفْتَاحٌ ؟» to contrast concrete objects. In the Quran, Allah employs this exact grammatical formula to challenge the human intellect with profound existential choices.",
      audioKey: 'quran_052035',
    },
  },
];

export const CH2_LESSON_01_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 2,
  lessonNum: 1,
  titleEn: 'General & Choice Questions',
  titleAr: 'السُّؤَالُ العَامُّ وَالخَاصُّ',
  wordsLearned: [
    'بُنْدُقِيَّةٌ',
    'دَبَّابَةٌ',
    'قُنْبُلَةٌ',
    'سَيْفٌ',
    'بَاخِرَةٌ',
    'مِدْفَعٌ',
    'حِصْنٌ',
    'سَهْمٌ',
    'قَوْسٌ',
    'مِلْعَقَةٌ',
    'كُوبٌ',
    'إِبْرِيقٌ',
    'مَوْقِدٌ',
    'فِنْجَانٌ',
    'مَمْلَحَةٌ',
    'صَحْنٌ',
    'مَطْبَخٌ',
  ],
  steps: CH2_LESSON_01_STEPS,
};
