// Lesson 8 Interactive Session Data (Directly mapped from Esho Arbi Shikhi Vol 1 Ch 1 Lesson 8, pages 43-45)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const LESSON_08_STEPS: SessionStep[] = [
  // 1. Page 43: Concept Discovery - Preposition فِي and Genitive Case
  {
    id: 'step-1-concept-fi-intro',
    type: 'concept_intro',
    pageNumber: 43,
    titleEn: 'Preposition فِي (In)',
    titleAr: 'حَرْفُ الجَرِّ «فِي»',
    instructionEn: 'Notice how فِي gives the noun a Kasrah (ـِ)',
    instructionBn: 'লক্ষ্য করো: فِي যুক্ত হলে শব্দের শেষে কাসরা (যের) হয়',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-fi-masjid',
          ar: 'الْمَسْجِدُ ➔ فِي الْمَسْجِدِ',
          romanized: 'al-masjidu ➔ fī al-masjidi',
          meaningEn: 'The mosque ➔ In the mosque',
          meaningBn: 'মসজিদটি ➔ মসজিদে',
          exampleAr: 'الرَّجُلُ فِي الْمَسْجِدِ',
          exampleEn: 'The man is in the mosque.',
          exampleBn: 'লোকটি মসজিদে আছে।',
          audioKey: 'fi_al_masjid',
          exampleAudioKey: 'ar_rajulu_fi_al_masjid',
          emoji: '🕌',
          compound: {
            baseAr: 'الْمَسْجِدُ',
            baseRom: 'al-masjidu',
            baseMeaningEn: 'The mosque',
            baseMeaningBn: 'মসজিদটি',
            baseAudioKey: 'al_masjidu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي الْمَسْجِدِ',
            resultRom: 'fī al-masjidi',
            resultMeaningEn: 'In the mosque',
            resultMeaningBn: 'মসজিদে',
            resultAudioKey: 'fi_al_masjid',
            badge: 'Kasrah Shift (مَجْرُور)',
          },
        },
        {
          id: 'cp-fi-qaryah',
          ar: 'الْقَرْيَةُ ➔ فِي الْقَرْيَةِ',
          romanized: 'al-qaryatu ➔ fī al-qaryati',
          meaningEn: 'The village ➔ In the village',
          meaningBn: 'গ্রামটি ➔ গ্রামে',
          exampleAr: 'الْمَرْأَةُ فِي الْقَرْيَةِ',
          exampleEn: 'The woman is in the village.',
          exampleBn: 'মহিলাটি গ্রামে আছে।',
          audioKey: 'fi_al_qaryah',
          exampleAudioKey: 'al_maratu_fi_al_qaryah',
          emoji: '🏡',
          compound: {
            baseAr: 'الْقَرْيَةُ',
            baseRom: 'al-qaryatu',
            baseMeaningEn: 'The village',
            baseMeaningBn: 'গ্রামটি',
            baseAudioKey: 'al_qaryatu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي الْقَرْيَةِ',
            resultRom: 'fī al-qaryati',
            resultMeaningEn: 'In the village',
            resultMeaningBn: 'গ্রামে',
            resultAudioKey: 'fi_al_qaryah',
            badge: 'Kasrah Shift (مَجْرُور)',
          },
        },
      ],
    },
  },

  // 2. Page 43: Attached Pronouns with فِي
  {
    id: 'step-2-concept-fi-pronouns',
    type: 'concept_intro',
    pageNumber: 43,
    titleEn: 'Attached Pronouns with فِي',
    titleAr: 'الضَّمَائِرُ الْمُتَّصِلَةُ مَعَ «فِي»',
    instructionEn: 'Notice how nouns with attached pronouns shift to Kasrah after فِي',
    instructionBn: 'সর্বনামযুক্ত শব্দের ক্ষেত্রেও فِي-এর পর কাসরা বিশিষ্ট রূপ ধারণ করে।',
    conceptPayload: {
      concepts: [
        {
          id: 'cp-fi-ghurfatihi',
          ar: 'غُرْفَتُهُ ➔ فِي غُرْفَتِهِ',
          romanized: 'ghurfatuhu ➔ fī ghurfatihi',
          meaningEn: 'His room ➔ In his room',
          meaningBn: 'তার কামরা ➔ তার কামরায়',
          exampleAr: 'هُوَ فِي غُرْفَتِهِ',
          exampleEn: 'He is in his room.',
          exampleBn: 'সে তার কামরায় আছে।',
          audioKey: 'fi_ghurfatihi',
          exampleAudioKey: 'huwa_fi_ghurfatihi',
          emoji: '🚪',
          compound: {
            baseAr: 'غُرْفَتُهُ',
            baseRom: 'ghurfatuhu',
            baseMeaningEn: 'His room',
            baseMeaningBn: 'তার কামরা',
            baseAudioKey: 'ghurfatuhu',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي غُرْفَتِهِ',
            resultRom: 'fī ghurfatihi',
            resultMeaningEn: 'In his room',
            resultMeaningBn: 'তার কামরায়',
            resultAudioKey: 'fi_ghurfatihi',
            badge: 'Pronoun Genitive Kasrah',
          },
        },
        {
          id: 'cp-fi-ghurfatiha',
          ar: 'غُرْفَتُهَا ➔ فِي غُرْفَتِهَا',
          romanized: 'ghurfatuhā ➔ fī ghurfatihā',
          meaningEn: 'Her room ➔ In her room',
          meaningBn: 'তার কামরা ➔ তার কামরায়',
          exampleAr: 'عَائِشَةُ فِي غُرْفَتِهَا',
          exampleEn: 'Aisha is in her room.',
          exampleBn: 'আয়েশা তার কামরায় আছে।',
          audioKey: 'fi_ghurfatiha',
          exampleAudioKey: 'aishatu_fi_ghurfatiha',
          emoji: '🛏️',
          compound: {
            baseAr: 'غُرْفَتُهَا',
            baseRom: 'ghurfatuhā',
            baseMeaningEn: 'Her room',
            baseMeaningBn: 'তার কামরা',
            baseAudioKey: 'ghurfatuha',
            operator: '+',
            particleAr: 'فِي',
            particleEn: 'in',
            resultAr: 'فِي غُرْفَتِهَا',
            resultRom: 'fī ghurfatihā',
            resultMeaningEn: 'In her room',
            resultMeaningBn: 'তার কামরায়',
            resultAudioKey: 'fi_ghurfatiha',
            badge: 'Pronoun Genitive Kasrah',
          },
        },
      ],
    },
  },

  // 3. Page 43: Active Recall Matching - Location Phrases
  {
    id: 'step-3-pair-fi-locations',
    type: 'speed_pair',
    pageNumber: 43,
    titleEn: 'Location Recall Drill',
    titleAr: 'تَطْبِيقُ عِبَارَاتِ «فِي»',
    instructionEn: 'Match each location phrase with its English meaning',
    instructionBn: 'স্থানবাচক বাক্যাংশগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pfl-1', ar: 'فِي الْمَسْجِدِ', meaning: 'In the mosque' },
        { id: 'pfl-2', ar: 'فِي الْغُرْفَةِ', meaning: 'In the room' },
        { id: 'pfl-3', ar: 'فِي الصُّنْدُوقِ', meaning: 'In the box' },
        { id: 'pfl-4', ar: 'فِي الْحَدِيقَةِ', meaning: 'In the garden' },
      ],
    },
  },

  // 4. Page 43: Dialogue Q&A - Who is in the mosque?
  {
    id: 'step-4-cloze-man-fi-masjid',
    type: 'cloze_choice',
    pageNumber: 43,
    titleEn: 'Dialogue Practice: In the Mosque',
    titleAr: 'مَنْ فِي الْمَسْجِدِ ؟',
    instructionEn: 'Complete the answer: "A man is in the mosque"',
    instructionBn: 'সঠিক শব্দটি নির্বাচন করে উত্তর দিন: "মসজিদে একজন লোক আছে"',
    clozePayload: {
      questionAr: 'مَنْ فِي الْمَسْجِدِ ؟',
      questionEn: 'Who is in the mosque?',
      questionBn: 'মসজিদে কে আছে?',
      partialAnswerAr: 'فِي الْمَسْجِدِ ...',
      correctAnswer: 'رَجُلٌ',
      options: ['رَجُلٌ', 'كِتَابٌ', 'سَيَّارَةٌ'],
      emoji: '🕌',
    },
  },

  // 5. Page 43: Dialogue Q&A - Where is the man?
  {
    id: 'step-5-cloze-ayna-rajul',
    type: 'cloze_choice',
    pageNumber: 43,
    titleEn: 'Dialogue Practice: Where is the Man?',
    titleAr: 'أَيْنَ الرَّجُلُ ؟',
    instructionEn: 'Complete the response: "He is in the mosque"',
    instructionBn: 'সঠিক উত্তরটি নির্বাচন করুন: "সে মসজিদে আছে"',
    clozePayload: {
      questionAr: 'أَيْنَ الرَّجُلُ ؟',
      questionEn: 'Where is the man?',
      questionBn: 'লোকটি কোথায়?',
      partialAnswerAr: 'هُوَ ...',
      correctAnswer: 'فِي الْمَسْجِدِ',
      options: ['فِي الْمَسْجِدِ', 'فَوْقَ الْمَسْجِدِ', 'وَرَاءَ الْبَابِ'],
      emoji: '🧍',
    },
  },

  // 6. Page 44: Dialogue Q&A - What is in Aisha's bag?
  {
    id: 'step-6-cloze-maza-fi-haqibah',
    type: 'cloze_choice',
    pageNumber: 44,
    titleEn: "Dialogue Practice: Aisha's Bag",
    titleAr: 'مَاذَا فِي حَقِيبَةِ عَائِشَةَ ؟',
    instructionEn: 'Complete the answer: "A book and a pen are in Aisha\'s bag"',
    instructionBn: 'সঠিক উত্তর নির্বাচন করুন: "আয়েশার ব্যাগে একটি বই ও একটি কলম আছে"',
    clozePayload: {
      questionAr: 'مَاذَا فِي حَقِيبَةِ عَائِشَةَ ؟',
      questionEn: "What is in Aisha's bag?",
      questionBn: 'আয়েশার ব্যাগে কী আছে?',
      partialAnswerAr: 'فِي حَقِيبَةِ عَائِشَةَ ...',
      correctAnswer: 'كِتَابٌ وَقَلَمٌ',
      options: ['كِتَابٌ وَقَلَمٌ', 'سَاعَةٌ فَقَطْ', 'مِفْتَاحٌ وَقُفْلٌ'],
      emoji: '🎒',
    },
  },

  // 7. Page 44: Vocabulary Priming - Lesson 8 Core Nouns
  {
    id: 'step-7-vocab-lesson8-nouns',
    type: 'vocab_prime',
    pageNumber: 44,
    titleEn: 'Places & Environment Vocabulary',
    titleAr: 'مُفْرَدَاتُ الأَمَاكِنِ وَالبِيئَةِ',
    instructionEn: 'Listen and memorize new words for places and environment',
    instructionBn: 'নতুন স্থান ও পরিবেশ সম্পর্কিত শব্দগুলোর উচ্চারণ শুনুন ও অর্থ জানুন।',
    vocabPayload: {
      words: [
        { id: 'v1_c8_dukkan', ar: 'دُكَّانٌ', en: 'Shop / store', bn: 'একটি দোকান', romanized: 'dukkānun', emoji: '🏪' },
        { id: 'v1_c8_shajarah', ar: 'شَجَرَةٌ', en: 'Tree', bn: 'একটি গাছ', romanized: 'shajaratun', emoji: '🌳' },
        { id: 'v1_c8_sunduq', ar: 'صُنْدُوقٌ', en: 'Box / chest', bn: 'একটি বাক্স', romanized: 'ṣundūqun', emoji: '📦' },
        { id: 'v1_c8_hadiqah', ar: 'حَدِيقَةٌ', en: 'Garden', bn: 'একটি বাগান', romanized: 'ḥadīqatun', emoji: '🏡' },
        { id: 'v1_c8_qabr', ar: 'قَبْرٌ', en: 'Grave', bn: 'একটি কবর', romanized: 'qabrun', emoji: '🪦' },
        { id: 'v1_c8_madinah_munawwarah', ar: 'الْمَدِينَةُ الْمُنَوَّرَةُ', en: 'Madinah Al-Munawwarah', bn: 'মদীনা মুনাওয়ারা', romanized: 'al-madīnatu al-munawwaratu', emoji: '🕌' },
      ],
    },
  },

  // 8. Page 44: Active Recall Matching - Core Nouns
  {
    id: 'step-8-pair-lesson8-nouns',
    type: 'speed_pair',
    pageNumber: 44,
    titleEn: 'Vocabulary Drill',
    titleAr: 'مُطَابَقَةُ مُفْرَدَاتِ الدَّرْسِ',
    instructionEn: 'Match each Arabic noun with its meaning',
    instructionBn: 'শব্দগুলোর সাথে সঠিক অর্থ মিলিয়ে নিন',
    pairPayload: {
      pairs: [
        { id: 'pn-dukkan', ar: 'دُكَّانٌ', meaning: 'Shop / store' },
        { id: 'pn-shajarah', ar: 'شَجَرَةٌ', meaning: 'Tree' },
        { id: 'pn-sunduq', ar: 'صُنْدُوقٌ', meaning: 'Box / chest' },
        { id: 'pn-hadiqah', ar: 'حَدِيقَةٌ', meaning: 'Garden' },
        { id: 'pn-qabr', ar: 'قَبْرٌ', meaning: 'Grave' },
      ],
    },
  },

  // 9. Page 44: Sentence Assembly - Tree in the Garden
  {
    id: 'step-9-assembly-shajarah-hadiqah',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: 'Sentence Building: Garden Tree',
    titleAr: 'تَرْكِيبُ: فِي الحَدِيقَةِ شَجَرَةٌ كَبِيرَةٌ',
    instructionEn: 'Assemble: "There is a big tree in the garden"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "বাগানে একটি বড় গাছ আছে"',
    assemblyPayload: {
      promptEn: 'There is a big tree in the garden',
      promptBn: 'বাগানে একটি বড় গাছ আছে',
      expectedAnswer: ['فِي', 'الْحَدِيقَةِ', 'شَجَرَةٌ', 'كَبِيرَةٌ'],
      chips: ['فِي', 'الْحَدِيقَةِ', 'شَجَرَةٌ', 'كَبِيرَةٌ', 'صَغِيرَةٌ', 'مَسْجِدٌ'],
      emoji: '🌳',
    },
  },

  // 10. Page 44: Sentence Assembly - Aisha in Her Room
  {
    id: 'step-10-assembly-aisha-room',
    type: 'sentence_assembly',
    pageNumber: 44,
    titleEn: 'Sentence Building: Aisha in Her Room',
    titleAr: 'تَرْكِيبُ: عَائِشَةُ فِي غُرْفَتِهَا',
    instructionEn: 'Assemble: "Aisha is in her room"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "আয়েশা তার কামরায় আছে"',
    assemblyPayload: {
      promptEn: 'Aisha is in her room',
      promptBn: 'আয়েশা তার কামরায় আছে',
      expectedAnswer: ['عَائِشَةُ', 'فِي', 'غُرْفَتِهَا'],
      chips: ['عَائِشَةُ', 'فِي', 'غُرْفَتِهَا', 'غُرْفَتِهِ', 'الْبَيْتِ'],
      emoji: '🛏️',
    },
  },

  // 11. Page 45: Dialogue Q&A - In Whose Heart is Light?
  {
    id: 'step-11-cloze-nur-qalb',
    type: 'cloze_choice',
    pageNumber: 45,
    titleEn: 'Spiritual Reading: Light in the Heart',
    titleAr: 'فِي قَلْبِ مَنِ النُّورُ ؟',
    instructionEn: 'Complete the response: "In the heart of the Muslim is light"',
    instructionBn: 'সঠিক উত্তর নির্বাচন করুন: "মুসলমানের অন্তরে আলো রয়েছে"',
    clozePayload: {
      questionAr: 'فِي قَلْبِ مَنِ النُّورُ ؟',
      questionEn: 'In whose heart is light?',
      questionBn: 'কার অন্তরে আলো রয়েছে?',
      partialAnswerAr: 'فِي قَلْبِ ... نُورٌ',
      correctAnswer: 'الْمُسْلِمِ',
      options: ['الْمُسْلِمِ', 'الْكَافِرِ', 'التَّاجِرِ'],
      emoji: '💚',
    },
  },

  // 12. Page 45: Sentence Assembly - The Messenger's Grave
  {
    id: 'step-12-assembly-qabru-rasul',
    type: 'sentence_assembly',
    pageNumber: 45,
    titleEn: "Islamic Reading: The Messenger's Grave",
    titleAr: 'تَرْكِيبُ: قَبْرُ الرَّسُولِ فِي المَدِينَةِ المُنَوَّرَةِ',
    instructionEn: 'Assemble: "The grave of the Messenger is in Madinah Al-Munawwarah"',
    instructionBn: 'শব্দগুলো সাজিয়ে লিখুন: "রাসূলের কবর মদীনা মুনাওয়ারায়"',
    assemblyPayload: {
      promptEn: "The grave of the Messenger is in Madinah Al-Munawwarah",
      promptBn: 'রাসূলের কবর মদীনা মুনাওয়ারায়',
      expectedAnswer: ['قَبْرُ', 'الرَّسُولِ', 'فِي', 'الْمَدِينَةِ', 'الْمُنَوَّرَةِ'],
      chips: ['قَبْرُ', 'الرَّسُولِ', 'فِي', 'الْمَدِينَةِ', 'الْمُنَوَّرَةِ', 'مَكَّةَ'],
      emoji: '🕌',
    },
  },

  // 13. Sacred Milestone: Quranic Echo (Surah Al-Baqarah 2:255)
  {
    id: 'step-13-quranic-echo',
    type: 'quranic_echo',
    pageNumber: 45,
    titleEn: 'Quranic Milestone',
    titleAr: 'الأَثَرُ القُرْآنِيُّ',
    instructionEn: 'Listen and observe the preposition فِي in Ayat al-Kursi (2:255)',
    instructionBn: 'আয়াতুল কুরসীতে ব্যবহৃত «فِي» হরফে জরের প্রয়োগ লক্ষ্য করুন ও শুদ্ধভাবে শুনুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 255,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      translationEn: 'To Him belongs whatever is in the heavens and whatever is in the earth.',
      translationBn: 'আসমান ও যমীনে যা কিছু আছে সবই তাঁর।',
      highlightedWords: ['فِي', 'السَّمَاوَاتِ', 'الْأَرْضِ'],
      reflection: "Notice the preposition 'فِي' (in) appearing twice in Ayat al-Kursi, governing both 'السَّمَاوَاتِ' (the heavens) and 'الْأَرْضِ' (the earth) into the genitive state.",
      audioKey: 'quran_002255',
    },
  },
];

export const LESSON_08_SESSION: LessonSessionData = {
  volumeId: 1,
  chapterId: 1,
  lessonNum: 8,
  titleEn: 'Preposition فِي and Genitive Case',
  titleAr: 'حَرْفُ الجَرِّ «فِي» وَحَالَةُ الجَرِّ',
  wordsLearned: [
    'فِي',
    'دُكَّانٌ',
    'شَجَرَةٌ',
    'صُنْدُوقٌ',
    'حَدِيقَةٌ',
    'قَبْرٌ',
    'الْمَدِينَةُ الْمُنَوَّرَةُ',
  ],
  steps: LESSON_08_STEPS,
};
