import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_07_STEPS: SessionStep[] = [
  // 1. Page 44-47: Concept Discovery - Form IV (Baab al-If'aal - بَابُ الإِفْعَالِ)
  {
    id: 'v2-c1-l7-step-1-concept-if-aal',
    type: 'concept_intro',
    pageNumber: 44,
    titleEn: 'Form IV Causative: Baab al-If\'aal (بَابُ الإِفْعَالِ)',
    titleAr: 'مَدْخَلُ بَابِ الإِفْعَالِ (أَفْعَلَ يُفْعِلُ أَفْعِلْ)',
    instructionEn: 'Observe how adding a hamzah prefix transforms intransitive Form I verbs into transitive causative Form IV verbs, and how hollow roots shift.',
    instructionBn: 'শুরুতে হামযাহ যুক্ত হয়ে কীভাবে ১ম বাবের অকর্মক ক্রিয়া ৪র্থ বাবে (বাবুল ইফ\'আল) সকর্মক ও কারণিক রূপ নেয় এবং আজওয়াফ ধাতুর পরিবর্তন লক্ষ্য করুন।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-if-aal-akhraja',
          ar: 'أَخْرَجَ يُخْرِجُ أَخْرِجْ',
          romanized: 'akhraja yukhriju akhrij',
          meaningEn: 'Causative: He brought out / He brings out / Bring out!',
          meaningBn: 'বের করল / বের করে / বের করো!',
          exampleAr: 'أَخْرَجَ رَاشِدٌ خَالِدًا مِنَ الغُرْفَةِ',
          exampleEn: 'Rashid brought Khalid out of the room.',
          exampleBn: 'রাশেদ খালেদকে কামরা থেকে বের করল।',
          audioKey: 'أَخْرَجَ يُخْرِجُ أَخْرِجْ',
          exampleAudioKey: 'أَخْرَجَ رَاشِدٌ خَالِدًا مِنَ الغُرْفَةِ',
          emoji: '🚪',
        },
        {
          id: 'c-if-aal-anzala',
          ar: 'أَنْزَلَ يُنْزِلُ أَنْزِلْ',
          romanized: 'anzala yunzilu anzil',
          meaningEn: 'Reveal / Send Down: He sent down / He sends down / Send down!',
          meaningBn: 'নাযিল করল / নাযিল করে / নাযিল করো!',
          exampleAr: 'أَنْزَلَ اللهُ القُرْآنَ عَلَى رَسُولِهِ',
          exampleEn: 'Allah revealed the Quran upon His Messenger.',
          exampleBn: 'আল্লাহ তাঁর রাসূলের উপর কুরআন নাযিল করেছেন।',
          audioKey: 'أَنْزَلَ يُنْزِلُ أَنْزِلْ',
          exampleAudioKey: 'أَنْزَلَ اللهُ القُرْآنَ عَلَى رَسُولِهِ',
          emoji: '📖',
        },
        {
          id: 'c-if-aal-ajaba',
          ar: 'أَجَابَ يُجِيبُ أَجِبْ',
          romanized: 'ajāba yujību ajib',
          meaningEn: 'Hollow Form IV: He answered / He answers / Answer!',
          meaningBn: 'আজওয়াফ ৪র্থ বাব: সে উত্তর দিল / সে উত্তর দেয় / উত্তর দাও!',
          exampleAr: 'أَجَابَ التِّلْمِيذُ عَلَى سُؤَالِ المُعَلِّمِ',
          exampleEn: 'The student answered the teacher\'s question.',
          exampleBn: 'ছাত্রটি শিক্ষকের প্রশ্নের উত্তর দিল।',
          audioKey: 'أَجَابَ يُجِيبُ أَجِبْ',
          exampleAudioKey: 'أَجَابَ التِّلْمِيذُ عَلَى سُؤَالِ المُعَلِّمِ',
          emoji: '🙋',
        },
        {
          id: 'c-if-aal-ata-a',
          ar: 'أَطَاعَ يُطِيعُ أَطِعْ',
          romanized: 'aṭā‘a yuṭī‘u aṭi‘',
          meaningEn: 'Obey: He obeyed / He obeys / Obey!',
          meaningBn: 'আনুগত্য করল / আনুগত্য করে / আনুগত্য করো!',
          exampleAr: 'أَطِعِ الرَّحْمَنَ وَلَا تُطِعِ الشَّيْطَانَ',
          exampleEn: 'Obey the Most Merciful and do not obey Satan.',
          exampleBn: 'দয়াময়ের আনুগত্য করো এবং শয়তানের আনুগত্য করো না।',
          audioKey: 'أَطَاعَ يُطِيعُ أَطِعْ',
          exampleAudioKey: 'أَطِعِ الرَّحْمَنَ وَلَا تُطِعِ الشَّيْطَانَ',
          emoji: '🤲',
        },
      ],
    },
  },

  // 2. Page 44: Verb Conjugator - أَخْرَجَ يُخْرِجُ (Bab al-If'aal)
  {
    id: 'v2-c1-l7-step-2-conjugator-akhraja',
    type: 'verb_conjugator',
    pageNumber: 44,
    titleEn: 'Verb Paradigm: أَخْرَجَ يُخْرِجُ (To Bring Out / Expel)',
    titleAr: 'تَصْرِيفُ فِعْلِ: أَخْرَجَ يُخْرِجُ (بَابُ الإِفْعَالِ)',
    instructionEn: 'Explore how Form IV takes a damma prefix in the present (يُخْرِجُ) and sukoon-kasra-sukoon in the imperative (أَخْرِجْ).',
    instructionBn: 'লক্ষ্য করুন কীভাবে ৪র্থ বাবের বর্তমানকালে শুরুতে পেশ (يُخْرِجُ) এবং আদেশে হামযায় যবর ও শেষ অক্ষরে সাকিন (أَخْرِجْ) হয়।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'past',
      verbs: [
        {
          id: 'verb_akhraja',
          rootAr: 'خ ر ج',
          masdarAr: 'إِخْرَاجٌ',
          meaningEn: 'To bring out / expel',
          meaningBn: 'বের করা',
          baabAr: 'بَابُ الإِفْعَالِ',
          baabEn: 'Bab al-If\'aal (Form IV)',
          emoji: '🚪',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'أَخْرَجَ',
              presentAr: 'يُخْرِجُ',
              imperativeAr: 'أَخْرِجْ',
              pastMeaningEn: 'He brought out',
              pastMeaningBn: 'সে বের করল',
              presentMeaningEn: 'He brings out',
              presentMeaningBn: 'সে বের করে',
              audioKey: 'أَخْرَجَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'أَخْرَجَتْ',
              presentAr: 'تُخْرِجُ',
              imperativeAr: 'أَخْرِجِي',
              pastMeaningEn: 'She brought out',
              pastMeaningBn: 'সে বের করল',
              presentMeaningEn: 'She brings out',
              presentMeaningBn: 'সে বের করে',
              audioKey: 'أَخْرَجَتْ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'أَخْرَجْتَ',
              presentAr: 'تُخْرِجُ',
              imperativeAr: 'أَخْرِجْ',
              pastMeaningEn: 'You brought out',
              pastMeaningBn: 'তুমি বের করলে',
              presentMeaningEn: 'You bring out',
              presentMeaningBn: 'তুমি বের করো',
              audioKey: 'أَخْرَجْتَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'أَخْرَجْتِ',
              presentAr: 'تُخْرِجِينَ',
              imperativeAr: 'أَخْرِجِي',
              pastMeaningEn: 'You brought out (f)',
              pastMeaningBn: 'তুমি বের করলে',
              presentMeaningEn: 'You bring out (f)',
              presentMeaningBn: 'তুমি বের করো',
              audioKey: 'أَخْرَجْتِ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'أَخْرَجْتُ',
              presentAr: 'أُخْرِجُ',
              imperativeAr: 'أَخْرِجْ',
              pastMeaningEn: 'I brought out',
              pastMeaningBn: 'আমি বের করলাম',
              presentMeaningEn: 'I bring out',
              presentMeaningBn: 'আমি বের করি',
              audioKey: 'أَخْرَجْتُ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 45: Word Construction - Deriving Form IV Verbs from Masdars (بَابُ الإِفْعَالِ)
  {
    id: 'v2-c1-l7-step-3-word-construction-if-aal',
    type: 'word_construction',
    pageNumber: 45,
    titleEn: 'Word Construction: Deriving Form IV Verbs from Masdars',
    titleAr: 'اشْتِقَاقُ بَابِ الإِفْعَالِ مِنَ المَصْدَرِ: بِنَاءُ الكَلِمَةِ',
    instructionEn: 'Derive the Form IV verb forms from the verbal nouns, observing prefix patterns and vowel changes.',
    instructionBn: 'মাছদার থেকে ৪র্থ বাবের (বাবুল ইফ\'আল) ক্রিয়া রূপগুলো গঠন করুন এবং শুরুতে হামযাহ ও পেশের ব্যবহার লক্ষ্য করুন।',
    itemId: 'v2_l7_word_construction_if_aal',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-l7-anfaqa',
          sourceWordAr: 'الإِنْفَاقُ',
          sourceWordLabelEn: 'Form IV Masdar',
          sourceWordLabelBn: '৪র্থ বাবের মাছদার',
          targetWordAr: 'أَنْفَقَ',
          promptEn: 'Derive the 3rd person masculine Past: "He spent"',
          promptBn: '৩য় পুরুষ পুংলিঙ্গ অতীত ক্রিয়া গঠন করুন: "সে খরচ করল"',
          targetMeaningEn: 'He spent',
          targetMeaningBn: 'সে খরচ করল',
          chips: ['أَ', 'نْ', 'فَ', 'قَ', 'يُ', 'فِ', 'قُ'],
          emoji: '💰',
        },
        {
          id: 'wc-l7-yursilu',
          sourceWordAr: 'الإِرْسَالُ',
          sourceWordLabelEn: 'Form IV Masdar',
          sourceWordLabelBn: '৪র্থ বাবের মাছদার',
          targetWordAr: 'يُرْسِلُ',
          promptEn: 'Derive the 3rd person masculine Present: "He sends" (Prefix with Dammah)',
          promptBn: '৩য় পুরুষ পুংলিঙ্গ বর্তমান ক্রিয়া গঠন করুন: "সে পাঠায়" (পেশযুক্ত মুদারীর হরফ সহ)',
          targetMeaningEn: 'He sends',
          targetMeaningBn: 'সে পাঠায়',
          chips: ['يُ', 'رْ', 'سِ', 'لُ', 'يَ', 'سَ', 'لَ'],
          emoji: '✉️',
        },
        {
          id: 'wc-l7-akrim',
          sourceWordAr: 'الإِكْرَامُ',
          sourceWordLabelEn: 'Form IV Masdar',
          sourceWordLabelBn: '৪র্থ বাবের মাছদার',
          targetWordAr: 'أَكْرِمْ',
          promptEn: 'Derive the Command (Amr): "Honor!" (m) (Hamzatul-Qat\' with Fathah)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "সম্মান করো!" (যবরযুক্ত হামযাতুল ক্বাত\' সহ)',
          targetMeaningEn: 'Honor! (m)',
          targetMeaningBn: 'সম্মান করো!',
          chips: ['أَ', 'كْ', 'رِ', 'مْ', 'اِ', 'رَ', 'مُ'],
          emoji: '👑',
        },
        {
          id: 'wc-l7-at-im',
          sourceWordAr: 'الإِطْعَامُ',
          sourceWordLabelEn: 'Form IV Masdar',
          sourceWordLabelBn: '৪র্থ বাবের মাছদার',
          targetWordAr: 'أَطْعِمْ',
          promptEn: 'Derive the Command (Amr): "Feed!" (m) (Hamzatul-Qat\' with Fathah)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "খাওয়ানো / খাবার দাও!" (যবরযুক্ত হামযাতুল ক্বাত\' সহ)',
          targetMeaningEn: 'Feed! (m)',
          targetMeaningBn: 'খাবার দাও!',
          chips: ['أَ', 'طْ', 'عِ', 'مْ', 'اِ', 'عَ', 'مُ'],
          emoji: '🍲',
        },
      ],
    },
  },

  // 4. Page 44-47: Vocab Prime - Essential Form IV Verbs & Nouns
  {
    id: 'v2-c1-l7-step-4-vocab-if-aal',
    type: 'vocab_prime',
    pageNumber: 44,
    titleEn: 'Vocabulary: Form IV Verbs & Spiritual Terms',
    titleAr: 'مُفْرَدَاتُ بَابِ الإِفْعَالِ',
    instructionEn: 'Listen to the newly introduced Form IV verbs and key vocabulary.',
    instructionBn: 'নতুন ৪র্থ বাবের ক্রিয়া ও শব্দগুলোর অর্থ মনোযোগ দিয়ে শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_akhraja', ar: 'أَخْرَجَ يُخْرِجُ', en: 'To Bring Out / Expel', bn: 'বের করা', romanized: 'akhraja yukhriju', emoji: '🚪' },
        { id: 'v2_anzala', ar: 'أَنْزَلَ يُنْزِلُ', en: 'To Reveal / Send Down', bn: 'নাযিল করা', romanized: 'anzala yunzilu', emoji: '📖' },
        { id: 'v2_afhama', ar: 'أَفْهَمَ يُفْهِمُ', en: 'To Explain', bn: 'বোঝানো', romanized: 'afhama yufhimu', emoji: '💡' },
        { id: 'v2_adkhala', ar: 'أَدْخَلَ يُدْخِلُ', en: 'To Admit / Enter', bn: 'প্রবেশ করানো', romanized: 'adkhala yudkhilu', emoji: '🗝️' },
        { id: 'v2_albasa', ar: 'أَلْبَسَ يُلْبِسُ', en: 'To Clothe / Dress', bn: 'পরিধান করানো', romanized: 'albasa yulbisu', emoji: '👕' },
        { id: 'v2_anfaqa', ar: 'أَنْفَقَ يُنْفِقُ', en: 'To Spend (Wealth)', bn: 'খরচ করা', romanized: 'anfaqa yunfiqu', emoji: '💰' },
        { id: 'v2_akrama', ar: 'أَكْرَمَ يُكْرِمُ', en: 'To Honor / Treat Generously', bn: 'সম্মান করা', romanized: 'akrama yukrimu', emoji: '🤝' },
        { id: 'v2_arsala', ar: 'أَرْسَلَ يُرْسِلُ', en: 'To Send (Messenger/Letter)', bn: 'পাঠানো', romanized: 'arsala yursilu', emoji: '✉️' },
        { id: 'v2_at-ama', ar: 'أَطْعَمَ يُطْعِمُ', en: 'To Feed', bn: 'খাওয়ানো', romanized: 'aṭ‘ama yuṭ‘imu', emoji: '🍲' },
        { id: 'v2_ajaba', ar: 'أَجَابَ يُجِيبُ', en: 'To Answer / Reply', bn: 'উত্তর দেওয়া', romanized: 'ajāba yujību', emoji: '🙋' },
        { id: 'v2_ata-a', ar: 'أَطَاعَ يُطِيعُ', en: 'To Obey', bn: 'আনুগত্য করা', romanized: 'aṭā‘a yuṭī‘u', emoji: '🤲' },
        { id: 'v2_aqama', ar: 'أَقَامَ يُقِيمُ', en: 'To Establish / Reside', bn: 'কায়েম করা / অবস্থান করা', romanized: 'aqāma yuqīmu', emoji: '🕌' },
        { id: 'v2_dhalam', ar: 'ظَلَامٌ', en: 'Darkness', bn: 'অন্ধকার', romanized: 'ẓalāmun', emoji: '🌑' },
        { id: 'v2_dayf', ar: 'ضَيْفٌ', en: 'Guest', bn: 'মেহমান', romanized: 'ḍayfun', emoji: '👥' },
      ],
    },
  },

  // 4. Page 44-48: Speed Pair - Match Form IV Expressions
  {
    id: 'v2-c1-l7-step-4-speed-pair-if-aal',
    type: 'speed_pair',
    pageNumber: 45,
    titleEn: 'Rapid Pairing: Form IV Directives & Collocations',
    titleAr: 'المُطَابَقَةُ السَّرِيعَةُ: عِبَارَاتُ بَابِ الإِفْعَالِ',
    instructionEn: 'Match each Form IV Arabic verbal phrase to its exact English meaning.',
    instructionBn: 'প্রতিটি আরবি বাক্যাংশকে তার সঠিক অর্থটির সাথে মিলান।',
    pairPayload: {
      pairs: [
        { id: 'p1', ar: 'أَنْزَلَ اللهُ المَطَرَ', meaning: 'Allah sent down rain', meaningBn: 'আল্লাহ বৃষ্টি নাযিল করেছেন' },
        { id: 'p2', ar: 'أَطِعِ الرَّحْمَنَ', meaning: 'Obey the Most Merciful', meaningBn: 'দয়াময়ের আনুগত্য করো' },
        { id: 'p3', ar: 'أَكْرِمْ ضَيْفَكَ', meaning: 'Honor your guest', meaningBn: 'তোমার মেহমানকে সম্মান করো' },
        { id: 'p4', ar: 'أَقِمِ الصَّلَاةَ', meaning: 'Establish prayer', meaningBn: 'নামাজ কায়েম করো' },
        { id: 'p5', ar: 'أَطْعَمَ الفَقِيرَ', meaning: 'He fed the poor person', meaningBn: 'সে গরিব লোকটিকে খাওয়াল' },
      ],
    },
  },

  // 5. Page 45: Sentence Assembly - Quran Revealed from Darkness to Light
  {
    id: 'v2-c1-l7-step-5-assembly-anzala-quran',
    type: 'sentence_assembly',
    pageNumber: 45,
    titleEn: 'Sentence Assembly: Revelation & Deliverance',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الإِنْزَالُ وَالإِخْرَاجُ مِنَ الظَّلَامِ',
    instructionEn: 'Assemble: "Allah revealed the Quran upon His Messenger and brought us out with it from darkness into light."',
    instructionBn: 'বাক্যটি সাজান: "আল্লাহ তাঁর রাসূলের উপর কুরআন নাযিল করেছেন এবং এর মাধ্যমে আমাদেরকে অন্ধকার থেকে আলোতে বের করে এনেছেন।"',
    assemblyPayload: {
      promptEn: 'Allah revealed the Quran upon His Messenger and brought us out with it from darkness into light.',
      promptBn: 'আল্লাহ তাঁর রাসূলের উপর কুরআন নাযিল করেছেন এবং এর মাধ্যমে আমাদেরকে অন্ধকার থেকে আলোতে বের করে এনেছেন।',
      expectedAnswer: ['أَنْزَلَ', 'اللهُ', 'عَلَى', 'رَسُولِهِ', 'القُرْآنَ', 'وَأَخْرَجَنَا', 'بِهِ', 'مِنَ', 'الظَّلَامِ', 'إِلَى', 'النُّورِ'],
      chips: ['أَنْزَلَ', 'اللهُ', 'عَلَى', 'رَسُولِهِ', 'القُرْآنَ', 'وَأَخْرَجَنَا', 'بِهِ', 'مِنَ', 'الظَّلَامِ', 'إِلَى', 'النُّورِ', 'نَزَلَ', 'خَرَجَ'],
      expectedAnswerBn: ['আল্লাহ', 'তাঁর', 'রাসূলের', 'উপর', 'কুরআন', 'নাযিল', 'করেছেন', 'এবং', 'এর', 'মাধ্যমে', 'আমাদেরকে', 'অন্ধকার', 'থেকে', 'আলোতে', 'বের', 'করে', 'এনেছেন'],
      chipsBn: ['আল্লাহ', 'তাঁর', 'রাসূলের', 'উপর', 'কুরআন', 'নাযিল', 'করেছেন', 'এবং', 'এর', 'মাধ্যমে', 'আমাদেরকে', 'অন্ধকার', 'থেকে', 'আলোতে', 'বের', 'করে', 'এনেছেন', 'নেমেছিল'],
      emoji: '📖',
    },
  },

  // 6. Page 45: Sentence Assembly - Mother Dressing Child & Sending Him
  {
    id: 'v2-c1-l7-step-6-assembly-albasat-ummu',
    type: 'sentence_assembly',
    pageNumber: 45,
    titleEn: 'Sentence Assembly: Dressing & Sending to School',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الإِلْبَاسُ وَالإِرْسَالُ',
    instructionEn: 'Assemble: "Majid\'s mother dressed her boy in school clothes and sent him to the school."',
    instructionBn: 'বাক্যটি সাজান: "মাজেদের মা তার ছেলেকে স্কুলের পোশাক পরালেন এবং তাকে স্কুলে পাঠালেন।"',
    assemblyPayload: {
      promptEn: 'Majid\'s mother dressed her boy in school clothes and sent him to the school.',
      promptBn: 'মাজেদের মা তার ছেলেকে স্কুলের পোশাক পরালেন এবং তাকে স্কুলে পাঠালেন।',
      expectedAnswer: ['أَلْبَسَتْ', 'أُمُّ', 'مَاجِدٍ', 'وَلَدَهَا', 'لِبَاسَ', 'المَدْرَسَةِ', 'وَأَرْسَلَتْهُ', 'إِلَى', 'المَدْرَسَةِ'],
      chips: ['أَلْبَسَتْ', 'أُمُّ', 'مَاجِدٍ', 'وَلَدَهَا', 'لِبَاسَ', 'المَدْرَسَةِ', 'وَأَرْسَلَتْهُ', 'إِلَى', 'المَدْرَسَةِ', 'لَبِسَ', 'رَسُولٌ'],
      expectedAnswerBn: ['মাজেদের', 'মা', 'তার', 'ছেলেকে', 'স্কুলের', 'পোশাক', 'পরালেন', 'এবং', 'তাকে', 'স্কুলে', 'পাঠালেন'],
      chipsBn: ['মাজেদের', 'মা', 'তার', 'ছেলেকে', 'স্কুলের', 'পোশাক', 'পরালেন', 'এবং', 'তাকে', 'স্কুলে', 'পাঠালেন', 'পড়ল'],
      emoji: '🎒',
    },
  },

  // 7. Page 46: Sentence Assembly - Honoring Guest & Sitting Beside Him
  {
    id: 'v2-c1-l7-step-7-assembly-akramana-allahu',
    type: 'sentence_assembly',
    pageNumber: 46,
    titleEn: 'Sentence Assembly: Honoring Guest in Islam',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الإِكْرَامُ وَالإِجْلَاسُ',
    instructionEn: 'Assemble: "Allah honored us with Islam, so honor your guest and seat him beside you."',
    instructionBn: 'বাক্যটি সাজান: "আল্লাহ আমাদেরকে ইসলাম দ্বারা সম্মানিত করেছেন, সুতরাং তোমার মেহমানকে সম্মান করো এবং তাকে তোমার পাশে বসাও।"',
    assemblyPayload: {
      promptEn: 'Allah honored us with Islam, so honor your guest and seat him beside you.',
      promptBn: 'আল্লাহ আমাদেরকে ইসলাম দ্বারা সম্মানিত করেছেন, সুতরাং তোমার মেহমানকে সম্মান করো এবং তাকে তোমার পাশে বসাও।',
      expectedAnswer: ['أَكْرَمَنَا', 'اللهُ', 'بِالإِسْلَامِ،', 'وَأَكْرِمْ', 'ضَيْفَكَ', 'وَأَجْلِسْهُ', 'بِجَانِبِكَ'],
      chips: ['أَكْرَمَنَا', 'اللهُ', 'بِالإِسْلَامِ،', 'وَأَكْرِمْ', 'ضَيْفَكَ', 'وَأَجْلِسْهُ', 'بِجَانِبِكَ', 'جَلَسَ', 'كَرِيمٌ'],
      expectedAnswerBn: ['আল্লাহ', 'আমাদেরকে', 'ইসলাম', 'দ্বারা', 'সম্মানিত', 'করেছেন', 'সুতরাং', 'তোমার', 'মেহমানকে', 'সম্মান', 'করো', 'এবং', 'তাকে', 'তোমার', 'পাশে', 'বসাও'],
      chipsBn: ['আল্লাহ', 'আমাদেরকে', 'ইসলাম', 'দ্বারা', 'সম্মানিত', 'করেছেন', 'সুতরাং', 'তোমার', 'মেহমানকে', 'সম্মান', 'করো', 'এবং', 'তাকে', 'তোমার', 'পাশে', 'বসাও', 'বসল'],
      emoji: '🤝',
    },
  },

  // 8. Page 45: Cloze Choice - Spending in the Path of Allah
  {
    id: 'v2-c1-l7-step-8-cloze-anfiq',
    type: 'cloze_choice',
    pageNumber: 45,
    titleEn: 'Cloze Selection: Form IV Imperative (أَنْفِقْ)',
    titleAr: 'اخْتِيَارُ فِعْلِ الأَمْرِ: أَنْفِقْ فِي سَبِيلِ اللهِ',
    instructionEn: 'Select the correct Form IV imperative form to command spending in Allah\'s cause.',
    instructionBn: 'আল্লাহর রাস্তায় খরচ করার আদেশবাচক ৪র্থ বাবের সঠিক রূপটি নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'أَيُّهَا المُسْلِمُ! ... مَالَكَ فِي سَبِيلِ اللهِ .',
      questionEn: 'O Muslim! [Spend] your wealth in the cause of Allah.',
      questionBn: 'হে মুসলিম! আল্লাহর রাস্তায় তোমার সম্পদ [খরচ করো]।',
      partialAnswerAr: 'أَيُّهَا المُسْلِمُ! ... مَالَكَ فِي سَبِيلِ اللهِ .',
      correctAnswer: 'أَنْفِقْ',
      options: ['أَنْفِقْ', 'نَفَقَ', 'يُنْفِقُ'],
      emoji: '💰',
    },
  },

  // 9. Page 46: Alternative QA - Rain from the Sky
  {
    id: 'v2-c1-l7-step-9-qa-rain',
    type: 'alternative_qa',
    pageNumber: 46,
    titleEn: 'Comprehension Q&A: The Provider of Rain',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: إِنْزَالُ المَطَرِ',
    instructionEn: 'Answer questions regarding who sends down life-giving rain from the sky.',
    instructionBn: 'আকাশ থেকে জীবনদায়ী বৃষ্টি কে নাযিল করেন সে সংক্রান্ত প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'اللهُ يُنْزِلُ لَنَا المَطَرَ مِنَ السَّمَاءِ، وَالمَطَرُ حَيَاةُ الأَرْضِ.',
      questions: [
        {
          id: 'q1-rain',
          questionAr: 'مَنْ يُنْزِلُ لَنَا المَطَرَ مِنَ السَّمَاءِ ؟',
          correctAnswerAr: 'اللهُ يُنْزِلُ لَنَا المَطَرَ',
          optionsAr: ['اللهُ يُنْزِلُ لَنَا المَطَرَ', 'المَلِكُ يُنْزِلُ المَطَرَ'],
        },
        {
          id: 'q2-rain-life',
          questionAr: 'أَ المَطَرُ حَيَاةُ الأَرْضِ ؟',
          correctAnswerAr: 'نَعَمْ .. المَطَرُ حَيَاةُ الأَرْضِ',
          optionsAr: ['نَعَمْ .. المَطَرُ حَيَاةُ الأَرْضِ', 'لَا .. لَيْسَ بِحَيَاةٍ'],
        },
      ],
    },
  },

  // 10. Page 48: Sentence Assembly - Ibrahim's Command to His Father
  {
    id: 'v2-c1-l7-step-10-assembly-ibrahim',
    type: 'sentence_assembly',
    pageNumber: 48,
    titleEn: 'Sentence Assembly: Obeying the Merciful (أَطِعِ الرَّحْمَنَ)',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَمْرُ إِبْرَاهِيمَ لِأَبِيهِ',
    instructionEn: 'Assemble: "Ibrahim said to his father: Obey the Most Merciful, and do not obey Satan."',
    instructionBn: 'বাক্যটি সাজান: "ইবরাহীম তাঁর পিতাকে বললেন: দয়াময়ের আনুগত্য করো, এবং শয়তানের আনুগত্য করো না।"',
    assemblyPayload: {
      promptEn: 'Ibrahim said to his father: Obey the Most Merciful, and do not obey Satan.',
      promptBn: 'ইবরাহীম তাঁর পিতাকে বললেন: দয়াময়ের আনুগত্য করো, এবং শয়তানের আনুগত্য করো না।',
      expectedAnswer: ['قَالَ', 'إِبْرَاهِيمُ', 'لِأَبِيهِ:', 'أَطِعِ', 'الرَّحْمَنَ،', 'وَلَا', 'تُطِعِ', 'الشَّيْطَانَ'],
      chips: ['قَالَ', 'إِبْرَاهِيمُ', 'لِأَبِيهِ:', 'أَطِعِ', 'الرَّحْمَنَ،', 'وَلَا', 'تُطِعِ', 'الشَّيْطَانَ', 'أَطَاعَ', 'يَعْبُدُ'],
      expectedAnswerBn: ['ইবরাহীম', 'তাঁর', 'পিতাকে', 'বললেন:', 'দয়াময়ের', 'আনুগত্য', 'করো', 'এবং', 'শয়তানের', 'আনুগত্য', 'করো', 'না'],
      chipsBn: ['ইবরাহীম', 'তাঁর', 'পিতাকে', 'বললেন:', 'দয়াময়ের', 'আনুগত্য', 'করো', 'এবং', 'শয়তানের', 'আনুগত্য', 'করো', 'না', 'আনুগত্য', 'করে'],
      emoji: '📜',
    },
  },

  // 11. Page 48: Sentence Assembly - Establishing a Small School in the Village
  {
    id: 'v2-c1-l7-step-11-assembly-aqama-alim',
    type: 'sentence_assembly',
    pageNumber: 48,
    titleEn: 'Sentence Assembly: Establishing a School (أَقَامَ)',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: إِقَامَةُ المَدْرَسَةِ فِي القَرْيَةِ',
    instructionEn: 'Assemble: "This righteous scholar established a small school in his village."',
    instructionBn: 'বাক্যটি সাজান: "এই নেককার আলেম তাঁর গ্রামে একটি ছোট মাদ্রাসা প্রতিষ্ঠা করলেন।"',
    assemblyPayload: {
      promptEn: 'This righteous scholar established a small school in his village.',
      promptBn: 'এই নেককার আলেম তাঁর গ্রামে একটি ছোট মাদ্রাসা প্রতিষ্ঠা করলেন।',
      expectedAnswer: ['أَقَامَ', 'هَذَا', 'العَالِمُ', 'الصَّالِحُ', 'فِي', 'قَرْيَتِهِ', 'مَدْرَسَةً', 'صَغِيرَةً'],
      chips: ['أَقَامَ', 'هَذَا', 'العَالِمُ', 'الصَّالِحُ', 'فِي', 'قَرْيَتِهِ', 'مَدْرَسَةً', 'صَغِيرَةً', 'قَامَ', 'كَبِيرَةً'],
      expectedAnswerBn: ['এই', 'নেককার', 'আলেম', 'তাঁর', 'গ্রামে', 'একটি', 'ছোট', 'মাদ্রাসা', 'প্রতিষ্ঠা', 'করলেন'],
      chipsBn: ['এই', 'নেককার', 'আলেম', 'তাঁর', 'গ্রামে', 'একটি', 'ছোট', 'মাদ্রাসা', 'প্রতিষ্ঠা', 'করলেন', 'দাঁড়াল', 'বড়'],
      emoji: '🏫',
    },
  },

  // 12. Page 48: Alternative QA - Obeying Allah & Disobeying Satan
  {
    id: 'v2-c1-l7-step-12-qa-obedience',
    type: 'alternative_qa',
    pageNumber: 48,
    titleEn: 'Dialogue Q&A: Divine Obedience',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: طَاعَةُ اللهِ وَرَسُولِهِ',
    instructionEn: 'Answer questions on whom the believer must obey and whom the believer rejects.',
    instructionBn: 'মুমিন কার আনুগত্য করবে এবং কাকে প্রত্যাখ্যান করবে সে সংক্রান্ত প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'المُسْلِمُ يُطِيعُ اللهَ وَرَسُولَهُ، وَلَا يُطِيعُ الشَّيْطَانَ.',
      questions: [
        {
          id: 'q1-obey',
          questionAr: 'هَلْ تُطِيعُ اللهَ وَرَسُولَهُ ؟',
          correctAnswerAr: 'نَعَمْ .. أُطِيعُ اللهَ وَرَسُولَهُ',
          optionsAr: ['نَعَمْ .. أُطِيعُ اللهَ وَرَسُولَهُ', 'لَا .. لَا أُطِيعُ'],
        },
        {
          id: 'q2-satan',
          questionAr: 'أَ تُطِيعُ الشَّيْطَانَ ؟',
          correctAnswerAr: 'لَا .. لَا أُطِيعُ الشَّيْطَانَ',
          optionsAr: ['لَا .. لَا أُطِيعُ الشَّيْطَانَ', 'نَعَمْ أُطِيعُهُ'],
        },
      ],
    },
  },

  // 13. Page 46: Sentence Assembly - Feeding the Poor for Allah's Sake
  {
    id: 'v2-c1-l7-step-13-assembly-ut-imukum',
    type: 'sentence_assembly',
    pageNumber: 46,
    titleEn: 'Sentence Assembly: Feeding for Allah\'s Sake (لِوَجْهِ اللهِ)',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الإِطْعَامُ لِوَجْهِ اللهِ',
    instructionEn: 'Assemble: "The wealthy man said to the hungry poor person: I feed you for the sake of Allah."',
    instructionBn: 'বাক্যটি সাজান: "ধনী লোকটি ক্ষুধার্ত গরিব লোকটিকে বলল: আমি তোমাদেরকে আল্লাহর সন্তুষ্টির জন্য খাওয়াই।"',
    assemblyPayload: {
      promptEn: 'The wealthy man said to the hungry poor person: I feed you for the sake of Allah.',
      promptBn: 'ধনী লোকটি ক্ষুধার্ত গরিব লোকটিকে বলল: আমি তোমাদেরকে আল্লাহর সন্তুষ্টির জন্য খাওয়াই।',
      expectedAnswer: ['قَالَ', 'الغَنِيُّ', 'لِلْفَقِيرِ', 'الجَائِعِ:', 'أُطْعِمُكُمْ', 'لِوَجْهِ', 'اللهِ'],
      chips: ['قَالَ', 'الغَنِيُّ', 'لِلْفَقِيرِ', 'الجَائِعِ:', 'أُطْعِمُكُمْ', 'لِوَجْهِ', 'اللهِ', 'طَعَامٌ', 'أَكَلَ'],
      expectedAnswerBn: ['ধনী', 'লোকটি', 'ক্ষুধার্ত', 'গরিব', 'লোকটিকে', 'বলল:', 'আমি', 'তোমাদেরকে', 'আল্লাহর', 'সন্তুষ্টির', 'জন্য', 'খাওয়াই'],
      chipsBn: ['ধনী', 'লোকটি', 'ক্ষুধার্ত', 'গরিব', 'লোকটিকে', 'বলল:', 'আমি', 'তোমাদেরকে', 'আল্লাহর', 'সন্তুষ্টির', 'জন্য', 'খাওয়াই', 'খাবার', 'খেয়েছিল'],
      emoji: '🍲',
    },
  },

  // 14. Page 48: Sentence Assembly - Honoring the Scholar for His Knowledge
  {
    id: 'v2-c1-l7-step-14-assembly-akrim-alim',
    type: 'sentence_assembly',
    pageNumber: 48,
    titleEn: 'Sentence Assembly: Honoring Knowledge & Never Humiliating',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: إِكْرَامُ العَالِمِ لِعِلْمِهِ',
    instructionEn: 'Assemble: "Honor the scholar for his knowledge, and never humiliate him."',
    instructionBn: 'বাক্যটি সাজান: "আলেমকে তাঁর জ্ঞানের জন্য সম্মান করো, এবং তাঁকে কখনো অপমান করো না।"',
    assemblyPayload: {
      promptEn: 'Honor the scholar for his knowledge, and never humiliate him.',
      promptBn: 'আলেমকে তাঁর জ্ঞানের জন্য সম্মান করো, এবং তাঁকে কখনো অপমান করো না।',
      expectedAnswer: ['أَكْرِمِ', 'العَالِمَ', 'لِعِلْمِهِ،', 'وَلَا', 'تُهِنْهُ', 'أَبَدًا'],
      chips: ['أَكْرِمِ', 'العَالِمَ', 'لِعِلْمِهِ،', 'وَلَا', 'تُهِنْهُ', 'أَبَدًا', 'كَرِيمٌ', 'أَهَانَ'],
      expectedAnswerBn: ['আলেমকে', 'তাঁর', 'জ্ঞানের', 'জন্য', 'সম্মান', 'করো', 'এবং', 'তাঁকে', 'কখনো', 'অপমান', 'করো', 'না'],
      chipsBn: ['আলেমকে', 'তাঁর', 'জ্ঞানের', 'জন্য', 'সম্মান', 'করো', 'এবং', 'তাঁকে', 'কখনো', 'অপমান', 'করো', 'না', 'সম্মানী', 'অপমান'],
      emoji: '🎓',
    },
  },

  // 15. Page 44: Syntactic Dissector (Tarkib) - Form IV Verb with Direct Object
  {
    id: 'v2-c1-l7-step-15-tarkib-anzala-matar',
    type: 'tarkib_dissector',
    pageNumber: 44,
    titleEn: 'Syntactic Dissector: Form IV Causative Verb',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَنْزَلَ اللهُ المَطَرَ',
    instructionEn: 'Slot each component: Form IV Past Verb, Doer, and Accusative Direct Object.',
    instructionBn: 'প্রতিটি অংশ বসান: ৪র্থ বাবের অতীত কাজ, কর্তা এবং কর্ম (মাফ\'উল বিহী)।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-anzala-matar',
          sentenceAr: 'أَنْزَلَ اللهُ المَطَرَ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ مِنْ بَابِ الإِفْعَالِ',
          sentenceTypeEn: 'Form IV Causative Verbal Sentence',
          sentenceTypeBn: '৪র্থ বাবের সকর্মক ক্রিয়াবাচক বাক্য',
          slots: [
            { roleAr: 'فِعْلٌ مَاضٍ (بَابُ الإِفْعَالِ)', roleEn: 'Form IV Past Verb', roleBn: '৪র্থ বাবের অতীত ক্রিয়া', expectedWordAr: 'أَنْزَلَ' },
            { roleAr: 'فَاعِلٌ (مَرْفُوعٌ بِالضَّمَّةِ)', roleEn: 'Doer / Subject (Nominative)', roleBn: 'কর্তা (ফায়েল)', expectedWordAr: 'اللهُ' },
            { roleAr: 'مَفْعُولٌ بِهِ (مَنْصُوبٌ بِالفَتْحَةِ)', roleEn: 'Direct Object (Accusative)', roleBn: 'কর্ম (মাফ\'উল বিহী)', expectedWordAr: 'المَطَرَ' },
          ],
          availableWordsAr: ['أَنْزَلَ', 'اللهُ', 'المَطَرَ'],
        },
      ],
    },
  },

  // 16. Page 48: Syntactic Dissector (Tarkib) - Hollow Form IV Verb with Direct Object
  {
    id: 'v2-c1-l7-step-16-tarkib-aqama-salat',
    type: 'tarkib_dissector',
    pageNumber: 48,
    titleEn: 'Syntactic Dissector: Hollow Form IV Verb (أَقَامَ)',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَقَامَ المُسْلِمُ الصَّلَاةَ',
    instructionEn: 'Slot each component: Hollow Form IV Verb, Doer, and Accusative Direct Object.',
    instructionBn: 'প্রতিটি অংশ বসান: আজওয়াফ ৪র্থ বাবের অতীত ক্রিয়া, কর্তা এবং কর্ম (মাফ\'উল বিহী)।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-aqama-salat',
          sentenceAr: 'أَقَامَ المُسْلِمُ الصَّلَاةَ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ جَوْفَاءُ مِنْ بَابِ الإِفْعَالِ',
          sentenceTypeEn: 'Hollow Form IV Verbal Sentence',
          sentenceTypeBn: 'আজওয়াফ ৪র্থ বাবের ক্রিয়াবাচক বাক্য',
          slots: [
            { roleAr: 'فِعْلٌ مَاضٍ أَجْوَفُ (بَابُ الإِفْعَالِ)', roleEn: 'Hollow Form IV Past Verb', roleBn: 'আজওয়াফ ৪র্থ বাবের অতীত ক্রিয়া', expectedWordAr: 'أَقَامَ' },
            { roleAr: 'فَاعِلٌ (مَرْفُوعٌ بِالضَّمَّةِ)', roleEn: 'Doer / Subject (Nominative)', roleBn: 'কর্তা (ফায়েল)', expectedWordAr: 'المُسْلِمُ' },
            { roleAr: 'مَفْعُولٌ بِهِ (مَنْصُوبٌ بِالفَتْحَةِ)', roleEn: 'Direct Object (Accusative)', roleBn: 'কর্ম (মাফ\'উল বিহী)', expectedWordAr: 'الصَّلَاةَ' },
          ],
          availableWordsAr: ['أَقَامَ', 'المُسْلِمُ', 'الصَّلَاةَ'],
        },
      ],
    },
  },

  // 17. Page 45: Quranic Echo - Surah Al-Baqarah (2:257) - Bringing Forth from Darkness to Light
  {
    id: 'v2-c1-l7-step-17-quranic-echo-yukhrijuhum',
    type: 'quranic_echo',
    pageNumber: 45,
    titleEn: 'Divine Deliverance: Bringing Forth from Darkness to Light',
    titleAr: 'صَدَى القُرْآنِ: (يُخْرِجُهُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ)',
    instructionEn: 'Reflect on how the Form IV present verb "يُخْرِجُ" describes Allah\'s ultimate deliverance of the believers in Surah Al-Baqarah (2:257).',
    instructionBn: 'সূরা আল-বাকারার ২৫৭ নং আয়াতে মুমিনদের মুক্তির বর্ণনায় ৪র্থ বাবের বর্তমান ক্রিয়া "يُخْرِجُ" কীভাবে এসেছে তা অনুধাবন করুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 257,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'اللَّهُ وَلِيُّ الَّذِينَ آمَنُوا يُخْرِجُهُم مِّنَ الظُّلُمَاتِ إِلَى النُّورِ',
      translationEn: 'Allah is the ally of those who believe. He brings them out from darknesses into the light.',
      translationBn: 'যারা ঈমান এনেছে আল্লাহ তাদের অভিভাবক; তিনি তাদেরকে অন্ধকার থেকে বের করে আলোতে নিয়ে যান।',
      highlightedWords: ['يُخْرِجُهُم', 'الظُّلُمَاتِ', 'النُّورِ'],
      reflection: 'The Form IV verb "أَخْرَجَ يُخْرِجُ" (to bring out) that you studied today in "أَخْرَجَنَا بِهِ مِنَ الظَّلَامِ إِلَى النُّورِ" is the very verb chosen in the Quran to convey Allah\'s divine act of taking believers from the depths of darkness into guidance and illumination.',
    },
  },
];

export const VOL2_CH1_LESSON_07_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 7,
  titleEn: 'Form IV Verbs: Baab al-If\'aal (بَابُ الإِفْعَالِ)',
  titleAr: 'بَابُ الإِفْعَالِ وَالأَفْعَالُ المُتَعَدِّيَةُ',
  wordsLearned: [
    'أَخْرَجَ', 'أَنْزَلَ', 'أَفْهَمَ', 'أَدْخَلَ', 'أَلْبَسَ', 'أَنْفَقَ', 'أَكْرَمَ',
    'أَرْسَلَ', 'أَطْعَمَ', 'أَجَابَ', 'أَطَاعَ', 'أَقَامَ', 'ظَلَامٌ', 'ضَيْفٌ'
  ],
  steps: VOL2_CH1_LESSON_07_STEPS,
};
