import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_10_STEPS: SessionStep[] = [
  // 1. Page 55-58: Concept Discovery - Volition (أَرَادَ / يُرِيدُ أَنْ) & Compound Interrogatives
  {
    id: 'v2-c1-l10-step-1-concept-volition',
    type: 'concept_intro',
    pageNumber: 55,
    titleEn: 'Volition & Subjunctive Subordination: أَرَادَ / يُرِيدُ أَنْ',
    titleAr: 'مَدْخَلُ فِعْلِ الإِرَادَةِ وَأَنْ المَصْدَرِيَّةِ',
    instructionEn: 'Observe how the particle "أَنْ" subordinates the present verb into the accusative (fathah), drops the feminine nun, and how interrogative prepositions contract.',
    instructionBn: 'লক্ষ্য করুন কীভাবে "أَنْ" অব্যয়টি পরবর্তী বর্তমান ক্রিয়ায় যবর দেয়, স্ত্রীলিঙ্গে নূন বিলুপ্ত করে এবং প্রশ্নবোধক অব্যয়গুলো সংক্ষেপিত হয়।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-volition-present',
          ar: 'يُرِيدُ أَنْ يَفْعَلَ (مُضَارِعٌ مَنْصُوبٌ)',
          romanized: "yurīdu an yaf'ala",
          meaningEn: 'Present Volition: He wants to do (Subjunctive with Fathah)',
          meaningBn: 'বর্তমান ইচ্ছা: সে করতে চায় (যবরযুক্ত বর্তমান ক্রিয়া)',
          exampleAr: 'يُرِيدُ أَخُو مَاجِدٍ أَنْ يَشْرَبَ مَاءً بَارِدًا',
          exampleEn: "Majid's brother wants to drink cold water.",
          exampleBn: 'মাজেদের ভাই ঠান্ডা পানি পান করতে চায়।',
          audioKey: 'يُرِيدُ أَنْ يَفْعَلَ',
          exampleAudioKey: 'يُرِيدُ أَخُو مَاجِدٍ أَنْ يَشْرَبَ مَاءً بَارِدًا',
          emoji: '🥛',
        },
        {
          id: 'c-volition-fem-noon-drop',
          ar: 'تُرِيدِينَ أَنْ تَفْعَلِي (بِحَذْفِ النُّونِ)',
          romanized: "turīdīna an taf'alī",
          meaningEn: 'Feminine Nun-Drop: You (f) want to do (Nun deleted after أَنْ)',
          meaningBn: 'স্ত্রীলিঙ্গে নূন বিলুপ্তি: তুমি (স্ত্রী) করতে চাও (أَنْ এর কারণে নূন বিলুপ্ত)',
          exampleAr: 'يَا صَدِيقَةَ زَيْنَبَ! أَنْتِ تُرِيدِينَ أَنْ تَشْرَبِي لَبَنَ البَقَرِ',
          exampleEn: "O friend of Zainab! You want to drink cow's milk.",
          exampleBn: 'হে যায়নাবের বান্ধবী! তুমি গরুর দুধ পান করতে চাও।',
          audioKey: 'تُرِيدِينَ أَنْ تَفْعَلِي',
          exampleAudioKey: 'أَنْتِ تُرِيدِينَ أَنْ تَشْرَبِي لَبَنَ البَقَرِ',
          emoji: '✂️',
        },
        {
          id: 'c-volition-past',
          ar: 'أَرَادَ أَنْ يَفْعَلَ (فِعْلٌ مَاضٍ مَعَ أَنْ)',
          romanized: "arāda an yaf'ala",
          meaningEn: 'Past Volition: He wanted to do (Past tense followed by subjunctive)',
          meaningBn: 'অতীত ইচ্ছা: সে করতে চেয়েছিল (অতীত ক্রিয়ার পর যবরযুক্ত বর্তমান ক্রিয়া)',
          exampleAr: 'أَرَادَتْ عَائِشَةُ أَنْ تَكْتُبَ خِطَابًا إِلَى صَدِيقَتِهَا',
          exampleEn: 'Aisha wanted to write a letter to her friend.',
          exampleBn: 'আয়েশা তার বান্ধবীর কাছে একটি চিঠি লিখতে চেয়েছিল।',
          audioKey: 'أَرَادَ أَنْ يَفْعَلَ',
          exampleAudioKey: 'أَرَادَتْ عَائِشَةُ أَنْ تَكْتُبَ خِطَابًا إِلَى صَدِيقَتِهَا',
          emoji: '✉️',
        },
        {
          id: 'c-contracted-interrogatives',
          ar: 'مِمَّ = مِنْ مَاذَا / إِلَامَ = إِلَى مَاذَا / لِمَ = لِـ مَاذَا',
          romanized: 'mimma / ilāma / lima',
          meaningEn: 'Contracted Interrogatives: From what? / To what? / Why?',
          meaningBn: 'সংক্ষেপিত প্রশ্নবোধক রূপ: কিসের থেকে? / কিসের দিকে? / কেন?',
          exampleAr: 'مِمَّ أَرَادَ اللهُ أَنْ يُخْرِجَ النَّاسَ؟',
          exampleEn: 'From what did Allah will to bring the people out?',
          exampleBn: 'আল্লাহ মানুষকে কিসের থেকে বের করতে চেয়েছেন?',
          audioKey: 'مِمَّ وَ إِلَامَ وَ لِمَ',
          exampleAudioKey: 'مِمَّ أَرَادَ اللهُ أَنْ يُخْرِجَ النَّاسَ؟',
          emoji: '❓',
        },
      ],
    },
  },

  // 2. Page 55: Verb Conjugator - Conjugating يُرِيدُ أَنْ across Pronouns
  {
    id: 'v2-c1-l10-step-2-conjugator-volition',
    type: 'verb_conjugator',
    pageNumber: 55,
    titleEn: 'Verb Paradigm: يُرِيدُ أَنْ يَشْرَبَ (Conjugating Volition Clauses)',
    titleAr: 'تَصْرِيفُ فِعْلِ: يُرِيدُ أَنْ يَشْرَبَ',
    instructionEn: 'Switch between pronouns to observe the main verb conjugation and the subjunctive marker on the subordinated verb.',
    instructionBn: 'বিভিন্ন সর্বনামের মধ্যে পরিবর্তন করে মূল ক্রিয়া এবং পরবর্তী অধস্তন ক্রিয়ার পরিবর্তন লক্ষ্য করুন।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'present',
      verbs: [
        {
          id: 'verb_yuridu_an_yashraba',
          rootAr: 'ر و د / ش ر ب',
          masdarAr: 'الإِرَادَةُ وَالشُّرْبُ',
          meaningEn: 'To want to drink',
          meaningBn: 'পান করতে চাওয়া',
          baabAr: 'بَابُ الإِفْعَالِ وَالسُّبُلُ المَنْصُوبَةُ',
          baabEn: 'Form IV with Subjunctive Clause',
          emoji: '🥤',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'أَرَادَ أَنْ يَشْرَبَ',
              presentAr: 'يُرِيدُ أَنْ يَشْرَبَ',
              imperativeAr: 'أَرِدْ أَنْ تَشْرَبَ',
              pastMeaningEn: 'He wanted to drink',
              pastMeaningBn: 'সে পান করতে চেয়েছিল',
              presentMeaningEn: 'He wants to drink',
              presentMeaningBn: 'সে পান করতে চায়',
              audioKey: 'يُرِيدُ أَنْ يَشْرَبَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'أَرَادَتْ أَنْ تَشْرَبَ',
              presentAr: 'تُرِيدُ أَنْ تَشْرَبَ',
              imperativeAr: 'أَرِيدِي أَنْ تَشْرَبِي',
              pastMeaningEn: 'She wanted to drink',
              pastMeaningBn: 'সে পান করতে চেয়েছিল',
              presentMeaningEn: 'She wants to drink',
              presentMeaningBn: 'সে পান করতে চায়',
              audioKey: 'تُرِيدُ أَنْ تَشْرَبَ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'أَرَدْتَ أَنْ تَشْرَبَ',
              presentAr: 'تُرِيدُ أَنْ تَشْرَبَ',
              imperativeAr: 'أَرِدْ أَنْ تَشْرَبَ',
              pastMeaningEn: 'You wanted to drink',
              pastMeaningBn: 'তুমি পান করতে চেয়েছিলে',
              presentMeaningEn: 'You want to drink',
              presentMeaningBn: 'তুমি পান করতে চাও',
              audioKey: 'تُرِيدُ أَنْ تَشْرَبَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'أَرَدْتِ أَنْ تَشْرَبِي',
              presentAr: 'تُرِيدِينَ أَنْ تَشْرَبِي',
              imperativeAr: 'أَرِيدِي أَنْ تَشْرَبِي',
              pastMeaningEn: 'You wanted to drink',
              pastMeaningBn: 'তুমি পান করতে চেয়েছিলে',
              presentMeaningEn: 'You want to drink',
              presentMeaningBn: 'তুমি পান করতে চাও',
              audioKey: 'تُرِيدِينَ أَنْ تَشْرَبِي',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'أَرَدْتُ أَنْ أَشْرَبَ',
              presentAr: 'أُرِيدُ أَنْ أَشْرَبَ',
              imperativeAr: 'أُرِيدُ أَنْ أَشْرَبَ',
              pastMeaningEn: 'I wanted to drink',
              pastMeaningBn: 'আমি পান করতে চেয়েছিলাম',
              presentMeaningEn: 'I want to drink',
              presentMeaningBn: 'আমি পান করতে চাই',
              audioKey: 'أُرِيدُ أَنْ أَشْرَبَ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 55-57: Word Construction - Nun-Dropping & Subjunctive Formations
  {
    id: 'v2-c1-l10-step-3-word-construction-volition',
    type: 'word_construction',
    pageNumber: 55,
    titleEn: 'Word Construction: Subjunctive Derivations & Nun-Dropping',
    titleAr: 'تَشْكِيلُ المُضَارِعِ المَنْصُوبِ: حَذْفُ النُّونِ',
    instructionEn: 'Derive the subordinated subjunctive verb forms, observing how the feminine nun is dropped after "أَنْ".',
    instructionBn: 'অধস্তন যবরযুক্ত ক্রিয়ারূপগুলো গঠন করুন এবং লক্ষ্য করুন কীভাবে "أَنْ" এর পর স্ত্রীলিঙ্গের নূন বিলুপ্ত হয়।',
    itemId: 'v2_l10_word_construction_volition',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-tashrabi',
          sourceWordAr: 'تَشْرَبِينَ',
          sourceWordLabelEn: '2nd Person Fem Indicative',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ সাধারণ বর্তমান',
          targetWordAr: 'تَشْرَبِي',
          promptEn: 'Derive Subjunctive: "...that you (f) drink" (Drop the final Nun)',
          promptBn: 'অধস্তন রূপ গঠন করুন: "...যেন তুমি (স্ত্রী) পান করো" (শেষের নূন বিলুপ্ত)',
          targetMeaningEn: 'You (f) drink (subjunctive)',
          targetMeaningBn: 'তুমি (স্ত্রী) পান করো',
          chips: ['تَ', 'شْ', 'رَ', 'بِ', 'ي', 'نَ', 'تُ', 'بُ'],
          emoji: '🥛',
        },
        {
          id: 'wc-tunfiqi',
          sourceWordAr: 'تُنْفِقِينَ',
          sourceWordLabelEn: '2nd Person Fem Indicative',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ সাধারণ বর্তমান',
          targetWordAr: 'تُنْفِقِي',
          promptEn: 'Derive Subjunctive: "...that you (f) spend" (Drop the final Nun)',
          promptBn: 'অধস্তন রূপ গঠন করুন: "...যেন তুমি (স্ত্রী) ব্যয় করো" (শেষের নূন বিলুপ্ত)',
          targetMeaningEn: 'You (f) spend (subjunctive)',
          targetMeaningBn: 'তুমি (স্ত্রী) ব্যয় করো',
          chips: ['تُ', 'نْ', 'فِ', 'قِ', 'ي', 'نَ', 'قُ', 'تَ'],
          emoji: '💰',
        },
        {
          id: 'wc-taktubi',
          sourceWordAr: 'تَكْتُبِينَ',
          sourceWordLabelEn: '2nd Person Fem Indicative',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ সাধারণ বর্তমান',
          targetWordAr: 'تَكْتُبِي',
          promptEn: 'Derive Subjunctive: "...that you (f) write" (Drop the final Nun)',
          promptBn: 'অধস্তন রূপ গঠন করুন: "...যেন তুমি (স্ত্রী) লেখো" (শেষের নূন বিলুপ্ত)',
          targetMeaningEn: 'You (f) write (subjunctive)',
          targetMeaningBn: 'তুমি (স্ত্রী) লেখো',
          chips: ['تَ', 'كْ', 'تُ', 'بِ', 'ي', 'نَ', 'بُ', 'تَ'],
          emoji: '✍️',
        },
        {
          id: 'wc-tal-abi',
          sourceWordAr: 'تَلْعَبِينَ',
          sourceWordLabelEn: '2nd Person Fem Indicative',
          sourceWordLabelBn: '২য় পুরুষ স্ত্রীলিঙ্গ সাধারণ বর্তমান',
          targetWordAr: 'تَلْعَبِي',
          promptEn: 'Derive Subjunctive: "...that you (f) play" (Drop the final Nun)',
          promptBn: 'অধস্তন রূপ গঠন করুন: "...যেন তুমি (স্ত্রী) খেলো" (শেষের নূন বিলুপ্ত)',
          targetMeaningEn: 'You (f) play (subjunctive)',
          targetMeaningBn: 'তুমি (স্ত্রী) খেলো',
          chips: ['تَ', 'لْ', 'عَ', 'بِ', 'ي', 'نَ', 'بُ', 'تُ'],
          emoji: '⚽',
        },
        {
          id: 'wc-uridu',
          sourceWordAr: 'الإِرَادَةُ',
          sourceWordLabelEn: 'Form IV Verbal Noun (Masdar)',
          sourceWordLabelBn: '৪র্থ বাবের মূল মাছদার',
          targetWordAr: 'أُرِيدُ',
          promptEn: 'Derive 1st Person Present: "I want"',
          promptBn: '১ম পুরুষ বর্তমান ক্রিয়া গঠন করুন: "আমি চাই"',
          targetMeaningEn: 'I want',
          targetMeaningBn: 'আমি চাই',
          chips: ['أُ', 'رِ', 'ي', 'دُ', 'يُ', 'رَ', 'دَ'],
          emoji: '💭',
        },
      ],
    },
  },

  // 4. Page 55-58: Vocabulary Prime
  {
    id: 'v2-c1-l10-step-4-vocab-prime',
    type: 'vocab_prime',
    pageNumber: 55,
    titleEn: 'Vocabulary: Volition, Animals & Inquiries',
    titleAr: 'مُفْرَدَاتُ الإِرَادَةِ وَالحَيَوَانَاتِ وَالاسْتِفْهَامِ',
    instructionEn: 'Master the key vocabulary for beverages, livestock, writing tools, and compound question words.',
    instructionBn: 'পানীয়, গবাদি পশু, লেখার উপকরণ এবং যৌগিক প্রশ্নবোধক শব্দের প্রয়োজনীয় শব্দভাণ্ডার আয়ত্ত করুন।',
    vocabPayload: {
      words: [
        { id: 'v2_asir', ar: 'عَصِيرٌ', en: 'Juice', bn: 'জুস / শরবত', romanized: "‘aṣīrun", emoji: '🥤' },
        { id: 'v2_hamid', ar: 'حَامِضٌ', en: 'Sour', bn: 'টক', romanized: 'ḥāmiḍun', emoji: '🍋' },
        { id: 'v2_shah', ar: 'شَاةٌ', en: 'Sheep / Ewe / Goat', bn: 'বকরী / দুম্বা', romanized: 'shātun', emoji: '🐑' },
        { id: 'v2_baqarah', ar: 'بَقَرَةٌ', en: 'Cow', bn: 'গাভী', romanized: 'baqaratun', emoji: '🐄' },
        { id: 'v2_kabsh', ar: 'كَبْشٌ', en: 'Ram', bn: 'দুম্বা / ভেড়া', romanized: 'kabshun', emoji: '🐏' },
        { id: 'v2_qirtas', ar: 'قِرْطَاسٌ', en: 'Paper / Scroll', bn: 'কাগজ', romanized: 'qirṭāsun', emoji: '📄' },
        { id: 'v2_mimma', ar: 'مِمَّ', en: 'From what?', bn: 'কিসের থেকে?', romanized: 'mimma', emoji: '❓' },
        { id: 'v2_ilama', ar: 'إِلَامَ', en: 'To what? / Until what?', bn: 'কিসের দিকে? / কতক্ষণ পর্যন্ত?', romanized: 'ilāma', emoji: '❓' },
        { id: 'v2_lima', ar: 'لِمَ', en: 'Why? / For what?', bn: 'কেন? / কিসের জন্য?', romanized: 'lima', emoji: '❓' },
        { id: 'v2_khalawa', ar: 'خَلَعَ يَخْلَعُ', en: 'To take off / remove clothes', bn: 'পোশাক খোলা', romanized: 'khala‘a yakhla‘u', emoji: '👕' },
        { id: 'v2_labisa', ar: 'لَبِسَ يَلْبَسُ', en: 'To wear / put on', bn: 'পোশাক পরা', romanized: 'labisa yalbasu', emoji: '👔' },
        { id: 'v2_sayyad', ar: 'صَيَّادٌ', en: 'Hunter', bn: 'শিকারী', romanized: 'ṣayyādun', emoji: '🏹' },
      ],
    },
  },

  // 5. Page 55-58: Speed Pair Matching
  {
    id: 'v2-c1-l10-step-5-speed-pair',
    type: 'speed_pair',
    pageNumber: 56,
    titleEn: 'Rapid Pairing: Volition Phrases & Interrogatives',
    titleAr: 'المُطَابَقَةُ السَّرِيعَةُ: عِبَارَاتُ الإِرَادَةِ',
    instructionEn: 'Match each Arabic clause to its exact English meaning.',
    instructionBn: 'প্রতিটি আরবি বাক্যাংশকে তার সঠিক ইংরেজি অর্থের সাথে মেলান।',
    pairPayload: {
      pairs: [
        { id: 'p1', ar: 'أُرِيدُ أَنْ أَشْرَبَ مَاءَ زَمْزَمَ', meaning: 'I want to drink Zamzam water', meaningBn: 'আমি যমযমের পানি পান করতে চাই' },
        { id: 'p2', ar: 'أَرَادَتْ أَنْ تَكْتُبَ خِطَابًا', meaning: 'She wanted to write a letter', meaningBn: 'সে একটি চিঠি লিখতে চেয়েছিল' },
        { id: 'p3', ar: 'مِمَّ أَرَادَ أَنْ يُخْرِجَهُمْ؟', meaning: 'From what did He want to bring them out?', meaningBn: 'তিনি তাদের কিসের থেকে বের করতে চেয়েছিলেন?' },
        { id: 'p4', ar: 'لِمَ أَخَذَتِ القِرْطَاسَ؟', meaning: 'Why did she take the paper?', meaningBn: 'সে কেন কাগজটি নিল?' },
        { id: 'p5', ar: 'أَنَا لَا أُرِيدُ، لِأَنَّهُ حَامِضٌ', meaning: 'I do not want, because it is sour', meaningBn: 'আমি চাই না, কারণ এটি টক' },
      ],
    },
  },

  // 6. Page 55: Sentence Assembly - Zamzam Water Desire
  {
    id: 'v2-c1-l10-step-6-assembly-zamzam',
    type: 'sentence_assembly',
    pageNumber: 55,
    titleEn: 'Sentence Assembly: Wanting to Drink Zamzam',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: شُرْبُ مَاءِ زَمْزَمَ',
    instructionEn: 'Assemble: "I want to drink Zamzam water."',
    instructionBn: 'বাক্যটি সাজান: "আমি যমযমের পানি পান করতে চাই।"',
    assemblyPayload: {
      promptEn: 'I want to drink Zamzam water.',
      promptBn: 'আমি যমযমের পানি পান করতে চাই।',
      expectedAnswer: ['أُرِيدُ', 'أَنْ', 'أَشْرَبَ', 'مَاءَ', 'زَمْزَمَ'],
      chips: ['أُرِيدُ', 'أَنْ', 'أَشْرَبَ', 'مَاءَ', 'زَمْزَمَ', 'أَشْرَبُ', 'شَرِبْتُ'],
      expectedAnswerBn: ['আমি', 'যমযমের', 'পানি', 'পান করতে', 'চাই'],
      chipsBn: ['আমি', 'যমযমের', 'পানি', 'পান করতে', 'চাই', 'পান করেছিলাম'],
      emoji: '🕋',
    },
  },

  // 7. Page 55: Polar Sort - Subjunctive Accuracy after أَنْ
  {
    id: 'v2-c1-l10-step-7-polar-subjunctive',
    type: 'polar_sort',
    pageNumber: 55,
    titleEn: 'Grammar Polarity: Subjunctive Fathah vs Indicative Error',
    titleAr: 'التَّمْيِيزُ القُطْبِيُّ: صِحَّةُ النَّصْبِ بَعْدَ أَنْ',
    instructionEn: 'Select the grammatically correct subjunctive construction after "أَنْ".',
    instructionBn: '"أَنْ" এর পর ব্যাকরণগতভাবে সঠিক রূপটি নির্বাচন করুন।',
    polarPayload: {
      arabicSubject: 'يُرِيدُ أَنْ',
      meaningEn: 'Subjunctive Agreement after An (Takes Fathah)',
      meaningBn: 'আনের পর যবরযুক্ত রূপ',
      correctAnswer: 'يُرِيدُ أَنْ يَشْرَبَ',
      options: ['يُرِيدُ أَنْ يَشْرَبَ', 'يُرِيدُ أَنْ يَشْرَبُ'],
      emoji: '⚖️',
    },
  },

  // 8. Page 56: Alternative Q&A - Grape Juice vs Apple Juice
  {
    id: 'v2-c1-l10-step-8-qa-juice',
    type: 'alternative_qa',
    pageNumber: 56,
    titleEn: 'Comprehension: Grape Juice or Apple Juice?',
    titleAr: 'سُؤَالٌ وَجَوَابٌ: عَصِيرُ العِنَبِ أَمْ عَصِيرُ التُّفَّاحِ؟',
    instructionEn: 'Answer the question based on the textbook dialogue: Did Aisha\'s friend want grape juice or apple juice?',
    instructionBn: 'পাঠ্যবইয়ের প্রশ্নোত্তর অনুযায়ী উত্তর দিন: আয়েশার বান্ধবী আঙ্গুরের জুস চেয়েছিল নাকি আপেলের জুস?',
    alternativeQAPayload: {
      contextAr: 'أَرَادَتْ صَدِيقَةُ عَائِشَةَ أَنْ تَشْرَبَ عَصِيرَ العِنَبِ، وَمَا أَرَادَتْ أَنْ تَشْرَبَ عَصِيرَ التُّفَّاحِ.',
      questions: [
        {
          id: 'q1',
          questionAr: 'أَ عَصِيرَ العِنَبِ أَرَادَتْ أَنْ تَشْرَبَ صَدِيقَةُ عَائِشَةَ أَمْ عَصِيرَ التُّفَّاحِ؟',
          optionsAr: [
            'أَرَادَتْ أَنْ تَشْرَبَ عَصِيرَ العِنَبِ',
            'أَرَادَتْ أَنْ تَشْرَبَ عَصِيرَ التُّفَّاحِ',
          ],
          correctAnswerAr: 'أَرَادَتْ أَنْ تَشْرَبَ عَصِيرَ العِنَبِ',
        },
      ],
    },
  },

  // 9. Page 57: Sentence Assembly - Bilal's Son Dressing for School
  {
    id: 'v2-c1-l10-step-9-assembly-bilal',
    type: 'sentence_assembly',
    pageNumber: 57,
    titleEn: "Sentence Assembly: Bilal's Son Going to School",
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: خُرُوجُ وَلَدِ بِلَالٍ',
    instructionEn: 'Assemble: "Bilal\'s boy wanted to go to the madrasah."',
    instructionBn: 'বাক্যটি সাজান: "বেলালের ছেলে মাদ্রাসায় যেতে চাইল।"',
    assemblyPayload: {
      promptEn: "Bilal's boy wanted to go to the madrasah.",
      promptBn: 'বেলালের ছেলে মাদ্রাসায় যেতে চাইল।',
      expectedAnswer: ['أَرَادَ', 'وَلَدُ', 'بِلَالٍ', 'أَنْ', 'يَذْهَبَ', 'إِلَى', 'المَدْرَسَةِ'],
      chips: ['أَرَادَ', 'وَلَدُ', 'بِلَالٍ', 'أَنْ', 'يَذْهَبَ', 'إِلَى', 'المَدْرَسَةِ', 'يَذْهَبُ', 'خَرَجَ'],
      expectedAnswerBn: ['বেলালের', 'ছেলে', 'মাদ্রাসায়', 'যেতে', 'চাইল'],
      chipsBn: ['বেলালের', 'ছেলে', 'মাদ্রাসায়', 'যেতে', 'চাইল', 'বের হলো'],
      emoji: '🏫',
    },
  },

  // 10. Page 55-56: Cloze Choice - Sour Juice Refusal
  {
    id: 'v2-c1-l10-step-10-cloze-sour',
    type: 'cloze_choice',
    pageNumber: 56,
    titleEn: 'Contextual Gap: The Reason for Refusing Juice',
    titleAr: 'مِلْءُ الفَرَاغِ: عِلَّةُ الامْتِنَاعِ عَنِ العَصِيرِ',
    instructionEn: 'Select the correct adjective describing why the speaker refuses to drink the juice.',
    instructionBn: 'জুস পান করতে অস্বীকৃতির সঠিক কারণ প্রকাশক বিশেষণটি নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'أَنَا لَا أُرِيدُ أَنْ أَشْرَبَ هَذَا العَصِيرَ، لِأَنَّهُ ...',
      questionEn: 'I do not want to drink this juice, because it is [sour].',
      questionBn: 'আমি এই জুস পান করতে চাই না, কারণ এটি [টক]।',
      partialAnswerAr: 'أَنَا لَا أُرِيدُ أَنْ أَشْرَبَ هَذَا العَصِيرَ، لِأَنَّهُ ...',
      correctAnswer: 'حَامِضٌ',
      options: ['حَامِضٌ', 'حُلْوٌ', 'بَارِدٌ'],
      emoji: '🍋',
    },
  },

  // 11. Page 56: Alternative Q&A - Cow's Milk vs Sheep's Milk
  {
    id: 'v2-c1-l10-step-11-qa-milk',
    type: 'alternative_qa',
    pageNumber: 56,
    titleEn: "Comprehension: Cow's Milk or Sheep's Milk?",
    titleAr: 'سُؤَالٌ وَجَوَابٌ: لَبَنُ البَقَرِ أَمْ لَبَنُ الشَّاةِ؟',
    instructionEn: 'Answer: What did Zainab\'s friend want to drink?',
    instructionBn: 'উত্তর দিন: যায়নাবের বান্ধবী কোন দুধ পান করতে চেয়েছিল?',
    alternativeQAPayload: {
      contextAr: 'يَا صَدِيقَةَ زَيْنَبَ! أَنْتِ تُرِيدِينَ أَنْ تَشْرَبِي لَبَنَ البَقَرِ.',
      questions: [
        {
          id: 'q-milk',
          questionAr: 'أَ لَبَنَ البَقَرِ تُرِيدِينَ أَنْ تَشْرَبِي يَا صَدِيقَةَ زَيْنَبَ أَمْ لَبَنَ الشَّاةِ؟',
          optionsAr: [
            'أُرِيدُ أَنْ أَشْرَبَ لَبَنَ البَقَرِ',
            'أُرِيدُ أَنْ أَشْرَبَ لَبَنَ الشَّاةِ',
          ],
          correctAnswerAr: 'أُرِيدُ أَنْ أَشْرَبَ لَبَنَ البَقَرِ',
        },
      ],
    },
  },

  // 12. Page 57: Sentence Assembly - Trustworthy Merchant Spending
  {
    id: 'v2-c1-l10-step-12-assembly-merchant',
    type: 'sentence_assembly',
    pageNumber: 57,
    titleEn: 'Sentence Assembly: The Trustworthy Merchant',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: التَّاجِرُ الأَمِينُ',
    instructionEn: 'Assemble: "I want to spend my wealth in the way of Allah."',
    instructionBn: 'বাক্যটি সাজান: "আমি আল্লাহর রাস্তায় আমার সম্পদ ব্যয় করতে চাই।"',
    assemblyPayload: {
      promptEn: 'I want to spend my wealth in the way of Allah.',
      promptBn: 'আমি আল্লাহর রাস্তায় আমার সম্পদ ব্যয় করতে চাই।',
      expectedAnswer: ['أَنَا', 'أُرِيدُ', 'أَنْ', 'أُنْفِقَ', 'مَالِي', 'فِي', 'سَبِيلِ', 'اللهِ'],
      chips: ['أَنَا', 'أُرِيدُ', 'أَنْ', 'أُنْفِقَ', 'مَالِي', 'فِي', 'سَبِيلِ', 'اللهِ', 'أُنْفِقُ', 'مَالُ'],
      expectedAnswerBn: ['আমি', 'আল্লাহর', 'রাস্তায়', 'আমার', 'সম্পদ', 'ব্যয় করতে', 'চাই'],
      chipsBn: ['আমি', 'আল্লাহর', 'রাস্তায়', 'আমার', 'সম্পদ', 'ব্যয় করতে', 'চাই', 'ব্যয় করেছি'],
      emoji: '💼',
    },
  },

  // 13. Page 57: Cloze Choice - Studying Arabic to Understand the Quran
  {
    id: 'v2-c1-l10-step-13-cloze-quran-purpose',
    type: 'cloze_choice',
    pageNumber: 57,
    titleEn: 'Contextual Gap: Studying Arabic to Understand the Quran',
    titleAr: 'مِلْءُ الفَرَاغِ: دِرَاسَةُ العَرَبِيَّةِ لِفَهْمِ القُرْآنِ',
    instructionEn: 'Complete Layla\'s response: "I want to study the Arabic language in order to understand the Quran."',
    instructionBn: 'লায়লার উত্তর সম্পূর্ণ করুন: "আমি কুরআন বোঝার জন্য আরবি ভাষা শিখতে চাই।"',
    clozePayload: {
      questionAr: 'أُرِيدُ أَنْ أَدْرُسَ اللُّغَةَ العَرَبِيَّةَ ... القُرْآنَ',
      questionEn: 'I want to study the Arabic language [in order to understand] the Quran.',
      questionBn: 'আমি কুরআন [বোঝার জন্য] আরবি ভাষা পড়তে চাই।',
      partialAnswerAr: 'أُرِيدُ أَنْ أَدْرُسَ اللُّغَةَ العَرَبِيَّةَ ... القُرْآنَ',
      correctAnswer: 'لِأَفْهَمَ',
      options: ['لِأَفْهَمَ', 'لِأَفْهَمُ', 'أَنْ أَفْهَمُ'],
      emoji: '📖',
    },
  },

  // 14. Page 57: Sentence Assembly - Aisha Writing a Letter
  {
    id: 'v2-c1-l10-step-14-assembly-aisha-letter',
    type: 'sentence_assembly',
    pageNumber: 57,
    titleEn: 'Sentence Assembly: Aisha Writing a Letter',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: كِتَابَةُ الخِطَابِ',
    instructionEn: 'Assemble: "Aisha wanted to write a letter to her friend."',
    instructionBn: 'বাক্যটি সাজান: "আয়েশা তার বান্ধবীর কাছে একটি চিঠি লিখতে চাইল।"',
    assemblyPayload: {
      promptEn: 'Aisha wanted to write a letter to her friend.',
      promptBn: 'আয়েশা তার বান্ধবীর কাছে একটি চিঠি লিখতে চাইল।',
      expectedAnswer: ['أَرَادَتْ', 'عَائِشَةُ', 'أَنْ', 'تَكْتُبَ', 'خِطَابًا', 'إِلَى', 'صَدِيقَتِهَا'],
      chips: ['أَرَادَتْ', 'عَائِشَةُ', 'أَنْ', 'تَكْتُبَ', 'خِطَابًا', 'إِلَى', 'صَدِيقَتِهَا', 'تَكْتُبُ', 'كَتَبَتْ'],
      expectedAnswerBn: ['আয়েশা', 'তার', 'বান্ধবীর', 'কাছে', 'চিঠি', 'লিখতে', 'চাইল'],
      chipsBn: ['আয়েশা', 'তার', 'বান্ধবীর', 'কাছে', 'চিঠি', 'লিখতে', 'চাইল', 'লিখেছিল'],
      emoji: '📝',
    },
  },

  // 15. Page 55: Tarkib Dissector - Subjunctive Subordination
  {
    id: 'v2-c1-l10-step-15-tarkib-subordination',
    type: 'tarkib_dissector',
    pageNumber: 55,
    titleEn: 'Syntactic Dissector: Volition & Subjunctive Subordination',
    titleAr: 'تَرْكِيبُ فِعْلِ الإِرَادَةِ مَعَ أَنْ المَصْدَرِيَّةِ',
    instructionEn: 'Slot each syntactic role: Main volitional verb, subjunctive subordinating particle, and accusative present verb.',
    instructionBn: 'প্রতিটি পদ নির্ধারণ করুন: মূল ইচ্ছা প্রকাশক ক্রিয়া, সাবজাঙ্কটিভ অব্যয় এবং যবরযুক্ত বর্তমান ক্রিয়া।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-volition',
          sentenceAr: 'يُرِيدُ أَنْ يَشْرَبَ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ ذَاتُ مَصْدَرٍ مُؤَوَّلٍ',
          sentenceTypeEn: 'Verbal Sentence with Subordinated Masdar Clause',
          sentenceTypeBn: 'মাসদারে মুয়াওওয়াল বিশিষ্ট ক্রিয়াবাচক বাক্য',
          slots: [
            {
              roleAr: 'فِعْلٌ مُضَارِعٌ (الفِعْلُ الرَّئِيسِيُّ)',
              roleEn: 'Main Present Verb',
              roleBn: 'মূল বর্তমান ক্রিয়া',
              expectedWordAr: 'يُرِيدُ',
            },
            {
              roleAr: 'حَرْفُ مَصْدَرٍ وَنَصْبٍ',
              roleEn: 'Subordinating Subjunctive Particle',
              roleBn: 'মাসদার গঠনকারী যবরদায়ক অব্যয়',
              expectedWordAr: 'أَنْ',
            },
            {
              roleAr: 'فِعْلٌ مُضَارِعٌ مَنْصُوبٌ بِالفَتْحَةِ',
              roleEn: 'Subordinated Accusative Present Verb',
              roleBn: 'যবরযুক্ত বর্তমান ক্রিয়া',
              expectedWordAr: 'يَشْرَبَ',
            },
          ],
          availableWordsAr: ['يُرِيدُ', 'أَنْ', 'يَشْرَبَ'],
        },
      ],
    },
  },

  // 16. Page 58: Tarkib Dissector - Contracted Interrogative (مِمَّ)
  {
    id: 'v2-c1-l10-step-16-tarkib-interrogative',
    type: 'tarkib_dissector',
    pageNumber: 58,
    titleEn: 'Syntactic Dissector: Contracted Prepositional Question (مِمَّ)',
    titleAr: 'تَرْكِيبُ المُرَكَّبِ الاسْتِفْهَامِيِّ (مِمَّ)',
    instructionEn: 'Analyze the contraction of "مِنْ + مَاذَا / مَا" into the unified interrogative "مِمَّ".',
    instructionBn: '"مِنْ + مَاذَا" মিলে কীভাবে সংক্ষিপ্ত রূপ "مِمَّ" গঠিত হয়েছে তা বিশ্লেষণ করুন।',
    tarkibPayload: {
      sentences: [
        {
          id: 's-tarkib-mimma',
          sentenceAr: 'مِمَّ خَرَجَ؟',
          sentenceTypeAr: 'جُمْلَةٌ اسْتِفْهَامِيَّةٌ مُرَكَّبَةٌ',
          sentenceTypeEn: 'Contracted Interrogative Sentence',
          sentenceTypeBn: 'সংক্ষেপিত প্রশ্নবোধক বাক্য',
          slots: [
            {
              roleAr: 'حَرْفُ جَرٍّ مُدْغَمٌ (مِنْ)',
              roleEn: 'Assimilated Preposition (Min)',
              roleBn: 'সন্ধিযুক্ত অব্যয় (মিন)',
              expectedWordAr: 'مِمْـ',
            },
            {
              roleAr: 'اسْمُ اسْتِفْهَامٍ (مَا)',
              roleEn: 'Interrogative Pronoun (Ma)',
              roleBn: 'প্রশ্নবোধক সর্বনাম (মা)',
              expectedWordAr: 'ـمَ',
            },
            {
              roleAr: 'فِعْلٌ مَاضٍ',
              roleEn: 'Past Verb',
              roleBn: 'অতীত ক্রিয়া',
              expectedWordAr: 'خَرَجَ',
            },
          ],
          availableWordsAr: ['مِمْـ', 'ـمَ', 'خَرَجَ'],
        },
      ],
    },
  },

  // 17. Quranic Milestone: Surah An-Nisa (4:28)
  {
    id: 'v2-c1-l10-step-17-quranic-echo-nisa',
    type: 'quranic_echo',
    pageNumber: 55,
    titleEn: 'Quranic Milestone: Divine Compassion & Human Vulnerability',
    titleAr: 'صَدَى القُرْآنِ: إِرَادَةُ اللهِ فِي التَّخْفِيفِ',
    instructionEn: 'Reflect on how the exact volition construct "يُرِيدُ اللَّهُ أَن يُخَفِّفَ" reveals divine mercy in Surah An-Nisa (4:28).',
    instructionBn: 'সূরা আন-নিসা (৪:২৮) এ হুবহু একই ব্যাকরণিক গঠন "يُرِيدُ اللَّهُ أَن يُخَفِّفَ" কীভাবে আল্লাহর রহমত প্রকাশ করে তা অনুধাবন করুন।',
    echoPayload: {
      surahNumber: 4,
      ayahNumber: 28,
      surahNameAr: 'النِّسَاء',
      surahNameEn: 'An-Nisa',
      arabicText: 'يُرِيدُ اللَّهُ أَن يُخَفِّفَ عَنكُمْ وَخُلِقَ الْإِنسَانُ ضَعِيفًا',
      translationEn: 'Allah wants to lighten for you [your burdens]; and mankind was created weak.',
      translationBn: 'আল্লাহ তোমাদের বোঝা হালকা করতে চান; আর মানুষকে সৃষ্টি করা হয়েছে দুর্বলরূপে।',
      highlightedWords: ['يُرِيدُ', 'أَن يُخَفِّفَ'],
      reflection: 'In this profound ayah, notice the exact grammatical structure of Lesson 10: "يُرِيدُ اللَّهُ" (Allah wills / wants) followed by "أَن يُخَفِّفَ" (to lighten), where the subjunctive particle "أَن" gives a fathah ending to the verb. The Quran pairs the majesty of divine volition with compassionate relief for human frailty.',
    },
  },
];

export const VOL2_CH1_LESSON_10_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 10,
  titleEn: 'Volition Clauses (أَرَادَ / يُرِيدُ أَنْ) & Compound Interrogatives',
  titleAr: 'أَرَادَ / يُرِيدُ أَنْ وَالمُرَكَّبَاتُ الاسْتِفْهَامِيَّةُ',
  wordsLearned: [
    'عَصِيرٌ', 'حَامِضٌ', 'شَاةٌ', 'بَقَرَةٌ', 'كَبْشٌ', 'قِرْطَاسٌ',
    'مِمَّ', 'إِلَامَ', 'لِمَ', 'خَلَعَ', 'لَبِسَ', 'صَيَّادٌ'
  ],
  steps: VOL2_CH1_LESSON_10_STEPS,
};
