import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_06_STEPS: SessionStep[] = [
  // 1. Page 38-39: Concept Discovery - The Hollow Verb (الفِعْلُ الأَجْوَفُ)
  {
    id: 'v2-c1-l6-step-1-concept-ajwaf',
    type: 'concept_intro',
    pageNumber: 38,
    titleEn: 'The Hollow Verb: Middle Weak Root Letter (الفِعْلُ الأَجْوَفُ)',
    titleAr: 'مَدْخَلُ الفِعْلِ الأَجْوَفِ',
    instructionEn: 'Observe how verbs with a weak middle letter (Waw or Yaa) transform across past, present, and command.',
    instructionBn: 'মাঝের হরফ দুর্বল (ওয়াও বা ইয়া) এমন ক্রিয়া কীভাবে অতীত, বর্তমান ও আদেশে পরিবর্তিত হয় লক্ষ্য করুন।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-ajwaf-qala',
          ar: 'قَالَ يَقُولُ قُلْ',
          romanized: 'qāla yaqūlu qul',
          meaningEn: 'Wawi Ajwaf: He said / He says / Say!',
          meaningBn: 'ওয়াওয়ী আজওয়াফ: সে বলল / সে বলে / বলো!',
          exampleAr: 'قُلْتُ لِمَاجِدٍ: تُبْ إِلَى اللهِ',
          exampleEn: 'I said to Majid: Repent to Allah.',
          exampleBn: 'আমি মাজেদকে বললাম: আল্লাহর কাছে তাওবা করো।',
          audioKey: 'قَالَ يَقُولُ قُلْ',
          exampleAudioKey: 'قُلْتُ لِمَاجِدٍ: تُبْ إِلَى اللهِ',
          emoji: '🗣️',
        },
        {
          id: 'c-ajwaf-baa',
          ar: 'بَاعَ يَبِيعُ بِعْ',
          romanized: 'bā‘a yabī‘u bi‘',
          meaningEn: 'Yaa-i Ajwaf: He sold / He sells / Sell!',
          meaningBn: 'ইয়া-ঈ আজওয়াফ: সে বিক্রি করল / সে বিক্রি করে / বিক্রি করো!',
          exampleAr: 'بِعْتُ كِتَابِي بِدِرْهَمٍ',
          exampleEn: 'I sold my book for a dirham.',
          exampleBn: 'আমি আমার বইটি এক দিরহামে বিক্রি করলাম।',
          audioKey: 'بَاعَ يَبِيعُ بِعْ',
          exampleAudioKey: 'بِعْتُ كِتَابِي بِدِرْهَمٍ',
          emoji: '🏷️',
        },
        {
          id: 'c-ajwaf-nama',
          ar: 'نَامَ يَنَامُ نَمْ',
          romanized: 'nāma yanāmu nam',
          meaningEn: 'Kasra Past Ajwaf: He slept / He sleeps / Sleep!',
          meaningBn: 'মাজহুর আজওয়াফ: সে ঘুমাল / সে ঘুমায় / ঘুমাও!',
          exampleAr: 'نِمْتُ بَعْدَ صَلَاةِ العِشَاءِ',
          exampleEn: 'I slept after the Isha prayer.',
          exampleBn: 'আমি এশার নামাজের পর ঘুমালাম।',
          audioKey: 'نَامَ يَنَامُ نَمْ',
          exampleAudioKey: 'نِمْتُ بَعْدَ صَلَاةِ العِشَاءِ',
          emoji: '🛏️',
        },
        {
          id: 'c-ajwaf-khafa',
          ar: 'خَافَ يَخَافُ خَفْ',
          romanized: 'khāfa yakhāfu khaf',
          meaningEn: 'Fear Verb: He feared / He fears / Fear!',
          meaningBn: 'ভয়সূচক আজওয়াফ: সে ভয় করল / সে ভয় করে / ভয় করো!',
          exampleAr: 'المُسْلِمُ يَخَافُ اللهَ وَلَا يَخَافُ غَيْرَهُ',
          exampleEn: 'The Muslim fears Allah and does not fear other than Him.',
          exampleBn: 'মুসলিম আল্লাহকে ভয় করে এবং অন্য কাউকে ভয় করে না।',
          audioKey: 'خَافَ يَخَافُ خَفْ',
          exampleAudioKey: 'المُسْلِمُ يَخَافُ اللهَ وَلَا يَخَافُ غَيْرَهُ',
          emoji: '🤲',
        },
      ],
    },
  },

  // 2. Page 38: Verb Conjugator - قَالَ يَقُولُ (Bab Nasara)
  {
    id: 'v2-c1-l6-step-2-conjugator-qala',
    type: 'verb_conjugator',
    pageNumber: 38,
    titleEn: 'Verb Paradigm: قَالَ يَقُولُ (To Say)',
    titleAr: 'تَصْرِيفُ فِعْلِ: قَالَ يَقُولُ (بَاب نَصَرَ)',
    instructionEn: 'Switch between pronouns to observe how the hollow root "ق و ل" drops the weak letter in "قُلْتُ" and "قُلْ".',
    instructionBn: 'সর্বনাম পরিবর্তন করে লক্ষ্য করুন কীভাবে "قُلْتُ" ও "قُلْ" এ দুর্বল হরফ বিলুপ্ত হয়।',
    conjugatorPayload: {
      mode: 'explore',
      targetTense: 'past',
      verbs: [
        {
          id: 'verb_qala',
          rootAr: 'ق و ل',
          masdarAr: 'قَوْلٌ',
          meaningEn: 'To say',
          meaningBn: 'বলা',
          baabAr: 'بَاب نَصَرَ يَنْصُرُ',
          baabEn: 'Bab Nasara (Hollow Wawi)',
          emoji: '🗣️',
          forms: [
            {
              subjectAr: 'هُوَ',
              subjectEn: 'He',
              subjectBn: 'সে (পুং)',
              pastAr: 'قَالَ',
              presentAr: 'يَقُولُ',
              imperativeAr: 'قُلْ',
              pastMeaningEn: 'He said',
              pastMeaningBn: 'সে বলল',
              presentMeaningEn: 'He says',
              presentMeaningBn: 'সে বলে',
              audioKey: 'قَالَ',
            },
            {
              subjectAr: 'هِيَ',
              subjectEn: 'She',
              subjectBn: 'সে (স্ত্রী)',
              pastAr: 'قَالَتْ',
              presentAr: 'تَقُولُ',
              imperativeAr: 'قُولِي',
              pastMeaningEn: 'She said',
              pastMeaningBn: 'সে বলল',
              presentMeaningEn: 'She says',
              presentMeaningBn: 'সে বলে',
              audioKey: 'قَالَتْ',
            },
            {
              subjectAr: 'أَنْتَ',
              subjectEn: 'You (m)',
              subjectBn: 'তুমি (পুং)',
              pastAr: 'قُلْتَ',
              presentAr: 'تَقُولُ',
              imperativeAr: 'قُلْ',
              pastMeaningEn: 'You said',
              pastMeaningBn: 'তুমি বললে',
              presentMeaningEn: 'You say',
              presentMeaningBn: 'তুমি বলো',
              audioKey: 'قُلْتَ',
            },
            {
              subjectAr: 'أَنْتِ',
              subjectEn: 'You (f)',
              subjectBn: 'তুমি (স্ত্রী)',
              pastAr: 'قُلْتِ',
              presentAr: 'تَقُولِينَ',
              imperativeAr: 'قُولِي',
              pastMeaningEn: 'You said (f)',
              pastMeaningBn: 'তুমি বললে',
              presentMeaningEn: 'You say (f)',
              presentMeaningBn: 'তুমি বলো',
              audioKey: 'قُلْتِ',
            },
            {
              subjectAr: 'أَنَا',
              subjectEn: 'I',
              subjectBn: 'আমি',
              pastAr: 'قُلْتُ',
              presentAr: 'أَقُولُ',
              imperativeAr: 'قُلْ',
              pastMeaningEn: 'I said',
              pastMeaningBn: 'আমি বললাম',
              presentMeaningEn: 'I say',
              presentMeaningBn: 'আমি বলি',
              audioKey: 'قُلْتُ',
            },
          ],
        },
      ],
    },
  },

  // 3. Page 39: Word Construction - Hollow Verb Transformations (حَذْفُ حَرْفِ العِلَّةِ)
  {
    id: 'v2-c1-l6-step-3-word-construction-ajwaf',
    type: 'word_construction',
    pageNumber: 39,
    titleEn: 'Word Construction: Deriving Weak Hollow Verbs',
    titleAr: 'اشْتِقَاقُ الفِعْلِ الأَجْوَفِ: بِنَاءُ الكَلِمَةِ',
    instructionEn: 'Derive the command and past forms from hollow Masdars, observing how the weak middle letter drops.',
    instructionBn: 'আজওয়াফ মাছদার থেকে আদেশ ও অতীত রূপ গঠন করুন এবং দুর্বল হরফের বিলুপ্তি লক্ষ্য করুন।',
    itemId: 'v2_l6_word_construction_ajwaf',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-l6-qul',
          sourceWordAr: 'القَوْلُ',
          sourceWordLabelEn: 'Hollow Masdar (Wawi)',
          sourceWordLabelBn: 'আজওয়াফ মাছদার (ওয়াওয়ী)',
          targetWordAr: 'قُلْ',
          promptEn: 'Derive the Command (Amr): "Say!" (Middle Waw dropped)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "বলো!" (মাঝের ওয়াও বিলুপ্ত)',
          targetMeaningEn: 'Say! (m)',
          targetMeaningBn: 'বলো!',
          chips: ['قُ', 'لْ', 'قُ', 'و', 'لْ', 'تَ'],
          emoji: '🗣️',
        },
        {
          id: 'wc-l6-nam',
          sourceWordAr: 'النَّوْمُ',
          sourceWordLabelEn: 'Hollow Masdar (Wawi)',
          sourceWordLabelBn: 'আজওয়াফ মাছদার (ওয়াওয়ী)',
          targetWordAr: 'نَمْ',
          promptEn: 'Derive the Command (Amr): "Sleep!" (Middle vowel dropped)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "ঘুমাও!" (দুর্বল হরফ বিলুপ্ত)',
          targetMeaningEn: 'Sleep! (m)',
          targetMeaningBn: 'ঘুমাও!',
          chips: ['نَ', 'مْ', 'نَ', 'ا', 'مْ', 'تُ'],
          emoji: '🛏️',
        },
        {
          id: 'wc-l6-bi',
          sourceWordAr: 'البَيْعُ',
          sourceWordLabelEn: 'Hollow Masdar (Yaa-i)',
          sourceWordLabelBn: 'আজওয়াফ মাছদার (ইয়া-ঈ)',
          targetWordAr: 'بِعْ',
          promptEn: 'Derive the Command (Amr): "Sell!" (Middle Yaa dropped)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "বিক্রি করো!" (মাঝের ইয়া বিলুপ্ত)',
          targetMeaningEn: 'Sell! (m)',
          targetMeaningBn: 'বিক্রি করো!',
          chips: ['بِ', 'عْ', 'بِ', 'ي', 'عْ', 'تِ'],
          emoji: '🏷️',
        },
        {
          id: 'wc-l6-sum',
          sourceWordAr: 'الصَّوْمُ',
          sourceWordLabelEn: 'Hollow Masdar (Wawi)',
          sourceWordLabelBn: 'আজওয়াফ মাছদার (ওয়াওয়ী)',
          targetWordAr: 'صُمْ',
          promptEn: 'Derive the Command (Amr): "Fast!" (Middle Waw dropped)',
          promptBn: 'নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "রোজা রাখো!" (মাঝের ওয়াও বিলুপ্ত)',
          targetMeaningEn: 'Fast! (m)',
          targetMeaningBn: 'রোজা রাখো!',
          chips: ['صُ', 'مْ', 'صُ', 'و', 'مْ', 'نَ'],
          emoji: '🌙',
        },
        {
          id: 'wc-l6-khiftu',
          sourceWordAr: 'الخَوْفُ',
          sourceWordLabelEn: 'Hollow Masdar (Wawi)',
          sourceWordLabelBn: 'আজওয়াফ মাছদার (ওয়াওয়ী)',
          targetWordAr: 'خِفْتُ',
          promptEn: 'Derive the 1st person Past: "I feared" (Weak letter dropped with kasrah)',
          promptBn: '১ম পুরুষ অতীত ক্রিয়া গঠন করুন: "আমি ভয় পেলাম" (জের সহ দুর্বল হরফ বিলুপ্ত)',
          targetMeaningEn: 'I feared',
          targetMeaningBn: 'আমি ভয় পেলাম',
          chips: ['خِ', 'فْ', 'تُ', 'خَ', 'ا', 'فْ'],
          emoji: '🤲',
        },
      ],
    },
  },

  // 4. Page 38-41: Vocab Prime - Essential Ajwaf Verbs & Nouns
  {
    id: 'v2-c1-l6-step-4-vocab-ajwaf',
    type: 'vocab_prime',
    pageNumber: 38,
    titleEn: 'Vocabulary: Hollow Verbs & Moral Terms',
    titleAr: 'مُفْرَدَاتُ الأَفْعَالِ الجَوْفَاءِ',
    instructionEn: 'Listen to the newly introduced hollow verbs and vocabulary.',
    instructionBn: 'নতুন আজওয়াফ ক্রিয়া ও শব্দগুলোর অর্থ মনোযোগ দিয়ে শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_sawm', ar: 'صَامَ يَصُومُ', en: 'To Fast', bn: 'রোজা রাখা', romanized: 'ṣāma yaṣūmu', emoji: '🌙' },
        { id: 'v2_baa', ar: 'بَاعَ يَبِيعُ', en: 'To Sell', bn: 'বিক্রি করা', romanized: 'bā‘a yabī‘u', emoji: '🏷️' },
        { id: 'v2_nama', ar: 'نَامَ يَنَامُ', en: 'To Sleep', bn: 'ঘুমানো', romanized: 'nāma yanāmu', emoji: '🛏️' },
        { id: 'v2_khafa', ar: 'خَافَ يَخَافُ', en: 'To Fear', bn: 'ভয় করা', romanized: 'khāfa yakhāfu', emoji: '🤲' },
        { id: 'v2_tara', ar: 'طَارَ يَطِيرُ', en: 'To Fly', bn: 'ওড়া', romanized: 'ṭāra yaṭīru', emoji: '🕊️' },
        { id: 'v2_farashah', ar: 'فَرَاشَةٌ', en: 'A Butterfly', bn: 'একটি প্রজাপতি', romanized: 'farāshatun', emoji: '🦋' },
        { id: 'v2_mawt', ar: 'مَوْتٌ', en: 'Death', bn: 'মৃত্যু', romanized: 'mawtun', emoji: '⏳' },
        { id: 'v2_an_particle', ar: 'عَنْ', en: 'About / From (Preposition)', bn: 'সম্পর্কে / থেকে (অব্যয়)', romanized: '‘an', emoji: '📍' },
      ],
    },
  },

  // 4. Page 38-40: Speed Pair - Hollow Verbs & Meanings
  {
    id: 'v2-c1-l6-step-4-speed-pair',
    type: 'speed_pair',
    pageNumber: 38,
    titleEn: 'Speed Pair: Hollow Verb Recognition',
    titleAr: 'مُطَابَقَةُ الفِعْلِ الأَجْوَفِ',
    instructionEn: 'Match each hollow verb form to its accurate meaning.',
    instructionBn: 'প্রতিটি আজওয়াফ ক্রিয়ারূপের সঠিক অর্থ মেলাও।',
    pairPayload: {
      pairs: [
        { id: 'sp-1', ar: 'قُلْتُ لَهُ', meaning: 'I said to him', meaningBn: 'আমি তাকে বললাম' },
        { id: 'sp-2', ar: 'لَا تَخَفْ', meaning: 'Do not fear (m)', meaningBn: 'ভয় পেয়ো না' },
        { id: 'sp-3', ar: 'صُمْتُ اليَوْمَ', meaning: 'I fasted today', meaningBn: 'আমি আজ রোজা রেখেছি' },
        { id: 'sp-4', ar: 'تَطِيرُ الفَرَاشَةُ', meaning: 'The butterfly flies', meaningBn: 'প্রজাপতিটি উড়ছে' },
        { id: 'sp-5', ar: 'مَاتَ الإِنْسَانُ', meaning: 'The person died', meaningBn: 'মানুষটি মারা গেল' },
      ],
    },
  },

  // 5. Page 40: Sentence Assembly - Muslim Fears Allah Alone
  {
    id: 'v2-c1-l6-step-5-assembly-fear-allah',
    type: 'sentence_assembly',
    pageNumber: 40,
    titleEn: 'Sentence Assembly: Fearing Allah Alone',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: خَوْفُ اللهِ وَحْدَهُ',
    instructionEn: 'Assemble: "The Muslim fears Allah and does not fear other than Allah."',
    instructionBn: 'বাক্যটি সাজান: "মুসলিম আল্লাহকে ভয় করে এবং আল্লাহ ছাড়া অন্য কাউকে ভয় করে না।"',
    assemblyPayload: {
      promptEn: 'The Muslim fears Allah and does not fear other than Allah.',
      promptBn: 'মুসলিম আল্লাহকে ভয় করে এবং আল্লাহ ছাড়া অন্য কাউকে ভয় করে না।',
      expectedAnswer: ['المُسْلِمُ', 'يَخَافُ', 'اللهَ', 'وَلَا', 'يَخَافُ', 'غَيْرَ', 'اللهِ'],
      chips: ['المُسْلِمُ', 'يَخَافُ', 'اللهَ', 'وَلَا', 'يَخَافُ', 'غَيْرَ', 'اللهِ', 'خَافَ', 'غَيْرُ'],
      expectedAnswerBn: ['মুসলিম', 'আল্লাহকে', 'ভয়', 'করে', 'এবং', 'আল্লাহ', 'ছাড়া', 'অন্য', 'কাউকে', 'ভয়', 'করে', 'না'],
      chipsBn: ['মুসলিম', 'আল্লাহকে', 'ভয়', 'করে', 'এবং', 'আল্লাহ', 'ছাড়া', 'অন্য', 'কাউকে', 'ভয়', 'করে', 'না', 'মানুষ', 'করেছিল'],
      emoji: '🤲',
    },
  },

  // 6. Page 40: Sentence Assembly - Admonition to Majid
  {
    id: 'v2-c1-l6-step-6-assembly-qultu-majid',
    type: 'sentence_assembly',
    pageNumber: 40,
    titleEn: 'Sentence Assembly: Admonition to Repent',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: النَّصِيحَةُ بِالتَّوْبَةِ',
    instructionEn: 'Assemble: "I said to Majid: Repent to Allah and do not abandon prayer."',
    instructionBn: 'বাক্যটি সাজান: "আমি মাজেদকে বললাম: আল্লাহর কাছে তাওবা করো এবং সালাত ত্যাগ করো না।"',
    assemblyPayload: {
      promptEn: 'I said to Majid: Repent to Allah and do not abandon prayer.',
      promptBn: 'আমি মাজেদকে বললাম: আল্লাহর কাছে তাওবা করো এবং সালাত ত্যাগ করো না।',
      expectedAnswer: ['قُلْتُ', 'لِمَاجِدٍ:', 'تُبْ', 'إِلَى', 'اللهِ', 'وَلَا', 'تَتْرُكِ', 'الصَّلَاةَ'],
      chips: ['قُلْتُ', 'لِمَاجِدٍ:', 'تُبْ', 'إِلَى', 'اللهِ', 'وَلَا', 'تَتْرُكِ', 'الصَّلَاةَ', 'قَالَ', 'تُوبِي'],
      expectedAnswerBn: ['আমি', 'মাজেদকে', 'বললাম:', 'আল্লাহর', 'কাছে', 'তাওবা', 'করো', 'এবং', 'সালাত', 'ত্যাগ', 'করো', 'না'],
      chipsBn: ['আমি', 'মাজেদকে', 'বললাম:', 'আল্লাহর', 'কাছে', 'তাওবা', 'করো', 'এবং', 'সালাত', 'ত্যাগ', 'করো', 'না', 'বলেছিল', 'রোজা'],
      emoji: '🕌',
    },
  },

  // 7. Page 40: Sentence Assembly - Muslim Does Not Fear Death
  {
    id: 'v2-c1-l6-step-7-assembly-muslim-death',
    type: 'sentence_assembly',
    pageNumber: 40,
    titleEn: 'Sentence Assembly: Overcoming Fear of Death',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: عَدَمُ خَوْفِ المَوْتِ',
    instructionEn: 'Assemble: "The Muslim does not fear death because he enters Paradise after death."',
    instructionBn: 'বাক্যটি সাজান: "মুসলিম মৃত্যুকে ভয় পায় না কেননা সে মৃত্যুর পর জান্নাতে প্রবেশ করবে।"',
    assemblyPayload: {
      promptEn: 'The Muslim does not fear death because he enters Paradise after death.',
      promptBn: 'মুসলিম মৃত্যুকে ভয় পায় না কেননা সে মৃত্যুর পর জান্নাতে প্রবেশ করবে।',
      expectedAnswer: ['لَا', 'يَخَافُ', 'المُسْلِمُ', 'المَوْتَ', 'لِأَنَّهُ', 'يَدْخُلُ', 'الجَنَّةَ', 'بَعْدَ', 'المَوْتِ'],
      chips: ['لَا', 'يَخَافُ', 'المُسْلِمُ', 'المَوْتَ', 'لِأَنَّهُ', 'يَدْخُلُ', 'الجَنَّةَ', 'بَعْدَ', 'المَوْتِ', 'المَوْتُ', 'النَّارَ'],
      expectedAnswerBn: ['মুসলিম', 'মৃত্যুকে', 'ভয়', 'পায়', 'না', 'কেননা', 'সে', 'মৃত্যুর', 'পর', 'জান্নাতে', 'প্রবেশ', 'করবে'],
      chipsBn: ['মুসলিম', 'মৃত্যুকে', 'ভয়', 'পায়', 'না', 'কেননা', 'সে', 'মৃত্যুর', 'পর', 'জান্নাতে', 'প্রবেশ', 'করবে', 'জাহান্নাম', 'আগে'],
      emoji: '🌿',
    },
  },

  // 8. Page 40: Cloze Choice - Ajwaf Conjugation Selection
  {
    id: 'v2-c1-l6-step-8-cloze-qultu',
    type: 'cloze_choice',
    pageNumber: 40,
    titleEn: 'Hollow Verb Conjugation: First Person "I Said"',
    titleAr: 'اخْتِيَارُ تَصْرِيفِ الفِعْلِ الأَجْوَفِ',
    instructionEn: 'Select the correct 1st-person past form of "qāla" with prepositional recipient: "قُلْتُ لَهُ".',
    instructionBn: '"বলা" ক্রিয়ার উত্তম পুরুষ অতীত রূপ "قُلْتُ لَهُ" নির্বাচন করুন।',
    clozePayload: {
      questionAr: 'أَنَا ... : يَا وَلَدُ! ادْخُلِ المَسْجِدَ .',
      questionEn: 'I [ said to him ]: O boy! Enter the mosque.',
      questionBn: 'আমি [ তাকে বললাম ]: হে ছেলে! মসজিদে প্রবেশ করো।',
      partialAnswerAr: 'أَنَا ... : يَا وَلَدُ! ادْخُلِ المَسْجِدَ .',
      correctAnswer: 'قُلْتُ لَهُ',
      options: ['قُلْتُ لَهُ', 'قَالَ لَهُ', 'قُولِي لَهُ'],
      emoji: '🗣️',
    },
  },

  // 9. Page 41: Alternative QA - Fear & Worship Comprehension
  {
    id: 'v2-c1-l6-step-9-qa-fear-worship',
    type: 'alternative_qa',
    pageNumber: 41,
    titleEn: 'Theological Dialogue: Whom Does the Muslim Fear?',
    titleAr: 'حِوَارُ العَقِيدَةِ: خَوْفُ اللهِ',
    instructionEn: 'Answer questions based on the dialogue on fearing Allah.',
    instructionBn: 'আল্লাহর ভয় সম্পর্কিত কথোপকথন অনুযায়ী প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'المُسْلِمُ يَخَافُ اللهَ وَلَا يَخَافُ غَيْرَ اللهِ. وَأَنَا لَا أَخَافُ المَوْتَ، لِأَنِّي أَدْخُلُ الجَنَّةَ بِرَحْمَةِ اللهِ.',
      questions: [
        {
          id: 'q-who-fears',
          questionAr: 'مَنْ يَخَافُهُ المُسْلِمُ ؟',
          optionsAr: ['يَخَافُ اللهَ', 'يَخَافُ النَّاسَ'],
          correctAnswerAr: 'يَخَافُ اللهَ',
        },
        {
          id: 'q-fear-other',
          questionAr: 'أَ غَيْرَ اللهِ يَخَافُ المُسْلِمُ ؟',
          optionsAr: ['لَا .. لَا يَخَافُ غَيْرَ اللهِ', 'نَعَمْ يَخَافُ'],
          correctAnswerAr: 'لَا .. لَا يَخَافُ غَيْرَ اللهِ',
        },
      ],
    },
  },

  // 10. Page 40: Sentence Assembly - Man Standing Before Allah
  {
    id: 'v2-c1-l6-step-10-assembly-standing-allah',
    type: 'sentence_assembly',
    pageNumber: 40,
    titleEn: 'Sentence Assembly: Standing Before Allah',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: القِيَامُ أَمَامَ اللهِ',
    instructionEn: 'Assemble: "Man will die one day and stand before Allah."',
    instructionBn: 'বাক্যটি সাজান: "মানুষ একদিন মারা যাবে এবং আল্লাহর সামনে দাঁড়াবে।"',
    assemblyPayload: {
      promptEn: 'Man will die one day and stand before Allah.',
      promptBn: 'মানুষ একদিন মারা যাবে এবং আল্লাহর সামনে দাঁড়াবে।',
      expectedAnswer: ['يَمُوتُ', 'الإِنْسَانُ', 'يَوْمًا', 'وَيَقُومُ', 'أَمَامَ', 'اللهِ'],
      chips: ['يَمُوتُ', 'الإِنْسَانُ', 'يَوْمًا', 'وَيَقُومُ', 'أَمَامَ', 'اللهِ', 'مَاتَ', 'قَامَ'],
      expectedAnswerBn: ['মানুষ', 'একদিন', 'মারা', 'যাবে', 'এবং', 'আল্লাহর', 'সামনে', 'দাঁড়াবে'],
      chipsBn: ['মানুষ', 'একদিন', 'মারা', 'যাবে', 'এবং', 'আল্লাহর', 'সামনে', 'দাঁড়াবে', 'মারা', 'গেল'],
      emoji: '⚖️',
    },
  },

  // 11. Page 40: Sentence Assembly - Fasting in Ramadan
  {
    id: 'v2-c1-l6-step-11-assembly-fasting-ramadan',
    type: 'sentence_assembly',
    pageNumber: 40,
    titleEn: 'Sentence Assembly: Fasting in Ramadan',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: الصِّيَامُ فِي رَمَضَانَ',
    instructionEn: 'Assemble: "The Muslim fasts in the month of Ramadan."',
    instructionBn: 'বাক্যটি সাজান: "মুসলিম রমজান মাসে রোজা রাখে।"',
    assemblyPayload: {
      promptEn: 'The Muslim fasts in the month of Ramadan.',
      promptBn: 'মুসলিম রমজান মাসে রোজা রাখে।',
      expectedAnswer: ['يَصُومُ', 'المُسْلِمُ', 'فِي', 'شَهْرِ', 'رَمَضَانَ'],
      chips: ['يَصُومُ', 'المُسْلِمُ', 'فِي', 'شَهْرِ', 'رَمَضَانَ', 'صَامَ', 'شَهْرُ'],
      expectedAnswerBn: ['মুসলিম', 'রমজান', 'মাসে', 'রোজা', 'রাখে'],
      chipsBn: ['মুসলিম', 'রমজান', 'মাসে', 'রোজা', 'রাখে', 'রেখেছিল', 'মাস'],
      emoji: '🌙',
    },
  },

  // 12. Page 42: Alternative QA - The Idolater's Fear
  {
    id: 'v2-c1-l6-step-12-qa-idolater-death',
    type: 'alternative_qa',
    pageNumber: 42,
    titleEn: 'Alternative QA: The Idolater\'s Fear of Death',
    titleAr: 'فَهْمُ حَالِ المُشْرِكِ عِنْدَ المَوْتِ',
    instructionEn: 'Answer questions about why the idolater fears death.',
    instructionBn: 'মুশরিক কেন মৃত্যুকে ভয় পায় সে সম্পর্কিত প্রশ্নের উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'يَخَافُ المُشْرِكُ المَوْتَ، لِأَنَّهُ يَدْخُلُ النَّارَ بَعْدَ المَوْتِ. أَمَّا المُسْلِمُ فَلَا يَخَافُهُ.',
      questions: [
        {
          id: 'q-why-mushrik-fear',
          questionAr: 'لِمَ يَخَافُ المُشْرِكُ المَوْتَ ؟',
          optionsAr: ['لِأَنَّهُ يَدْخُلُ النَّارَ بَعْدَ المَوْتِ', 'لِأَنَّهُ فَقِيرٌ'],
          correctAnswerAr: 'لِأَنَّهُ يَدْخُلُ النَّارَ بَعْدَ المَوْتِ',
        },
        {
          id: 'q-does-muslim-fear',
          questionAr: 'هَلْ يَخَافُ المُسْلِمُ المَوْتَ ؟',
          optionsAr: ['لَا يَخَافُ المَوْتَ', 'نَعَمْ يَخَافُ'],
          correctAnswerAr: 'لَا يَخَافُ المَوْتَ',
        },
      ],
    },
  },

  // 13. Page 41: Sentence Assembly - The Flying Butterfly
  {
    id: 'v2-c1-l6-step-13-assembly-butterfly',
    type: 'sentence_assembly',
    pageNumber: 41,
    titleEn: 'Sentence Assembly: The Beautiful Butterfly',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: طَيَرَانُ الفَرَاشَةِ',
    instructionEn: 'Assemble: "This beautiful butterfly flies from flower to flower."',
    instructionBn: 'বাক্যটি সাজান: "এই সুন্দর প্রজাপতিটি এক ফুল থেকে অন্য ফুলে উড়ছে।"',
    assemblyPayload: {
      promptEn: 'This beautiful butterfly flies from flower to flower.',
      promptBn: 'এই সুন্দর প্রজাপতিটি এক ফুল থেকে অন্য ফুলে উড়ছে।',
      expectedAnswer: ['هَذِهِ', 'الفَرَاشَةُ', 'الجَمِيلَةُ', 'تَطِيرُ', 'مِنْ', 'زَهْرَةٍ', 'إِلَى', 'زَهْرَةٍ'],
      chips: ['هَذِهِ', 'الفَرَاشَةُ', 'الجَمِيلَةُ', 'تَطِيرُ', 'مِنْ', 'زَهْرَةٍ', 'إِلَى', 'زَهْرَةٍ', 'طَارَ', 'عُصْفُورٌ'],
      expectedAnswerBn: ['এই', 'সুন্দর', 'প্রজাপতিটি', 'এক', 'ফুল', 'থেকে', 'অন্য', 'ফুলে', 'উড়ছে'],
      chipsBn: ['এই', 'সুন্দর', 'প্রজাপতিটি', 'এক', 'ফুল', 'থেকে', 'অন্য', 'ফুলে', 'উড়ছে', 'পাখি', 'উড়েছিল'],
      emoji: '🦋',
    },
  },

  // 14. Page 41: Sentence Assembly - Sleeping After Isha
  {
    id: 'v2-c1-l6-step-14-assembly-sleep-isha',
    type: 'sentence_assembly',
    pageNumber: 41,
    titleEn: 'Sentence Assembly: Sleeping Discipline',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: النَّوْمُ بَعْدَ العِشَاءِ',
    instructionEn: 'Assemble: "I do not sleep before Isha; rather, I sleep after Isha."',
    instructionBn: 'বাক্যটি সাজান: "আমি এশার পূর্বে ঘুমাই না, বরং এশার পরে ঘুমাই।"',
    assemblyPayload: {
      promptEn: 'I do not sleep before Isha; rather, I sleep after Isha.',
      promptBn: 'আমি এশার পূর্বে ঘুমাই না, বরং এশার পরে ঘুমাই।',
      expectedAnswer: ['لَا', 'أَنَامُ', 'قَبْلَ', 'العِشَاءِ،', 'بَلْ', 'أَنَامُ', 'بَعْدَ', 'العِشَاءِ'],
      chips: ['لَا', 'أَنَامُ', 'قَبْلَ', 'العِشَاءِ،', 'بَلْ', 'أَنَامُ', 'بَعْدَ', 'العِشَاءِ', 'نِمْتُ', 'المَغْرِبِ'],
      expectedAnswerBn: ['আমি', 'এশার', 'পূর্বে', 'ঘুমাই', 'না,', 'বরং', 'এশার', 'পরে', 'ঘুমাই'],
      chipsBn: ['আমি', 'এশার', 'পূর্বে', 'ঘুমাই', 'না,', 'বরং', 'এশার', 'পরে', 'ঘুমাই', 'ঘুমালাম', 'মাগরিব'],
      emoji: '🛏️',
    },
  },

  // 15. Page 40: Syntactic Dissector (Tarkib) - Hollow Verb with Indirect Object
  {
    id: 'v2-c1-l6-step-15-tarkib-qala-indirect',
    type: 'tarkib_dissector',
    pageNumber: 40,
    titleEn: 'Syntactic Dissector: Hollow Verb with Prepositional Recipient',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: قَالَ لَهُ',
    instructionEn: 'Slot each component: Hollow Past Verb, Doer, and Prepositional Recipient.',
    instructionBn: 'প্রতিটি অংশ বসান: আজওয়াফ অতীত ক্রিয়া, কর্তা এবং متعلق।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-qala-rashid-abihi',
          sentenceAr: 'قَالَ رَاشِدٌ لِأَبِيهِ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ جَوْفَاءُ مَعَ مُتَعَلِّقٍ',
          sentenceTypeEn: 'Hollow Verbal Sentence with Prepositional Attachment',
          sentenceTypeBn: 'আজওয়াফ ক্রিয়াবাচক বাক্য متعلق সহ',
          slots: [
            { roleAr: 'فِعْلٌ مَاضٍ أَجْوَفُ', roleEn: 'Hollow Past Verb', roleBn: 'আজওয়াফ অতীত কাজ', expectedWordAr: 'قَالَ' },
            { roleAr: 'فَاعِلٌ (مَرْفُوعٌ بِالضَّمَّةِ)', roleEn: 'Doer / Subject (Nominative)', roleBn: 'কর্তা (ফায়েল)', expectedWordAr: 'رَاشِدٌ' },
            { roleAr: 'مُتَعَلِّقٌ بِالفِعْلِ (جَارٌّ وَمَجْرُورٌ)', roleEn: 'Prepositional Recipient', roleBn: 'ক্রিয়ার متعلق', expectedWordAr: 'لِأَبِيهِ' },
          ],
          availableWordsAr: ['قَالَ', 'رَاشِدٌ', 'لِأَبِيهِ'],
        },
      ],
    },
  },

  // 16. Page 40: Syntactic Dissector (Tarkib) - Hollow Verb with Direct Object
  {
    id: 'v2-c1-l6-step-16-tarkib-yakhafu-allaha',
    type: 'tarkib_dissector',
    pageNumber: 40,
    titleEn: 'Syntactic Dissector: Hollow Verb with Direct Object',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: يَخَافُ المُسْلِمُ اللهَ',
    instructionEn: 'Slot each component: Present Hollow Verb, Doer, and Accusative Direct Object.',
    instructionBn: 'প্রতিটি অংশ বসান: বর্তমান আজওয়াফ ক্রিয়া, কর্তা এবং কর্ম (মাফ\'উল বিহী)।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-yakhafu-allaha',
          sentenceAr: 'يَخَافُ المُسْلِمُ اللهَ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ جَوْفَاءُ مُتَعَدِّيَةٌ',
          sentenceTypeEn: 'Transitive Hollow Verbal Sentence',
          sentenceTypeBn: 'সকর্মক আজওয়াফ ক্রিয়াবাচক বাক্য',
          slots: [
            { roleAr: 'فِعْلٌ مُضَارِعٌ أَجْوَفُ', roleEn: 'Present Hollow Verb', roleBn: 'বর্তমান আজওয়াফ ক্রিয়া', expectedWordAr: 'يَخَافُ' },
            { roleAr: 'فَاعِلٌ (مَرْفُوعٌ بِالضَّمَّةِ)', roleEn: 'Doer / Subject (Nominative)', roleBn: 'কর্তা (ফায়েল)', expectedWordAr: 'المُسْلِمُ' },
            { roleAr: 'مَفْعُولٌ بِهِ (مَنْصُوبٌ بِالفَتْحَةِ)', roleEn: 'Direct Object (Accusative)', roleBn: 'কর্ম (মাফ\'উল বিহী)', expectedWordAr: 'اللهَ' },
          ],
          availableWordsAr: ['يَخَافُ', 'المُسْلِمُ', 'اللهَ'],
        },
      ],
    },
  },

  // 17. Page 39: Quranic Echo - Surah Al-Baqarah (2:255) - Ayat Al-Kursi
  {
    id: 'v2-c1-l6-step-17-quranic-echo-nawm',
    type: 'quranic_echo',
    pageNumber: 39,
    titleEn: 'Divine Perfection: Neither Slumber Nor Sleep',
    titleAr: 'صَدَى القُرْآنِ: (لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ)',
    instructionEn: 'Reflect on how the hollow root "ن و م" (sleep) appears in the greatest verse of the Quran (Ayat Al-Kursi).',
    instructionBn: 'কুরআনের শ্রেষ্ঠতম আয়াত আয়াতুল কুরসীতে "ن و م" (ঘুম) ধাতুটি কীভাবে এসেছে তা অনুধাবন করুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 255,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ',
      translationEn: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep.',
      translationBn: 'আল্লাহ, তিনি ছাড়া কোনো সত্য ইলাহ নেই, তিনি চিরঞ্জীব, সর্বসত্তার ধারক। তন্দ্রা বা নিদ্রা তাঁকে স্পর্শ করতে পারে না।',
      highlightedWords: ['الْحَيُّ', 'الْقَيُّومُ', 'نَوْمٌ'],
      reflection: 'The noun "نَوْمٌ" (sleep) and its verbal root "نَامَ يَنَامُ" you mastered today is celebrated in Ayat Al-Kursi as an attribute of human limitation that can never touch the majesty of Allah, the Ever-Living Sustainer.',
    },
  },
];

export const VOL2_CH1_LESSON_06_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 6,
  titleEn: 'The Hollow Verbs Paradigm (الفِعْلُ الأَجْوَفُ)',
  titleAr: 'الفِعْلُ الأَجْوَفُ وَتَصْرِيفَاتُهُ',
  wordsLearned: [
    'قَالَ', 'صَامَ', 'قَامَ', 'تَابَ', 'مَاتَ', 'بَاعَ', 'صَادَ', 'خَاطَ', 'طَارَ',
    'نَامَ', 'خَافَ', 'فَرَاشَةٌ', 'مَوْتٌ', 'عَنْ'
  ],
  steps: VOL2_CH1_LESSON_06_STEPS,
};
