// Volume 2 Chapter 1 Lesson 3 Interactive Session Steps (100% Curricular Parity with Physical Book Scans pages 24-27)
import type { LessonSessionData, SessionStep } from './lessonSessionTypes';

export const VOL2_CH1_LESSON_03_STEPS: SessionStep[] = [
  // 1. Page 24: Concept Discovery - The Masdar (Verbal Noun) & 4 Abwaab
  {
    id: 'v2-c1-l3-step-1-concept-masdar',
    type: 'concept_intro',
    pageNumber: 24,
    titleEn: 'The Masdar: Origin of Verbs',
    titleAr: 'مَدْخَلُ المَصْدَرِ وَالأَبْوَابِ الأَرْبَعَةِ',
    instructionEn: 'Learn how Arabic verbs originate from root verbal nouns (Masdar) across 4 standard phonetic patterns (Abwaab).',
    instructionBn: 'ক্রিয়ার মূল উৎস ক্রিয়ামূল (মাসদার) এবং এর ৪টি প্রধান রূপান্তর পদ্ধতি (বাব) লক্ষ্য করুন।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-masdar-fataha',
          ar: 'الفِعْلُ ➔ فَعَلَ يَفْعَلُ',
          romanized: 'al-fi‘lu ➔ fa‘ala yaf‘alu',
          meaningEn: 'The Doing ➔ Bab Fataha (a - a pattern)',
          meaningBn: 'করা ➔ ফা-তা-হা বাবের ওজন (মাযী যবর - মুদারী যবর)',
          exampleAr: 'القِرَاءَةُ ➔ قَرَأَ يَقْرَأُ',
          exampleEn: 'Reading ➔ He read / He reads',
          exampleBn: 'পড়া ➔ সে পড়ল / সে পড়ছে',
          audioKey: 'الفِعْلُ',
          exampleAudioKey: 'قَرَأَ يَقْرَأُ',
          emoji: '📖',
        },
        {
          id: 'c-masdar-nasara',
          ar: 'الخُرُوجُ ➔ خَرَجَ يَخْرُجُ',
          romanized: 'al-khurūju ➔ kharaja yakhruju',
          meaningEn: 'The Exiting ➔ Bab Nasara (a - u pattern)',
          meaningBn: 'বের হওয়া ➔ না-সা-রা বাবের ওজন (মাযী যবর - মুদারী পেশ)',
          exampleAr: 'الكِتَابَةُ ➔ كَتَبَ يَكْتُبُ',
          exampleEn: 'Writing ➔ He wrote / He writes',
          exampleBn: 'লেখা ➔ সে লিখল / সে লিখছে',
          audioKey: 'الخُرُوجُ',
          exampleAudioKey: 'كَتَبَ يَكْتُبُ',
          emoji: '🚪',
        },
        {
          id: 'c-masdar-daraba',
          ar: 'الجُلُوسُ ➔ جَلَسَ يَجْلِسُ',
          romanized: 'al-julūsu ➔ jalasa yajlisu',
          meaningEn: 'The Sitting ➔ Bab Daraba (a - i pattern)',
          meaningBn: 'বসা ➔ দা-রা-বা বাবের ওজন (মাযী যবর - মুদারী যের)',
          exampleAr: 'الرُّجُوعُ ➔ رَجَعَ يَرْجِعُ',
          exampleEn: 'Returning ➔ He returned / He returns',
          exampleBn: 'ফেরা ➔ সে ফিরল / সে ফিরছে',
          audioKey: 'الجُلُوسُ',
          exampleAudioKey: 'رَجَعَ يَرْجِعُ',
          emoji: '🪑',
        },
        {
          id: 'c-masdar-samia',
          ar: 'اللَّعِبُ ➔ لَعِبَ يَلْعَبُ',
          romanized: 'al-la‘ibu ➔ la‘iba yal‘abu',
          meaningEn: 'The Playing ➔ Bab Sami‘a (i - a pattern)',
          meaningBn: 'খেলা ➔ সা-মি-\'আ বাবের ওজন (মাযী যের - মুদারী যবর)',
          exampleAr: 'الشُّرْبُ ➔ شَرِبَ يَشْرَبُ',
          exampleEn: 'Drinking ➔ He drank / He drinks',
          exampleBn: 'পান করা ➔ সে পান করল / সে পান করছে',
          audioKey: 'اللَّعِبُ',
          exampleAudioKey: 'شَرِبَ يَشْرَبُ',
          emoji: '⚽',
        },
      ],
    },
  },

  // 2. Page 24-25: Interactive Masdar Factory
  {
    id: 'v2-c1-l3-step-2-masdar-factory',
    type: 'masdar_factory',
    pageNumber: 24,
    titleEn: 'The Masdar Factory: 4 Families of Verbs',
    titleAr: 'مَصْنَعُ المَصَادِرِ: أَوْزَانُ الأَفْعَالِ',
    instructionEn: 'Observe the verbal noun (Masdar) and discover how its verb pattern determines the vowel in the present tense.',
    instructionBn: 'ক্রিয়ামূল (মাসদার) লক্ষ্য করুন এবং জানুন কীভাবে বাবের নিয়ম বর্তমান কালের হরকত নির্ধারণ করে।',
    masdarPayload: {
      items: [
        {
          id: 'mf-qiraah',
          masdarAr: 'القِرَاءَةُ',
          masdarMeaningEn: 'Reading',
          masdarMeaningBn: 'পড়া',
          baabPatternAr: 'بَاب فَتَحَ يَفْتَحُ',
          baabPatternEn: 'Bab Fataha (a ➔ a)',
          baabPatternBn: 'ফা-তা-হা বাব (a ➔ a)',
          vowelShiftEn: 'a ➔ a (Fathah ➔ Fathah)',
          vowelShiftBn: 'a ➔ a (যবর ➔ যবর)',
          patternRuleEn: 'The middle letter keeps Fathah (a) in both past and present.',
          patternRuleBn: 'অতীত ও বর্তমান উভয় রূপেই মাঝের অক্ষরে যবর থাকে।',
          pastAr: 'قَرَأَ',
          pastMeaningEn: 'He read',
          pastMeaningBn: 'সে পড়ল',
          presentAr: 'يَقْرَأُ',
          presentMeaningEn: 'He reads',
          presentMeaningBn: 'সে পড়ে',
          presentOptionsAr: ['يَقْرَأُ', 'يَقْرُؤُ', 'يَقْرِئُ'],
          imperativeAr: 'اِقْرَأْ',
          imperativeMeaningEn: 'Read! (m)',
          imperativeMeaningBn: 'তুমি পড়ো',
          prohibitionAr: 'لَا تَقْرَأْ',
          prohibitionMeaningEn: "Don't read! (m)",
          prohibitionMeaningBn: 'তুমি পড়ো না',
          emoji: '📖',
        },
        {
          id: 'mf-kitabah',
          masdarAr: 'الكِتَابَةُ',
          masdarMeaningEn: 'Writing',
          masdarMeaningBn: 'লেখা',
          baabPatternAr: 'بَاب نَصَرَ يَنْصُرُ',
          baabPatternEn: 'Bab Nasara (a ➔ u)',
          baabPatternBn: 'না-সা-রা বাব (a ➔ u)',
          vowelShiftEn: 'a ➔ u (Fathah ➔ Dammah)',
          vowelShiftBn: 'a ➔ u (যবর ➔ পেশ)',
          patternRuleEn: 'The middle letter shifts from Fathah (a) in past to Dammah (u) in present.',
          patternRuleBn: 'মাযীতে মাঝের অক্ষরে যবর (a) থাকলেও মুদারীতে পেশ (u) হয়।',
          pastAr: 'كَتَبَ',
          pastMeaningEn: 'He wrote',
          pastMeaningBn: 'সে লিখল',
          presentAr: 'يَكْتُبُ',
          presentMeaningEn: 'He writes',
          presentMeaningBn: 'সে লেখে',
          presentOptionsAr: ['يَكْتُبُ', 'يَكْتَبُ', 'يَكْتِبُ'],
          imperativeAr: 'اُكْتُبْ',
          imperativeMeaningEn: 'Write! (m)',
          imperativeMeaningBn: 'তুমি লেখো',
          prohibitionAr: 'لَا تَكْتُبْ',
          prohibitionMeaningEn: "Don't write! (m)",
          prohibitionMeaningBn: 'তুমি লিখো না',
          emoji: '✍️',
        },
        {
          id: 'mf-julus',
          masdarAr: 'الجُلُوسُ',
          masdarMeaningEn: 'Sitting',
          masdarMeaningBn: 'বসা',
          baabPatternAr: 'بَاب ضَرَبَ يَضْرِبُ',
          baabPatternEn: 'Bab Daraba (a ➔ i)',
          baabPatternBn: 'দা-রা-বা বাব (a ➔ i)',
          vowelShiftEn: 'a ➔ i (Fathah ➔ Kasrah)',
          vowelShiftBn: 'a ➔ i (যবর ➔ যের)',
          patternRuleEn: 'The middle letter shifts from Fathah (a) in past to Kasrah (i) in present.',
          patternRuleBn: 'মাযীতে মাঝের অক্ষরে যবর (a) থাকলেও মুদারীতে যের (i) হয়।',
          pastAr: 'جَلَسَ',
          pastMeaningEn: 'He sat',
          pastMeaningBn: 'সে বসল',
          presentAr: 'يَجْلِسُ',
          presentMeaningEn: 'He sits',
          presentMeaningBn: 'সে বসে',
          presentOptionsAr: ['يَجْلِسُ', 'يَجْلَسُ', 'يَجْلُسُ'],
          imperativeAr: 'اِجْلِسْ',
          imperativeMeaningEn: 'Sit! (m)',
          imperativeMeaningBn: 'তুমি বসো',
          prohibitionAr: 'لَا تَجْلِسْ',
          prohibitionMeaningEn: "Don't sit! (m)",
          prohibitionMeaningBn: 'তুমি বসো না',
          emoji: '🪑',
        },
        {
          id: 'mf-shurb',
          masdarAr: 'الشُّرْبُ',
          masdarMeaningEn: 'Drinking',
          masdarMeaningBn: 'পান করা',
          baabPatternAr: 'بَاب سَمِعَ يَسْمَعُ',
          baabPatternEn: 'Bab Sami‘a (i ➔ a)',
          baabPatternBn: 'সা-মি-‘আ বাব (i ➔ a)',
          vowelShiftEn: 'i ➔ a (Kasrah ➔ Fathah)',
          vowelShiftBn: 'i ➔ a (যের ➔ যবর)',
          patternRuleEn: 'The middle letter shifts from Kasrah (i) in past to Fathah (a) in present.',
          patternRuleBn: 'মাযীতে মাঝের অক্ষরে যের (i) থাকলেও মুদারীতে যবর (a) হয়।',
          pastAr: 'شَرِبَ',
          pastMeaningEn: 'He drank',
          pastMeaningBn: 'সে পান করল',
          presentAr: 'يَشْرَبُ',
          presentMeaningEn: 'He drinks',
          presentMeaningBn: 'সে পান করে',
          presentOptionsAr: ['يَشْرَبُ', 'يَشْرُبُ', 'يَشْرِبُ'],
          imperativeAr: 'اِشْرَبْ',
          imperativeMeaningEn: 'Drink! (m)',
          imperativeMeaningBn: 'তুমি পান করো',
          prohibitionAr: 'لَا تَشْرَبْ',
          prohibitionMeaningEn: "Don't drink! (m)",
          prohibitionMeaningBn: 'তুমি পান করো না',
          emoji: '🥤',
        },
      ],
    },
  },

  // 3. Page 24-25: Word Construction - Deriving Verbs from Primary Masdars
  {
    id: 'v2-c1-l3-step-3-word-construction-primary',
    type: 'word_construction',
    pageNumber: 24,
    titleEn: 'Word Construction: Deriving Verbs from Masdars',
    titleAr: 'اشْتِقَاقُ الفِعْلِ مِنَ المَصْدَرِ: بِنَاءُ الكَلِمَةِ',
    instructionEn: 'Derive the required verb form from the verbal noun and assemble the letters in order.',
    instructionBn: 'মূল মাছদার থেকে নির্দেশিত ক্রিয়া রূপটি গঠন করুন এবং বর্ণগুলো ক্রমানুসারে সাজান।',
    itemId: 'v2_l3_word_construction_primary',
    wordConstructionPayload: {
      items: [
        {
          id: 'wc-l3-kitabah',
          sourceWordAr: 'الكِتَابَةُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'اُكْتُبْ',
          promptEn: 'Derive the Command (Amr) for Baab Nasara: "Write!" (m)',
          promptBn: 'বাব নাসারা এর নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "তুমি লেখো"',
          targetMeaningEn: 'Write! (m)',
          targetMeaningBn: 'তুমি লেখো',
          chips: ['اُ', 'كْ', 'تُ', 'بْ', 'اِ', 'تَ', 'بَ'],
          emoji: '✍️',
        },
        {
          id: 'wc-l3-qiraah',
          sourceWordAr: 'القِرَاءَةُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'اِقْرَأْ',
          promptEn: 'Derive the Command (Amr) for Baab Fataha: "Read!" (m)',
          promptBn: 'বাব ফাতাহা এর নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "তুমি পড়ো"',
          targetMeaningEn: 'Read! (m)',
          targetMeaningBn: 'তুমি পড়ো',
          chips: ['اِ', 'قْ', 'رَ', 'أْ', 'اُ', 'تَ', 'يَ'],
          emoji: '📖',
        },
        {
          id: 'wc-l3-julus',
          sourceWordAr: 'الجُلُوسُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'يَجْلِسُ',
          promptEn: 'Derive the Present (Mudari) for Baab Daraba: "He sits"',
          promptBn: 'বাব দারাবা এর বর্তমান ক্রিয়া (মুদারী) গঠন করুন: "সে বসে"',
          targetMeaningEn: 'He sits',
          targetMeaningBn: 'সে বসে',
          chips: ['يَ', 'جْ', 'لِ', 'سُ', 'تَ', 'سَ', 'لُ'],
          emoji: '🪑',
        },
        {
          id: 'wc-l3-akl',
          sourceWordAr: 'الأَكْلُ',
          sourceWordLabelEn: 'Verbal Noun (Masdar)',
          sourceWordLabelBn: 'মূল মাছদার',
          targetWordAr: 'كُلْ',
          promptEn: 'Derive the irregular Command (Amr): "Eat!" (Hamzah dropped)',
          promptBn: 'হামযাহ বিলুপ্তির বিশেষ নির্দেশবাচক ক্রিয়া (আমর) গঠন করুন: "তুমি খাও"',
          targetMeaningEn: 'Eat! (m)',
          targetMeaningBn: 'তুমি খাও',
          chips: ['كُ', 'لْ', 'اُ', 'كْ', 'لُ'],
          emoji: '🍽️',
        },
      ],
    },
  },

  // 4. Page 25: Vocab Prime - Second Wave of Masdars
  {
    id: 'v2-c1-l3-step-4-vocab-second-wave',
    type: 'vocab_prime',
    pageNumber: 25,
    titleEn: 'Verbal Nouns (Masdars) Inventory',
    titleAr: 'قَائِمَةُ المَصَادِرِ الجَدِيدَةِ',
    instructionEn: 'Listen to the 8 newly introduced verbal nouns and their everyday roots.',
    instructionBn: '৮টি নতুন ক্রিয়ামূল (মাসদার) ও তাদের অর্থ মনোযোগ দিয়ে শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_sibahah', ar: 'السِّبَاحَةُ', en: 'Swimming', bn: 'সাঁতার কাটা', romanized: 'as-sibāḥatu', emoji: '🏊' },
        { id: 'v2_najah', ar: 'النَّجَاحُ', en: 'Succeeding', bn: 'সফল হওয়া', romanized: 'an-najāḥu', emoji: '🏆' },
        { id: 'v2_nuzul', ar: 'النُّزُولُ', en: 'Descending', bn: 'নামা / অবতীর্ণ হওয়া', romanized: 'an-nuzūlu', emoji: '🌧️' },
        { id: 'v2_sidq', ar: 'الصِّدْقُ', en: 'Truth-telling', bn: 'সত্য বলা', romanized: 'aṣ-ṣidqu', emoji: '💎' },
        { id: 'v2_kidhb', ar: 'الكَذِبُ', en: 'Lying', bn: 'মিথ্যা বলা', romanized: 'al-kidhibu', emoji: '🤥' },
        { id: 'v2_akl', ar: 'الأَكْلُ', en: 'Eating', bn: 'খাওয়া', romanized: 'al-aklu', emoji: '🍽️' },
        { id: 'v2_shurb_v', ar: 'الشُّرْبُ', en: 'Drinking', bn: 'পান করা', romanized: 'ash-shurbu', emoji: '🥤' },
        { id: 'v2_dahik', ar: 'الضَّحِكُ', en: 'Laughing', bn: 'হাসা', romanized: 'aḍ-ḍaḥiku', emoji: '😄' },
      ],
    },
  },

  // 4. Page 26: Concept Discovery - Causal Particle لِأَنَّ ("Because")
  {
    id: 'v2-c1-l3-step-4-concept-lianna',
    type: 'concept_intro',
    pageNumber: 26,
    titleEn: 'Causal Connector: لِأَنَّ (Because)',
    titleAr: 'أَدَاةُ التَّعْلِيلِ: (لِأَنَّ)',
    instructionEn: 'Study how لِأَنَّ connects clauses with attached pronoun suffixes to explain the reason for an action.',
    instructionBn: 'ক্রিয়ার কারণ বোঝাতে সর্বনামসহ لِأَنَّ এর ব্যবহার লক্ষ্য করুন।',
    conceptPayload: {
      concepts: [
        {
          id: 'c-liannahu',
          ar: 'لِأَنَّهُ صَائِمٌ',
          romanized: 'li-annahu ṣā’imun',
          meaningEn: 'Because he is fasting',
          meaningBn: 'কেননা সে রোযাদার',
          exampleAr: 'مَا أَكَلَ رَاشِدٌ لِأَنَّهُ صَائِمٌ',
          exampleEn: 'Rashid did not eat because he is fasting.',
          exampleBn: 'রাশেদ খায়নি কেননা সে রোযাদার।',
          audioKey: 'لِأَنَّهُ صَائِمٌ',
          exampleAudioKey: 'مَا أَكَلَ رَاشِدٌ لِأَنَّهُ صَائِمٌ',
          emoji: '🌙',
        },
        {
          id: 'c-liannaha',
          ar: 'لِأَنَّهَا طِفْلَةٌ',
          romanized: 'li-annahā ṭiflatun',
          meaningEn: 'Because she is a young child',
          meaningBn: 'কেননা সে ছোট শিশু',
          exampleAr: 'أَكَلَتْ فَاطِمَةُ لِأَنَّهَا طِفْلَةٌ صَغِيرَةٌ',
          exampleEn: 'Fatima ate because she is a little child.',
          exampleBn: 'ফাতেমা খেয়েছে কেননা সে ছোট মেয়ে।',
          audioKey: 'لِأَنَّهَا طِفْلَةٌ',
          exampleAudioKey: 'أَكَلَتْ فَاطِمَةُ لِأَنَّهَا طِفْلَةٌ صَغِيرَةٌ',
          emoji: '👧',
        },
        {
          id: 'c-lianni',
          ar: 'لِأَنِّي مَرِيضٌ',
          romanized: 'li-annī marīḍun',
          meaningEn: 'Because I am sick',
          meaningBn: 'কেননা আমি অসুস্থ',
          exampleAr: 'مَا ذَهَبْتُ إِلَى الْمَدْرَسَةِ لِأَنِّي مَرِيضٌ',
          exampleEn: 'I did not go to school because I am sick.',
          exampleBn: 'আমি মাদরাসায় যাইনি কেননা আমি অসুস্থ।',
          audioKey: 'لِأَنِّي مَرِيضٌ',
          exampleAudioKey: 'مَا ذَهَبْتُ إِلَى الْمَدْرَسَةِ لِأَنِّي مَرِيضٌ',
          emoji: '🤒',
        },
      ],
    },
  },

  // 5. Page 26: Vocab Prime - Ramadan & Life Nouns
  {
    id: 'v2-c1-l3-step-5-vocab-ramadan',
    type: 'vocab_prime',
    pageNumber: 26,
    titleEn: 'Ramadan, Time & Character Nouns',
    titleAr: 'مُفْرَدَاتُ رَمَضَانَ وَالحَيَاةِ',
    instructionEn: 'Listen to the thematic nouns of Ramadan and human virtue.',
    instructionBn: 'রমযান মাস ও মানবজীবনের গুণবাচক শব্দগুলো শুনুন।',
    vocabPayload: {
      words: [
        { id: 'v2_shahr', ar: 'شَهْرٌ', en: 'Month', bn: 'মাস', romanized: 'shahrun', emoji: '📅' },
        { id: 'v2_ramadan', ar: 'رَمَضَانُ', en: 'Ramadan', bn: 'রমযান মাস', romanized: 'Ramaḍānu', emoji: '🌙' },
        { id: 'v2_saim', ar: 'صَائِمٌ', en: 'Fasting person', bn: 'রোযাদার', romanized: 'ṣā’imun', emoji: '🤲' },
        { id: 'v2_nahar', ar: 'نَهَارٌ', en: 'Daytime', bn: 'দিন / দিবস', romanized: 'nahārun', emoji: '☀️' },
        { id: 'v2_matar', ar: 'مَطَرٌ', en: 'Rain', bn: 'বৃষ্টি', romanized: 'maṭarun', emoji: '🌧️' },
        { id: 'v2_hayah', ar: 'حَيَاةٌ', en: 'Life', bn: 'জীবন', romanized: 'ḥayātun', emoji: '🌱' },
        { id: 'v2_kaslan', ar: 'كَسْلَانُ', en: 'Lazy', bn: 'অলস', romanized: 'kaslānu', emoji: '🥱' },
      ],
    },
  },

  // 6. Page 25: Speed Pair - Masdar to Verb
  {
    id: 'v2-c1-l3-step-6-pair-masdar-verb',
    type: 'speed_pair',
    pageNumber: 25,
    titleEn: 'Synaptic Recall: Masdar to Action',
    titleAr: 'تَطْبِيقُ المَصَادِرِ وَالأَفْعَالِ',
    instructionEn: 'Match each Masdar or verb to its correct meaning.',
    instructionBn: 'মাসদার ও ক্রিয়ার সাথে সঠিক অর্থ মিলিয়ে দিন।',
    pairPayload: {
      pairs: [
        { id: 'p-sidq', ar: 'الصِّدْقُ', meaning: 'Truth-telling' },
        { id: 'p-kidhb', ar: 'الكَذِبُ', meaning: 'Lying' },
        { id: 'p-nuzul', ar: 'النُّزُولُ', meaning: 'Descending' },
        { id: 'p-yasbahu', ar: 'يَسْبَحُ', meaning: 'He swims' },
        { id: 'p-yanzilu', ar: 'يَنْزِلُ', meaning: 'He descends' },
      ],
    },
  },

  // 7. Page 26: Sentence Assembly - Fatima Eating in Ramadan
  {
    id: 'v2-c1-l3-step-7-assembly-fatima-ramadan',
    type: 'sentence_assembly',
    pageNumber: 26,
    titleEn: 'Causal Clause: Fatima Ate',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: أَكْلُ فَاطِمَةَ',
    instructionEn: 'Assemble: "Fatima ate and drank in Ramadan daytime because she is a little girl."',
    instructionBn: 'বাক্যটি সাজান: "ফাতেমা রমযানের দিনে খেল ও পান করল কেননা সে ছোট মেয়ে।"',
    assemblyPayload: {
      promptEn: 'Fatima ate and drank in Ramadan daytime because she is a little girl.',
      promptBn: 'ফাতেমা রমযানের দিনে খেল ও পান করল কেননা সে ছোট মেয়ে।',
      expectedAnswer: ['أَكَلَتْ', 'فَاطِمَةُ', 'فِي', 'نَهَارِ', 'رَمَضَانَ', 'لِأَنَّهَا', 'طِفْلَةٌ', 'صَغِيرَةٌ'],
      chips: ['أَكَلَتْ', 'فَاطِمَةُ', 'فِي', 'نَهَارِ', 'رَمَضَانَ', 'لِأَنَّهَا', 'طِفْلَةٌ', 'صَغِيرَةٌ', 'لِأَنَّهُ', 'صَائِمٌ'],
      expectedAnswerBn: ['ফাতেমা', 'রমযানের', 'দিনে', 'খেল', 'কেননা', 'সে', 'ছোট', 'মেয়ে'],
      chipsBn: ['ফাতেমা', 'রমযানের', 'দিনে', 'খেল', 'কেননা', 'সে', 'ছোট', 'মেয়ে', 'রোযাদার', 'গেল'],
      emoji: '👧',
    },
  },

  // 8. Page 26: Sentence Assembly - Rashid Fasting
  {
    id: 'v2-c1-l3-step-8-assembly-rashid-fasting',
    type: 'sentence_assembly',
    pageNumber: 26,
    titleEn: 'Causal Clause: Rashid Fasting',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ: صِيَامُ رَاشِدٍ',
    instructionEn: 'Assemble: "Rashid did not eat and did not drink because he is fasting."',
    instructionBn: 'বাক্যটি সাজান: "রাশেদ খায়নি এবং পান করেনি কেননা সে রোযাদার।"',
    assemblyPayload: {
      promptEn: 'Rashid did not eat and did not drink because he is fasting.',
      promptBn: 'রাশেদ খায়নি এবং পান করেনি কেননা সে রোযাদার।',
      expectedAnswer: ['مَا', 'أَكَلَ', 'رَاشِدٌ', 'وَمَا', 'شَرِبَ', 'لِأَنَّهُ', 'صَائِمٌ'],
      chips: ['مَا', 'أَكَلَ', 'رَاشِدٌ', 'وَمَا', 'شَرِبَ', 'لِأَنَّهُ', 'صَائِمٌ', 'لِأَنَّهَا', 'طِفْلَةٌ'],
      expectedAnswerBn: ['রাশেদ', 'খায়নি', 'এবং', 'পান', 'করেনি', 'কেননা', 'সে', 'রোযাদার'],
      chipsBn: ['রাশেদ', 'খায়নি', 'এবং', 'পান', 'করেনি', 'কেননা', 'সে', 'রোযাদার', 'খেয়েছে', 'ছোট'],
      emoji: '🌙',
    },
  },

  // 9. Page 26: Sentence Assembly - Truth-telling Muslim
  {
    id: 'v2-c1-l3-step-9-assembly-truth-muslim',
    type: 'sentence_assembly',
    pageNumber: 26,
    titleEn: 'Moral Maxim: The Truthful Muslim',
    titleAr: 'صِدْقُ المُسْلِمِ',
    instructionEn: 'Assemble: "The Muslim always speaks the truth and never lies."',
    instructionBn: 'বাক্যটি সাজান: "মুসলিম সর্বদা সত্য বলে এবং কখনো মিথ্যা বলে না।"',
    assemblyPayload: {
      promptEn: 'The Muslim always speaks the truth and never lies.',
      promptBn: 'মুসলিম সর্বদা সত্য বলে এবং কখনো মিথ্যা বলে না।',
      expectedAnswer: ['يَصْدُقُ', 'الْمُسْلِمُ', 'دَائِمًا', 'وَلَا', 'يَكْذِبُ', 'أَبَدًا'],
      chips: ['يَصْدُقُ', 'الْمُسْلِمُ', 'دَائِمًا', 'وَلَا', 'يَكْذِبُ', 'أَبَدًا', 'مَا', 'كَذَبَ'],
      expectedAnswerBn: ['মুসলিম', 'সর্বদা', 'সত্য', 'বলে', 'এবং', 'কখনো', 'মিথ্যা', 'বলে', 'না'],
      chipsBn: ['মুসলিম', 'সর্বদা', 'সত্য', 'বলে', 'এবং', 'কখনো', 'মিথ্যা', 'বলে', 'না', 'বলেছে', 'গেল'],
      emoji: '💎',
    },
  },

  // 10. Page 27: Alternative QA - Reading Comprehension
  {
    id: 'v2-c1-l3-step-10-qa-ramadan',
    type: 'alternative_qa',
    pageNumber: 27,
    titleEn: 'Textbook Comprehension: Quran & Ramadan',
    titleAr: 'اسْتِيعَابُ القُرْآنِ وَرَمَضَانَ',
    instructionEn: 'Answer each question about the reading passage accurately.',
    instructionBn: 'পঠিত অনুচ্ছেদের আলোকে প্রশ্নগুলোর সঠিক উত্তর দিন।',
    alternativeQAPayload: {
      contextAr: 'نَزَلَ القُرْآنُ فِي شَهْرِ رَمَضَانَ عَلَى رَسُولِ اللهِ ، وَيَصْدُقُ المُسْلِمُ دَائِمًا ، وَيَنْزِلُ المَطَرُ مِنَ السَّمَاءِ.',
      questions: [
        {
          id: 'q-quran-desc',
          questionAr: 'أَ فِي شَهْرِ رَمَضَانَ نَزَلَ القُرْآنُ أَمْ فِي شَهْرِ شَعْبَانَ ؟',
          optionsAr: ['فِي شَهْرِ رَمَضَانَ', 'فِي شَهْرِ شَعْبَانَ'],
          correctAnswerAr: 'فِي شَهْرِ رَمَضَانَ',
        },
        {
          id: 'q-truth-choice',
          questionAr: 'أَ يَصْدُقُ المُسْلِمُ دَائِمًا أَمْ يَكْذِبُ ؟',
          optionsAr: ['يَصْدُقُ دَائِمًا', 'يَكْذِبُ'],
          correctAnswerAr: 'يَصْدُقُ دَائِمًا',
        },
        {
          id: 'q-rain-desc',
          questionAr: 'أَ يَنْزِلُ المَطَرُ مِنَ السَّمَاءِ أَمْ مِنَ الأَرْضِ ؟',
          optionsAr: ['مِنَ السَّمَاءِ', 'مِنَ الأَرْضِ'],
          correctAnswerAr: 'مِنَ السَّمَاءِ',
        },
      ],
    },
  },

  // 11. Page 27: Tarkib Dissector Tier 4 - Verb + Subject + Adjective + Muta'allaq
  {
    id: 'v2-c1-l3-step-11-tarkib-adjective-mutaallaq',
    type: 'tarkib_dissector',
    pageNumber: 27,
    titleEn: 'Syntactic Dissector: Verb + Subject + Adjective + Attachment',
    titleAr: 'تَرْكِيبُ الجُمْلَةِ الفِعْلِيَّةِ: فِعْل + فَاعِل + صِفَة + مُتَعَلِّق',
    instructionEn: 'Slot each word into its exact grammatical role in this advanced verbal sentence.',
    instructionBn: 'প্রতিটি শব্দকে তার সঠিক ব্যাকরণিক স্থানে বসান: কাজ, কর্তা, গুণবাচক বিশেষণ ও متعلق।',
    tarkibPayload: {
      sentences: [
        {
          id: 'tarkib-tilmidh-jadid',
          sentenceAr: 'خَرَجَ التِّلْمِيذُ الجَدِيدُ مِنَ الفَصْلِ',
          sentenceTypeAr: 'جُمْلَةٌ فِعْلِيَّةٌ مُرَكَّبَةٌ',
          sentenceTypeEn: 'Complex Verbal Sentence',
          sentenceTypeBn: 'বিশেষণযুক্ত ক্রিয়াবাচক বাক্য',
          slots: [
            { roleAr: 'فِعْلٌ', roleEn: 'Action / Verb', roleBn: 'কাজ (ফেল)', expectedWordAr: 'خَرَجَ' },
            { roleAr: 'فَاعِلٌ', roleEn: 'Doer / Subject', roleBn: 'কর্তা (ফায়েল)', expectedWordAr: 'التِّلْمِيذُ' },
            { roleAr: 'صِفَةُ الفَاعِلِ', roleEn: 'Subject Adjective', roleBn: 'কর্তার গুণ (সিফাত)', expectedWordAr: 'الجَدِيدُ' },
            { roleAr: 'مُتَعَلِّقٌ بِالفِعْلِ', roleEn: 'Prepositional Attachment', roleBn: 'ক্রিয়ার متعلق', expectedWordAr: 'مِنَ الفَصْلِ' },
          ],
          availableWordsAr: ['خَرَجَ', 'التِّلْمِيذُ', 'الجَدِيدُ', 'مِنَ الفَصْلِ'],
        },
      ],
    },
  },

  // 12. Page 26: Quranic Echo - Surah Al-Baqarah (2:185)
  {
    id: 'v2-c1-l3-step-12-quranic-echo-baqarah',
    type: 'quranic_echo',
    pageNumber: 26,
    titleEn: 'The Month of Revelation: شَهْرُ رَمَضَانَ',
    titleAr: 'صَدَى القُرْآنِ: (شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ)',
    instructionEn: 'Reflect on how "شَهْرُ رَمَضَانَ" and the verb of descent "نَزَلَ / أُنزِلَ" appear in the Holy Quran.',
    instructionBn: 'আজকের পাঠের "شَهْرُ رَمَضَانَ" এবং "نَزَلَ / أُنزِلَ" ক্রিয়া কীভাবে কুরআনুল কারীমে এসেছে তা হৃদয়ঙ্গম করুন।',
    echoPayload: {
      surahNumber: 2,
      ayahNumber: 185,
      surahNameAr: 'البَقَرَة',
      surahNameEn: 'Al-Baqarah',
      arabicText: 'شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ هُدًى لِّلنَّاسِ',
      translationEn: 'The month of Ramadan in which was revealed the Quran, a guidance for the people.',
      translationBn: 'রমযান মাস—যার মধ্যে কুরআন অবতীর্ণ করা হয়েছে মানবজাতির পথপ্রদর্শক হিসেবে।',
      highlightedWords: ['شَهْرُ', 'رَمَضَانَ', 'أُنزِلَ'],
      reflection: 'The exact nouns "شَهْرُ رَمَضَانَ" (the month of Ramadan) and the root "نَزَلَ" (to descend/reveal) you mastered today form the magnificent declaration of Allah when defining the month of fasting in Surah Al-Baqarah.',
      audioKey: 'quran_002_185',
      patternNameEn: 'Verbal Noun & Passive Verb of Descent · نُزُول / أُنزِلَ',
      patternNameBn: 'অবতরণ ক্রিয়ামূল ও কর্মবাচ্য ক্রিয়া (নুযূল / উনযিলা)',
      lessonPatternAr: 'نَزَلَ القُرْآنُ فِي شَهْرِ رَمَضَانَ',
      lessonPatternEn: 'The Quran descended in the month of Ramadan',
      lessonPatternBn: 'রমযান মাসে কুরআন অবতীর্ণ হলো',
      quranPatternAr: 'شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ',
      quranPatternEn: 'The month of Ramadan in which was revealed the Quran',
      quranPatternBn: 'রমযান মাস যাতে অবতীর্ণ হয়েছে কুরআন',
    },
  },
];

export const VOL2_CH1_LESSON_03_SESSION: LessonSessionData = {
  volumeId: 2,
  chapterId: 1,
  lessonNum: 3,
  titleEn: 'The Masdar Factory, 4 Abwaab & Causal Connector (لِأَنَّ)',
  titleAr: 'مَصْنَعُ المَصَادِرِ وَالأَبْوَابُ الأَرْبَعَةُ وَأَدَاةُ التَّعْلِيلِ (لِأَنَّ)',
  wordsLearned: [
    'الفِعْلُ',
    'الخُرُوجُ',
    'الذَّهَابُ',
    'الجُلُوسُ',
    'القِرَاءَةُ',
    'الكِتَابَةُ',
    'الرُّجُوعُ',
    'اللَّعِبُ',
    'السِّبَاحَةُ',
    'النَّجَاحُ',
    'النُّزُولُ',
    'الصِّدْقُ',
    'الكَذِبُ',
    'الأَكْلُ',
    'الشُّرْبُ',
    'الضَّحِكُ',
    'لِأَنَّ',
    'شَهْرٌ',
    'رَمَضَانُ',
    'صَائِمٌ',
    'نَهَارٌ',
    'مَطَرٌ',
    'حَيَاةٌ',
    'كَسْلَانُ',
  ],
  steps: VOL2_CH1_LESSON_03_STEPS,
};
